/*
** charmstr@student.42.fr
*/

#include <stdio.h>
#include "../includes/printf_lover_test_func.h"

int	test_func_c(int c)
{
setbuf(stdout, NULL);
	my_ft_putstr_fd("Printf(\"-->|%-4.c|<--\\n\", c);	==>	", 1);
	printf("-->|%-4.c|<--\n", c);
	my_ft_putstr_fd("Printf(\"-->|%-4c|<--\\n\", c);	==>	", 1);
	printf("-->|%-4c|<--\n", c);
	my_ft_putstr_fd("Printf(\"-->|%-3.c|<--\\n\", c);	==>	", 1);
	printf("-->|%-3.c|<--\n", c);
	my_ft_putstr_fd("Printf(\"-->|%-3c|<--\\n\", c);	==>	", 1);
	printf("-->|%-3c|<--\n", c);
	my_ft_putstr_fd("Printf(\"-->|%-2.c|<--\\n\", c);	==>	", 1);
	printf("-->|%-2.c|<--\n", c);
	my_ft_putstr_fd("Printf(\"-->|%-2c|<--\\n\", c);	==>	", 1);
	printf("-->|%-2c|<--\n", c);
	my_ft_putstr_fd("Printf(\"-->|%-1.c|<--\\n\", c);	==>	", 1);
	printf("-->|%-1.c|<--\n", c);
	my_ft_putstr_fd("Printf(\"-->|%-1c|<--\\n\", c);	==>	", 1);
	printf("-->|%-1c|<--\n", c);
	my_ft_putstr_fd("Printf(\"-->|%.c|<--\\n\", c);	==>	", 1);
	printf("-->|%.c|<--\n", c);
	my_ft_putstr_fd("Printf(\"-->|%c|<--\\n\", c);	==>	", 1);
	printf("-->|%c|<--\n", c);
	my_ft_putstr_fd("Printf(\"-->|%*.c|<--\\n\", -4, c);	==>	", 1);
	printf("-->|%*.c|<--\n", -4, c);
	my_ft_putstr_fd("Printf(\"-->|%*.c|<--\\n\", -3, c);	==>	", 1);
	printf("-->|%*.c|<--\n", -3, c);
	my_ft_putstr_fd("Printf(\"-->|%*.c|<--\\n\", -2, c);	==>	", 1);
	printf("-->|%*.c|<--\n", -2, c);
	my_ft_putstr_fd("Printf(\"-->|%*.c|<--\\n\", -1, c);	==>	", 1);
	printf("-->|%*.c|<--\n", -1, c);
	my_ft_putstr_fd("Printf(\"-->|%*.c|<--\\n\", 0, c);	==>	", 1);
	printf("-->|%*.c|<--\n", 0, c);
	my_ft_putstr_fd("Printf(\"-->|%*.c|<--\\n\", 1, c);	==>	", 1);
	printf("-->|%*.c|<--\n", 1, c);
	my_ft_putstr_fd("Printf(\"-->|%*.c|<--\\n\", 2, c);	==>	", 1);
	printf("-->|%*.c|<--\n", 2, c);
	my_ft_putstr_fd("Printf(\"-->|%*.c|<--\\n\", 3, c);	==>	", 1);
	printf("-->|%*.c|<--\n", 3, c);
	my_ft_putstr_fd("Printf(\"-->|%*.c|<--\\n\", 4, c);	==>	", 1);
	printf("-->|%*.c|<--\n", 4, c);
	my_ft_putstr_fd("Printf(\"-->|%*c|<--\\n\", -4, c);	==>	", 1);
	printf("-->|%*c|<--\n", -4, c);
	my_ft_putstr_fd("Printf(\"-->|%*c|<--\\n\", -3, c);	==>	", 1);
	printf("-->|%*c|<--\n", -3, c);
	my_ft_putstr_fd("Printf(\"-->|%*c|<--\\n\", -2, c);	==>	", 1);
	printf("-->|%*c|<--\n", -2, c);
	my_ft_putstr_fd("Printf(\"-->|%*c|<--\\n\", -1, c);	==>	", 1);
	printf("-->|%*c|<--\n", -1, c);
	my_ft_putstr_fd("Printf(\"-->|%*c|<--\\n\", 0, c);	==>	", 1);
	printf("-->|%*c|<--\n", 0, c);
	my_ft_putstr_fd("Printf(\"-->|%*c|<--\\n\", 1, c);	==>	", 1);
	printf("-->|%*c|<--\n", 1, c);
	my_ft_putstr_fd("Printf(\"-->|%*c|<--\\n\", 2, c);	==>	", 1);
	printf("-->|%*c|<--\n", 2, c);
	my_ft_putstr_fd("Printf(\"-->|%*c|<--\\n\", 3, c);	==>	", 1);
	printf("-->|%*c|<--\n", 3, c);
	my_ft_putstr_fd("Printf(\"-->|%*c|<--\\n\", 4, c);	==>	", 1);
	printf("-->|%*c|<--\n", 4, c);
	my_ft_putstr_fd("Printf(\"-->|%1.c|<--\\n\", c);	==>	", 1);
	printf("-->|%1.c|<--\n", c);
	my_ft_putstr_fd("Printf(\"-->|%1c|<--\\n\", c);	==>	", 1);
	printf("-->|%1c|<--\n", c);
	my_ft_putstr_fd("Printf(\"-->|%2.c|<--\\n\", c);	==>	", 1);
	printf("-->|%2.c|<--\n", c);
	my_ft_putstr_fd("Printf(\"-->|%2c|<--\\n\", c);	==>	", 1);
	printf("-->|%2c|<--\n", c);
	my_ft_putstr_fd("Printf(\"-->|%3.c|<--\\n\", c);	==>	", 1);
	printf("-->|%3.c|<--\n", c);
	my_ft_putstr_fd("Printf(\"-->|%3c|<--\\n\", c);	==>	", 1);
	printf("-->|%3c|<--\n", c);
	my_ft_putstr_fd("Printf(\"-->|%4.c|<--\\n\", c);	==>	", 1);
	printf("-->|%4.c|<--\n", c);
	my_ft_putstr_fd("Printf(\"-->|%4c|<--\\n\", c);	==>	", 1);
	printf("-->|%4c|<--\n", c);
	my_ft_putstr_fd("Printf(\"-->|%--4.c|<--\\n\", c);	==>	", 1);
	printf("-->|%--4.c|<--\n", c);
	my_ft_putstr_fd("Printf(\"-->|%--4c|<--\\n\", c);	==>	", 1);
	printf("-->|%--4c|<--\n", c);
	my_ft_putstr_fd("Printf(\"-->|%--3.c|<--\\n\", c);	==>	", 1);
	printf("-->|%--3.c|<--\n", c);
	my_ft_putstr_fd("Printf(\"-->|%--3c|<--\\n\", c);	==>	", 1);
	printf("-->|%--3c|<--\n", c);
	my_ft_putstr_fd("Printf(\"-->|%--2.c|<--\\n\", c);	==>	", 1);
	printf("-->|%--2.c|<--\n", c);
	my_ft_putstr_fd("Printf(\"-->|%--2c|<--\\n\", c);	==>	", 1);
	printf("-->|%--2c|<--\n", c);
	my_ft_putstr_fd("Printf(\"-->|%--1.c|<--\\n\", c);	==>	", 1);
	printf("-->|%--1.c|<--\n", c);
	my_ft_putstr_fd("Printf(\"-->|%--1c|<--\\n\", c);	==>	", 1);
	printf("-->|%--1c|<--\n", c);
	my_ft_putstr_fd("Printf(\"-->|%-.c|<--\\n\", c);	==>	", 1);
	printf("-->|%-.c|<--\n", c);
	my_ft_putstr_fd("Printf(\"-->|%-c|<--\\n\", c);	==>	", 1);
	printf("-->|%-c|<--\n", c);
	my_ft_putstr_fd("Printf(\"-->|%-*.c|<--\\n\", -4, c);	==>	", 1);
	printf("-->|%-*.c|<--\n", -4, c);
	my_ft_putstr_fd("Printf(\"-->|%-*.c|<--\\n\", -3, c);	==>	", 1);
	printf("-->|%-*.c|<--\n", -3, c);
	my_ft_putstr_fd("Printf(\"-->|%-*.c|<--\\n\", -2, c);	==>	", 1);
	printf("-->|%-*.c|<--\n", -2, c);
	my_ft_putstr_fd("Printf(\"-->|%-*.c|<--\\n\", -1, c);	==>	", 1);
	printf("-->|%-*.c|<--\n", -1, c);
	my_ft_putstr_fd("Printf(\"-->|%-*.c|<--\\n\", 0, c);	==>	", 1);
	printf("-->|%-*.c|<--\n", 0, c);
	my_ft_putstr_fd("Printf(\"-->|%-*.c|<--\\n\", 1, c);	==>	", 1);
	printf("-->|%-*.c|<--\n", 1, c);
	my_ft_putstr_fd("Printf(\"-->|%-*.c|<--\\n\", 2, c);	==>	", 1);
	printf("-->|%-*.c|<--\n", 2, c);
	my_ft_putstr_fd("Printf(\"-->|%-*.c|<--\\n\", 3, c);	==>	", 1);
	printf("-->|%-*.c|<--\n", 3, c);
	my_ft_putstr_fd("Printf(\"-->|%-*.c|<--\\n\", 4, c);	==>	", 1);
	printf("-->|%-*.c|<--\n", 4, c);
	my_ft_putstr_fd("Printf(\"-->|%-*c|<--\\n\", -4, c);	==>	", 1);
	printf("-->|%-*c|<--\n", -4, c);
	my_ft_putstr_fd("Printf(\"-->|%-*c|<--\\n\", -3, c);	==>	", 1);
	printf("-->|%-*c|<--\n", -3, c);
	my_ft_putstr_fd("Printf(\"-->|%-*c|<--\\n\", -2, c);	==>	", 1);
	printf("-->|%-*c|<--\n", -2, c);
	my_ft_putstr_fd("Printf(\"-->|%-*c|<--\\n\", -1, c);	==>	", 1);
	printf("-->|%-*c|<--\n", -1, c);
	my_ft_putstr_fd("Printf(\"-->|%-*c|<--\\n\", 0, c);	==>	", 1);
	printf("-->|%-*c|<--\n", 0, c);
	my_ft_putstr_fd("Printf(\"-->|%-*c|<--\\n\", 1, c);	==>	", 1);
	printf("-->|%-*c|<--\n", 1, c);
	my_ft_putstr_fd("Printf(\"-->|%-*c|<--\\n\", 2, c);	==>	", 1);
	printf("-->|%-*c|<--\n", 2, c);
	my_ft_putstr_fd("Printf(\"-->|%-*c|<--\\n\", 3, c);	==>	", 1);
	printf("-->|%-*c|<--\n", 3, c);
	my_ft_putstr_fd("Printf(\"-->|%-*c|<--\\n\", 4, c);	==>	", 1);
	printf("-->|%-*c|<--\n", 4, c);
	my_ft_putstr_fd("Printf(\"-->|%-1.c|<--\\n\", c);	==>	", 1);
	printf("-->|%-1.c|<--\n", c);
	my_ft_putstr_fd("Printf(\"-->|%-1c|<--\\n\", c);	==>	", 1);
	printf("-->|%-1c|<--\n", c);
	my_ft_putstr_fd("Printf(\"-->|%-2.c|<--\\n\", c);	==>	", 1);
	printf("-->|%-2.c|<--\n", c);
	my_ft_putstr_fd("Printf(\"-->|%-2c|<--\\n\", c);	==>	", 1);
	printf("-->|%-2c|<--\n", c);
	my_ft_putstr_fd("Printf(\"-->|%-3.c|<--\\n\", c);	==>	", 1);
	printf("-->|%-3.c|<--\n", c);
	my_ft_putstr_fd("Printf(\"-->|%-3c|<--\\n\", c);	==>	", 1);
	printf("-->|%-3c|<--\n", c);
	my_ft_putstr_fd("Printf(\"-->|%-4.c|<--\\n\", c);	==>	", 1);
	printf("-->|%-4.c|<--\n", c);
	my_ft_putstr_fd("Printf(\"-->|%-4c|<--\\n\", c);	==>	", 1);
	printf("-->|%-4c|<--\n", c);
	return(0);
}
/*
** charmstr@student.42.fr
**
** 72 different calls generated automatically according to your options
*/
