/*
** charmstr@student.42.fr
*/

#include <stdio.h>
#include "../includes/printf_lover_test_func.h"

int	test_func_p(void *p)
{
setbuf(stdout, NULL);
	my_ft_putstr_fd("Printf(\"-->|%-16.p|<--\\n\", p);	==>	", 1);
	printf("-->|%-16.p|<--\n", p);
	my_ft_putstr_fd("Printf(\"-->|%-16p|<--\\n\", p);	==>	", 1);
	printf("-->|%-16p|<--\n", p);
	my_ft_putstr_fd("Printf(\"-->|%-15.p|<--\\n\", p);	==>	", 1);
	printf("-->|%-15.p|<--\n", p);
	my_ft_putstr_fd("Printf(\"-->|%-15p|<--\\n\", p);	==>	", 1);
	printf("-->|%-15p|<--\n", p);
	my_ft_putstr_fd("Printf(\"-->|%-14.p|<--\\n\", p);	==>	", 1);
	printf("-->|%-14.p|<--\n", p);
	my_ft_putstr_fd("Printf(\"-->|%-14p|<--\\n\", p);	==>	", 1);
	printf("-->|%-14p|<--\n", p);
	my_ft_putstr_fd("Printf(\"-->|%-13.p|<--\\n\", p);	==>	", 1);
	printf("-->|%-13.p|<--\n", p);
	my_ft_putstr_fd("Printf(\"-->|%-13p|<--\\n\", p);	==>	", 1);
	printf("-->|%-13p|<--\n", p);
	my_ft_putstr_fd("Printf(\"-->|%-12.p|<--\\n\", p);	==>	", 1);
	printf("-->|%-12.p|<--\n", p);
	my_ft_putstr_fd("Printf(\"-->|%-12p|<--\\n\", p);	==>	", 1);
	printf("-->|%-12p|<--\n", p);
	my_ft_putstr_fd("Printf(\"-->|%-11.p|<--\\n\", p);	==>	", 1);
	printf("-->|%-11.p|<--\n", p);
	my_ft_putstr_fd("Printf(\"-->|%-11p|<--\\n\", p);	==>	", 1);
	printf("-->|%-11p|<--\n", p);
	my_ft_putstr_fd("Printf(\"-->|%-9.p|<--\\n\", p);	==>	", 1);
	printf("-->|%-9.p|<--\n", p);
	my_ft_putstr_fd("Printf(\"-->|%-9p|<--\\n\", p);	==>	", 1);
	printf("-->|%-9p|<--\n", p);
	my_ft_putstr_fd("Printf(\"-->|%-8.p|<--\\n\", p);	==>	", 1);
	printf("-->|%-8.p|<--\n", p);
	my_ft_putstr_fd("Printf(\"-->|%-8p|<--\\n\", p);	==>	", 1);
	printf("-->|%-8p|<--\n", p);
	my_ft_putstr_fd("Printf(\"-->|%-7.p|<--\\n\", p);	==>	", 1);
	printf("-->|%-7.p|<--\n", p);
	my_ft_putstr_fd("Printf(\"-->|%-7p|<--\\n\", p);	==>	", 1);
	printf("-->|%-7p|<--\n", p);
	my_ft_putstr_fd("Printf(\"-->|%-6.p|<--\\n\", p);	==>	", 1);
	printf("-->|%-6.p|<--\n", p);
	my_ft_putstr_fd("Printf(\"-->|%-6p|<--\\n\", p);	==>	", 1);
	printf("-->|%-6p|<--\n", p);
	my_ft_putstr_fd("Printf(\"-->|%-5.p|<--\\n\", p);	==>	", 1);
	printf("-->|%-5.p|<--\n", p);
	my_ft_putstr_fd("Printf(\"-->|%-5p|<--\\n\", p);	==>	", 1);
	printf("-->|%-5p|<--\n", p);
	my_ft_putstr_fd("Printf(\"-->|%-4.p|<--\\n\", p);	==>	", 1);
	printf("-->|%-4.p|<--\n", p);
	my_ft_putstr_fd("Printf(\"-->|%-4p|<--\\n\", p);	==>	", 1);
	printf("-->|%-4p|<--\n", p);
	my_ft_putstr_fd("Printf(\"-->|%-3.p|<--\\n\", p);	==>	", 1);
	printf("-->|%-3.p|<--\n", p);
	my_ft_putstr_fd("Printf(\"-->|%-3p|<--\\n\", p);	==>	", 1);
	printf("-->|%-3p|<--\n", p);
	my_ft_putstr_fd("Printf(\"-->|%-2.p|<--\\n\", p);	==>	", 1);
	printf("-->|%-2.p|<--\n", p);
	my_ft_putstr_fd("Printf(\"-->|%-2p|<--\\n\", p);	==>	", 1);
	printf("-->|%-2p|<--\n", p);
	my_ft_putstr_fd("Printf(\"-->|%-1.p|<--\\n\", p);	==>	", 1);
	printf("-->|%-1.p|<--\n", p);
	my_ft_putstr_fd("Printf(\"-->|%-1p|<--\\n\", p);	==>	", 1);
	printf("-->|%-1p|<--\n", p);
	my_ft_putstr_fd("Printf(\"-->|%.p|<--\\n\", p);	==>	", 1);
	printf("-->|%.p|<--\n", p);
	my_ft_putstr_fd("Printf(\"-->|%p|<--\\n\", p);	==>	", 1);
	printf("-->|%p|<--\n", p);
	my_ft_putstr_fd("Printf(\"-->|%*.p|<--\\n\", -16, p);	==>	", 1);
	printf("-->|%*.p|<--\n", -16, p);
	my_ft_putstr_fd("Printf(\"-->|%*.p|<--\\n\", -15, p);	==>	", 1);
	printf("-->|%*.p|<--\n", -15, p);
	my_ft_putstr_fd("Printf(\"-->|%*.p|<--\\n\", -14, p);	==>	", 1);
	printf("-->|%*.p|<--\n", -14, p);
	my_ft_putstr_fd("Printf(\"-->|%*.p|<--\\n\", -13, p);	==>	", 1);
	printf("-->|%*.p|<--\n", -13, p);
	my_ft_putstr_fd("Printf(\"-->|%*.p|<--\\n\", -12, p);	==>	", 1);
	printf("-->|%*.p|<--\n", -12, p);
	my_ft_putstr_fd("Printf(\"-->|%*.p|<--\\n\", -11, p);	==>	", 1);
	printf("-->|%*.p|<--\n", -11, p);
	my_ft_putstr_fd("Printf(\"-->|%*.p|<--\\n\", -10, p);	==>	", 1);
	printf("-->|%*.p|<--\n", -10, p);
	my_ft_putstr_fd("Printf(\"-->|%*.p|<--\\n\", -9, p);	==>	", 1);
	printf("-->|%*.p|<--\n", -9, p);
	my_ft_putstr_fd("Printf(\"-->|%*.p|<--\\n\", -8, p);	==>	", 1);
	printf("-->|%*.p|<--\n", -8, p);
	my_ft_putstr_fd("Printf(\"-->|%*.p|<--\\n\", -7, p);	==>	", 1);
	printf("-->|%*.p|<--\n", -7, p);
	my_ft_putstr_fd("Printf(\"-->|%*.p|<--\\n\", -6, p);	==>	", 1);
	printf("-->|%*.p|<--\n", -6, p);
	my_ft_putstr_fd("Printf(\"-->|%*.p|<--\\n\", -5, p);	==>	", 1);
	printf("-->|%*.p|<--\n", -5, p);
	my_ft_putstr_fd("Printf(\"-->|%*.p|<--\\n\", -4, p);	==>	", 1);
	printf("-->|%*.p|<--\n", -4, p);
	my_ft_putstr_fd("Printf(\"-->|%*.p|<--\\n\", -3, p);	==>	", 1);
	printf("-->|%*.p|<--\n", -3, p);
	my_ft_putstr_fd("Printf(\"-->|%*.p|<--\\n\", -2, p);	==>	", 1);
	printf("-->|%*.p|<--\n", -2, p);
	my_ft_putstr_fd("Printf(\"-->|%*.p|<--\\n\", -1, p);	==>	", 1);
	printf("-->|%*.p|<--\n", -1, p);
	my_ft_putstr_fd("Printf(\"-->|%*.p|<--\\n\", 0, p);	==>	", 1);
	printf("-->|%*.p|<--\n", 0, p);
	my_ft_putstr_fd("Printf(\"-->|%*.p|<--\\n\", 1, p);	==>	", 1);
	printf("-->|%*.p|<--\n", 1, p);
	my_ft_putstr_fd("Printf(\"-->|%*.p|<--\\n\", 2, p);	==>	", 1);
	printf("-->|%*.p|<--\n", 2, p);
	my_ft_putstr_fd("Printf(\"-->|%*.p|<--\\n\", 3, p);	==>	", 1);
	printf("-->|%*.p|<--\n", 3, p);
	my_ft_putstr_fd("Printf(\"-->|%*.p|<--\\n\", 4, p);	==>	", 1);
	printf("-->|%*.p|<--\n", 4, p);
	my_ft_putstr_fd("Printf(\"-->|%*.p|<--\\n\", 5, p);	==>	", 1);
	printf("-->|%*.p|<--\n", 5, p);
	my_ft_putstr_fd("Printf(\"-->|%*.p|<--\\n\", 6, p);	==>	", 1);
	printf("-->|%*.p|<--\n", 6, p);
	my_ft_putstr_fd("Printf(\"-->|%*.p|<--\\n\", 7, p);	==>	", 1);
	printf("-->|%*.p|<--\n", 7, p);
	my_ft_putstr_fd("Printf(\"-->|%*.p|<--\\n\", 8, p);	==>	", 1);
	printf("-->|%*.p|<--\n", 8, p);
	my_ft_putstr_fd("Printf(\"-->|%*.p|<--\\n\", 9, p);	==>	", 1);
	printf("-->|%*.p|<--\n", 9, p);
	my_ft_putstr_fd("Printf(\"-->|%*.p|<--\\n\", 10, p);	==>	", 1);
	printf("-->|%*.p|<--\n", 10, p);
	my_ft_putstr_fd("Printf(\"-->|%*.p|<--\\n\", 11, p);	==>	", 1);
	printf("-->|%*.p|<--\n", 11, p);
	my_ft_putstr_fd("Printf(\"-->|%*.p|<--\\n\", 12, p);	==>	", 1);
	printf("-->|%*.p|<--\n", 12, p);
	my_ft_putstr_fd("Printf(\"-->|%*.p|<--\\n\", 13, p);	==>	", 1);
	printf("-->|%*.p|<--\n", 13, p);
	my_ft_putstr_fd("Printf(\"-->|%*.p|<--\\n\", 14, p);	==>	", 1);
	printf("-->|%*.p|<--\n", 14, p);
	my_ft_putstr_fd("Printf(\"-->|%*.p|<--\\n\", 15, p);	==>	", 1);
	printf("-->|%*.p|<--\n", 15, p);
	my_ft_putstr_fd("Printf(\"-->|%*.p|<--\\n\", 16, p);	==>	", 1);
	printf("-->|%*.p|<--\n", 16, p);
	my_ft_putstr_fd("Printf(\"-->|%*p|<--\\n\", -16, p);	==>	", 1);
	printf("-->|%*p|<--\n", -16, p);
	my_ft_putstr_fd("Printf(\"-->|%*p|<--\\n\", -15, p);	==>	", 1);
	printf("-->|%*p|<--\n", -15, p);
	my_ft_putstr_fd("Printf(\"-->|%*p|<--\\n\", -14, p);	==>	", 1);
	printf("-->|%*p|<--\n", -14, p);
	my_ft_putstr_fd("Printf(\"-->|%*p|<--\\n\", -13, p);	==>	", 1);
	printf("-->|%*p|<--\n", -13, p);
	my_ft_putstr_fd("Printf(\"-->|%*p|<--\\n\", -12, p);	==>	", 1);
	printf("-->|%*p|<--\n", -12, p);
	my_ft_putstr_fd("Printf(\"-->|%*p|<--\\n\", -11, p);	==>	", 1);
	printf("-->|%*p|<--\n", -11, p);
	my_ft_putstr_fd("Printf(\"-->|%*p|<--\\n\", -10, p);	==>	", 1);
	printf("-->|%*p|<--\n", -10, p);
	my_ft_putstr_fd("Printf(\"-->|%*p|<--\\n\", -9, p);	==>	", 1);
	printf("-->|%*p|<--\n", -9, p);
	my_ft_putstr_fd("Printf(\"-->|%*p|<--\\n\", -8, p);	==>	", 1);
	printf("-->|%*p|<--\n", -8, p);
	my_ft_putstr_fd("Printf(\"-->|%*p|<--\\n\", -7, p);	==>	", 1);
	printf("-->|%*p|<--\n", -7, p);
	my_ft_putstr_fd("Printf(\"-->|%*p|<--\\n\", -6, p);	==>	", 1);
	printf("-->|%*p|<--\n", -6, p);
	my_ft_putstr_fd("Printf(\"-->|%*p|<--\\n\", -5, p);	==>	", 1);
	printf("-->|%*p|<--\n", -5, p);
	my_ft_putstr_fd("Printf(\"-->|%*p|<--\\n\", -4, p);	==>	", 1);
	printf("-->|%*p|<--\n", -4, p);
	my_ft_putstr_fd("Printf(\"-->|%*p|<--\\n\", -3, p);	==>	", 1);
	printf("-->|%*p|<--\n", -3, p);
	my_ft_putstr_fd("Printf(\"-->|%*p|<--\\n\", -2, p);	==>	", 1);
	printf("-->|%*p|<--\n", -2, p);
	my_ft_putstr_fd("Printf(\"-->|%*p|<--\\n\", -1, p);	==>	", 1);
	printf("-->|%*p|<--\n", -1, p);
	my_ft_putstr_fd("Printf(\"-->|%*p|<--\\n\", 0, p);	==>	", 1);
	printf("-->|%*p|<--\n", 0, p);
	my_ft_putstr_fd("Printf(\"-->|%*p|<--\\n\", 1, p);	==>	", 1);
	printf("-->|%*p|<--\n", 1, p);
	my_ft_putstr_fd("Printf(\"-->|%*p|<--\\n\", 2, p);	==>	", 1);
	printf("-->|%*p|<--\n", 2, p);
	my_ft_putstr_fd("Printf(\"-->|%*p|<--\\n\", 3, p);	==>	", 1);
	printf("-->|%*p|<--\n", 3, p);
	my_ft_putstr_fd("Printf(\"-->|%*p|<--\\n\", 4, p);	==>	", 1);
	printf("-->|%*p|<--\n", 4, p);
	my_ft_putstr_fd("Printf(\"-->|%*p|<--\\n\", 5, p);	==>	", 1);
	printf("-->|%*p|<--\n", 5, p);
	my_ft_putstr_fd("Printf(\"-->|%*p|<--\\n\", 6, p);	==>	", 1);
	printf("-->|%*p|<--\n", 6, p);
	my_ft_putstr_fd("Printf(\"-->|%*p|<--\\n\", 7, p);	==>	", 1);
	printf("-->|%*p|<--\n", 7, p);
	my_ft_putstr_fd("Printf(\"-->|%*p|<--\\n\", 8, p);	==>	", 1);
	printf("-->|%*p|<--\n", 8, p);
	my_ft_putstr_fd("Printf(\"-->|%*p|<--\\n\", 9, p);	==>	", 1);
	printf("-->|%*p|<--\n", 9, p);
	my_ft_putstr_fd("Printf(\"-->|%*p|<--\\n\", 10, p);	==>	", 1);
	printf("-->|%*p|<--\n", 10, p);
	my_ft_putstr_fd("Printf(\"-->|%*p|<--\\n\", 11, p);	==>	", 1);
	printf("-->|%*p|<--\n", 11, p);
	my_ft_putstr_fd("Printf(\"-->|%*p|<--\\n\", 12, p);	==>	", 1);
	printf("-->|%*p|<--\n", 12, p);
	my_ft_putstr_fd("Printf(\"-->|%*p|<--\\n\", 13, p);	==>	", 1);
	printf("-->|%*p|<--\n", 13, p);
	my_ft_putstr_fd("Printf(\"-->|%*p|<--\\n\", 14, p);	==>	", 1);
	printf("-->|%*p|<--\n", 14, p);
	my_ft_putstr_fd("Printf(\"-->|%*p|<--\\n\", 15, p);	==>	", 1);
	printf("-->|%*p|<--\n", 15, p);
	my_ft_putstr_fd("Printf(\"-->|%*p|<--\\n\", 16, p);	==>	", 1);
	printf("-->|%*p|<--\n", 16, p);
	my_ft_putstr_fd("Printf(\"-->|%1.p|<--\\n\", p);	==>	", 1);
	printf("-->|%1.p|<--\n", p);
	my_ft_putstr_fd("Printf(\"-->|%1p|<--\\n\", p);	==>	", 1);
	printf("-->|%1p|<--\n", p);
	my_ft_putstr_fd("Printf(\"-->|%2.p|<--\\n\", p);	==>	", 1);
	printf("-->|%2.p|<--\n", p);
	my_ft_putstr_fd("Printf(\"-->|%2p|<--\\n\", p);	==>	", 1);
	printf("-->|%2p|<--\n", p);
	my_ft_putstr_fd("Printf(\"-->|%3.p|<--\\n\", p);	==>	", 1);
	printf("-->|%3.p|<--\n", p);
	my_ft_putstr_fd("Printf(\"-->|%3p|<--\\n\", p);	==>	", 1);
	printf("-->|%3p|<--\n", p);
	my_ft_putstr_fd("Printf(\"-->|%4.p|<--\\n\", p);	==>	", 1);
	printf("-->|%4.p|<--\n", p);
	my_ft_putstr_fd("Printf(\"-->|%4p|<--\\n\", p);	==>	", 1);
	printf("-->|%4p|<--\n", p);
	my_ft_putstr_fd("Printf(\"-->|%5.p|<--\\n\", p);	==>	", 1);
	printf("-->|%5.p|<--\n", p);
	my_ft_putstr_fd("Printf(\"-->|%5p|<--\\n\", p);	==>	", 1);
	printf("-->|%5p|<--\n", p);
	my_ft_putstr_fd("Printf(\"-->|%6.p|<--\\n\", p);	==>	", 1);
	printf("-->|%6.p|<--\n", p);
	my_ft_putstr_fd("Printf(\"-->|%6p|<--\\n\", p);	==>	", 1);
	printf("-->|%6p|<--\n", p);
	my_ft_putstr_fd("Printf(\"-->|%7.p|<--\\n\", p);	==>	", 1);
	printf("-->|%7.p|<--\n", p);
	my_ft_putstr_fd("Printf(\"-->|%7p|<--\\n\", p);	==>	", 1);
	printf("-->|%7p|<--\n", p);
	my_ft_putstr_fd("Printf(\"-->|%8.p|<--\\n\", p);	==>	", 1);
	printf("-->|%8.p|<--\n", p);
	my_ft_putstr_fd("Printf(\"-->|%8p|<--\\n\", p);	==>	", 1);
	printf("-->|%8p|<--\n", p);
	my_ft_putstr_fd("Printf(\"-->|%9.p|<--\\n\", p);	==>	", 1);
	printf("-->|%9.p|<--\n", p);
	my_ft_putstr_fd("Printf(\"-->|%9p|<--\\n\", p);	==>	", 1);
	printf("-->|%9p|<--\n", p);
	my_ft_putstr_fd("Printf(\"-->|%11.p|<--\\n\", p);	==>	", 1);
	printf("-->|%11.p|<--\n", p);
	my_ft_putstr_fd("Printf(\"-->|%11p|<--\\n\", p);	==>	", 1);
	printf("-->|%11p|<--\n", p);
	my_ft_putstr_fd("Printf(\"-->|%12.p|<--\\n\", p);	==>	", 1);
	printf("-->|%12.p|<--\n", p);
	my_ft_putstr_fd("Printf(\"-->|%12p|<--\\n\", p);	==>	", 1);
	printf("-->|%12p|<--\n", p);
	my_ft_putstr_fd("Printf(\"-->|%13.p|<--\\n\", p);	==>	", 1);
	printf("-->|%13.p|<--\n", p);
	my_ft_putstr_fd("Printf(\"-->|%13p|<--\\n\", p);	==>	", 1);
	printf("-->|%13p|<--\n", p);
	my_ft_putstr_fd("Printf(\"-->|%14.p|<--\\n\", p);	==>	", 1);
	printf("-->|%14.p|<--\n", p);
	my_ft_putstr_fd("Printf(\"-->|%14p|<--\\n\", p);	==>	", 1);
	printf("-->|%14p|<--\n", p);
	my_ft_putstr_fd("Printf(\"-->|%15.p|<--\\n\", p);	==>	", 1);
	printf("-->|%15.p|<--\n", p);
	my_ft_putstr_fd("Printf(\"-->|%15p|<--\\n\", p);	==>	", 1);
	printf("-->|%15p|<--\n", p);
	my_ft_putstr_fd("Printf(\"-->|%16.p|<--\\n\", p);	==>	", 1);
	printf("-->|%16.p|<--\n", p);
	my_ft_putstr_fd("Printf(\"-->|%16p|<--\\n\", p);	==>	", 1);
	printf("-->|%16p|<--\n", p);
	my_ft_putstr_fd("Printf(\"-->|%--16.p|<--\\n\", p);	==>	", 1);
	printf("-->|%--16.p|<--\n", p);
	my_ft_putstr_fd("Printf(\"-->|%--16p|<--\\n\", p);	==>	", 1);
	printf("-->|%--16p|<--\n", p);
	my_ft_putstr_fd("Printf(\"-->|%--15.p|<--\\n\", p);	==>	", 1);
	printf("-->|%--15.p|<--\n", p);
	my_ft_putstr_fd("Printf(\"-->|%--15p|<--\\n\", p);	==>	", 1);
	printf("-->|%--15p|<--\n", p);
	my_ft_putstr_fd("Printf(\"-->|%--14.p|<--\\n\", p);	==>	", 1);
	printf("-->|%--14.p|<--\n", p);
	my_ft_putstr_fd("Printf(\"-->|%--14p|<--\\n\", p);	==>	", 1);
	printf("-->|%--14p|<--\n", p);
	my_ft_putstr_fd("Printf(\"-->|%--13.p|<--\\n\", p);	==>	", 1);
	printf("-->|%--13.p|<--\n", p);
	my_ft_putstr_fd("Printf(\"-->|%--13p|<--\\n\", p);	==>	", 1);
	printf("-->|%--13p|<--\n", p);
	my_ft_putstr_fd("Printf(\"-->|%--12.p|<--\\n\", p);	==>	", 1);
	printf("-->|%--12.p|<--\n", p);
	my_ft_putstr_fd("Printf(\"-->|%--12p|<--\\n\", p);	==>	", 1);
	printf("-->|%--12p|<--\n", p);
	my_ft_putstr_fd("Printf(\"-->|%--11.p|<--\\n\", p);	==>	", 1);
	printf("-->|%--11.p|<--\n", p);
	my_ft_putstr_fd("Printf(\"-->|%--11p|<--\\n\", p);	==>	", 1);
	printf("-->|%--11p|<--\n", p);
	my_ft_putstr_fd("Printf(\"-->|%--9.p|<--\\n\", p);	==>	", 1);
	printf("-->|%--9.p|<--\n", p);
	my_ft_putstr_fd("Printf(\"-->|%--9p|<--\\n\", p);	==>	", 1);
	printf("-->|%--9p|<--\n", p);
	my_ft_putstr_fd("Printf(\"-->|%--8.p|<--\\n\", p);	==>	", 1);
	printf("-->|%--8.p|<--\n", p);
	my_ft_putstr_fd("Printf(\"-->|%--8p|<--\\n\", p);	==>	", 1);
	printf("-->|%--8p|<--\n", p);
	my_ft_putstr_fd("Printf(\"-->|%--7.p|<--\\n\", p);	==>	", 1);
	printf("-->|%--7.p|<--\n", p);
	my_ft_putstr_fd("Printf(\"-->|%--7p|<--\\n\", p);	==>	", 1);
	printf("-->|%--7p|<--\n", p);
	my_ft_putstr_fd("Printf(\"-->|%--6.p|<--\\n\", p);	==>	", 1);
	printf("-->|%--6.p|<--\n", p);
	my_ft_putstr_fd("Printf(\"-->|%--6p|<--\\n\", p);	==>	", 1);
	printf("-->|%--6p|<--\n", p);
	my_ft_putstr_fd("Printf(\"-->|%--5.p|<--\\n\", p);	==>	", 1);
	printf("-->|%--5.p|<--\n", p);
	my_ft_putstr_fd("Printf(\"-->|%--5p|<--\\n\", p);	==>	", 1);
	printf("-->|%--5p|<--\n", p);
	my_ft_putstr_fd("Printf(\"-->|%--4.p|<--\\n\", p);	==>	", 1);
	printf("-->|%--4.p|<--\n", p);
	my_ft_putstr_fd("Printf(\"-->|%--4p|<--\\n\", p);	==>	", 1);
	printf("-->|%--4p|<--\n", p);
	my_ft_putstr_fd("Printf(\"-->|%--3.p|<--\\n\", p);	==>	", 1);
	printf("-->|%--3.p|<--\n", p);
	my_ft_putstr_fd("Printf(\"-->|%--3p|<--\\n\", p);	==>	", 1);
	printf("-->|%--3p|<--\n", p);
	my_ft_putstr_fd("Printf(\"-->|%--2.p|<--\\n\", p);	==>	", 1);
	printf("-->|%--2.p|<--\n", p);
	my_ft_putstr_fd("Printf(\"-->|%--2p|<--\\n\", p);	==>	", 1);
	printf("-->|%--2p|<--\n", p);
	my_ft_putstr_fd("Printf(\"-->|%--1.p|<--\\n\", p);	==>	", 1);
	printf("-->|%--1.p|<--\n", p);
	my_ft_putstr_fd("Printf(\"-->|%--1p|<--\\n\", p);	==>	", 1);
	printf("-->|%--1p|<--\n", p);
	my_ft_putstr_fd("Printf(\"-->|%-.p|<--\\n\", p);	==>	", 1);
	printf("-->|%-.p|<--\n", p);
	my_ft_putstr_fd("Printf(\"-->|%-p|<--\\n\", p);	==>	", 1);
	printf("-->|%-p|<--\n", p);
	my_ft_putstr_fd("Printf(\"-->|%-*.p|<--\\n\", -16, p);	==>	", 1);
	printf("-->|%-*.p|<--\n", -16, p);
	my_ft_putstr_fd("Printf(\"-->|%-*.p|<--\\n\", -15, p);	==>	", 1);
	printf("-->|%-*.p|<--\n", -15, p);
	my_ft_putstr_fd("Printf(\"-->|%-*.p|<--\\n\", -14, p);	==>	", 1);
	printf("-->|%-*.p|<--\n", -14, p);
	my_ft_putstr_fd("Printf(\"-->|%-*.p|<--\\n\", -13, p);	==>	", 1);
	printf("-->|%-*.p|<--\n", -13, p);
	my_ft_putstr_fd("Printf(\"-->|%-*.p|<--\\n\", -12, p);	==>	", 1);
	printf("-->|%-*.p|<--\n", -12, p);
	my_ft_putstr_fd("Printf(\"-->|%-*.p|<--\\n\", -11, p);	==>	", 1);
	printf("-->|%-*.p|<--\n", -11, p);
	my_ft_putstr_fd("Printf(\"-->|%-*.p|<--\\n\", -10, p);	==>	", 1);
	printf("-->|%-*.p|<--\n", -10, p);
	my_ft_putstr_fd("Printf(\"-->|%-*.p|<--\\n\", -9, p);	==>	", 1);
	printf("-->|%-*.p|<--\n", -9, p);
	my_ft_putstr_fd("Printf(\"-->|%-*.p|<--\\n\", -8, p);	==>	", 1);
	printf("-->|%-*.p|<--\n", -8, p);
	my_ft_putstr_fd("Printf(\"-->|%-*.p|<--\\n\", -7, p);	==>	", 1);
	printf("-->|%-*.p|<--\n", -7, p);
	my_ft_putstr_fd("Printf(\"-->|%-*.p|<--\\n\", -6, p);	==>	", 1);
	printf("-->|%-*.p|<--\n", -6, p);
	my_ft_putstr_fd("Printf(\"-->|%-*.p|<--\\n\", -5, p);	==>	", 1);
	printf("-->|%-*.p|<--\n", -5, p);
	my_ft_putstr_fd("Printf(\"-->|%-*.p|<--\\n\", -4, p);	==>	", 1);
	printf("-->|%-*.p|<--\n", -4, p);
	my_ft_putstr_fd("Printf(\"-->|%-*.p|<--\\n\", -3, p);	==>	", 1);
	printf("-->|%-*.p|<--\n", -3, p);
	my_ft_putstr_fd("Printf(\"-->|%-*.p|<--\\n\", -2, p);	==>	", 1);
	printf("-->|%-*.p|<--\n", -2, p);
	my_ft_putstr_fd("Printf(\"-->|%-*.p|<--\\n\", -1, p);	==>	", 1);
	printf("-->|%-*.p|<--\n", -1, p);
	my_ft_putstr_fd("Printf(\"-->|%-*.p|<--\\n\", 0, p);	==>	", 1);
	printf("-->|%-*.p|<--\n", 0, p);
	my_ft_putstr_fd("Printf(\"-->|%-*.p|<--\\n\", 1, p);	==>	", 1);
	printf("-->|%-*.p|<--\n", 1, p);
	my_ft_putstr_fd("Printf(\"-->|%-*.p|<--\\n\", 2, p);	==>	", 1);
	printf("-->|%-*.p|<--\n", 2, p);
	my_ft_putstr_fd("Printf(\"-->|%-*.p|<--\\n\", 3, p);	==>	", 1);
	printf("-->|%-*.p|<--\n", 3, p);
	my_ft_putstr_fd("Printf(\"-->|%-*.p|<--\\n\", 4, p);	==>	", 1);
	printf("-->|%-*.p|<--\n", 4, p);
	my_ft_putstr_fd("Printf(\"-->|%-*.p|<--\\n\", 5, p);	==>	", 1);
	printf("-->|%-*.p|<--\n", 5, p);
	my_ft_putstr_fd("Printf(\"-->|%-*.p|<--\\n\", 6, p);	==>	", 1);
	printf("-->|%-*.p|<--\n", 6, p);
	my_ft_putstr_fd("Printf(\"-->|%-*.p|<--\\n\", 7, p);	==>	", 1);
	printf("-->|%-*.p|<--\n", 7, p);
	my_ft_putstr_fd("Printf(\"-->|%-*.p|<--\\n\", 8, p);	==>	", 1);
	printf("-->|%-*.p|<--\n", 8, p);
	my_ft_putstr_fd("Printf(\"-->|%-*.p|<--\\n\", 9, p);	==>	", 1);
	printf("-->|%-*.p|<--\n", 9, p);
	my_ft_putstr_fd("Printf(\"-->|%-*.p|<--\\n\", 10, p);	==>	", 1);
	printf("-->|%-*.p|<--\n", 10, p);
	my_ft_putstr_fd("Printf(\"-->|%-*.p|<--\\n\", 11, p);	==>	", 1);
	printf("-->|%-*.p|<--\n", 11, p);
	my_ft_putstr_fd("Printf(\"-->|%-*.p|<--\\n\", 12, p);	==>	", 1);
	printf("-->|%-*.p|<--\n", 12, p);
	my_ft_putstr_fd("Printf(\"-->|%-*.p|<--\\n\", 13, p);	==>	", 1);
	printf("-->|%-*.p|<--\n", 13, p);
	my_ft_putstr_fd("Printf(\"-->|%-*.p|<--\\n\", 14, p);	==>	", 1);
	printf("-->|%-*.p|<--\n", 14, p);
	my_ft_putstr_fd("Printf(\"-->|%-*.p|<--\\n\", 15, p);	==>	", 1);
	printf("-->|%-*.p|<--\n", 15, p);
	my_ft_putstr_fd("Printf(\"-->|%-*.p|<--\\n\", 16, p);	==>	", 1);
	printf("-->|%-*.p|<--\n", 16, p);
	my_ft_putstr_fd("Printf(\"-->|%-*p|<--\\n\", -16, p);	==>	", 1);
	printf("-->|%-*p|<--\n", -16, p);
	my_ft_putstr_fd("Printf(\"-->|%-*p|<--\\n\", -15, p);	==>	", 1);
	printf("-->|%-*p|<--\n", -15, p);
	my_ft_putstr_fd("Printf(\"-->|%-*p|<--\\n\", -14, p);	==>	", 1);
	printf("-->|%-*p|<--\n", -14, p);
	my_ft_putstr_fd("Printf(\"-->|%-*p|<--\\n\", -13, p);	==>	", 1);
	printf("-->|%-*p|<--\n", -13, p);
	my_ft_putstr_fd("Printf(\"-->|%-*p|<--\\n\", -12, p);	==>	", 1);
	printf("-->|%-*p|<--\n", -12, p);
	my_ft_putstr_fd("Printf(\"-->|%-*p|<--\\n\", -11, p);	==>	", 1);
	printf("-->|%-*p|<--\n", -11, p);
	my_ft_putstr_fd("Printf(\"-->|%-*p|<--\\n\", -10, p);	==>	", 1);
	printf("-->|%-*p|<--\n", -10, p);
	my_ft_putstr_fd("Printf(\"-->|%-*p|<--\\n\", -9, p);	==>	", 1);
	printf("-->|%-*p|<--\n", -9, p);
	my_ft_putstr_fd("Printf(\"-->|%-*p|<--\\n\", -8, p);	==>	", 1);
	printf("-->|%-*p|<--\n", -8, p);
	my_ft_putstr_fd("Printf(\"-->|%-*p|<--\\n\", -7, p);	==>	", 1);
	printf("-->|%-*p|<--\n", -7, p);
	my_ft_putstr_fd("Printf(\"-->|%-*p|<--\\n\", -6, p);	==>	", 1);
	printf("-->|%-*p|<--\n", -6, p);
	my_ft_putstr_fd("Printf(\"-->|%-*p|<--\\n\", -5, p);	==>	", 1);
	printf("-->|%-*p|<--\n", -5, p);
	my_ft_putstr_fd("Printf(\"-->|%-*p|<--\\n\", -4, p);	==>	", 1);
	printf("-->|%-*p|<--\n", -4, p);
	my_ft_putstr_fd("Printf(\"-->|%-*p|<--\\n\", -3, p);	==>	", 1);
	printf("-->|%-*p|<--\n", -3, p);
	my_ft_putstr_fd("Printf(\"-->|%-*p|<--\\n\", -2, p);	==>	", 1);
	printf("-->|%-*p|<--\n", -2, p);
	my_ft_putstr_fd("Printf(\"-->|%-*p|<--\\n\", -1, p);	==>	", 1);
	printf("-->|%-*p|<--\n", -1, p);
	my_ft_putstr_fd("Printf(\"-->|%-*p|<--\\n\", 0, p);	==>	", 1);
	printf("-->|%-*p|<--\n", 0, p);
	my_ft_putstr_fd("Printf(\"-->|%-*p|<--\\n\", 1, p);	==>	", 1);
	printf("-->|%-*p|<--\n", 1, p);
	my_ft_putstr_fd("Printf(\"-->|%-*p|<--\\n\", 2, p);	==>	", 1);
	printf("-->|%-*p|<--\n", 2, p);
	my_ft_putstr_fd("Printf(\"-->|%-*p|<--\\n\", 3, p);	==>	", 1);
	printf("-->|%-*p|<--\n", 3, p);
	my_ft_putstr_fd("Printf(\"-->|%-*p|<--\\n\", 4, p);	==>	", 1);
	printf("-->|%-*p|<--\n", 4, p);
	my_ft_putstr_fd("Printf(\"-->|%-*p|<--\\n\", 5, p);	==>	", 1);
	printf("-->|%-*p|<--\n", 5, p);
	my_ft_putstr_fd("Printf(\"-->|%-*p|<--\\n\", 6, p);	==>	", 1);
	printf("-->|%-*p|<--\n", 6, p);
	my_ft_putstr_fd("Printf(\"-->|%-*p|<--\\n\", 7, p);	==>	", 1);
	printf("-->|%-*p|<--\n", 7, p);
	my_ft_putstr_fd("Printf(\"-->|%-*p|<--\\n\", 8, p);	==>	", 1);
	printf("-->|%-*p|<--\n", 8, p);
	my_ft_putstr_fd("Printf(\"-->|%-*p|<--\\n\", 9, p);	==>	", 1);
	printf("-->|%-*p|<--\n", 9, p);
	my_ft_putstr_fd("Printf(\"-->|%-*p|<--\\n\", 10, p);	==>	", 1);
	printf("-->|%-*p|<--\n", 10, p);
	my_ft_putstr_fd("Printf(\"-->|%-*p|<--\\n\", 11, p);	==>	", 1);
	printf("-->|%-*p|<--\n", 11, p);
	my_ft_putstr_fd("Printf(\"-->|%-*p|<--\\n\", 12, p);	==>	", 1);
	printf("-->|%-*p|<--\n", 12, p);
	my_ft_putstr_fd("Printf(\"-->|%-*p|<--\\n\", 13, p);	==>	", 1);
	printf("-->|%-*p|<--\n", 13, p);
	my_ft_putstr_fd("Printf(\"-->|%-*p|<--\\n\", 14, p);	==>	", 1);
	printf("-->|%-*p|<--\n", 14, p);
	my_ft_putstr_fd("Printf(\"-->|%-*p|<--\\n\", 15, p);	==>	", 1);
	printf("-->|%-*p|<--\n", 15, p);
	my_ft_putstr_fd("Printf(\"-->|%-*p|<--\\n\", 16, p);	==>	", 1);
	printf("-->|%-*p|<--\n", 16, p);
	my_ft_putstr_fd("Printf(\"-->|%-1.p|<--\\n\", p);	==>	", 1);
	printf("-->|%-1.p|<--\n", p);
	my_ft_putstr_fd("Printf(\"-->|%-1p|<--\\n\", p);	==>	", 1);
	printf("-->|%-1p|<--\n", p);
	my_ft_putstr_fd("Printf(\"-->|%-2.p|<--\\n\", p);	==>	", 1);
	printf("-->|%-2.p|<--\n", p);
	my_ft_putstr_fd("Printf(\"-->|%-2p|<--\\n\", p);	==>	", 1);
	printf("-->|%-2p|<--\n", p);
	my_ft_putstr_fd("Printf(\"-->|%-3.p|<--\\n\", p);	==>	", 1);
	printf("-->|%-3.p|<--\n", p);
	my_ft_putstr_fd("Printf(\"-->|%-3p|<--\\n\", p);	==>	", 1);
	printf("-->|%-3p|<--\n", p);
	my_ft_putstr_fd("Printf(\"-->|%-4.p|<--\\n\", p);	==>	", 1);
	printf("-->|%-4.p|<--\n", p);
	my_ft_putstr_fd("Printf(\"-->|%-4p|<--\\n\", p);	==>	", 1);
	printf("-->|%-4p|<--\n", p);
	my_ft_putstr_fd("Printf(\"-->|%-5.p|<--\\n\", p);	==>	", 1);
	printf("-->|%-5.p|<--\n", p);
	my_ft_putstr_fd("Printf(\"-->|%-5p|<--\\n\", p);	==>	", 1);
	printf("-->|%-5p|<--\n", p);
	my_ft_putstr_fd("Printf(\"-->|%-6.p|<--\\n\", p);	==>	", 1);
	printf("-->|%-6.p|<--\n", p);
	my_ft_putstr_fd("Printf(\"-->|%-6p|<--\\n\", p);	==>	", 1);
	printf("-->|%-6p|<--\n", p);
	my_ft_putstr_fd("Printf(\"-->|%-7.p|<--\\n\", p);	==>	", 1);
	printf("-->|%-7.p|<--\n", p);
	my_ft_putstr_fd("Printf(\"-->|%-7p|<--\\n\", p);	==>	", 1);
	printf("-->|%-7p|<--\n", p);
	my_ft_putstr_fd("Printf(\"-->|%-8.p|<--\\n\", p);	==>	", 1);
	printf("-->|%-8.p|<--\n", p);
	my_ft_putstr_fd("Printf(\"-->|%-8p|<--\\n\", p);	==>	", 1);
	printf("-->|%-8p|<--\n", p);
	my_ft_putstr_fd("Printf(\"-->|%-9.p|<--\\n\", p);	==>	", 1);
	printf("-->|%-9.p|<--\n", p);
	my_ft_putstr_fd("Printf(\"-->|%-9p|<--\\n\", p);	==>	", 1);
	printf("-->|%-9p|<--\n", p);
	my_ft_putstr_fd("Printf(\"-->|%-11.p|<--\\n\", p);	==>	", 1);
	printf("-->|%-11.p|<--\n", p);
	my_ft_putstr_fd("Printf(\"-->|%-11p|<--\\n\", p);	==>	", 1);
	printf("-->|%-11p|<--\n", p);
	my_ft_putstr_fd("Printf(\"-->|%-12.p|<--\\n\", p);	==>	", 1);
	printf("-->|%-12.p|<--\n", p);
	my_ft_putstr_fd("Printf(\"-->|%-12p|<--\\n\", p);	==>	", 1);
	printf("-->|%-12p|<--\n", p);
	my_ft_putstr_fd("Printf(\"-->|%-13.p|<--\\n\", p);	==>	", 1);
	printf("-->|%-13.p|<--\n", p);
	my_ft_putstr_fd("Printf(\"-->|%-13p|<--\\n\", p);	==>	", 1);
	printf("-->|%-13p|<--\n", p);
	my_ft_putstr_fd("Printf(\"-->|%-14.p|<--\\n\", p);	==>	", 1);
	printf("-->|%-14.p|<--\n", p);
	my_ft_putstr_fd("Printf(\"-->|%-14p|<--\\n\", p);	==>	", 1);
	printf("-->|%-14p|<--\n", p);
	my_ft_putstr_fd("Printf(\"-->|%-15.p|<--\\n\", p);	==>	", 1);
	printf("-->|%-15.p|<--\n", p);
	my_ft_putstr_fd("Printf(\"-->|%-15p|<--\\n\", p);	==>	", 1);
	printf("-->|%-15p|<--\n", p);
	my_ft_putstr_fd("Printf(\"-->|%-16.p|<--\\n\", p);	==>	", 1);
	printf("-->|%-16.p|<--\n", p);
	my_ft_putstr_fd("Printf(\"-->|%-16p|<--\\n\", p);	==>	", 1);
	printf("-->|%-16p|<--\n", p);
	return(0);
}
/*
** charmstr@student.42.fr
**
** 256 different calls generated automatically according to your options
*/
