/*
** charmstr@student.42.fr
*/

#include <stdio.h>
#include "../includes/printf_lover_test_func.h"

int	test_func_u(unsigned int u)
{
setbuf(stdout, NULL);
	my_ft_putstr_fd("Printf(\"-->|%-4.u|<--\\n\", u);	==>	", 1);
	printf("-->|%-4.u|<--\n", u);
	my_ft_putstr_fd("Printf(\"-->|%-4.*u|<--\\n\", -4, u);	==>	", 1);
	printf("-->|%-4.*u|<--\n", -4, u);
	my_ft_putstr_fd("Printf(\"-->|%-4.*u|<--\\n\", -3, u);	==>	", 1);
	printf("-->|%-4.*u|<--\n", -3, u);
	my_ft_putstr_fd("Printf(\"-->|%-4.*u|<--\\n\", -2, u);	==>	", 1);
	printf("-->|%-4.*u|<--\n", -2, u);
	my_ft_putstr_fd("Printf(\"-->|%-4.*u|<--\\n\", -1, u);	==>	", 1);
	printf("-->|%-4.*u|<--\n", -1, u);
	my_ft_putstr_fd("Printf(\"-->|%-4.*u|<--\\n\", 0, u);	==>	", 1);
	printf("-->|%-4.*u|<--\n", 0, u);
	my_ft_putstr_fd("Printf(\"-->|%-4.*u|<--\\n\", 1, u);	==>	", 1);
	printf("-->|%-4.*u|<--\n", 1, u);
	my_ft_putstr_fd("Printf(\"-->|%-4.*u|<--\\n\", 2, u);	==>	", 1);
	printf("-->|%-4.*u|<--\n", 2, u);
	my_ft_putstr_fd("Printf(\"-->|%-4.*u|<--\\n\", 3, u);	==>	", 1);
	printf("-->|%-4.*u|<--\n", 3, u);
	my_ft_putstr_fd("Printf(\"-->|%-4.*u|<--\\n\", 4, u);	==>	", 1);
	printf("-->|%-4.*u|<--\n", 4, u);
	my_ft_putstr_fd("Printf(\"-->|%-4.0u|<--\\n\", u);	==>	", 1);
	printf("-->|%-4.0u|<--\n", u);
	my_ft_putstr_fd("Printf(\"-->|%-4.1u|<--\\n\", u);	==>	", 1);
	printf("-->|%-4.1u|<--\n", u);
	my_ft_putstr_fd("Printf(\"-->|%-4.2u|<--\\n\", u);	==>	", 1);
	printf("-->|%-4.2u|<--\n", u);
	my_ft_putstr_fd("Printf(\"-->|%-4.3u|<--\\n\", u);	==>	", 1);
	printf("-->|%-4.3u|<--\n", u);
	my_ft_putstr_fd("Printf(\"-->|%-4.4u|<--\\n\", u);	==>	", 1);
	printf("-->|%-4.4u|<--\n", u);
	my_ft_putstr_fd("Printf(\"-->|%-4u|<--\\n\", u);	==>	", 1);
	printf("-->|%-4u|<--\n", u);
	my_ft_putstr_fd("Printf(\"-->|%-3.u|<--\\n\", u);	==>	", 1);
	printf("-->|%-3.u|<--\n", u);
	my_ft_putstr_fd("Printf(\"-->|%-3.*u|<--\\n\", -4, u);	==>	", 1);
	printf("-->|%-3.*u|<--\n", -4, u);
	my_ft_putstr_fd("Printf(\"-->|%-3.*u|<--\\n\", -3, u);	==>	", 1);
	printf("-->|%-3.*u|<--\n", -3, u);
	my_ft_putstr_fd("Printf(\"-->|%-3.*u|<--\\n\", -2, u);	==>	", 1);
	printf("-->|%-3.*u|<--\n", -2, u);
	my_ft_putstr_fd("Printf(\"-->|%-3.*u|<--\\n\", -1, u);	==>	", 1);
	printf("-->|%-3.*u|<--\n", -1, u);
	my_ft_putstr_fd("Printf(\"-->|%-3.*u|<--\\n\", 0, u);	==>	", 1);
	printf("-->|%-3.*u|<--\n", 0, u);
	my_ft_putstr_fd("Printf(\"-->|%-3.*u|<--\\n\", 1, u);	==>	", 1);
	printf("-->|%-3.*u|<--\n", 1, u);
	my_ft_putstr_fd("Printf(\"-->|%-3.*u|<--\\n\", 2, u);	==>	", 1);
	printf("-->|%-3.*u|<--\n", 2, u);
	my_ft_putstr_fd("Printf(\"-->|%-3.*u|<--\\n\", 3, u);	==>	", 1);
	printf("-->|%-3.*u|<--\n", 3, u);
	my_ft_putstr_fd("Printf(\"-->|%-3.*u|<--\\n\", 4, u);	==>	", 1);
	printf("-->|%-3.*u|<--\n", 4, u);
	my_ft_putstr_fd("Printf(\"-->|%-3.0u|<--\\n\", u);	==>	", 1);
	printf("-->|%-3.0u|<--\n", u);
	my_ft_putstr_fd("Printf(\"-->|%-3.1u|<--\\n\", u);	==>	", 1);
	printf("-->|%-3.1u|<--\n", u);
	my_ft_putstr_fd("Printf(\"-->|%-3.2u|<--\\n\", u);	==>	", 1);
	printf("-->|%-3.2u|<--\n", u);
	my_ft_putstr_fd("Printf(\"-->|%-3.3u|<--\\n\", u);	==>	", 1);
	printf("-->|%-3.3u|<--\n", u);
	my_ft_putstr_fd("Printf(\"-->|%-3.4u|<--\\n\", u);	==>	", 1);
	printf("-->|%-3.4u|<--\n", u);
	my_ft_putstr_fd("Printf(\"-->|%-3u|<--\\n\", u);	==>	", 1);
	printf("-->|%-3u|<--\n", u);
	my_ft_putstr_fd("Printf(\"-->|%-2.u|<--\\n\", u);	==>	", 1);
	printf("-->|%-2.u|<--\n", u);
	my_ft_putstr_fd("Printf(\"-->|%-2.*u|<--\\n\", -4, u);	==>	", 1);
	printf("-->|%-2.*u|<--\n", -4, u);
	my_ft_putstr_fd("Printf(\"-->|%-2.*u|<--\\n\", -3, u);	==>	", 1);
	printf("-->|%-2.*u|<--\n", -3, u);
	my_ft_putstr_fd("Printf(\"-->|%-2.*u|<--\\n\", -2, u);	==>	", 1);
	printf("-->|%-2.*u|<--\n", -2, u);
	my_ft_putstr_fd("Printf(\"-->|%-2.*u|<--\\n\", -1, u);	==>	", 1);
	printf("-->|%-2.*u|<--\n", -1, u);
	my_ft_putstr_fd("Printf(\"-->|%-2.*u|<--\\n\", 0, u);	==>	", 1);
	printf("-->|%-2.*u|<--\n", 0, u);
	my_ft_putstr_fd("Printf(\"-->|%-2.*u|<--\\n\", 1, u);	==>	", 1);
	printf("-->|%-2.*u|<--\n", 1, u);
	my_ft_putstr_fd("Printf(\"-->|%-2.*u|<--\\n\", 2, u);	==>	", 1);
	printf("-->|%-2.*u|<--\n", 2, u);
	my_ft_putstr_fd("Printf(\"-->|%-2.*u|<--\\n\", 3, u);	==>	", 1);
	printf("-->|%-2.*u|<--\n", 3, u);
	my_ft_putstr_fd("Printf(\"-->|%-2.*u|<--\\n\", 4, u);	==>	", 1);
	printf("-->|%-2.*u|<--\n", 4, u);
	my_ft_putstr_fd("Printf(\"-->|%-2.0u|<--\\n\", u);	==>	", 1);
	printf("-->|%-2.0u|<--\n", u);
	my_ft_putstr_fd("Printf(\"-->|%-2.1u|<--\\n\", u);	==>	", 1);
	printf("-->|%-2.1u|<--\n", u);
	my_ft_putstr_fd("Printf(\"-->|%-2.2u|<--\\n\", u);	==>	", 1);
	printf("-->|%-2.2u|<--\n", u);
	my_ft_putstr_fd("Printf(\"-->|%-2.3u|<--\\n\", u);	==>	", 1);
	printf("-->|%-2.3u|<--\n", u);
	my_ft_putstr_fd("Printf(\"-->|%-2.4u|<--\\n\", u);	==>	", 1);
	printf("-->|%-2.4u|<--\n", u);
	my_ft_putstr_fd("Printf(\"-->|%-2u|<--\\n\", u);	==>	", 1);
	printf("-->|%-2u|<--\n", u);
	my_ft_putstr_fd("Printf(\"-->|%-1.u|<--\\n\", u);	==>	", 1);
	printf("-->|%-1.u|<--\n", u);
	my_ft_putstr_fd("Printf(\"-->|%-1.*u|<--\\n\", -4, u);	==>	", 1);
	printf("-->|%-1.*u|<--\n", -4, u);
	my_ft_putstr_fd("Printf(\"-->|%-1.*u|<--\\n\", -3, u);	==>	", 1);
	printf("-->|%-1.*u|<--\n", -3, u);
	my_ft_putstr_fd("Printf(\"-->|%-1.*u|<--\\n\", -2, u);	==>	", 1);
	printf("-->|%-1.*u|<--\n", -2, u);
	my_ft_putstr_fd("Printf(\"-->|%-1.*u|<--\\n\", -1, u);	==>	", 1);
	printf("-->|%-1.*u|<--\n", -1, u);
	my_ft_putstr_fd("Printf(\"-->|%-1.*u|<--\\n\", 0, u);	==>	", 1);
	printf("-->|%-1.*u|<--\n", 0, u);
	my_ft_putstr_fd("Printf(\"-->|%-1.*u|<--\\n\", 1, u);	==>	", 1);
	printf("-->|%-1.*u|<--\n", 1, u);
	my_ft_putstr_fd("Printf(\"-->|%-1.*u|<--\\n\", 2, u);	==>	", 1);
	printf("-->|%-1.*u|<--\n", 2, u);
	my_ft_putstr_fd("Printf(\"-->|%-1.*u|<--\\n\", 3, u);	==>	", 1);
	printf("-->|%-1.*u|<--\n", 3, u);
	my_ft_putstr_fd("Printf(\"-->|%-1.*u|<--\\n\", 4, u);	==>	", 1);
	printf("-->|%-1.*u|<--\n", 4, u);
	my_ft_putstr_fd("Printf(\"-->|%-1.0u|<--\\n\", u);	==>	", 1);
	printf("-->|%-1.0u|<--\n", u);
	my_ft_putstr_fd("Printf(\"-->|%-1.1u|<--\\n\", u);	==>	", 1);
	printf("-->|%-1.1u|<--\n", u);
	my_ft_putstr_fd("Printf(\"-->|%-1.2u|<--\\n\", u);	==>	", 1);
	printf("-->|%-1.2u|<--\n", u);
	my_ft_putstr_fd("Printf(\"-->|%-1.3u|<--\\n\", u);	==>	", 1);
	printf("-->|%-1.3u|<--\n", u);
	my_ft_putstr_fd("Printf(\"-->|%-1.4u|<--\\n\", u);	==>	", 1);
	printf("-->|%-1.4u|<--\n", u);
	my_ft_putstr_fd("Printf(\"-->|%-1u|<--\\n\", u);	==>	", 1);
	printf("-->|%-1u|<--\n", u);
	my_ft_putstr_fd("Printf(\"-->|%.u|<--\\n\", u);	==>	", 1);
	printf("-->|%.u|<--\n", u);
	my_ft_putstr_fd("Printf(\"-->|%.*u|<--\\n\", -4, u);	==>	", 1);
	printf("-->|%.*u|<--\n", -4, u);
	my_ft_putstr_fd("Printf(\"-->|%.*u|<--\\n\", -3, u);	==>	", 1);
	printf("-->|%.*u|<--\n", -3, u);
	my_ft_putstr_fd("Printf(\"-->|%.*u|<--\\n\", -2, u);	==>	", 1);
	printf("-->|%.*u|<--\n", -2, u);
	my_ft_putstr_fd("Printf(\"-->|%.*u|<--\\n\", -1, u);	==>	", 1);
	printf("-->|%.*u|<--\n", -1, u);
	my_ft_putstr_fd("Printf(\"-->|%.*u|<--\\n\", 0, u);	==>	", 1);
	printf("-->|%.*u|<--\n", 0, u);
	my_ft_putstr_fd("Printf(\"-->|%.*u|<--\\n\", 1, u);	==>	", 1);
	printf("-->|%.*u|<--\n", 1, u);
	my_ft_putstr_fd("Printf(\"-->|%.*u|<--\\n\", 2, u);	==>	", 1);
	printf("-->|%.*u|<--\n", 2, u);
	my_ft_putstr_fd("Printf(\"-->|%.*u|<--\\n\", 3, u);	==>	", 1);
	printf("-->|%.*u|<--\n", 3, u);
	my_ft_putstr_fd("Printf(\"-->|%.*u|<--\\n\", 4, u);	==>	", 1);
	printf("-->|%.*u|<--\n", 4, u);
	my_ft_putstr_fd("Printf(\"-->|%.0u|<--\\n\", u);	==>	", 1);
	printf("-->|%.0u|<--\n", u);
	my_ft_putstr_fd("Printf(\"-->|%.1u|<--\\n\", u);	==>	", 1);
	printf("-->|%.1u|<--\n", u);
	my_ft_putstr_fd("Printf(\"-->|%.2u|<--\\n\", u);	==>	", 1);
	printf("-->|%.2u|<--\n", u);
	my_ft_putstr_fd("Printf(\"-->|%.3u|<--\\n\", u);	==>	", 1);
	printf("-->|%.3u|<--\n", u);
	my_ft_putstr_fd("Printf(\"-->|%.4u|<--\\n\", u);	==>	", 1);
	printf("-->|%.4u|<--\n", u);
	my_ft_putstr_fd("Printf(\"-->|%u|<--\\n\", u);	==>	", 1);
	printf("-->|%u|<--\n", u);
	my_ft_putstr_fd("Printf(\"-->|%*.u|<--\\n\", -4, u);	==>	", 1);
	printf("-->|%*.u|<--\n", -4, u);
	my_ft_putstr_fd("Printf(\"-->|%*.u|<--\\n\", -3, u);	==>	", 1);
	printf("-->|%*.u|<--\n", -3, u);
	my_ft_putstr_fd("Printf(\"-->|%*.u|<--\\n\", -2, u);	==>	", 1);
	printf("-->|%*.u|<--\n", -2, u);
	my_ft_putstr_fd("Printf(\"-->|%*.u|<--\\n\", -1, u);	==>	", 1);
	printf("-->|%*.u|<--\n", -1, u);
	my_ft_putstr_fd("Printf(\"-->|%*.u|<--\\n\", 0, u);	==>	", 1);
	printf("-->|%*.u|<--\n", 0, u);
	my_ft_putstr_fd("Printf(\"-->|%*.u|<--\\n\", 1, u);	==>	", 1);
	printf("-->|%*.u|<--\n", 1, u);
	my_ft_putstr_fd("Printf(\"-->|%*.u|<--\\n\", 2, u);	==>	", 1);
	printf("-->|%*.u|<--\n", 2, u);
	my_ft_putstr_fd("Printf(\"-->|%*.u|<--\\n\", 3, u);	==>	", 1);
	printf("-->|%*.u|<--\n", 3, u);
	my_ft_putstr_fd("Printf(\"-->|%*.u|<--\\n\", 4, u);	==>	", 1);
	printf("-->|%*.u|<--\n", 4, u);
	my_ft_putstr_fd("Printf(\"-->|%*.*u|<--\\n\", -4, -4, u);	==>	", 1);
	printf("-->|%*.*u|<--\n", -4, -4, u);
	my_ft_putstr_fd("Printf(\"-->|%*.*u|<--\\n\", -4, -3, u);	==>	", 1);
	printf("-->|%*.*u|<--\n", -4, -3, u);
	my_ft_putstr_fd("Printf(\"-->|%*.*u|<--\\n\", -4, -2, u);	==>	", 1);
	printf("-->|%*.*u|<--\n", -4, -2, u);
	my_ft_putstr_fd("Printf(\"-->|%*.*u|<--\\n\", -4, -1, u);	==>	", 1);
	printf("-->|%*.*u|<--\n", -4, -1, u);
	my_ft_putstr_fd("Printf(\"-->|%*.*u|<--\\n\", -4, 0, u);	==>	", 1);
	printf("-->|%*.*u|<--\n", -4, 0, u);
	my_ft_putstr_fd("Printf(\"-->|%*.*u|<--\\n\", -4, 1, u);	==>	", 1);
	printf("-->|%*.*u|<--\n", -4, 1, u);
	my_ft_putstr_fd("Printf(\"-->|%*.*u|<--\\n\", -4, 2, u);	==>	", 1);
	printf("-->|%*.*u|<--\n", -4, 2, u);
	my_ft_putstr_fd("Printf(\"-->|%*.*u|<--\\n\", -4, 3, u);	==>	", 1);
	printf("-->|%*.*u|<--\n", -4, 3, u);
	my_ft_putstr_fd("Printf(\"-->|%*.*u|<--\\n\", -4, 4, u);	==>	", 1);
	printf("-->|%*.*u|<--\n", -4, 4, u);
	my_ft_putstr_fd("Printf(\"-->|%*.*u|<--\\n\", -3, -4, u);	==>	", 1);
	printf("-->|%*.*u|<--\n", -3, -4, u);
	my_ft_putstr_fd("Printf(\"-->|%*.*u|<--\\n\", -3, -3, u);	==>	", 1);
	printf("-->|%*.*u|<--\n", -3, -3, u);
	my_ft_putstr_fd("Printf(\"-->|%*.*u|<--\\n\", -3, -2, u);	==>	", 1);
	printf("-->|%*.*u|<--\n", -3, -2, u);
	my_ft_putstr_fd("Printf(\"-->|%*.*u|<--\\n\", -3, -1, u);	==>	", 1);
	printf("-->|%*.*u|<--\n", -3, -1, u);
	my_ft_putstr_fd("Printf(\"-->|%*.*u|<--\\n\", -3, 0, u);	==>	", 1);
	printf("-->|%*.*u|<--\n", -3, 0, u);
	my_ft_putstr_fd("Printf(\"-->|%*.*u|<--\\n\", -3, 1, u);	==>	", 1);
	printf("-->|%*.*u|<--\n", -3, 1, u);
	my_ft_putstr_fd("Printf(\"-->|%*.*u|<--\\n\", -3, 2, u);	==>	", 1);
	printf("-->|%*.*u|<--\n", -3, 2, u);
	my_ft_putstr_fd("Printf(\"-->|%*.*u|<--\\n\", -3, 3, u);	==>	", 1);
	printf("-->|%*.*u|<--\n", -3, 3, u);
	my_ft_putstr_fd("Printf(\"-->|%*.*u|<--\\n\", -3, 4, u);	==>	", 1);
	printf("-->|%*.*u|<--\n", -3, 4, u);
	my_ft_putstr_fd("Printf(\"-->|%*.*u|<--\\n\", -2, -4, u);	==>	", 1);
	printf("-->|%*.*u|<--\n", -2, -4, u);
	my_ft_putstr_fd("Printf(\"-->|%*.*u|<--\\n\", -2, -3, u);	==>	", 1);
	printf("-->|%*.*u|<--\n", -2, -3, u);
	my_ft_putstr_fd("Printf(\"-->|%*.*u|<--\\n\", -2, -2, u);	==>	", 1);
	printf("-->|%*.*u|<--\n", -2, -2, u);
	my_ft_putstr_fd("Printf(\"-->|%*.*u|<--\\n\", -2, -1, u);	==>	", 1);
	printf("-->|%*.*u|<--\n", -2, -1, u);
	my_ft_putstr_fd("Printf(\"-->|%*.*u|<--\\n\", -2, 0, u);	==>	", 1);
	printf("-->|%*.*u|<--\n", -2, 0, u);
	my_ft_putstr_fd("Printf(\"-->|%*.*u|<--\\n\", -2, 1, u);	==>	", 1);
	printf("-->|%*.*u|<--\n", -2, 1, u);
	my_ft_putstr_fd("Printf(\"-->|%*.*u|<--\\n\", -2, 2, u);	==>	", 1);
	printf("-->|%*.*u|<--\n", -2, 2, u);
	my_ft_putstr_fd("Printf(\"-->|%*.*u|<--\\n\", -2, 3, u);	==>	", 1);
	printf("-->|%*.*u|<--\n", -2, 3, u);
	my_ft_putstr_fd("Printf(\"-->|%*.*u|<--\\n\", -2, 4, u);	==>	", 1);
	printf("-->|%*.*u|<--\n", -2, 4, u);
	my_ft_putstr_fd("Printf(\"-->|%*.*u|<--\\n\", -1, -4, u);	==>	", 1);
	printf("-->|%*.*u|<--\n", -1, -4, u);
	my_ft_putstr_fd("Printf(\"-->|%*.*u|<--\\n\", -1, -3, u);	==>	", 1);
	printf("-->|%*.*u|<--\n", -1, -3, u);
	my_ft_putstr_fd("Printf(\"-->|%*.*u|<--\\n\", -1, -2, u);	==>	", 1);
	printf("-->|%*.*u|<--\n", -1, -2, u);
	my_ft_putstr_fd("Printf(\"-->|%*.*u|<--\\n\", -1, -1, u);	==>	", 1);
	printf("-->|%*.*u|<--\n", -1, -1, u);
	my_ft_putstr_fd("Printf(\"-->|%*.*u|<--\\n\", -1, 0, u);	==>	", 1);
	printf("-->|%*.*u|<--\n", -1, 0, u);
	my_ft_putstr_fd("Printf(\"-->|%*.*u|<--\\n\", -1, 1, u);	==>	", 1);
	printf("-->|%*.*u|<--\n", -1, 1, u);
	my_ft_putstr_fd("Printf(\"-->|%*.*u|<--\\n\", -1, 2, u);	==>	", 1);
	printf("-->|%*.*u|<--\n", -1, 2, u);
	my_ft_putstr_fd("Printf(\"-->|%*.*u|<--\\n\", -1, 3, u);	==>	", 1);
	printf("-->|%*.*u|<--\n", -1, 3, u);
	my_ft_putstr_fd("Printf(\"-->|%*.*u|<--\\n\", -1, 4, u);	==>	", 1);
	printf("-->|%*.*u|<--\n", -1, 4, u);
	my_ft_putstr_fd("Printf(\"-->|%*.*u|<--\\n\", 0, -4, u);	==>	", 1);
	printf("-->|%*.*u|<--\n", 0, -4, u);
	my_ft_putstr_fd("Printf(\"-->|%*.*u|<--\\n\", 0, -3, u);	==>	", 1);
	printf("-->|%*.*u|<--\n", 0, -3, u);
	my_ft_putstr_fd("Printf(\"-->|%*.*u|<--\\n\", 0, -2, u);	==>	", 1);
	printf("-->|%*.*u|<--\n", 0, -2, u);
	my_ft_putstr_fd("Printf(\"-->|%*.*u|<--\\n\", 0, -1, u);	==>	", 1);
	printf("-->|%*.*u|<--\n", 0, -1, u);
	my_ft_putstr_fd("Printf(\"-->|%*.*u|<--\\n\", 0, 0, u);	==>	", 1);
	printf("-->|%*.*u|<--\n", 0, 0, u);
	my_ft_putstr_fd("Printf(\"-->|%*.*u|<--\\n\", 0, 1, u);	==>	", 1);
	printf("-->|%*.*u|<--\n", 0, 1, u);
	my_ft_putstr_fd("Printf(\"-->|%*.*u|<--\\n\", 0, 2, u);	==>	", 1);
	printf("-->|%*.*u|<--\n", 0, 2, u);
	my_ft_putstr_fd("Printf(\"-->|%*.*u|<--\\n\", 0, 3, u);	==>	", 1);
	printf("-->|%*.*u|<--\n", 0, 3, u);
	my_ft_putstr_fd("Printf(\"-->|%*.*u|<--\\n\", 0, 4, u);	==>	", 1);
	printf("-->|%*.*u|<--\n", 0, 4, u);
	my_ft_putstr_fd("Printf(\"-->|%*.*u|<--\\n\", 1, -4, u);	==>	", 1);
	printf("-->|%*.*u|<--\n", 1, -4, u);
	my_ft_putstr_fd("Printf(\"-->|%*.*u|<--\\n\", 1, -3, u);	==>	", 1);
	printf("-->|%*.*u|<--\n", 1, -3, u);
	my_ft_putstr_fd("Printf(\"-->|%*.*u|<--\\n\", 1, -2, u);	==>	", 1);
	printf("-->|%*.*u|<--\n", 1, -2, u);
	my_ft_putstr_fd("Printf(\"-->|%*.*u|<--\\n\", 1, -1, u);	==>	", 1);
	printf("-->|%*.*u|<--\n", 1, -1, u);
	my_ft_putstr_fd("Printf(\"-->|%*.*u|<--\\n\", 1, 0, u);	==>	", 1);
	printf("-->|%*.*u|<--\n", 1, 0, u);
	my_ft_putstr_fd("Printf(\"-->|%*.*u|<--\\n\", 1, 1, u);	==>	", 1);
	printf("-->|%*.*u|<--\n", 1, 1, u);
	my_ft_putstr_fd("Printf(\"-->|%*.*u|<--\\n\", 1, 2, u);	==>	", 1);
	printf("-->|%*.*u|<--\n", 1, 2, u);
	my_ft_putstr_fd("Printf(\"-->|%*.*u|<--\\n\", 1, 3, u);	==>	", 1);
	printf("-->|%*.*u|<--\n", 1, 3, u);
	my_ft_putstr_fd("Printf(\"-->|%*.*u|<--\\n\", 1, 4, u);	==>	", 1);
	printf("-->|%*.*u|<--\n", 1, 4, u);
	my_ft_putstr_fd("Printf(\"-->|%*.*u|<--\\n\", 2, -4, u);	==>	", 1);
	printf("-->|%*.*u|<--\n", 2, -4, u);
	my_ft_putstr_fd("Printf(\"-->|%*.*u|<--\\n\", 2, -3, u);	==>	", 1);
	printf("-->|%*.*u|<--\n", 2, -3, u);
	my_ft_putstr_fd("Printf(\"-->|%*.*u|<--\\n\", 2, -2, u);	==>	", 1);
	printf("-->|%*.*u|<--\n", 2, -2, u);
	my_ft_putstr_fd("Printf(\"-->|%*.*u|<--\\n\", 2, -1, u);	==>	", 1);
	printf("-->|%*.*u|<--\n", 2, -1, u);
	my_ft_putstr_fd("Printf(\"-->|%*.*u|<--\\n\", 2, 0, u);	==>	", 1);
	printf("-->|%*.*u|<--\n", 2, 0, u);
	my_ft_putstr_fd("Printf(\"-->|%*.*u|<--\\n\", 2, 1, u);	==>	", 1);
	printf("-->|%*.*u|<--\n", 2, 1, u);
	my_ft_putstr_fd("Printf(\"-->|%*.*u|<--\\n\", 2, 2, u);	==>	", 1);
	printf("-->|%*.*u|<--\n", 2, 2, u);
	my_ft_putstr_fd("Printf(\"-->|%*.*u|<--\\n\", 2, 3, u);	==>	", 1);
	printf("-->|%*.*u|<--\n", 2, 3, u);
	my_ft_putstr_fd("Printf(\"-->|%*.*u|<--\\n\", 2, 4, u);	==>	", 1);
	printf("-->|%*.*u|<--\n", 2, 4, u);
	my_ft_putstr_fd("Printf(\"-->|%*.*u|<--\\n\", 3, -4, u);	==>	", 1);
	printf("-->|%*.*u|<--\n", 3, -4, u);
	my_ft_putstr_fd("Printf(\"-->|%*.*u|<--\\n\", 3, -3, u);	==>	", 1);
	printf("-->|%*.*u|<--\n", 3, -3, u);
	my_ft_putstr_fd("Printf(\"-->|%*.*u|<--\\n\", 3, -2, u);	==>	", 1);
	printf("-->|%*.*u|<--\n", 3, -2, u);
	my_ft_putstr_fd("Printf(\"-->|%*.*u|<--\\n\", 3, -1, u);	==>	", 1);
	printf("-->|%*.*u|<--\n", 3, -1, u);
	my_ft_putstr_fd("Printf(\"-->|%*.*u|<--\\n\", 3, 0, u);	==>	", 1);
	printf("-->|%*.*u|<--\n", 3, 0, u);
	my_ft_putstr_fd("Printf(\"-->|%*.*u|<--\\n\", 3, 1, u);	==>	", 1);
	printf("-->|%*.*u|<--\n", 3, 1, u);
	my_ft_putstr_fd("Printf(\"-->|%*.*u|<--\\n\", 3, 2, u);	==>	", 1);
	printf("-->|%*.*u|<--\n", 3, 2, u);
	my_ft_putstr_fd("Printf(\"-->|%*.*u|<--\\n\", 3, 3, u);	==>	", 1);
	printf("-->|%*.*u|<--\n", 3, 3, u);
	my_ft_putstr_fd("Printf(\"-->|%*.*u|<--\\n\", 3, 4, u);	==>	", 1);
	printf("-->|%*.*u|<--\n", 3, 4, u);
	my_ft_putstr_fd("Printf(\"-->|%*.*u|<--\\n\", 4, -4, u);	==>	", 1);
	printf("-->|%*.*u|<--\n", 4, -4, u);
	my_ft_putstr_fd("Printf(\"-->|%*.*u|<--\\n\", 4, -3, u);	==>	", 1);
	printf("-->|%*.*u|<--\n", 4, -3, u);
	my_ft_putstr_fd("Printf(\"-->|%*.*u|<--\\n\", 4, -2, u);	==>	", 1);
	printf("-->|%*.*u|<--\n", 4, -2, u);
	my_ft_putstr_fd("Printf(\"-->|%*.*u|<--\\n\", 4, -1, u);	==>	", 1);
	printf("-->|%*.*u|<--\n", 4, -1, u);
	my_ft_putstr_fd("Printf(\"-->|%*.*u|<--\\n\", 4, 0, u);	==>	", 1);
	printf("-->|%*.*u|<--\n", 4, 0, u);
	my_ft_putstr_fd("Printf(\"-->|%*.*u|<--\\n\", 4, 1, u);	==>	", 1);
	printf("-->|%*.*u|<--\n", 4, 1, u);
	my_ft_putstr_fd("Printf(\"-->|%*.*u|<--\\n\", 4, 2, u);	==>	", 1);
	printf("-->|%*.*u|<--\n", 4, 2, u);
	my_ft_putstr_fd("Printf(\"-->|%*.*u|<--\\n\", 4, 3, u);	==>	", 1);
	printf("-->|%*.*u|<--\n", 4, 3, u);
	my_ft_putstr_fd("Printf(\"-->|%*.*u|<--\\n\", 4, 4, u);	==>	", 1);
	printf("-->|%*.*u|<--\n", 4, 4, u);
	my_ft_putstr_fd("Printf(\"-->|%*.0u|<--\\n\", -4, u);	==>	", 1);
	printf("-->|%*.0u|<--\n", -4, u);
	my_ft_putstr_fd("Printf(\"-->|%*.0u|<--\\n\", -3, u);	==>	", 1);
	printf("-->|%*.0u|<--\n", -3, u);
	my_ft_putstr_fd("Printf(\"-->|%*.0u|<--\\n\", -2, u);	==>	", 1);
	printf("-->|%*.0u|<--\n", -2, u);
	my_ft_putstr_fd("Printf(\"-->|%*.0u|<--\\n\", -1, u);	==>	", 1);
	printf("-->|%*.0u|<--\n", -1, u);
	my_ft_putstr_fd("Printf(\"-->|%*.0u|<--\\n\", 0, u);	==>	", 1);
	printf("-->|%*.0u|<--\n", 0, u);
	my_ft_putstr_fd("Printf(\"-->|%*.0u|<--\\n\", 1, u);	==>	", 1);
	printf("-->|%*.0u|<--\n", 1, u);
	my_ft_putstr_fd("Printf(\"-->|%*.0u|<--\\n\", 2, u);	==>	", 1);
	printf("-->|%*.0u|<--\n", 2, u);
	my_ft_putstr_fd("Printf(\"-->|%*.0u|<--\\n\", 3, u);	==>	", 1);
	printf("-->|%*.0u|<--\n", 3, u);
	my_ft_putstr_fd("Printf(\"-->|%*.0u|<--\\n\", 4, u);	==>	", 1);
	printf("-->|%*.0u|<--\n", 4, u);
	my_ft_putstr_fd("Printf(\"-->|%*.1u|<--\\n\", -4, u);	==>	", 1);
	printf("-->|%*.1u|<--\n", -4, u);
	my_ft_putstr_fd("Printf(\"-->|%*.1u|<--\\n\", -3, u);	==>	", 1);
	printf("-->|%*.1u|<--\n", -3, u);
	my_ft_putstr_fd("Printf(\"-->|%*.1u|<--\\n\", -2, u);	==>	", 1);
	printf("-->|%*.1u|<--\n", -2, u);
	my_ft_putstr_fd("Printf(\"-->|%*.1u|<--\\n\", -1, u);	==>	", 1);
	printf("-->|%*.1u|<--\n", -1, u);
	my_ft_putstr_fd("Printf(\"-->|%*.1u|<--\\n\", 0, u);	==>	", 1);
	printf("-->|%*.1u|<--\n", 0, u);
	my_ft_putstr_fd("Printf(\"-->|%*.1u|<--\\n\", 1, u);	==>	", 1);
	printf("-->|%*.1u|<--\n", 1, u);
	my_ft_putstr_fd("Printf(\"-->|%*.1u|<--\\n\", 2, u);	==>	", 1);
	printf("-->|%*.1u|<--\n", 2, u);
	my_ft_putstr_fd("Printf(\"-->|%*.1u|<--\\n\", 3, u);	==>	", 1);
	printf("-->|%*.1u|<--\n", 3, u);
	my_ft_putstr_fd("Printf(\"-->|%*.1u|<--\\n\", 4, u);	==>	", 1);
	printf("-->|%*.1u|<--\n", 4, u);
	my_ft_putstr_fd("Printf(\"-->|%*.2u|<--\\n\", -4, u);	==>	", 1);
	printf("-->|%*.2u|<--\n", -4, u);
	my_ft_putstr_fd("Printf(\"-->|%*.2u|<--\\n\", -3, u);	==>	", 1);
	printf("-->|%*.2u|<--\n", -3, u);
	my_ft_putstr_fd("Printf(\"-->|%*.2u|<--\\n\", -2, u);	==>	", 1);
	printf("-->|%*.2u|<--\n", -2, u);
	my_ft_putstr_fd("Printf(\"-->|%*.2u|<--\\n\", -1, u);	==>	", 1);
	printf("-->|%*.2u|<--\n", -1, u);
	my_ft_putstr_fd("Printf(\"-->|%*.2u|<--\\n\", 0, u);	==>	", 1);
	printf("-->|%*.2u|<--\n", 0, u);
	my_ft_putstr_fd("Printf(\"-->|%*.2u|<--\\n\", 1, u);	==>	", 1);
	printf("-->|%*.2u|<--\n", 1, u);
	my_ft_putstr_fd("Printf(\"-->|%*.2u|<--\\n\", 2, u);	==>	", 1);
	printf("-->|%*.2u|<--\n", 2, u);
	my_ft_putstr_fd("Printf(\"-->|%*.2u|<--\\n\", 3, u);	==>	", 1);
	printf("-->|%*.2u|<--\n", 3, u);
	my_ft_putstr_fd("Printf(\"-->|%*.2u|<--\\n\", 4, u);	==>	", 1);
	printf("-->|%*.2u|<--\n", 4, u);
	my_ft_putstr_fd("Printf(\"-->|%*.3u|<--\\n\", -4, u);	==>	", 1);
	printf("-->|%*.3u|<--\n", -4, u);
	my_ft_putstr_fd("Printf(\"-->|%*.3u|<--\\n\", -3, u);	==>	", 1);
	printf("-->|%*.3u|<--\n", -3, u);
	my_ft_putstr_fd("Printf(\"-->|%*.3u|<--\\n\", -2, u);	==>	", 1);
	printf("-->|%*.3u|<--\n", -2, u);
	my_ft_putstr_fd("Printf(\"-->|%*.3u|<--\\n\", -1, u);	==>	", 1);
	printf("-->|%*.3u|<--\n", -1, u);
	my_ft_putstr_fd("Printf(\"-->|%*.3u|<--\\n\", 0, u);	==>	", 1);
	printf("-->|%*.3u|<--\n", 0, u);
	my_ft_putstr_fd("Printf(\"-->|%*.3u|<--\\n\", 1, u);	==>	", 1);
	printf("-->|%*.3u|<--\n", 1, u);
	my_ft_putstr_fd("Printf(\"-->|%*.3u|<--\\n\", 2, u);	==>	", 1);
	printf("-->|%*.3u|<--\n", 2, u);
	my_ft_putstr_fd("Printf(\"-->|%*.3u|<--\\n\", 3, u);	==>	", 1);
	printf("-->|%*.3u|<--\n", 3, u);
	my_ft_putstr_fd("Printf(\"-->|%*.3u|<--\\n\", 4, u);	==>	", 1);
	printf("-->|%*.3u|<--\n", 4, u);
	my_ft_putstr_fd("Printf(\"-->|%*.4u|<--\\n\", -4, u);	==>	", 1);
	printf("-->|%*.4u|<--\n", -4, u);
	my_ft_putstr_fd("Printf(\"-->|%*.4u|<--\\n\", -3, u);	==>	", 1);
	printf("-->|%*.4u|<--\n", -3, u);
	my_ft_putstr_fd("Printf(\"-->|%*.4u|<--\\n\", -2, u);	==>	", 1);
	printf("-->|%*.4u|<--\n", -2, u);
	my_ft_putstr_fd("Printf(\"-->|%*.4u|<--\\n\", -1, u);	==>	", 1);
	printf("-->|%*.4u|<--\n", -1, u);
	my_ft_putstr_fd("Printf(\"-->|%*.4u|<--\\n\", 0, u);	==>	", 1);
	printf("-->|%*.4u|<--\n", 0, u);
	my_ft_putstr_fd("Printf(\"-->|%*.4u|<--\\n\", 1, u);	==>	", 1);
	printf("-->|%*.4u|<--\n", 1, u);
	my_ft_putstr_fd("Printf(\"-->|%*.4u|<--\\n\", 2, u);	==>	", 1);
	printf("-->|%*.4u|<--\n", 2, u);
	my_ft_putstr_fd("Printf(\"-->|%*.4u|<--\\n\", 3, u);	==>	", 1);
	printf("-->|%*.4u|<--\n", 3, u);
	my_ft_putstr_fd("Printf(\"-->|%*.4u|<--\\n\", 4, u);	==>	", 1);
	printf("-->|%*.4u|<--\n", 4, u);
	my_ft_putstr_fd("Printf(\"-->|%*u|<--\\n\", -4, u);	==>	", 1);
	printf("-->|%*u|<--\n", -4, u);
	my_ft_putstr_fd("Printf(\"-->|%*u|<--\\n\", -3, u);	==>	", 1);
	printf("-->|%*u|<--\n", -3, u);
	my_ft_putstr_fd("Printf(\"-->|%*u|<--\\n\", -2, u);	==>	", 1);
	printf("-->|%*u|<--\n", -2, u);
	my_ft_putstr_fd("Printf(\"-->|%*u|<--\\n\", -1, u);	==>	", 1);
	printf("-->|%*u|<--\n", -1, u);
	my_ft_putstr_fd("Printf(\"-->|%*u|<--\\n\", 0, u);	==>	", 1);
	printf("-->|%*u|<--\n", 0, u);
	my_ft_putstr_fd("Printf(\"-->|%*u|<--\\n\", 1, u);	==>	", 1);
	printf("-->|%*u|<--\n", 1, u);
	my_ft_putstr_fd("Printf(\"-->|%*u|<--\\n\", 2, u);	==>	", 1);
	printf("-->|%*u|<--\n", 2, u);
	my_ft_putstr_fd("Printf(\"-->|%*u|<--\\n\", 3, u);	==>	", 1);
	printf("-->|%*u|<--\n", 3, u);
	my_ft_putstr_fd("Printf(\"-->|%*u|<--\\n\", 4, u);	==>	", 1);
	printf("-->|%*u|<--\n", 4, u);
	my_ft_putstr_fd("Printf(\"-->|%0.u|<--\\n\", u);	==>	", 1);
	printf("-->|%0.u|<--\n", u);
	my_ft_putstr_fd("Printf(\"-->|%0.*u|<--\\n\", -4, u);	==>	", 1);
	printf("-->|%0.*u|<--\n", -4, u);
	my_ft_putstr_fd("Printf(\"-->|%0.*u|<--\\n\", -3, u);	==>	", 1);
	printf("-->|%0.*u|<--\n", -3, u);
	my_ft_putstr_fd("Printf(\"-->|%0.*u|<--\\n\", -2, u);	==>	", 1);
	printf("-->|%0.*u|<--\n", -2, u);
	my_ft_putstr_fd("Printf(\"-->|%0.*u|<--\\n\", -1, u);	==>	", 1);
	printf("-->|%0.*u|<--\n", -1, u);
	my_ft_putstr_fd("Printf(\"-->|%0.*u|<--\\n\", 0, u);	==>	", 1);
	printf("-->|%0.*u|<--\n", 0, u);
	my_ft_putstr_fd("Printf(\"-->|%0.*u|<--\\n\", 1, u);	==>	", 1);
	printf("-->|%0.*u|<--\n", 1, u);
	my_ft_putstr_fd("Printf(\"-->|%0.*u|<--\\n\", 2, u);	==>	", 1);
	printf("-->|%0.*u|<--\n", 2, u);
	my_ft_putstr_fd("Printf(\"-->|%0.*u|<--\\n\", 3, u);	==>	", 1);
	printf("-->|%0.*u|<--\n", 3, u);
	my_ft_putstr_fd("Printf(\"-->|%0.*u|<--\\n\", 4, u);	==>	", 1);
	printf("-->|%0.*u|<--\n", 4, u);
	my_ft_putstr_fd("Printf(\"-->|%0.0u|<--\\n\", u);	==>	", 1);
	printf("-->|%0.0u|<--\n", u);
	my_ft_putstr_fd("Printf(\"-->|%0.1u|<--\\n\", u);	==>	", 1);
	printf("-->|%0.1u|<--\n", u);
	my_ft_putstr_fd("Printf(\"-->|%0.2u|<--\\n\", u);	==>	", 1);
	printf("-->|%0.2u|<--\n", u);
	my_ft_putstr_fd("Printf(\"-->|%0.3u|<--\\n\", u);	==>	", 1);
	printf("-->|%0.3u|<--\n", u);
	my_ft_putstr_fd("Printf(\"-->|%0.4u|<--\\n\", u);	==>	", 1);
	printf("-->|%0.4u|<--\n", u);
	my_ft_putstr_fd("Printf(\"-->|%0u|<--\\n\", u);	==>	", 1);
	printf("-->|%0u|<--\n", u);
	my_ft_putstr_fd("Printf(\"-->|%1.u|<--\\n\", u);	==>	", 1);
	printf("-->|%1.u|<--\n", u);
	my_ft_putstr_fd("Printf(\"-->|%1.*u|<--\\n\", -4, u);	==>	", 1);
	printf("-->|%1.*u|<--\n", -4, u);
	my_ft_putstr_fd("Printf(\"-->|%1.*u|<--\\n\", -3, u);	==>	", 1);
	printf("-->|%1.*u|<--\n", -3, u);
	my_ft_putstr_fd("Printf(\"-->|%1.*u|<--\\n\", -2, u);	==>	", 1);
	printf("-->|%1.*u|<--\n", -2, u);
	my_ft_putstr_fd("Printf(\"-->|%1.*u|<--\\n\", -1, u);	==>	", 1);
	printf("-->|%1.*u|<--\n", -1, u);
	my_ft_putstr_fd("Printf(\"-->|%1.*u|<--\\n\", 0, u);	==>	", 1);
	printf("-->|%1.*u|<--\n", 0, u);
	my_ft_putstr_fd("Printf(\"-->|%1.*u|<--\\n\", 1, u);	==>	", 1);
	printf("-->|%1.*u|<--\n", 1, u);
	my_ft_putstr_fd("Printf(\"-->|%1.*u|<--\\n\", 2, u);	==>	", 1);
	printf("-->|%1.*u|<--\n", 2, u);
	my_ft_putstr_fd("Printf(\"-->|%1.*u|<--\\n\", 3, u);	==>	", 1);
	printf("-->|%1.*u|<--\n", 3, u);
	my_ft_putstr_fd("Printf(\"-->|%1.*u|<--\\n\", 4, u);	==>	", 1);
	printf("-->|%1.*u|<--\n", 4, u);
	my_ft_putstr_fd("Printf(\"-->|%1.0u|<--\\n\", u);	==>	", 1);
	printf("-->|%1.0u|<--\n", u);
	my_ft_putstr_fd("Printf(\"-->|%1.1u|<--\\n\", u);	==>	", 1);
	printf("-->|%1.1u|<--\n", u);
	my_ft_putstr_fd("Printf(\"-->|%1.2u|<--\\n\", u);	==>	", 1);
	printf("-->|%1.2u|<--\n", u);
	my_ft_putstr_fd("Printf(\"-->|%1.3u|<--\\n\", u);	==>	", 1);
	printf("-->|%1.3u|<--\n", u);
	my_ft_putstr_fd("Printf(\"-->|%1.4u|<--\\n\", u);	==>	", 1);
	printf("-->|%1.4u|<--\n", u);
	my_ft_putstr_fd("Printf(\"-->|%1u|<--\\n\", u);	==>	", 1);
	printf("-->|%1u|<--\n", u);
	my_ft_putstr_fd("Printf(\"-->|%2.u|<--\\n\", u);	==>	", 1);
	printf("-->|%2.u|<--\n", u);
	my_ft_putstr_fd("Printf(\"-->|%2.*u|<--\\n\", -4, u);	==>	", 1);
	printf("-->|%2.*u|<--\n", -4, u);
	my_ft_putstr_fd("Printf(\"-->|%2.*u|<--\\n\", -3, u);	==>	", 1);
	printf("-->|%2.*u|<--\n", -3, u);
	my_ft_putstr_fd("Printf(\"-->|%2.*u|<--\\n\", -2, u);	==>	", 1);
	printf("-->|%2.*u|<--\n", -2, u);
	my_ft_putstr_fd("Printf(\"-->|%2.*u|<--\\n\", -1, u);	==>	", 1);
	printf("-->|%2.*u|<--\n", -1, u);
	my_ft_putstr_fd("Printf(\"-->|%2.*u|<--\\n\", 0, u);	==>	", 1);
	printf("-->|%2.*u|<--\n", 0, u);
	my_ft_putstr_fd("Printf(\"-->|%2.*u|<--\\n\", 1, u);	==>	", 1);
	printf("-->|%2.*u|<--\n", 1, u);
	my_ft_putstr_fd("Printf(\"-->|%2.*u|<--\\n\", 2, u);	==>	", 1);
	printf("-->|%2.*u|<--\n", 2, u);
	my_ft_putstr_fd("Printf(\"-->|%2.*u|<--\\n\", 3, u);	==>	", 1);
	printf("-->|%2.*u|<--\n", 3, u);
	my_ft_putstr_fd("Printf(\"-->|%2.*u|<--\\n\", 4, u);	==>	", 1);
	printf("-->|%2.*u|<--\n", 4, u);
	my_ft_putstr_fd("Printf(\"-->|%2.0u|<--\\n\", u);	==>	", 1);
	printf("-->|%2.0u|<--\n", u);
	my_ft_putstr_fd("Printf(\"-->|%2.1u|<--\\n\", u);	==>	", 1);
	printf("-->|%2.1u|<--\n", u);
	my_ft_putstr_fd("Printf(\"-->|%2.2u|<--\\n\", u);	==>	", 1);
	printf("-->|%2.2u|<--\n", u);
	my_ft_putstr_fd("Printf(\"-->|%2.3u|<--\\n\", u);	==>	", 1);
	printf("-->|%2.3u|<--\n", u);
	my_ft_putstr_fd("Printf(\"-->|%2.4u|<--\\n\", u);	==>	", 1);
	printf("-->|%2.4u|<--\n", u);
	my_ft_putstr_fd("Printf(\"-->|%2u|<--\\n\", u);	==>	", 1);
	printf("-->|%2u|<--\n", u);
	my_ft_putstr_fd("Printf(\"-->|%3.u|<--\\n\", u);	==>	", 1);
	printf("-->|%3.u|<--\n", u);
	my_ft_putstr_fd("Printf(\"-->|%3.*u|<--\\n\", -4, u);	==>	", 1);
	printf("-->|%3.*u|<--\n", -4, u);
	my_ft_putstr_fd("Printf(\"-->|%3.*u|<--\\n\", -3, u);	==>	", 1);
	printf("-->|%3.*u|<--\n", -3, u);
	my_ft_putstr_fd("Printf(\"-->|%3.*u|<--\\n\", -2, u);	==>	", 1);
	printf("-->|%3.*u|<--\n", -2, u);
	my_ft_putstr_fd("Printf(\"-->|%3.*u|<--\\n\", -1, u);	==>	", 1);
	printf("-->|%3.*u|<--\n", -1, u);
	my_ft_putstr_fd("Printf(\"-->|%3.*u|<--\\n\", 0, u);	==>	", 1);
	printf("-->|%3.*u|<--\n", 0, u);
	my_ft_putstr_fd("Printf(\"-->|%3.*u|<--\\n\", 1, u);	==>	", 1);
	printf("-->|%3.*u|<--\n", 1, u);
	my_ft_putstr_fd("Printf(\"-->|%3.*u|<--\\n\", 2, u);	==>	", 1);
	printf("-->|%3.*u|<--\n", 2, u);
	my_ft_putstr_fd("Printf(\"-->|%3.*u|<--\\n\", 3, u);	==>	", 1);
	printf("-->|%3.*u|<--\n", 3, u);
	my_ft_putstr_fd("Printf(\"-->|%3.*u|<--\\n\", 4, u);	==>	", 1);
	printf("-->|%3.*u|<--\n", 4, u);
	my_ft_putstr_fd("Printf(\"-->|%3.0u|<--\\n\", u);	==>	", 1);
	printf("-->|%3.0u|<--\n", u);
	my_ft_putstr_fd("Printf(\"-->|%3.1u|<--\\n\", u);	==>	", 1);
	printf("-->|%3.1u|<--\n", u);
	my_ft_putstr_fd("Printf(\"-->|%3.2u|<--\\n\", u);	==>	", 1);
	printf("-->|%3.2u|<--\n", u);
	my_ft_putstr_fd("Printf(\"-->|%3.3u|<--\\n\", u);	==>	", 1);
	printf("-->|%3.3u|<--\n", u);
	my_ft_putstr_fd("Printf(\"-->|%3.4u|<--\\n\", u);	==>	", 1);
	printf("-->|%3.4u|<--\n", u);
	my_ft_putstr_fd("Printf(\"-->|%3u|<--\\n\", u);	==>	", 1);
	printf("-->|%3u|<--\n", u);
	my_ft_putstr_fd("Printf(\"-->|%4.u|<--\\n\", u);	==>	", 1);
	printf("-->|%4.u|<--\n", u);
	my_ft_putstr_fd("Printf(\"-->|%4.*u|<--\\n\", -4, u);	==>	", 1);
	printf("-->|%4.*u|<--\n", -4, u);
	my_ft_putstr_fd("Printf(\"-->|%4.*u|<--\\n\", -3, u);	==>	", 1);
	printf("-->|%4.*u|<--\n", -3, u);
	my_ft_putstr_fd("Printf(\"-->|%4.*u|<--\\n\", -2, u);	==>	", 1);
	printf("-->|%4.*u|<--\n", -2, u);
	my_ft_putstr_fd("Printf(\"-->|%4.*u|<--\\n\", -1, u);	==>	", 1);
	printf("-->|%4.*u|<--\n", -1, u);
	my_ft_putstr_fd("Printf(\"-->|%4.*u|<--\\n\", 0, u);	==>	", 1);
	printf("-->|%4.*u|<--\n", 0, u);
	my_ft_putstr_fd("Printf(\"-->|%4.*u|<--\\n\", 1, u);	==>	", 1);
	printf("-->|%4.*u|<--\n", 1, u);
	my_ft_putstr_fd("Printf(\"-->|%4.*u|<--\\n\", 2, u);	==>	", 1);
	printf("-->|%4.*u|<--\n", 2, u);
	my_ft_putstr_fd("Printf(\"-->|%4.*u|<--\\n\", 3, u);	==>	", 1);
	printf("-->|%4.*u|<--\n", 3, u);
	my_ft_putstr_fd("Printf(\"-->|%4.*u|<--\\n\", 4, u);	==>	", 1);
	printf("-->|%4.*u|<--\n", 4, u);
	my_ft_putstr_fd("Printf(\"-->|%4.0u|<--\\n\", u);	==>	", 1);
	printf("-->|%4.0u|<--\n", u);
	my_ft_putstr_fd("Printf(\"-->|%4.1u|<--\\n\", u);	==>	", 1);
	printf("-->|%4.1u|<--\n", u);
	my_ft_putstr_fd("Printf(\"-->|%4.2u|<--\\n\", u);	==>	", 1);
	printf("-->|%4.2u|<--\n", u);
	my_ft_putstr_fd("Printf(\"-->|%4.3u|<--\\n\", u);	==>	", 1);
	printf("-->|%4.3u|<--\n", u);
	my_ft_putstr_fd("Printf(\"-->|%4.4u|<--\\n\", u);	==>	", 1);
	printf("-->|%4.4u|<--\n", u);
	my_ft_putstr_fd("Printf(\"-->|%4u|<--\\n\", u);	==>	", 1);
	printf("-->|%4u|<--\n", u);
	my_ft_putstr_fd("Printf(\"-->|%0.u|<--\\n\", u);	==>	", 1);
	printf("-->|%0.u|<--\n", u);
	my_ft_putstr_fd("Printf(\"-->|%0.*u|<--\\n\", -4, u);	==>	", 1);
	printf("-->|%0.*u|<--\n", -4, u);
	my_ft_putstr_fd("Printf(\"-->|%0.*u|<--\\n\", -3, u);	==>	", 1);
	printf("-->|%0.*u|<--\n", -3, u);
	my_ft_putstr_fd("Printf(\"-->|%0.*u|<--\\n\", -2, u);	==>	", 1);
	printf("-->|%0.*u|<--\n", -2, u);
	my_ft_putstr_fd("Printf(\"-->|%0.*u|<--\\n\", -1, u);	==>	", 1);
	printf("-->|%0.*u|<--\n", -1, u);
	my_ft_putstr_fd("Printf(\"-->|%0.*u|<--\\n\", 0, u);	==>	", 1);
	printf("-->|%0.*u|<--\n", 0, u);
	my_ft_putstr_fd("Printf(\"-->|%0.*u|<--\\n\", 1, u);	==>	", 1);
	printf("-->|%0.*u|<--\n", 1, u);
	my_ft_putstr_fd("Printf(\"-->|%0.*u|<--\\n\", 2, u);	==>	", 1);
	printf("-->|%0.*u|<--\n", 2, u);
	my_ft_putstr_fd("Printf(\"-->|%0.*u|<--\\n\", 3, u);	==>	", 1);
	printf("-->|%0.*u|<--\n", 3, u);
	my_ft_putstr_fd("Printf(\"-->|%0.*u|<--\\n\", 4, u);	==>	", 1);
	printf("-->|%0.*u|<--\n", 4, u);
	my_ft_putstr_fd("Printf(\"-->|%0.0u|<--\\n\", u);	==>	", 1);
	printf("-->|%0.0u|<--\n", u);
	my_ft_putstr_fd("Printf(\"-->|%0.1u|<--\\n\", u);	==>	", 1);
	printf("-->|%0.1u|<--\n", u);
	my_ft_putstr_fd("Printf(\"-->|%0.2u|<--\\n\", u);	==>	", 1);
	printf("-->|%0.2u|<--\n", u);
	my_ft_putstr_fd("Printf(\"-->|%0.3u|<--\\n\", u);	==>	", 1);
	printf("-->|%0.3u|<--\n", u);
	my_ft_putstr_fd("Printf(\"-->|%0.4u|<--\\n\", u);	==>	", 1);
	printf("-->|%0.4u|<--\n", u);
	my_ft_putstr_fd("Printf(\"-->|%0u|<--\\n\", u);	==>	", 1);
	printf("-->|%0u|<--\n", u);
	my_ft_putstr_fd("Printf(\"-->|%0*.u|<--\\n\", -4, u);	==>	", 1);
	printf("-->|%0*.u|<--\n", -4, u);
	my_ft_putstr_fd("Printf(\"-->|%0*.u|<--\\n\", -3, u);	==>	", 1);
	printf("-->|%0*.u|<--\n", -3, u);
	my_ft_putstr_fd("Printf(\"-->|%0*.u|<--\\n\", -2, u);	==>	", 1);
	printf("-->|%0*.u|<--\n", -2, u);
	my_ft_putstr_fd("Printf(\"-->|%0*.u|<--\\n\", -1, u);	==>	", 1);
	printf("-->|%0*.u|<--\n", -1, u);
	my_ft_putstr_fd("Printf(\"-->|%0*.u|<--\\n\", 0, u);	==>	", 1);
	printf("-->|%0*.u|<--\n", 0, u);
	my_ft_putstr_fd("Printf(\"-->|%0*.u|<--\\n\", 1, u);	==>	", 1);
	printf("-->|%0*.u|<--\n", 1, u);
	my_ft_putstr_fd("Printf(\"-->|%0*.u|<--\\n\", 2, u);	==>	", 1);
	printf("-->|%0*.u|<--\n", 2, u);
	my_ft_putstr_fd("Printf(\"-->|%0*.u|<--\\n\", 3, u);	==>	", 1);
	printf("-->|%0*.u|<--\n", 3, u);
	my_ft_putstr_fd("Printf(\"-->|%0*.u|<--\\n\", 4, u);	==>	", 1);
	printf("-->|%0*.u|<--\n", 4, u);
	my_ft_putstr_fd("Printf(\"-->|%0*.*u|<--\\n\", -4, -4, u);	==>	", 1);
	printf("-->|%0*.*u|<--\n", -4, -4, u);
	my_ft_putstr_fd("Printf(\"-->|%0*.*u|<--\\n\", -4, -3, u);	==>	", 1);
	printf("-->|%0*.*u|<--\n", -4, -3, u);
	my_ft_putstr_fd("Printf(\"-->|%0*.*u|<--\\n\", -4, -2, u);	==>	", 1);
	printf("-->|%0*.*u|<--\n", -4, -2, u);
	my_ft_putstr_fd("Printf(\"-->|%0*.*u|<--\\n\", -4, -1, u);	==>	", 1);
	printf("-->|%0*.*u|<--\n", -4, -1, u);
	my_ft_putstr_fd("Printf(\"-->|%0*.*u|<--\\n\", -4, 0, u);	==>	", 1);
	printf("-->|%0*.*u|<--\n", -4, 0, u);
	my_ft_putstr_fd("Printf(\"-->|%0*.*u|<--\\n\", -4, 1, u);	==>	", 1);
	printf("-->|%0*.*u|<--\n", -4, 1, u);
	my_ft_putstr_fd("Printf(\"-->|%0*.*u|<--\\n\", -4, 2, u);	==>	", 1);
	printf("-->|%0*.*u|<--\n", -4, 2, u);
	my_ft_putstr_fd("Printf(\"-->|%0*.*u|<--\\n\", -4, 3, u);	==>	", 1);
	printf("-->|%0*.*u|<--\n", -4, 3, u);
	my_ft_putstr_fd("Printf(\"-->|%0*.*u|<--\\n\", -4, 4, u);	==>	", 1);
	printf("-->|%0*.*u|<--\n", -4, 4, u);
	my_ft_putstr_fd("Printf(\"-->|%0*.*u|<--\\n\", -3, -4, u);	==>	", 1);
	printf("-->|%0*.*u|<--\n", -3, -4, u);
	my_ft_putstr_fd("Printf(\"-->|%0*.*u|<--\\n\", -3, -3, u);	==>	", 1);
	printf("-->|%0*.*u|<--\n", -3, -3, u);
	my_ft_putstr_fd("Printf(\"-->|%0*.*u|<--\\n\", -3, -2, u);	==>	", 1);
	printf("-->|%0*.*u|<--\n", -3, -2, u);
	my_ft_putstr_fd("Printf(\"-->|%0*.*u|<--\\n\", -3, -1, u);	==>	", 1);
	printf("-->|%0*.*u|<--\n", -3, -1, u);
	my_ft_putstr_fd("Printf(\"-->|%0*.*u|<--\\n\", -3, 0, u);	==>	", 1);
	printf("-->|%0*.*u|<--\n", -3, 0, u);
	my_ft_putstr_fd("Printf(\"-->|%0*.*u|<--\\n\", -3, 1, u);	==>	", 1);
	printf("-->|%0*.*u|<--\n", -3, 1, u);
	my_ft_putstr_fd("Printf(\"-->|%0*.*u|<--\\n\", -3, 2, u);	==>	", 1);
	printf("-->|%0*.*u|<--\n", -3, 2, u);
	my_ft_putstr_fd("Printf(\"-->|%0*.*u|<--\\n\", -3, 3, u);	==>	", 1);
	printf("-->|%0*.*u|<--\n", -3, 3, u);
	my_ft_putstr_fd("Printf(\"-->|%0*.*u|<--\\n\", -3, 4, u);	==>	", 1);
	printf("-->|%0*.*u|<--\n", -3, 4, u);
	my_ft_putstr_fd("Printf(\"-->|%0*.*u|<--\\n\", -2, -4, u);	==>	", 1);
	printf("-->|%0*.*u|<--\n", -2, -4, u);
	my_ft_putstr_fd("Printf(\"-->|%0*.*u|<--\\n\", -2, -3, u);	==>	", 1);
	printf("-->|%0*.*u|<--\n", -2, -3, u);
	my_ft_putstr_fd("Printf(\"-->|%0*.*u|<--\\n\", -2, -2, u);	==>	", 1);
	printf("-->|%0*.*u|<--\n", -2, -2, u);
	my_ft_putstr_fd("Printf(\"-->|%0*.*u|<--\\n\", -2, -1, u);	==>	", 1);
	printf("-->|%0*.*u|<--\n", -2, -1, u);
	my_ft_putstr_fd("Printf(\"-->|%0*.*u|<--\\n\", -2, 0, u);	==>	", 1);
	printf("-->|%0*.*u|<--\n", -2, 0, u);
	my_ft_putstr_fd("Printf(\"-->|%0*.*u|<--\\n\", -2, 1, u);	==>	", 1);
	printf("-->|%0*.*u|<--\n", -2, 1, u);
	my_ft_putstr_fd("Printf(\"-->|%0*.*u|<--\\n\", -2, 2, u);	==>	", 1);
	printf("-->|%0*.*u|<--\n", -2, 2, u);
	my_ft_putstr_fd("Printf(\"-->|%0*.*u|<--\\n\", -2, 3, u);	==>	", 1);
	printf("-->|%0*.*u|<--\n", -2, 3, u);
	my_ft_putstr_fd("Printf(\"-->|%0*.*u|<--\\n\", -2, 4, u);	==>	", 1);
	printf("-->|%0*.*u|<--\n", -2, 4, u);
	my_ft_putstr_fd("Printf(\"-->|%0*.*u|<--\\n\", -1, -4, u);	==>	", 1);
	printf("-->|%0*.*u|<--\n", -1, -4, u);
	my_ft_putstr_fd("Printf(\"-->|%0*.*u|<--\\n\", -1, -3, u);	==>	", 1);
	printf("-->|%0*.*u|<--\n", -1, -3, u);
	my_ft_putstr_fd("Printf(\"-->|%0*.*u|<--\\n\", -1, -2, u);	==>	", 1);
	printf("-->|%0*.*u|<--\n", -1, -2, u);
	my_ft_putstr_fd("Printf(\"-->|%0*.*u|<--\\n\", -1, -1, u);	==>	", 1);
	printf("-->|%0*.*u|<--\n", -1, -1, u);
	my_ft_putstr_fd("Printf(\"-->|%0*.*u|<--\\n\", -1, 0, u);	==>	", 1);
	printf("-->|%0*.*u|<--\n", -1, 0, u);
	my_ft_putstr_fd("Printf(\"-->|%0*.*u|<--\\n\", -1, 1, u);	==>	", 1);
	printf("-->|%0*.*u|<--\n", -1, 1, u);
	my_ft_putstr_fd("Printf(\"-->|%0*.*u|<--\\n\", -1, 2, u);	==>	", 1);
	printf("-->|%0*.*u|<--\n", -1, 2, u);
	my_ft_putstr_fd("Printf(\"-->|%0*.*u|<--\\n\", -1, 3, u);	==>	", 1);
	printf("-->|%0*.*u|<--\n", -1, 3, u);
	my_ft_putstr_fd("Printf(\"-->|%0*.*u|<--\\n\", -1, 4, u);	==>	", 1);
	printf("-->|%0*.*u|<--\n", -1, 4, u);
	my_ft_putstr_fd("Printf(\"-->|%0*.*u|<--\\n\", 0, -4, u);	==>	", 1);
	printf("-->|%0*.*u|<--\n", 0, -4, u);
	my_ft_putstr_fd("Printf(\"-->|%0*.*u|<--\\n\", 0, -3, u);	==>	", 1);
	printf("-->|%0*.*u|<--\n", 0, -3, u);
	my_ft_putstr_fd("Printf(\"-->|%0*.*u|<--\\n\", 0, -2, u);	==>	", 1);
	printf("-->|%0*.*u|<--\n", 0, -2, u);
	my_ft_putstr_fd("Printf(\"-->|%0*.*u|<--\\n\", 0, -1, u);	==>	", 1);
	printf("-->|%0*.*u|<--\n", 0, -1, u);
	my_ft_putstr_fd("Printf(\"-->|%0*.*u|<--\\n\", 0, 0, u);	==>	", 1);
	printf("-->|%0*.*u|<--\n", 0, 0, u);
	my_ft_putstr_fd("Printf(\"-->|%0*.*u|<--\\n\", 0, 1, u);	==>	", 1);
	printf("-->|%0*.*u|<--\n", 0, 1, u);
	my_ft_putstr_fd("Printf(\"-->|%0*.*u|<--\\n\", 0, 2, u);	==>	", 1);
	printf("-->|%0*.*u|<--\n", 0, 2, u);
	my_ft_putstr_fd("Printf(\"-->|%0*.*u|<--\\n\", 0, 3, u);	==>	", 1);
	printf("-->|%0*.*u|<--\n", 0, 3, u);
	my_ft_putstr_fd("Printf(\"-->|%0*.*u|<--\\n\", 0, 4, u);	==>	", 1);
	printf("-->|%0*.*u|<--\n", 0, 4, u);
	my_ft_putstr_fd("Printf(\"-->|%0*.*u|<--\\n\", 1, -4, u);	==>	", 1);
	printf("-->|%0*.*u|<--\n", 1, -4, u);
	my_ft_putstr_fd("Printf(\"-->|%0*.*u|<--\\n\", 1, -3, u);	==>	", 1);
	printf("-->|%0*.*u|<--\n", 1, -3, u);
	my_ft_putstr_fd("Printf(\"-->|%0*.*u|<--\\n\", 1, -2, u);	==>	", 1);
	printf("-->|%0*.*u|<--\n", 1, -2, u);
	my_ft_putstr_fd("Printf(\"-->|%0*.*u|<--\\n\", 1, -1, u);	==>	", 1);
	printf("-->|%0*.*u|<--\n", 1, -1, u);
	my_ft_putstr_fd("Printf(\"-->|%0*.*u|<--\\n\", 1, 0, u);	==>	", 1);
	printf("-->|%0*.*u|<--\n", 1, 0, u);
	my_ft_putstr_fd("Printf(\"-->|%0*.*u|<--\\n\", 1, 1, u);	==>	", 1);
	printf("-->|%0*.*u|<--\n", 1, 1, u);
	my_ft_putstr_fd("Printf(\"-->|%0*.*u|<--\\n\", 1, 2, u);	==>	", 1);
	printf("-->|%0*.*u|<--\n", 1, 2, u);
	my_ft_putstr_fd("Printf(\"-->|%0*.*u|<--\\n\", 1, 3, u);	==>	", 1);
	printf("-->|%0*.*u|<--\n", 1, 3, u);
	my_ft_putstr_fd("Printf(\"-->|%0*.*u|<--\\n\", 1, 4, u);	==>	", 1);
	printf("-->|%0*.*u|<--\n", 1, 4, u);
	my_ft_putstr_fd("Printf(\"-->|%0*.*u|<--\\n\", 2, -4, u);	==>	", 1);
	printf("-->|%0*.*u|<--\n", 2, -4, u);
	my_ft_putstr_fd("Printf(\"-->|%0*.*u|<--\\n\", 2, -3, u);	==>	", 1);
	printf("-->|%0*.*u|<--\n", 2, -3, u);
	my_ft_putstr_fd("Printf(\"-->|%0*.*u|<--\\n\", 2, -2, u);	==>	", 1);
	printf("-->|%0*.*u|<--\n", 2, -2, u);
	my_ft_putstr_fd("Printf(\"-->|%0*.*u|<--\\n\", 2, -1, u);	==>	", 1);
	printf("-->|%0*.*u|<--\n", 2, -1, u);
	my_ft_putstr_fd("Printf(\"-->|%0*.*u|<--\\n\", 2, 0, u);	==>	", 1);
	printf("-->|%0*.*u|<--\n", 2, 0, u);
	my_ft_putstr_fd("Printf(\"-->|%0*.*u|<--\\n\", 2, 1, u);	==>	", 1);
	printf("-->|%0*.*u|<--\n", 2, 1, u);
	my_ft_putstr_fd("Printf(\"-->|%0*.*u|<--\\n\", 2, 2, u);	==>	", 1);
	printf("-->|%0*.*u|<--\n", 2, 2, u);
	my_ft_putstr_fd("Printf(\"-->|%0*.*u|<--\\n\", 2, 3, u);	==>	", 1);
	printf("-->|%0*.*u|<--\n", 2, 3, u);
	my_ft_putstr_fd("Printf(\"-->|%0*.*u|<--\\n\", 2, 4, u);	==>	", 1);
	printf("-->|%0*.*u|<--\n", 2, 4, u);
	my_ft_putstr_fd("Printf(\"-->|%0*.*u|<--\\n\", 3, -4, u);	==>	", 1);
	printf("-->|%0*.*u|<--\n", 3, -4, u);
	my_ft_putstr_fd("Printf(\"-->|%0*.*u|<--\\n\", 3, -3, u);	==>	", 1);
	printf("-->|%0*.*u|<--\n", 3, -3, u);
	my_ft_putstr_fd("Printf(\"-->|%0*.*u|<--\\n\", 3, -2, u);	==>	", 1);
	printf("-->|%0*.*u|<--\n", 3, -2, u);
	my_ft_putstr_fd("Printf(\"-->|%0*.*u|<--\\n\", 3, -1, u);	==>	", 1);
	printf("-->|%0*.*u|<--\n", 3, -1, u);
	my_ft_putstr_fd("Printf(\"-->|%0*.*u|<--\\n\", 3, 0, u);	==>	", 1);
	printf("-->|%0*.*u|<--\n", 3, 0, u);
	my_ft_putstr_fd("Printf(\"-->|%0*.*u|<--\\n\", 3, 1, u);	==>	", 1);
	printf("-->|%0*.*u|<--\n", 3, 1, u);
	my_ft_putstr_fd("Printf(\"-->|%0*.*u|<--\\n\", 3, 2, u);	==>	", 1);
	printf("-->|%0*.*u|<--\n", 3, 2, u);
	my_ft_putstr_fd("Printf(\"-->|%0*.*u|<--\\n\", 3, 3, u);	==>	", 1);
	printf("-->|%0*.*u|<--\n", 3, 3, u);
	my_ft_putstr_fd("Printf(\"-->|%0*.*u|<--\\n\", 3, 4, u);	==>	", 1);
	printf("-->|%0*.*u|<--\n", 3, 4, u);
	my_ft_putstr_fd("Printf(\"-->|%0*.*u|<--\\n\", 4, -4, u);	==>	", 1);
	printf("-->|%0*.*u|<--\n", 4, -4, u);
	my_ft_putstr_fd("Printf(\"-->|%0*.*u|<--\\n\", 4, -3, u);	==>	", 1);
	printf("-->|%0*.*u|<--\n", 4, -3, u);
	my_ft_putstr_fd("Printf(\"-->|%0*.*u|<--\\n\", 4, -2, u);	==>	", 1);
	printf("-->|%0*.*u|<--\n", 4, -2, u);
	my_ft_putstr_fd("Printf(\"-->|%0*.*u|<--\\n\", 4, -1, u);	==>	", 1);
	printf("-->|%0*.*u|<--\n", 4, -1, u);
	my_ft_putstr_fd("Printf(\"-->|%0*.*u|<--\\n\", 4, 0, u);	==>	", 1);
	printf("-->|%0*.*u|<--\n", 4, 0, u);
	my_ft_putstr_fd("Printf(\"-->|%0*.*u|<--\\n\", 4, 1, u);	==>	", 1);
	printf("-->|%0*.*u|<--\n", 4, 1, u);
	my_ft_putstr_fd("Printf(\"-->|%0*.*u|<--\\n\", 4, 2, u);	==>	", 1);
	printf("-->|%0*.*u|<--\n", 4, 2, u);
	my_ft_putstr_fd("Printf(\"-->|%0*.*u|<--\\n\", 4, 3, u);	==>	", 1);
	printf("-->|%0*.*u|<--\n", 4, 3, u);
	my_ft_putstr_fd("Printf(\"-->|%0*.*u|<--\\n\", 4, 4, u);	==>	", 1);
	printf("-->|%0*.*u|<--\n", 4, 4, u);
	my_ft_putstr_fd("Printf(\"-->|%0*.0u|<--\\n\", -4, u);	==>	", 1);
	printf("-->|%0*.0u|<--\n", -4, u);
	my_ft_putstr_fd("Printf(\"-->|%0*.0u|<--\\n\", -3, u);	==>	", 1);
	printf("-->|%0*.0u|<--\n", -3, u);
	my_ft_putstr_fd("Printf(\"-->|%0*.0u|<--\\n\", -2, u);	==>	", 1);
	printf("-->|%0*.0u|<--\n", -2, u);
	my_ft_putstr_fd("Printf(\"-->|%0*.0u|<--\\n\", -1, u);	==>	", 1);
	printf("-->|%0*.0u|<--\n", -1, u);
	my_ft_putstr_fd("Printf(\"-->|%0*.0u|<--\\n\", 0, u);	==>	", 1);
	printf("-->|%0*.0u|<--\n", 0, u);
	my_ft_putstr_fd("Printf(\"-->|%0*.0u|<--\\n\", 1, u);	==>	", 1);
	printf("-->|%0*.0u|<--\n", 1, u);
	my_ft_putstr_fd("Printf(\"-->|%0*.0u|<--\\n\", 2, u);	==>	", 1);
	printf("-->|%0*.0u|<--\n", 2, u);
	my_ft_putstr_fd("Printf(\"-->|%0*.0u|<--\\n\", 3, u);	==>	", 1);
	printf("-->|%0*.0u|<--\n", 3, u);
	my_ft_putstr_fd("Printf(\"-->|%0*.0u|<--\\n\", 4, u);	==>	", 1);
	printf("-->|%0*.0u|<--\n", 4, u);
	my_ft_putstr_fd("Printf(\"-->|%0*.1u|<--\\n\", -4, u);	==>	", 1);
	printf("-->|%0*.1u|<--\n", -4, u);
	my_ft_putstr_fd("Printf(\"-->|%0*.1u|<--\\n\", -3, u);	==>	", 1);
	printf("-->|%0*.1u|<--\n", -3, u);
	my_ft_putstr_fd("Printf(\"-->|%0*.1u|<--\\n\", -2, u);	==>	", 1);
	printf("-->|%0*.1u|<--\n", -2, u);
	my_ft_putstr_fd("Printf(\"-->|%0*.1u|<--\\n\", -1, u);	==>	", 1);
	printf("-->|%0*.1u|<--\n", -1, u);
	my_ft_putstr_fd("Printf(\"-->|%0*.1u|<--\\n\", 0, u);	==>	", 1);
	printf("-->|%0*.1u|<--\n", 0, u);
	my_ft_putstr_fd("Printf(\"-->|%0*.1u|<--\\n\", 1, u);	==>	", 1);
	printf("-->|%0*.1u|<--\n", 1, u);
	my_ft_putstr_fd("Printf(\"-->|%0*.1u|<--\\n\", 2, u);	==>	", 1);
	printf("-->|%0*.1u|<--\n", 2, u);
	my_ft_putstr_fd("Printf(\"-->|%0*.1u|<--\\n\", 3, u);	==>	", 1);
	printf("-->|%0*.1u|<--\n", 3, u);
	my_ft_putstr_fd("Printf(\"-->|%0*.1u|<--\\n\", 4, u);	==>	", 1);
	printf("-->|%0*.1u|<--\n", 4, u);
	my_ft_putstr_fd("Printf(\"-->|%0*.2u|<--\\n\", -4, u);	==>	", 1);
	printf("-->|%0*.2u|<--\n", -4, u);
	my_ft_putstr_fd("Printf(\"-->|%0*.2u|<--\\n\", -3, u);	==>	", 1);
	printf("-->|%0*.2u|<--\n", -3, u);
	my_ft_putstr_fd("Printf(\"-->|%0*.2u|<--\\n\", -2, u);	==>	", 1);
	printf("-->|%0*.2u|<--\n", -2, u);
	my_ft_putstr_fd("Printf(\"-->|%0*.2u|<--\\n\", -1, u);	==>	", 1);
	printf("-->|%0*.2u|<--\n", -1, u);
	my_ft_putstr_fd("Printf(\"-->|%0*.2u|<--\\n\", 0, u);	==>	", 1);
	printf("-->|%0*.2u|<--\n", 0, u);
	my_ft_putstr_fd("Printf(\"-->|%0*.2u|<--\\n\", 1, u);	==>	", 1);
	printf("-->|%0*.2u|<--\n", 1, u);
	my_ft_putstr_fd("Printf(\"-->|%0*.2u|<--\\n\", 2, u);	==>	", 1);
	printf("-->|%0*.2u|<--\n", 2, u);
	my_ft_putstr_fd("Printf(\"-->|%0*.2u|<--\\n\", 3, u);	==>	", 1);
	printf("-->|%0*.2u|<--\n", 3, u);
	my_ft_putstr_fd("Printf(\"-->|%0*.2u|<--\\n\", 4, u);	==>	", 1);
	printf("-->|%0*.2u|<--\n", 4, u);
	my_ft_putstr_fd("Printf(\"-->|%0*.3u|<--\\n\", -4, u);	==>	", 1);
	printf("-->|%0*.3u|<--\n", -4, u);
	my_ft_putstr_fd("Printf(\"-->|%0*.3u|<--\\n\", -3, u);	==>	", 1);
	printf("-->|%0*.3u|<--\n", -3, u);
	my_ft_putstr_fd("Printf(\"-->|%0*.3u|<--\\n\", -2, u);	==>	", 1);
	printf("-->|%0*.3u|<--\n", -2, u);
	my_ft_putstr_fd("Printf(\"-->|%0*.3u|<--\\n\", -1, u);	==>	", 1);
	printf("-->|%0*.3u|<--\n", -1, u);
	my_ft_putstr_fd("Printf(\"-->|%0*.3u|<--\\n\", 0, u);	==>	", 1);
	printf("-->|%0*.3u|<--\n", 0, u);
	my_ft_putstr_fd("Printf(\"-->|%0*.3u|<--\\n\", 1, u);	==>	", 1);
	printf("-->|%0*.3u|<--\n", 1, u);
	my_ft_putstr_fd("Printf(\"-->|%0*.3u|<--\\n\", 2, u);	==>	", 1);
	printf("-->|%0*.3u|<--\n", 2, u);
	my_ft_putstr_fd("Printf(\"-->|%0*.3u|<--\\n\", 3, u);	==>	", 1);
	printf("-->|%0*.3u|<--\n", 3, u);
	my_ft_putstr_fd("Printf(\"-->|%0*.3u|<--\\n\", 4, u);	==>	", 1);
	printf("-->|%0*.3u|<--\n", 4, u);
	my_ft_putstr_fd("Printf(\"-->|%0*.4u|<--\\n\", -4, u);	==>	", 1);
	printf("-->|%0*.4u|<--\n", -4, u);
	my_ft_putstr_fd("Printf(\"-->|%0*.4u|<--\\n\", -3, u);	==>	", 1);
	printf("-->|%0*.4u|<--\n", -3, u);
	my_ft_putstr_fd("Printf(\"-->|%0*.4u|<--\\n\", -2, u);	==>	", 1);
	printf("-->|%0*.4u|<--\n", -2, u);
	my_ft_putstr_fd("Printf(\"-->|%0*.4u|<--\\n\", -1, u);	==>	", 1);
	printf("-->|%0*.4u|<--\n", -1, u);
	my_ft_putstr_fd("Printf(\"-->|%0*.4u|<--\\n\", 0, u);	==>	", 1);
	printf("-->|%0*.4u|<--\n", 0, u);
	my_ft_putstr_fd("Printf(\"-->|%0*.4u|<--\\n\", 1, u);	==>	", 1);
	printf("-->|%0*.4u|<--\n", 1, u);
	my_ft_putstr_fd("Printf(\"-->|%0*.4u|<--\\n\", 2, u);	==>	", 1);
	printf("-->|%0*.4u|<--\n", 2, u);
	my_ft_putstr_fd("Printf(\"-->|%0*.4u|<--\\n\", 3, u);	==>	", 1);
	printf("-->|%0*.4u|<--\n", 3, u);
	my_ft_putstr_fd("Printf(\"-->|%0*.4u|<--\\n\", 4, u);	==>	", 1);
	printf("-->|%0*.4u|<--\n", 4, u);
	my_ft_putstr_fd("Printf(\"-->|%0*u|<--\\n\", -4, u);	==>	", 1);
	printf("-->|%0*u|<--\n", -4, u);
	my_ft_putstr_fd("Printf(\"-->|%0*u|<--\\n\", -3, u);	==>	", 1);
	printf("-->|%0*u|<--\n", -3, u);
	my_ft_putstr_fd("Printf(\"-->|%0*u|<--\\n\", -2, u);	==>	", 1);
	printf("-->|%0*u|<--\n", -2, u);
	my_ft_putstr_fd("Printf(\"-->|%0*u|<--\\n\", -1, u);	==>	", 1);
	printf("-->|%0*u|<--\n", -1, u);
	my_ft_putstr_fd("Printf(\"-->|%0*u|<--\\n\", 0, u);	==>	", 1);
	printf("-->|%0*u|<--\n", 0, u);
	my_ft_putstr_fd("Printf(\"-->|%0*u|<--\\n\", 1, u);	==>	", 1);
	printf("-->|%0*u|<--\n", 1, u);
	my_ft_putstr_fd("Printf(\"-->|%0*u|<--\\n\", 2, u);	==>	", 1);
	printf("-->|%0*u|<--\n", 2, u);
	my_ft_putstr_fd("Printf(\"-->|%0*u|<--\\n\", 3, u);	==>	", 1);
	printf("-->|%0*u|<--\n", 3, u);
	my_ft_putstr_fd("Printf(\"-->|%0*u|<--\\n\", 4, u);	==>	", 1);
	printf("-->|%0*u|<--\n", 4, u);
	my_ft_putstr_fd("Printf(\"-->|%00.u|<--\\n\", u);	==>	", 1);
	printf("-->|%00.u|<--\n", u);
	my_ft_putstr_fd("Printf(\"-->|%00.*u|<--\\n\", -4, u);	==>	", 1);
	printf("-->|%00.*u|<--\n", -4, u);
	my_ft_putstr_fd("Printf(\"-->|%00.*u|<--\\n\", -3, u);	==>	", 1);
	printf("-->|%00.*u|<--\n", -3, u);
	my_ft_putstr_fd("Printf(\"-->|%00.*u|<--\\n\", -2, u);	==>	", 1);
	printf("-->|%00.*u|<--\n", -2, u);
	my_ft_putstr_fd("Printf(\"-->|%00.*u|<--\\n\", -1, u);	==>	", 1);
	printf("-->|%00.*u|<--\n", -1, u);
	my_ft_putstr_fd("Printf(\"-->|%00.*u|<--\\n\", 0, u);	==>	", 1);
	printf("-->|%00.*u|<--\n", 0, u);
	my_ft_putstr_fd("Printf(\"-->|%00.*u|<--\\n\", 1, u);	==>	", 1);
	printf("-->|%00.*u|<--\n", 1, u);
	my_ft_putstr_fd("Printf(\"-->|%00.*u|<--\\n\", 2, u);	==>	", 1);
	printf("-->|%00.*u|<--\n", 2, u);
	my_ft_putstr_fd("Printf(\"-->|%00.*u|<--\\n\", 3, u);	==>	", 1);
	printf("-->|%00.*u|<--\n", 3, u);
	my_ft_putstr_fd("Printf(\"-->|%00.*u|<--\\n\", 4, u);	==>	", 1);
	printf("-->|%00.*u|<--\n", 4, u);
	my_ft_putstr_fd("Printf(\"-->|%00.0u|<--\\n\", u);	==>	", 1);
	printf("-->|%00.0u|<--\n", u);
	my_ft_putstr_fd("Printf(\"-->|%00.1u|<--\\n\", u);	==>	", 1);
	printf("-->|%00.1u|<--\n", u);
	my_ft_putstr_fd("Printf(\"-->|%00.2u|<--\\n\", u);	==>	", 1);
	printf("-->|%00.2u|<--\n", u);
	my_ft_putstr_fd("Printf(\"-->|%00.3u|<--\\n\", u);	==>	", 1);
	printf("-->|%00.3u|<--\n", u);
	my_ft_putstr_fd("Printf(\"-->|%00.4u|<--\\n\", u);	==>	", 1);
	printf("-->|%00.4u|<--\n", u);
	my_ft_putstr_fd("Printf(\"-->|%00u|<--\\n\", u);	==>	", 1);
	printf("-->|%00u|<--\n", u);
	my_ft_putstr_fd("Printf(\"-->|%01.u|<--\\n\", u);	==>	", 1);
	printf("-->|%01.u|<--\n", u);
	my_ft_putstr_fd("Printf(\"-->|%01.*u|<--\\n\", -4, u);	==>	", 1);
	printf("-->|%01.*u|<--\n", -4, u);
	my_ft_putstr_fd("Printf(\"-->|%01.*u|<--\\n\", -3, u);	==>	", 1);
	printf("-->|%01.*u|<--\n", -3, u);
	my_ft_putstr_fd("Printf(\"-->|%01.*u|<--\\n\", -2, u);	==>	", 1);
	printf("-->|%01.*u|<--\n", -2, u);
	my_ft_putstr_fd("Printf(\"-->|%01.*u|<--\\n\", -1, u);	==>	", 1);
	printf("-->|%01.*u|<--\n", -1, u);
	my_ft_putstr_fd("Printf(\"-->|%01.*u|<--\\n\", 0, u);	==>	", 1);
	printf("-->|%01.*u|<--\n", 0, u);
	my_ft_putstr_fd("Printf(\"-->|%01.*u|<--\\n\", 1, u);	==>	", 1);
	printf("-->|%01.*u|<--\n", 1, u);
	my_ft_putstr_fd("Printf(\"-->|%01.*u|<--\\n\", 2, u);	==>	", 1);
	printf("-->|%01.*u|<--\n", 2, u);
	my_ft_putstr_fd("Printf(\"-->|%01.*u|<--\\n\", 3, u);	==>	", 1);
	printf("-->|%01.*u|<--\n", 3, u);
	my_ft_putstr_fd("Printf(\"-->|%01.*u|<--\\n\", 4, u);	==>	", 1);
	printf("-->|%01.*u|<--\n", 4, u);
	my_ft_putstr_fd("Printf(\"-->|%01.0u|<--\\n\", u);	==>	", 1);
	printf("-->|%01.0u|<--\n", u);
	my_ft_putstr_fd("Printf(\"-->|%01.1u|<--\\n\", u);	==>	", 1);
	printf("-->|%01.1u|<--\n", u);
	my_ft_putstr_fd("Printf(\"-->|%01.2u|<--\\n\", u);	==>	", 1);
	printf("-->|%01.2u|<--\n", u);
	my_ft_putstr_fd("Printf(\"-->|%01.3u|<--\\n\", u);	==>	", 1);
	printf("-->|%01.3u|<--\n", u);
	my_ft_putstr_fd("Printf(\"-->|%01.4u|<--\\n\", u);	==>	", 1);
	printf("-->|%01.4u|<--\n", u);
	my_ft_putstr_fd("Printf(\"-->|%01u|<--\\n\", u);	==>	", 1);
	printf("-->|%01u|<--\n", u);
	my_ft_putstr_fd("Printf(\"-->|%02.u|<--\\n\", u);	==>	", 1);
	printf("-->|%02.u|<--\n", u);
	my_ft_putstr_fd("Printf(\"-->|%02.*u|<--\\n\", -4, u);	==>	", 1);
	printf("-->|%02.*u|<--\n", -4, u);
	my_ft_putstr_fd("Printf(\"-->|%02.*u|<--\\n\", -3, u);	==>	", 1);
	printf("-->|%02.*u|<--\n", -3, u);
	my_ft_putstr_fd("Printf(\"-->|%02.*u|<--\\n\", -2, u);	==>	", 1);
	printf("-->|%02.*u|<--\n", -2, u);
	my_ft_putstr_fd("Printf(\"-->|%02.*u|<--\\n\", -1, u);	==>	", 1);
	printf("-->|%02.*u|<--\n", -1, u);
	my_ft_putstr_fd("Printf(\"-->|%02.*u|<--\\n\", 0, u);	==>	", 1);
	printf("-->|%02.*u|<--\n", 0, u);
	my_ft_putstr_fd("Printf(\"-->|%02.*u|<--\\n\", 1, u);	==>	", 1);
	printf("-->|%02.*u|<--\n", 1, u);
	my_ft_putstr_fd("Printf(\"-->|%02.*u|<--\\n\", 2, u);	==>	", 1);
	printf("-->|%02.*u|<--\n", 2, u);
	my_ft_putstr_fd("Printf(\"-->|%02.*u|<--\\n\", 3, u);	==>	", 1);
	printf("-->|%02.*u|<--\n", 3, u);
	my_ft_putstr_fd("Printf(\"-->|%02.*u|<--\\n\", 4, u);	==>	", 1);
	printf("-->|%02.*u|<--\n", 4, u);
	my_ft_putstr_fd("Printf(\"-->|%02.0u|<--\\n\", u);	==>	", 1);
	printf("-->|%02.0u|<--\n", u);
	my_ft_putstr_fd("Printf(\"-->|%02.1u|<--\\n\", u);	==>	", 1);
	printf("-->|%02.1u|<--\n", u);
	my_ft_putstr_fd("Printf(\"-->|%02.2u|<--\\n\", u);	==>	", 1);
	printf("-->|%02.2u|<--\n", u);
	my_ft_putstr_fd("Printf(\"-->|%02.3u|<--\\n\", u);	==>	", 1);
	printf("-->|%02.3u|<--\n", u);
	my_ft_putstr_fd("Printf(\"-->|%02.4u|<--\\n\", u);	==>	", 1);
	printf("-->|%02.4u|<--\n", u);
	my_ft_putstr_fd("Printf(\"-->|%02u|<--\\n\", u);	==>	", 1);
	printf("-->|%02u|<--\n", u);
	my_ft_putstr_fd("Printf(\"-->|%03.u|<--\\n\", u);	==>	", 1);
	printf("-->|%03.u|<--\n", u);
	my_ft_putstr_fd("Printf(\"-->|%03.*u|<--\\n\", -4, u);	==>	", 1);
	printf("-->|%03.*u|<--\n", -4, u);
	my_ft_putstr_fd("Printf(\"-->|%03.*u|<--\\n\", -3, u);	==>	", 1);
	printf("-->|%03.*u|<--\n", -3, u);
	my_ft_putstr_fd("Printf(\"-->|%03.*u|<--\\n\", -2, u);	==>	", 1);
	printf("-->|%03.*u|<--\n", -2, u);
	my_ft_putstr_fd("Printf(\"-->|%03.*u|<--\\n\", -1, u);	==>	", 1);
	printf("-->|%03.*u|<--\n", -1, u);
	my_ft_putstr_fd("Printf(\"-->|%03.*u|<--\\n\", 0, u);	==>	", 1);
	printf("-->|%03.*u|<--\n", 0, u);
	my_ft_putstr_fd("Printf(\"-->|%03.*u|<--\\n\", 1, u);	==>	", 1);
	printf("-->|%03.*u|<--\n", 1, u);
	my_ft_putstr_fd("Printf(\"-->|%03.*u|<--\\n\", 2, u);	==>	", 1);
	printf("-->|%03.*u|<--\n", 2, u);
	my_ft_putstr_fd("Printf(\"-->|%03.*u|<--\\n\", 3, u);	==>	", 1);
	printf("-->|%03.*u|<--\n", 3, u);
	my_ft_putstr_fd("Printf(\"-->|%03.*u|<--\\n\", 4, u);	==>	", 1);
	printf("-->|%03.*u|<--\n", 4, u);
	my_ft_putstr_fd("Printf(\"-->|%03.0u|<--\\n\", u);	==>	", 1);
	printf("-->|%03.0u|<--\n", u);
	my_ft_putstr_fd("Printf(\"-->|%03.1u|<--\\n\", u);	==>	", 1);
	printf("-->|%03.1u|<--\n", u);
	my_ft_putstr_fd("Printf(\"-->|%03.2u|<--\\n\", u);	==>	", 1);
	printf("-->|%03.2u|<--\n", u);
	my_ft_putstr_fd("Printf(\"-->|%03.3u|<--\\n\", u);	==>	", 1);
	printf("-->|%03.3u|<--\n", u);
	my_ft_putstr_fd("Printf(\"-->|%03.4u|<--\\n\", u);	==>	", 1);
	printf("-->|%03.4u|<--\n", u);
	my_ft_putstr_fd("Printf(\"-->|%03u|<--\\n\", u);	==>	", 1);
	printf("-->|%03u|<--\n", u);
	my_ft_putstr_fd("Printf(\"-->|%04.u|<--\\n\", u);	==>	", 1);
	printf("-->|%04.u|<--\n", u);
	my_ft_putstr_fd("Printf(\"-->|%04.*u|<--\\n\", -4, u);	==>	", 1);
	printf("-->|%04.*u|<--\n", -4, u);
	my_ft_putstr_fd("Printf(\"-->|%04.*u|<--\\n\", -3, u);	==>	", 1);
	printf("-->|%04.*u|<--\n", -3, u);
	my_ft_putstr_fd("Printf(\"-->|%04.*u|<--\\n\", -2, u);	==>	", 1);
	printf("-->|%04.*u|<--\n", -2, u);
	my_ft_putstr_fd("Printf(\"-->|%04.*u|<--\\n\", -1, u);	==>	", 1);
	printf("-->|%04.*u|<--\n", -1, u);
	my_ft_putstr_fd("Printf(\"-->|%04.*u|<--\\n\", 0, u);	==>	", 1);
	printf("-->|%04.*u|<--\n", 0, u);
	my_ft_putstr_fd("Printf(\"-->|%04.*u|<--\\n\", 1, u);	==>	", 1);
	printf("-->|%04.*u|<--\n", 1, u);
	my_ft_putstr_fd("Printf(\"-->|%04.*u|<--\\n\", 2, u);	==>	", 1);
	printf("-->|%04.*u|<--\n", 2, u);
	my_ft_putstr_fd("Printf(\"-->|%04.*u|<--\\n\", 3, u);	==>	", 1);
	printf("-->|%04.*u|<--\n", 3, u);
	my_ft_putstr_fd("Printf(\"-->|%04.*u|<--\\n\", 4, u);	==>	", 1);
	printf("-->|%04.*u|<--\n", 4, u);
	my_ft_putstr_fd("Printf(\"-->|%04.0u|<--\\n\", u);	==>	", 1);
	printf("-->|%04.0u|<--\n", u);
	my_ft_putstr_fd("Printf(\"-->|%04.1u|<--\\n\", u);	==>	", 1);
	printf("-->|%04.1u|<--\n", u);
	my_ft_putstr_fd("Printf(\"-->|%04.2u|<--\\n\", u);	==>	", 1);
	printf("-->|%04.2u|<--\n", u);
	my_ft_putstr_fd("Printf(\"-->|%04.3u|<--\\n\", u);	==>	", 1);
	printf("-->|%04.3u|<--\n", u);
	my_ft_putstr_fd("Printf(\"-->|%04.4u|<--\\n\", u);	==>	", 1);
	printf("-->|%04.4u|<--\n", u);
	my_ft_putstr_fd("Printf(\"-->|%04u|<--\\n\", u);	==>	", 1);
	printf("-->|%04u|<--\n", u);
	my_ft_putstr_fd("Printf(\"-->|%--4.u|<--\\n\", u);	==>	", 1);
	printf("-->|%--4.u|<--\n", u);
	my_ft_putstr_fd("Printf(\"-->|%--4.*u|<--\\n\", -4, u);	==>	", 1);
	printf("-->|%--4.*u|<--\n", -4, u);
	my_ft_putstr_fd("Printf(\"-->|%--4.*u|<--\\n\", -3, u);	==>	", 1);
	printf("-->|%--4.*u|<--\n", -3, u);
	my_ft_putstr_fd("Printf(\"-->|%--4.*u|<--\\n\", -2, u);	==>	", 1);
	printf("-->|%--4.*u|<--\n", -2, u);
	my_ft_putstr_fd("Printf(\"-->|%--4.*u|<--\\n\", -1, u);	==>	", 1);
	printf("-->|%--4.*u|<--\n", -1, u);
	my_ft_putstr_fd("Printf(\"-->|%--4.*u|<--\\n\", 0, u);	==>	", 1);
	printf("-->|%--4.*u|<--\n", 0, u);
	my_ft_putstr_fd("Printf(\"-->|%--4.*u|<--\\n\", 1, u);	==>	", 1);
	printf("-->|%--4.*u|<--\n", 1, u);
	my_ft_putstr_fd("Printf(\"-->|%--4.*u|<--\\n\", 2, u);	==>	", 1);
	printf("-->|%--4.*u|<--\n", 2, u);
	my_ft_putstr_fd("Printf(\"-->|%--4.*u|<--\\n\", 3, u);	==>	", 1);
	printf("-->|%--4.*u|<--\n", 3, u);
	my_ft_putstr_fd("Printf(\"-->|%--4.*u|<--\\n\", 4, u);	==>	", 1);
	printf("-->|%--4.*u|<--\n", 4, u);
	my_ft_putstr_fd("Printf(\"-->|%--4.0u|<--\\n\", u);	==>	", 1);
	printf("-->|%--4.0u|<--\n", u);
	my_ft_putstr_fd("Printf(\"-->|%--4.1u|<--\\n\", u);	==>	", 1);
	printf("-->|%--4.1u|<--\n", u);
	my_ft_putstr_fd("Printf(\"-->|%--4.2u|<--\\n\", u);	==>	", 1);
	printf("-->|%--4.2u|<--\n", u);
	my_ft_putstr_fd("Printf(\"-->|%--4.3u|<--\\n\", u);	==>	", 1);
	printf("-->|%--4.3u|<--\n", u);
	my_ft_putstr_fd("Printf(\"-->|%--4.4u|<--\\n\", u);	==>	", 1);
	printf("-->|%--4.4u|<--\n", u);
	my_ft_putstr_fd("Printf(\"-->|%--4u|<--\\n\", u);	==>	", 1);
	printf("-->|%--4u|<--\n", u);
	my_ft_putstr_fd("Printf(\"-->|%--3.u|<--\\n\", u);	==>	", 1);
	printf("-->|%--3.u|<--\n", u);
	my_ft_putstr_fd("Printf(\"-->|%--3.*u|<--\\n\", -4, u);	==>	", 1);
	printf("-->|%--3.*u|<--\n", -4, u);
	my_ft_putstr_fd("Printf(\"-->|%--3.*u|<--\\n\", -3, u);	==>	", 1);
	printf("-->|%--3.*u|<--\n", -3, u);
	my_ft_putstr_fd("Printf(\"-->|%--3.*u|<--\\n\", -2, u);	==>	", 1);
	printf("-->|%--3.*u|<--\n", -2, u);
	my_ft_putstr_fd("Printf(\"-->|%--3.*u|<--\\n\", -1, u);	==>	", 1);
	printf("-->|%--3.*u|<--\n", -1, u);
	my_ft_putstr_fd("Printf(\"-->|%--3.*u|<--\\n\", 0, u);	==>	", 1);
	printf("-->|%--3.*u|<--\n", 0, u);
	my_ft_putstr_fd("Printf(\"-->|%--3.*u|<--\\n\", 1, u);	==>	", 1);
	printf("-->|%--3.*u|<--\n", 1, u);
	my_ft_putstr_fd("Printf(\"-->|%--3.*u|<--\\n\", 2, u);	==>	", 1);
	printf("-->|%--3.*u|<--\n", 2, u);
	my_ft_putstr_fd("Printf(\"-->|%--3.*u|<--\\n\", 3, u);	==>	", 1);
	printf("-->|%--3.*u|<--\n", 3, u);
	my_ft_putstr_fd("Printf(\"-->|%--3.*u|<--\\n\", 4, u);	==>	", 1);
	printf("-->|%--3.*u|<--\n", 4, u);
	my_ft_putstr_fd("Printf(\"-->|%--3.0u|<--\\n\", u);	==>	", 1);
	printf("-->|%--3.0u|<--\n", u);
	my_ft_putstr_fd("Printf(\"-->|%--3.1u|<--\\n\", u);	==>	", 1);
	printf("-->|%--3.1u|<--\n", u);
	my_ft_putstr_fd("Printf(\"-->|%--3.2u|<--\\n\", u);	==>	", 1);
	printf("-->|%--3.2u|<--\n", u);
	my_ft_putstr_fd("Printf(\"-->|%--3.3u|<--\\n\", u);	==>	", 1);
	printf("-->|%--3.3u|<--\n", u);
	my_ft_putstr_fd("Printf(\"-->|%--3.4u|<--\\n\", u);	==>	", 1);
	printf("-->|%--3.4u|<--\n", u);
	my_ft_putstr_fd("Printf(\"-->|%--3u|<--\\n\", u);	==>	", 1);
	printf("-->|%--3u|<--\n", u);
	my_ft_putstr_fd("Printf(\"-->|%--2.u|<--\\n\", u);	==>	", 1);
	printf("-->|%--2.u|<--\n", u);
	my_ft_putstr_fd("Printf(\"-->|%--2.*u|<--\\n\", -4, u);	==>	", 1);
	printf("-->|%--2.*u|<--\n", -4, u);
	my_ft_putstr_fd("Printf(\"-->|%--2.*u|<--\\n\", -3, u);	==>	", 1);
	printf("-->|%--2.*u|<--\n", -3, u);
	my_ft_putstr_fd("Printf(\"-->|%--2.*u|<--\\n\", -2, u);	==>	", 1);
	printf("-->|%--2.*u|<--\n", -2, u);
	my_ft_putstr_fd("Printf(\"-->|%--2.*u|<--\\n\", -1, u);	==>	", 1);
	printf("-->|%--2.*u|<--\n", -1, u);
	my_ft_putstr_fd("Printf(\"-->|%--2.*u|<--\\n\", 0, u);	==>	", 1);
	printf("-->|%--2.*u|<--\n", 0, u);
	my_ft_putstr_fd("Printf(\"-->|%--2.*u|<--\\n\", 1, u);	==>	", 1);
	printf("-->|%--2.*u|<--\n", 1, u);
	my_ft_putstr_fd("Printf(\"-->|%--2.*u|<--\\n\", 2, u);	==>	", 1);
	printf("-->|%--2.*u|<--\n", 2, u);
	my_ft_putstr_fd("Printf(\"-->|%--2.*u|<--\\n\", 3, u);	==>	", 1);
	printf("-->|%--2.*u|<--\n", 3, u);
	my_ft_putstr_fd("Printf(\"-->|%--2.*u|<--\\n\", 4, u);	==>	", 1);
	printf("-->|%--2.*u|<--\n", 4, u);
	my_ft_putstr_fd("Printf(\"-->|%--2.0u|<--\\n\", u);	==>	", 1);
	printf("-->|%--2.0u|<--\n", u);
	my_ft_putstr_fd("Printf(\"-->|%--2.1u|<--\\n\", u);	==>	", 1);
	printf("-->|%--2.1u|<--\n", u);
	my_ft_putstr_fd("Printf(\"-->|%--2.2u|<--\\n\", u);	==>	", 1);
	printf("-->|%--2.2u|<--\n", u);
	my_ft_putstr_fd("Printf(\"-->|%--2.3u|<--\\n\", u);	==>	", 1);
	printf("-->|%--2.3u|<--\n", u);
	my_ft_putstr_fd("Printf(\"-->|%--2.4u|<--\\n\", u);	==>	", 1);
	printf("-->|%--2.4u|<--\n", u);
	my_ft_putstr_fd("Printf(\"-->|%--2u|<--\\n\", u);	==>	", 1);
	printf("-->|%--2u|<--\n", u);
	my_ft_putstr_fd("Printf(\"-->|%--1.u|<--\\n\", u);	==>	", 1);
	printf("-->|%--1.u|<--\n", u);
	my_ft_putstr_fd("Printf(\"-->|%--1.*u|<--\\n\", -4, u);	==>	", 1);
	printf("-->|%--1.*u|<--\n", -4, u);
	my_ft_putstr_fd("Printf(\"-->|%--1.*u|<--\\n\", -3, u);	==>	", 1);
	printf("-->|%--1.*u|<--\n", -3, u);
	my_ft_putstr_fd("Printf(\"-->|%--1.*u|<--\\n\", -2, u);	==>	", 1);
	printf("-->|%--1.*u|<--\n", -2, u);
	my_ft_putstr_fd("Printf(\"-->|%--1.*u|<--\\n\", -1, u);	==>	", 1);
	printf("-->|%--1.*u|<--\n", -1, u);
	my_ft_putstr_fd("Printf(\"-->|%--1.*u|<--\\n\", 0, u);	==>	", 1);
	printf("-->|%--1.*u|<--\n", 0, u);
	my_ft_putstr_fd("Printf(\"-->|%--1.*u|<--\\n\", 1, u);	==>	", 1);
	printf("-->|%--1.*u|<--\n", 1, u);
	my_ft_putstr_fd("Printf(\"-->|%--1.*u|<--\\n\", 2, u);	==>	", 1);
	printf("-->|%--1.*u|<--\n", 2, u);
	my_ft_putstr_fd("Printf(\"-->|%--1.*u|<--\\n\", 3, u);	==>	", 1);
	printf("-->|%--1.*u|<--\n", 3, u);
	my_ft_putstr_fd("Printf(\"-->|%--1.*u|<--\\n\", 4, u);	==>	", 1);
	printf("-->|%--1.*u|<--\n", 4, u);
	my_ft_putstr_fd("Printf(\"-->|%--1.0u|<--\\n\", u);	==>	", 1);
	printf("-->|%--1.0u|<--\n", u);
	my_ft_putstr_fd("Printf(\"-->|%--1.1u|<--\\n\", u);	==>	", 1);
	printf("-->|%--1.1u|<--\n", u);
	my_ft_putstr_fd("Printf(\"-->|%--1.2u|<--\\n\", u);	==>	", 1);
	printf("-->|%--1.2u|<--\n", u);
	my_ft_putstr_fd("Printf(\"-->|%--1.3u|<--\\n\", u);	==>	", 1);
	printf("-->|%--1.3u|<--\n", u);
	my_ft_putstr_fd("Printf(\"-->|%--1.4u|<--\\n\", u);	==>	", 1);
	printf("-->|%--1.4u|<--\n", u);
	my_ft_putstr_fd("Printf(\"-->|%--1u|<--\\n\", u);	==>	", 1);
	printf("-->|%--1u|<--\n", u);
	my_ft_putstr_fd("Printf(\"-->|%-.u|<--\\n\", u);	==>	", 1);
	printf("-->|%-.u|<--\n", u);
	my_ft_putstr_fd("Printf(\"-->|%-.*u|<--\\n\", -4, u);	==>	", 1);
	printf("-->|%-.*u|<--\n", -4, u);
	my_ft_putstr_fd("Printf(\"-->|%-.*u|<--\\n\", -3, u);	==>	", 1);
	printf("-->|%-.*u|<--\n", -3, u);
	my_ft_putstr_fd("Printf(\"-->|%-.*u|<--\\n\", -2, u);	==>	", 1);
	printf("-->|%-.*u|<--\n", -2, u);
	my_ft_putstr_fd("Printf(\"-->|%-.*u|<--\\n\", -1, u);	==>	", 1);
	printf("-->|%-.*u|<--\n", -1, u);
	my_ft_putstr_fd("Printf(\"-->|%-.*u|<--\\n\", 0, u);	==>	", 1);
	printf("-->|%-.*u|<--\n", 0, u);
	my_ft_putstr_fd("Printf(\"-->|%-.*u|<--\\n\", 1, u);	==>	", 1);
	printf("-->|%-.*u|<--\n", 1, u);
	my_ft_putstr_fd("Printf(\"-->|%-.*u|<--\\n\", 2, u);	==>	", 1);
	printf("-->|%-.*u|<--\n", 2, u);
	my_ft_putstr_fd("Printf(\"-->|%-.*u|<--\\n\", 3, u);	==>	", 1);
	printf("-->|%-.*u|<--\n", 3, u);
	my_ft_putstr_fd("Printf(\"-->|%-.*u|<--\\n\", 4, u);	==>	", 1);
	printf("-->|%-.*u|<--\n", 4, u);
	my_ft_putstr_fd("Printf(\"-->|%-.0u|<--\\n\", u);	==>	", 1);
	printf("-->|%-.0u|<--\n", u);
	my_ft_putstr_fd("Printf(\"-->|%-.1u|<--\\n\", u);	==>	", 1);
	printf("-->|%-.1u|<--\n", u);
	my_ft_putstr_fd("Printf(\"-->|%-.2u|<--\\n\", u);	==>	", 1);
	printf("-->|%-.2u|<--\n", u);
	my_ft_putstr_fd("Printf(\"-->|%-.3u|<--\\n\", u);	==>	", 1);
	printf("-->|%-.3u|<--\n", u);
	my_ft_putstr_fd("Printf(\"-->|%-.4u|<--\\n\", u);	==>	", 1);
	printf("-->|%-.4u|<--\n", u);
	my_ft_putstr_fd("Printf(\"-->|%-u|<--\\n\", u);	==>	", 1);
	printf("-->|%-u|<--\n", u);
	my_ft_putstr_fd("Printf(\"-->|%-*.u|<--\\n\", -4, u);	==>	", 1);
	printf("-->|%-*.u|<--\n", -4, u);
	my_ft_putstr_fd("Printf(\"-->|%-*.u|<--\\n\", -3, u);	==>	", 1);
	printf("-->|%-*.u|<--\n", -3, u);
	my_ft_putstr_fd("Printf(\"-->|%-*.u|<--\\n\", -2, u);	==>	", 1);
	printf("-->|%-*.u|<--\n", -2, u);
	my_ft_putstr_fd("Printf(\"-->|%-*.u|<--\\n\", -1, u);	==>	", 1);
	printf("-->|%-*.u|<--\n", -1, u);
	my_ft_putstr_fd("Printf(\"-->|%-*.u|<--\\n\", 0, u);	==>	", 1);
	printf("-->|%-*.u|<--\n", 0, u);
	my_ft_putstr_fd("Printf(\"-->|%-*.u|<--\\n\", 1, u);	==>	", 1);
	printf("-->|%-*.u|<--\n", 1, u);
	my_ft_putstr_fd("Printf(\"-->|%-*.u|<--\\n\", 2, u);	==>	", 1);
	printf("-->|%-*.u|<--\n", 2, u);
	my_ft_putstr_fd("Printf(\"-->|%-*.u|<--\\n\", 3, u);	==>	", 1);
	printf("-->|%-*.u|<--\n", 3, u);
	my_ft_putstr_fd("Printf(\"-->|%-*.u|<--\\n\", 4, u);	==>	", 1);
	printf("-->|%-*.u|<--\n", 4, u);
	my_ft_putstr_fd("Printf(\"-->|%-*.*u|<--\\n\", -4, -4, u);	==>	", 1);
	printf("-->|%-*.*u|<--\n", -4, -4, u);
	my_ft_putstr_fd("Printf(\"-->|%-*.*u|<--\\n\", -4, -3, u);	==>	", 1);
	printf("-->|%-*.*u|<--\n", -4, -3, u);
	my_ft_putstr_fd("Printf(\"-->|%-*.*u|<--\\n\", -4, -2, u);	==>	", 1);
	printf("-->|%-*.*u|<--\n", -4, -2, u);
	my_ft_putstr_fd("Printf(\"-->|%-*.*u|<--\\n\", -4, -1, u);	==>	", 1);
	printf("-->|%-*.*u|<--\n", -4, -1, u);
	my_ft_putstr_fd("Printf(\"-->|%-*.*u|<--\\n\", -4, 0, u);	==>	", 1);
	printf("-->|%-*.*u|<--\n", -4, 0, u);
	my_ft_putstr_fd("Printf(\"-->|%-*.*u|<--\\n\", -4, 1, u);	==>	", 1);
	printf("-->|%-*.*u|<--\n", -4, 1, u);
	my_ft_putstr_fd("Printf(\"-->|%-*.*u|<--\\n\", -4, 2, u);	==>	", 1);
	printf("-->|%-*.*u|<--\n", -4, 2, u);
	my_ft_putstr_fd("Printf(\"-->|%-*.*u|<--\\n\", -4, 3, u);	==>	", 1);
	printf("-->|%-*.*u|<--\n", -4, 3, u);
	my_ft_putstr_fd("Printf(\"-->|%-*.*u|<--\\n\", -4, 4, u);	==>	", 1);
	printf("-->|%-*.*u|<--\n", -4, 4, u);
	my_ft_putstr_fd("Printf(\"-->|%-*.*u|<--\\n\", -3, -4, u);	==>	", 1);
	printf("-->|%-*.*u|<--\n", -3, -4, u);
	my_ft_putstr_fd("Printf(\"-->|%-*.*u|<--\\n\", -3, -3, u);	==>	", 1);
	printf("-->|%-*.*u|<--\n", -3, -3, u);
	my_ft_putstr_fd("Printf(\"-->|%-*.*u|<--\\n\", -3, -2, u);	==>	", 1);
	printf("-->|%-*.*u|<--\n", -3, -2, u);
	my_ft_putstr_fd("Printf(\"-->|%-*.*u|<--\\n\", -3, -1, u);	==>	", 1);
	printf("-->|%-*.*u|<--\n", -3, -1, u);
	my_ft_putstr_fd("Printf(\"-->|%-*.*u|<--\\n\", -3, 0, u);	==>	", 1);
	printf("-->|%-*.*u|<--\n", -3, 0, u);
	my_ft_putstr_fd("Printf(\"-->|%-*.*u|<--\\n\", -3, 1, u);	==>	", 1);
	printf("-->|%-*.*u|<--\n", -3, 1, u);
	my_ft_putstr_fd("Printf(\"-->|%-*.*u|<--\\n\", -3, 2, u);	==>	", 1);
	printf("-->|%-*.*u|<--\n", -3, 2, u);
	my_ft_putstr_fd("Printf(\"-->|%-*.*u|<--\\n\", -3, 3, u);	==>	", 1);
	printf("-->|%-*.*u|<--\n", -3, 3, u);
	my_ft_putstr_fd("Printf(\"-->|%-*.*u|<--\\n\", -3, 4, u);	==>	", 1);
	printf("-->|%-*.*u|<--\n", -3, 4, u);
	my_ft_putstr_fd("Printf(\"-->|%-*.*u|<--\\n\", -2, -4, u);	==>	", 1);
	printf("-->|%-*.*u|<--\n", -2, -4, u);
	my_ft_putstr_fd("Printf(\"-->|%-*.*u|<--\\n\", -2, -3, u);	==>	", 1);
	printf("-->|%-*.*u|<--\n", -2, -3, u);
	my_ft_putstr_fd("Printf(\"-->|%-*.*u|<--\\n\", -2, -2, u);	==>	", 1);
	printf("-->|%-*.*u|<--\n", -2, -2, u);
	my_ft_putstr_fd("Printf(\"-->|%-*.*u|<--\\n\", -2, -1, u);	==>	", 1);
	printf("-->|%-*.*u|<--\n", -2, -1, u);
	my_ft_putstr_fd("Printf(\"-->|%-*.*u|<--\\n\", -2, 0, u);	==>	", 1);
	printf("-->|%-*.*u|<--\n", -2, 0, u);
	my_ft_putstr_fd("Printf(\"-->|%-*.*u|<--\\n\", -2, 1, u);	==>	", 1);
	printf("-->|%-*.*u|<--\n", -2, 1, u);
	my_ft_putstr_fd("Printf(\"-->|%-*.*u|<--\\n\", -2, 2, u);	==>	", 1);
	printf("-->|%-*.*u|<--\n", -2, 2, u);
	my_ft_putstr_fd("Printf(\"-->|%-*.*u|<--\\n\", -2, 3, u);	==>	", 1);
	printf("-->|%-*.*u|<--\n", -2, 3, u);
	my_ft_putstr_fd("Printf(\"-->|%-*.*u|<--\\n\", -2, 4, u);	==>	", 1);
	printf("-->|%-*.*u|<--\n", -2, 4, u);
	my_ft_putstr_fd("Printf(\"-->|%-*.*u|<--\\n\", -1, -4, u);	==>	", 1);
	printf("-->|%-*.*u|<--\n", -1, -4, u);
	my_ft_putstr_fd("Printf(\"-->|%-*.*u|<--\\n\", -1, -3, u);	==>	", 1);
	printf("-->|%-*.*u|<--\n", -1, -3, u);
	my_ft_putstr_fd("Printf(\"-->|%-*.*u|<--\\n\", -1, -2, u);	==>	", 1);
	printf("-->|%-*.*u|<--\n", -1, -2, u);
	my_ft_putstr_fd("Printf(\"-->|%-*.*u|<--\\n\", -1, -1, u);	==>	", 1);
	printf("-->|%-*.*u|<--\n", -1, -1, u);
	my_ft_putstr_fd("Printf(\"-->|%-*.*u|<--\\n\", -1, 0, u);	==>	", 1);
	printf("-->|%-*.*u|<--\n", -1, 0, u);
	my_ft_putstr_fd("Printf(\"-->|%-*.*u|<--\\n\", -1, 1, u);	==>	", 1);
	printf("-->|%-*.*u|<--\n", -1, 1, u);
	my_ft_putstr_fd("Printf(\"-->|%-*.*u|<--\\n\", -1, 2, u);	==>	", 1);
	printf("-->|%-*.*u|<--\n", -1, 2, u);
	my_ft_putstr_fd("Printf(\"-->|%-*.*u|<--\\n\", -1, 3, u);	==>	", 1);
	printf("-->|%-*.*u|<--\n", -1, 3, u);
	my_ft_putstr_fd("Printf(\"-->|%-*.*u|<--\\n\", -1, 4, u);	==>	", 1);
	printf("-->|%-*.*u|<--\n", -1, 4, u);
	my_ft_putstr_fd("Printf(\"-->|%-*.*u|<--\\n\", 0, -4, u);	==>	", 1);
	printf("-->|%-*.*u|<--\n", 0, -4, u);
	my_ft_putstr_fd("Printf(\"-->|%-*.*u|<--\\n\", 0, -3, u);	==>	", 1);
	printf("-->|%-*.*u|<--\n", 0, -3, u);
	my_ft_putstr_fd("Printf(\"-->|%-*.*u|<--\\n\", 0, -2, u);	==>	", 1);
	printf("-->|%-*.*u|<--\n", 0, -2, u);
	my_ft_putstr_fd("Printf(\"-->|%-*.*u|<--\\n\", 0, -1, u);	==>	", 1);
	printf("-->|%-*.*u|<--\n", 0, -1, u);
	my_ft_putstr_fd("Printf(\"-->|%-*.*u|<--\\n\", 0, 0, u);	==>	", 1);
	printf("-->|%-*.*u|<--\n", 0, 0, u);
	my_ft_putstr_fd("Printf(\"-->|%-*.*u|<--\\n\", 0, 1, u);	==>	", 1);
	printf("-->|%-*.*u|<--\n", 0, 1, u);
	my_ft_putstr_fd("Printf(\"-->|%-*.*u|<--\\n\", 0, 2, u);	==>	", 1);
	printf("-->|%-*.*u|<--\n", 0, 2, u);
	my_ft_putstr_fd("Printf(\"-->|%-*.*u|<--\\n\", 0, 3, u);	==>	", 1);
	printf("-->|%-*.*u|<--\n", 0, 3, u);
	my_ft_putstr_fd("Printf(\"-->|%-*.*u|<--\\n\", 0, 4, u);	==>	", 1);
	printf("-->|%-*.*u|<--\n", 0, 4, u);
	my_ft_putstr_fd("Printf(\"-->|%-*.*u|<--\\n\", 1, -4, u);	==>	", 1);
	printf("-->|%-*.*u|<--\n", 1, -4, u);
	my_ft_putstr_fd("Printf(\"-->|%-*.*u|<--\\n\", 1, -3, u);	==>	", 1);
	printf("-->|%-*.*u|<--\n", 1, -3, u);
	my_ft_putstr_fd("Printf(\"-->|%-*.*u|<--\\n\", 1, -2, u);	==>	", 1);
	printf("-->|%-*.*u|<--\n", 1, -2, u);
	my_ft_putstr_fd("Printf(\"-->|%-*.*u|<--\\n\", 1, -1, u);	==>	", 1);
	printf("-->|%-*.*u|<--\n", 1, -1, u);
	my_ft_putstr_fd("Printf(\"-->|%-*.*u|<--\\n\", 1, 0, u);	==>	", 1);
	printf("-->|%-*.*u|<--\n", 1, 0, u);
	my_ft_putstr_fd("Printf(\"-->|%-*.*u|<--\\n\", 1, 1, u);	==>	", 1);
	printf("-->|%-*.*u|<--\n", 1, 1, u);
	my_ft_putstr_fd("Printf(\"-->|%-*.*u|<--\\n\", 1, 2, u);	==>	", 1);
	printf("-->|%-*.*u|<--\n", 1, 2, u);
	my_ft_putstr_fd("Printf(\"-->|%-*.*u|<--\\n\", 1, 3, u);	==>	", 1);
	printf("-->|%-*.*u|<--\n", 1, 3, u);
	my_ft_putstr_fd("Printf(\"-->|%-*.*u|<--\\n\", 1, 4, u);	==>	", 1);
	printf("-->|%-*.*u|<--\n", 1, 4, u);
	my_ft_putstr_fd("Printf(\"-->|%-*.*u|<--\\n\", 2, -4, u);	==>	", 1);
	printf("-->|%-*.*u|<--\n", 2, -4, u);
	my_ft_putstr_fd("Printf(\"-->|%-*.*u|<--\\n\", 2, -3, u);	==>	", 1);
	printf("-->|%-*.*u|<--\n", 2, -3, u);
	my_ft_putstr_fd("Printf(\"-->|%-*.*u|<--\\n\", 2, -2, u);	==>	", 1);
	printf("-->|%-*.*u|<--\n", 2, -2, u);
	my_ft_putstr_fd("Printf(\"-->|%-*.*u|<--\\n\", 2, -1, u);	==>	", 1);
	printf("-->|%-*.*u|<--\n", 2, -1, u);
	my_ft_putstr_fd("Printf(\"-->|%-*.*u|<--\\n\", 2, 0, u);	==>	", 1);
	printf("-->|%-*.*u|<--\n", 2, 0, u);
	my_ft_putstr_fd("Printf(\"-->|%-*.*u|<--\\n\", 2, 1, u);	==>	", 1);
	printf("-->|%-*.*u|<--\n", 2, 1, u);
	my_ft_putstr_fd("Printf(\"-->|%-*.*u|<--\\n\", 2, 2, u);	==>	", 1);
	printf("-->|%-*.*u|<--\n", 2, 2, u);
	my_ft_putstr_fd("Printf(\"-->|%-*.*u|<--\\n\", 2, 3, u);	==>	", 1);
	printf("-->|%-*.*u|<--\n", 2, 3, u);
	my_ft_putstr_fd("Printf(\"-->|%-*.*u|<--\\n\", 2, 4, u);	==>	", 1);
	printf("-->|%-*.*u|<--\n", 2, 4, u);
	my_ft_putstr_fd("Printf(\"-->|%-*.*u|<--\\n\", 3, -4, u);	==>	", 1);
	printf("-->|%-*.*u|<--\n", 3, -4, u);
	my_ft_putstr_fd("Printf(\"-->|%-*.*u|<--\\n\", 3, -3, u);	==>	", 1);
	printf("-->|%-*.*u|<--\n", 3, -3, u);
	my_ft_putstr_fd("Printf(\"-->|%-*.*u|<--\\n\", 3, -2, u);	==>	", 1);
	printf("-->|%-*.*u|<--\n", 3, -2, u);
	my_ft_putstr_fd("Printf(\"-->|%-*.*u|<--\\n\", 3, -1, u);	==>	", 1);
	printf("-->|%-*.*u|<--\n", 3, -1, u);
	my_ft_putstr_fd("Printf(\"-->|%-*.*u|<--\\n\", 3, 0, u);	==>	", 1);
	printf("-->|%-*.*u|<--\n", 3, 0, u);
	my_ft_putstr_fd("Printf(\"-->|%-*.*u|<--\\n\", 3, 1, u);	==>	", 1);
	printf("-->|%-*.*u|<--\n", 3, 1, u);
	my_ft_putstr_fd("Printf(\"-->|%-*.*u|<--\\n\", 3, 2, u);	==>	", 1);
	printf("-->|%-*.*u|<--\n", 3, 2, u);
	my_ft_putstr_fd("Printf(\"-->|%-*.*u|<--\\n\", 3, 3, u);	==>	", 1);
	printf("-->|%-*.*u|<--\n", 3, 3, u);
	my_ft_putstr_fd("Printf(\"-->|%-*.*u|<--\\n\", 3, 4, u);	==>	", 1);
	printf("-->|%-*.*u|<--\n", 3, 4, u);
	my_ft_putstr_fd("Printf(\"-->|%-*.*u|<--\\n\", 4, -4, u);	==>	", 1);
	printf("-->|%-*.*u|<--\n", 4, -4, u);
	my_ft_putstr_fd("Printf(\"-->|%-*.*u|<--\\n\", 4, -3, u);	==>	", 1);
	printf("-->|%-*.*u|<--\n", 4, -3, u);
	my_ft_putstr_fd("Printf(\"-->|%-*.*u|<--\\n\", 4, -2, u);	==>	", 1);
	printf("-->|%-*.*u|<--\n", 4, -2, u);
	my_ft_putstr_fd("Printf(\"-->|%-*.*u|<--\\n\", 4, -1, u);	==>	", 1);
	printf("-->|%-*.*u|<--\n", 4, -1, u);
	my_ft_putstr_fd("Printf(\"-->|%-*.*u|<--\\n\", 4, 0, u);	==>	", 1);
	printf("-->|%-*.*u|<--\n", 4, 0, u);
	my_ft_putstr_fd("Printf(\"-->|%-*.*u|<--\\n\", 4, 1, u);	==>	", 1);
	printf("-->|%-*.*u|<--\n", 4, 1, u);
	my_ft_putstr_fd("Printf(\"-->|%-*.*u|<--\\n\", 4, 2, u);	==>	", 1);
	printf("-->|%-*.*u|<--\n", 4, 2, u);
	my_ft_putstr_fd("Printf(\"-->|%-*.*u|<--\\n\", 4, 3, u);	==>	", 1);
	printf("-->|%-*.*u|<--\n", 4, 3, u);
	my_ft_putstr_fd("Printf(\"-->|%-*.*u|<--\\n\", 4, 4, u);	==>	", 1);
	printf("-->|%-*.*u|<--\n", 4, 4, u);
	my_ft_putstr_fd("Printf(\"-->|%-*.0u|<--\\n\", -4, u);	==>	", 1);
	printf("-->|%-*.0u|<--\n", -4, u);
	my_ft_putstr_fd("Printf(\"-->|%-*.0u|<--\\n\", -3, u);	==>	", 1);
	printf("-->|%-*.0u|<--\n", -3, u);
	my_ft_putstr_fd("Printf(\"-->|%-*.0u|<--\\n\", -2, u);	==>	", 1);
	printf("-->|%-*.0u|<--\n", -2, u);
	my_ft_putstr_fd("Printf(\"-->|%-*.0u|<--\\n\", -1, u);	==>	", 1);
	printf("-->|%-*.0u|<--\n", -1, u);
	my_ft_putstr_fd("Printf(\"-->|%-*.0u|<--\\n\", 0, u);	==>	", 1);
	printf("-->|%-*.0u|<--\n", 0, u);
	my_ft_putstr_fd("Printf(\"-->|%-*.0u|<--\\n\", 1, u);	==>	", 1);
	printf("-->|%-*.0u|<--\n", 1, u);
	my_ft_putstr_fd("Printf(\"-->|%-*.0u|<--\\n\", 2, u);	==>	", 1);
	printf("-->|%-*.0u|<--\n", 2, u);
	my_ft_putstr_fd("Printf(\"-->|%-*.0u|<--\\n\", 3, u);	==>	", 1);
	printf("-->|%-*.0u|<--\n", 3, u);
	my_ft_putstr_fd("Printf(\"-->|%-*.0u|<--\\n\", 4, u);	==>	", 1);
	printf("-->|%-*.0u|<--\n", 4, u);
	my_ft_putstr_fd("Printf(\"-->|%-*.1u|<--\\n\", -4, u);	==>	", 1);
	printf("-->|%-*.1u|<--\n", -4, u);
	my_ft_putstr_fd("Printf(\"-->|%-*.1u|<--\\n\", -3, u);	==>	", 1);
	printf("-->|%-*.1u|<--\n", -3, u);
	my_ft_putstr_fd("Printf(\"-->|%-*.1u|<--\\n\", -2, u);	==>	", 1);
	printf("-->|%-*.1u|<--\n", -2, u);
	my_ft_putstr_fd("Printf(\"-->|%-*.1u|<--\\n\", -1, u);	==>	", 1);
	printf("-->|%-*.1u|<--\n", -1, u);
	my_ft_putstr_fd("Printf(\"-->|%-*.1u|<--\\n\", 0, u);	==>	", 1);
	printf("-->|%-*.1u|<--\n", 0, u);
	my_ft_putstr_fd("Printf(\"-->|%-*.1u|<--\\n\", 1, u);	==>	", 1);
	printf("-->|%-*.1u|<--\n", 1, u);
	my_ft_putstr_fd("Printf(\"-->|%-*.1u|<--\\n\", 2, u);	==>	", 1);
	printf("-->|%-*.1u|<--\n", 2, u);
	my_ft_putstr_fd("Printf(\"-->|%-*.1u|<--\\n\", 3, u);	==>	", 1);
	printf("-->|%-*.1u|<--\n", 3, u);
	my_ft_putstr_fd("Printf(\"-->|%-*.1u|<--\\n\", 4, u);	==>	", 1);
	printf("-->|%-*.1u|<--\n", 4, u);
	my_ft_putstr_fd("Printf(\"-->|%-*.2u|<--\\n\", -4, u);	==>	", 1);
	printf("-->|%-*.2u|<--\n", -4, u);
	my_ft_putstr_fd("Printf(\"-->|%-*.2u|<--\\n\", -3, u);	==>	", 1);
	printf("-->|%-*.2u|<--\n", -3, u);
	my_ft_putstr_fd("Printf(\"-->|%-*.2u|<--\\n\", -2, u);	==>	", 1);
	printf("-->|%-*.2u|<--\n", -2, u);
	my_ft_putstr_fd("Printf(\"-->|%-*.2u|<--\\n\", -1, u);	==>	", 1);
	printf("-->|%-*.2u|<--\n", -1, u);
	my_ft_putstr_fd("Printf(\"-->|%-*.2u|<--\\n\", 0, u);	==>	", 1);
	printf("-->|%-*.2u|<--\n", 0, u);
	my_ft_putstr_fd("Printf(\"-->|%-*.2u|<--\\n\", 1, u);	==>	", 1);
	printf("-->|%-*.2u|<--\n", 1, u);
	my_ft_putstr_fd("Printf(\"-->|%-*.2u|<--\\n\", 2, u);	==>	", 1);
	printf("-->|%-*.2u|<--\n", 2, u);
	my_ft_putstr_fd("Printf(\"-->|%-*.2u|<--\\n\", 3, u);	==>	", 1);
	printf("-->|%-*.2u|<--\n", 3, u);
	my_ft_putstr_fd("Printf(\"-->|%-*.2u|<--\\n\", 4, u);	==>	", 1);
	printf("-->|%-*.2u|<--\n", 4, u);
	my_ft_putstr_fd("Printf(\"-->|%-*.3u|<--\\n\", -4, u);	==>	", 1);
	printf("-->|%-*.3u|<--\n", -4, u);
	my_ft_putstr_fd("Printf(\"-->|%-*.3u|<--\\n\", -3, u);	==>	", 1);
	printf("-->|%-*.3u|<--\n", -3, u);
	my_ft_putstr_fd("Printf(\"-->|%-*.3u|<--\\n\", -2, u);	==>	", 1);
	printf("-->|%-*.3u|<--\n", -2, u);
	my_ft_putstr_fd("Printf(\"-->|%-*.3u|<--\\n\", -1, u);	==>	", 1);
	printf("-->|%-*.3u|<--\n", -1, u);
	my_ft_putstr_fd("Printf(\"-->|%-*.3u|<--\\n\", 0, u);	==>	", 1);
	printf("-->|%-*.3u|<--\n", 0, u);
	my_ft_putstr_fd("Printf(\"-->|%-*.3u|<--\\n\", 1, u);	==>	", 1);
	printf("-->|%-*.3u|<--\n", 1, u);
	my_ft_putstr_fd("Printf(\"-->|%-*.3u|<--\\n\", 2, u);	==>	", 1);
	printf("-->|%-*.3u|<--\n", 2, u);
	my_ft_putstr_fd("Printf(\"-->|%-*.3u|<--\\n\", 3, u);	==>	", 1);
	printf("-->|%-*.3u|<--\n", 3, u);
	my_ft_putstr_fd("Printf(\"-->|%-*.3u|<--\\n\", 4, u);	==>	", 1);
	printf("-->|%-*.3u|<--\n", 4, u);
	my_ft_putstr_fd("Printf(\"-->|%-*.4u|<--\\n\", -4, u);	==>	", 1);
	printf("-->|%-*.4u|<--\n", -4, u);
	my_ft_putstr_fd("Printf(\"-->|%-*.4u|<--\\n\", -3, u);	==>	", 1);
	printf("-->|%-*.4u|<--\n", -3, u);
	my_ft_putstr_fd("Printf(\"-->|%-*.4u|<--\\n\", -2, u);	==>	", 1);
	printf("-->|%-*.4u|<--\n", -2, u);
	my_ft_putstr_fd("Printf(\"-->|%-*.4u|<--\\n\", -1, u);	==>	", 1);
	printf("-->|%-*.4u|<--\n", -1, u);
	my_ft_putstr_fd("Printf(\"-->|%-*.4u|<--\\n\", 0, u);	==>	", 1);
	printf("-->|%-*.4u|<--\n", 0, u);
	my_ft_putstr_fd("Printf(\"-->|%-*.4u|<--\\n\", 1, u);	==>	", 1);
	printf("-->|%-*.4u|<--\n", 1, u);
	my_ft_putstr_fd("Printf(\"-->|%-*.4u|<--\\n\", 2, u);	==>	", 1);
	printf("-->|%-*.4u|<--\n", 2, u);
	my_ft_putstr_fd("Printf(\"-->|%-*.4u|<--\\n\", 3, u);	==>	", 1);
	printf("-->|%-*.4u|<--\n", 3, u);
	my_ft_putstr_fd("Printf(\"-->|%-*.4u|<--\\n\", 4, u);	==>	", 1);
	printf("-->|%-*.4u|<--\n", 4, u);
	my_ft_putstr_fd("Printf(\"-->|%-*u|<--\\n\", -4, u);	==>	", 1);
	printf("-->|%-*u|<--\n", -4, u);
	my_ft_putstr_fd("Printf(\"-->|%-*u|<--\\n\", -3, u);	==>	", 1);
	printf("-->|%-*u|<--\n", -3, u);
	my_ft_putstr_fd("Printf(\"-->|%-*u|<--\\n\", -2, u);	==>	", 1);
	printf("-->|%-*u|<--\n", -2, u);
	my_ft_putstr_fd("Printf(\"-->|%-*u|<--\\n\", -1, u);	==>	", 1);
	printf("-->|%-*u|<--\n", -1, u);
	my_ft_putstr_fd("Printf(\"-->|%-*u|<--\\n\", 0, u);	==>	", 1);
	printf("-->|%-*u|<--\n", 0, u);
	my_ft_putstr_fd("Printf(\"-->|%-*u|<--\\n\", 1, u);	==>	", 1);
	printf("-->|%-*u|<--\n", 1, u);
	my_ft_putstr_fd("Printf(\"-->|%-*u|<--\\n\", 2, u);	==>	", 1);
	printf("-->|%-*u|<--\n", 2, u);
	my_ft_putstr_fd("Printf(\"-->|%-*u|<--\\n\", 3, u);	==>	", 1);
	printf("-->|%-*u|<--\n", 3, u);
	my_ft_putstr_fd("Printf(\"-->|%-*u|<--\\n\", 4, u);	==>	", 1);
	printf("-->|%-*u|<--\n", 4, u);
	my_ft_putstr_fd("Printf(\"-->|%-1.u|<--\\n\", u);	==>	", 1);
	printf("-->|%-1.u|<--\n", u);
	my_ft_putstr_fd("Printf(\"-->|%-1.*u|<--\\n\", -4, u);	==>	", 1);
	printf("-->|%-1.*u|<--\n", -4, u);
	my_ft_putstr_fd("Printf(\"-->|%-1.*u|<--\\n\", -3, u);	==>	", 1);
	printf("-->|%-1.*u|<--\n", -3, u);
	my_ft_putstr_fd("Printf(\"-->|%-1.*u|<--\\n\", -2, u);	==>	", 1);
	printf("-->|%-1.*u|<--\n", -2, u);
	my_ft_putstr_fd("Printf(\"-->|%-1.*u|<--\\n\", -1, u);	==>	", 1);
	printf("-->|%-1.*u|<--\n", -1, u);
	my_ft_putstr_fd("Printf(\"-->|%-1.*u|<--\\n\", 0, u);	==>	", 1);
	printf("-->|%-1.*u|<--\n", 0, u);
	my_ft_putstr_fd("Printf(\"-->|%-1.*u|<--\\n\", 1, u);	==>	", 1);
	printf("-->|%-1.*u|<--\n", 1, u);
	my_ft_putstr_fd("Printf(\"-->|%-1.*u|<--\\n\", 2, u);	==>	", 1);
	printf("-->|%-1.*u|<--\n", 2, u);
	my_ft_putstr_fd("Printf(\"-->|%-1.*u|<--\\n\", 3, u);	==>	", 1);
	printf("-->|%-1.*u|<--\n", 3, u);
	my_ft_putstr_fd("Printf(\"-->|%-1.*u|<--\\n\", 4, u);	==>	", 1);
	printf("-->|%-1.*u|<--\n", 4, u);
	my_ft_putstr_fd("Printf(\"-->|%-1.0u|<--\\n\", u);	==>	", 1);
	printf("-->|%-1.0u|<--\n", u);
	my_ft_putstr_fd("Printf(\"-->|%-1.1u|<--\\n\", u);	==>	", 1);
	printf("-->|%-1.1u|<--\n", u);
	my_ft_putstr_fd("Printf(\"-->|%-1.2u|<--\\n\", u);	==>	", 1);
	printf("-->|%-1.2u|<--\n", u);
	my_ft_putstr_fd("Printf(\"-->|%-1.3u|<--\\n\", u);	==>	", 1);
	printf("-->|%-1.3u|<--\n", u);
	my_ft_putstr_fd("Printf(\"-->|%-1.4u|<--\\n\", u);	==>	", 1);
	printf("-->|%-1.4u|<--\n", u);
	my_ft_putstr_fd("Printf(\"-->|%-1u|<--\\n\", u);	==>	", 1);
	printf("-->|%-1u|<--\n", u);
	my_ft_putstr_fd("Printf(\"-->|%-2.u|<--\\n\", u);	==>	", 1);
	printf("-->|%-2.u|<--\n", u);
	my_ft_putstr_fd("Printf(\"-->|%-2.*u|<--\\n\", -4, u);	==>	", 1);
	printf("-->|%-2.*u|<--\n", -4, u);
	my_ft_putstr_fd("Printf(\"-->|%-2.*u|<--\\n\", -3, u);	==>	", 1);
	printf("-->|%-2.*u|<--\n", -3, u);
	my_ft_putstr_fd("Printf(\"-->|%-2.*u|<--\\n\", -2, u);	==>	", 1);
	printf("-->|%-2.*u|<--\n", -2, u);
	my_ft_putstr_fd("Printf(\"-->|%-2.*u|<--\\n\", -1, u);	==>	", 1);
	printf("-->|%-2.*u|<--\n", -1, u);
	my_ft_putstr_fd("Printf(\"-->|%-2.*u|<--\\n\", 0, u);	==>	", 1);
	printf("-->|%-2.*u|<--\n", 0, u);
	my_ft_putstr_fd("Printf(\"-->|%-2.*u|<--\\n\", 1, u);	==>	", 1);
	printf("-->|%-2.*u|<--\n", 1, u);
	my_ft_putstr_fd("Printf(\"-->|%-2.*u|<--\\n\", 2, u);	==>	", 1);
	printf("-->|%-2.*u|<--\n", 2, u);
	my_ft_putstr_fd("Printf(\"-->|%-2.*u|<--\\n\", 3, u);	==>	", 1);
	printf("-->|%-2.*u|<--\n", 3, u);
	my_ft_putstr_fd("Printf(\"-->|%-2.*u|<--\\n\", 4, u);	==>	", 1);
	printf("-->|%-2.*u|<--\n", 4, u);
	my_ft_putstr_fd("Printf(\"-->|%-2.0u|<--\\n\", u);	==>	", 1);
	printf("-->|%-2.0u|<--\n", u);
	my_ft_putstr_fd("Printf(\"-->|%-2.1u|<--\\n\", u);	==>	", 1);
	printf("-->|%-2.1u|<--\n", u);
	my_ft_putstr_fd("Printf(\"-->|%-2.2u|<--\\n\", u);	==>	", 1);
	printf("-->|%-2.2u|<--\n", u);
	my_ft_putstr_fd("Printf(\"-->|%-2.3u|<--\\n\", u);	==>	", 1);
	printf("-->|%-2.3u|<--\n", u);
	my_ft_putstr_fd("Printf(\"-->|%-2.4u|<--\\n\", u);	==>	", 1);
	printf("-->|%-2.4u|<--\n", u);
	my_ft_putstr_fd("Printf(\"-->|%-2u|<--\\n\", u);	==>	", 1);
	printf("-->|%-2u|<--\n", u);
	my_ft_putstr_fd("Printf(\"-->|%-3.u|<--\\n\", u);	==>	", 1);
	printf("-->|%-3.u|<--\n", u);
	my_ft_putstr_fd("Printf(\"-->|%-3.*u|<--\\n\", -4, u);	==>	", 1);
	printf("-->|%-3.*u|<--\n", -4, u);
	my_ft_putstr_fd("Printf(\"-->|%-3.*u|<--\\n\", -3, u);	==>	", 1);
	printf("-->|%-3.*u|<--\n", -3, u);
	my_ft_putstr_fd("Printf(\"-->|%-3.*u|<--\\n\", -2, u);	==>	", 1);
	printf("-->|%-3.*u|<--\n", -2, u);
	my_ft_putstr_fd("Printf(\"-->|%-3.*u|<--\\n\", -1, u);	==>	", 1);
	printf("-->|%-3.*u|<--\n", -1, u);
	my_ft_putstr_fd("Printf(\"-->|%-3.*u|<--\\n\", 0, u);	==>	", 1);
	printf("-->|%-3.*u|<--\n", 0, u);
	my_ft_putstr_fd("Printf(\"-->|%-3.*u|<--\\n\", 1, u);	==>	", 1);
	printf("-->|%-3.*u|<--\n", 1, u);
	my_ft_putstr_fd("Printf(\"-->|%-3.*u|<--\\n\", 2, u);	==>	", 1);
	printf("-->|%-3.*u|<--\n", 2, u);
	my_ft_putstr_fd("Printf(\"-->|%-3.*u|<--\\n\", 3, u);	==>	", 1);
	printf("-->|%-3.*u|<--\n", 3, u);
	my_ft_putstr_fd("Printf(\"-->|%-3.*u|<--\\n\", 4, u);	==>	", 1);
	printf("-->|%-3.*u|<--\n", 4, u);
	my_ft_putstr_fd("Printf(\"-->|%-3.0u|<--\\n\", u);	==>	", 1);
	printf("-->|%-3.0u|<--\n", u);
	my_ft_putstr_fd("Printf(\"-->|%-3.1u|<--\\n\", u);	==>	", 1);
	printf("-->|%-3.1u|<--\n", u);
	my_ft_putstr_fd("Printf(\"-->|%-3.2u|<--\\n\", u);	==>	", 1);
	printf("-->|%-3.2u|<--\n", u);
	my_ft_putstr_fd("Printf(\"-->|%-3.3u|<--\\n\", u);	==>	", 1);
	printf("-->|%-3.3u|<--\n", u);
	my_ft_putstr_fd("Printf(\"-->|%-3.4u|<--\\n\", u);	==>	", 1);
	printf("-->|%-3.4u|<--\n", u);
	my_ft_putstr_fd("Printf(\"-->|%-3u|<--\\n\", u);	==>	", 1);
	printf("-->|%-3u|<--\n", u);
	my_ft_putstr_fd("Printf(\"-->|%-4.u|<--\\n\", u);	==>	", 1);
	printf("-->|%-4.u|<--\n", u);
	my_ft_putstr_fd("Printf(\"-->|%-4.*u|<--\\n\", -4, u);	==>	", 1);
	printf("-->|%-4.*u|<--\n", -4, u);
	my_ft_putstr_fd("Printf(\"-->|%-4.*u|<--\\n\", -3, u);	==>	", 1);
	printf("-->|%-4.*u|<--\n", -3, u);
	my_ft_putstr_fd("Printf(\"-->|%-4.*u|<--\\n\", -2, u);	==>	", 1);
	printf("-->|%-4.*u|<--\n", -2, u);
	my_ft_putstr_fd("Printf(\"-->|%-4.*u|<--\\n\", -1, u);	==>	", 1);
	printf("-->|%-4.*u|<--\n", -1, u);
	my_ft_putstr_fd("Printf(\"-->|%-4.*u|<--\\n\", 0, u);	==>	", 1);
	printf("-->|%-4.*u|<--\n", 0, u);
	my_ft_putstr_fd("Printf(\"-->|%-4.*u|<--\\n\", 1, u);	==>	", 1);
	printf("-->|%-4.*u|<--\n", 1, u);
	my_ft_putstr_fd("Printf(\"-->|%-4.*u|<--\\n\", 2, u);	==>	", 1);
	printf("-->|%-4.*u|<--\n", 2, u);
	my_ft_putstr_fd("Printf(\"-->|%-4.*u|<--\\n\", 3, u);	==>	", 1);
	printf("-->|%-4.*u|<--\n", 3, u);
	my_ft_putstr_fd("Printf(\"-->|%-4.*u|<--\\n\", 4, u);	==>	", 1);
	printf("-->|%-4.*u|<--\n", 4, u);
	my_ft_putstr_fd("Printf(\"-->|%-4.0u|<--\\n\", u);	==>	", 1);
	printf("-->|%-4.0u|<--\n", u);
	my_ft_putstr_fd("Printf(\"-->|%-4.1u|<--\\n\", u);	==>	", 1);
	printf("-->|%-4.1u|<--\n", u);
	my_ft_putstr_fd("Printf(\"-->|%-4.2u|<--\\n\", u);	==>	", 1);
	printf("-->|%-4.2u|<--\n", u);
	my_ft_putstr_fd("Printf(\"-->|%-4.3u|<--\\n\", u);	==>	", 1);
	printf("-->|%-4.3u|<--\n", u);
	my_ft_putstr_fd("Printf(\"-->|%-4.4u|<--\\n\", u);	==>	", 1);
	printf("-->|%-4.4u|<--\n", u);
	my_ft_putstr_fd("Printf(\"-->|%-4u|<--\\n\", u);	==>	", 1);
	printf("-->|%-4u|<--\n", u);
	return(0);
}
/*
** charmstr@student.42.fr
**
** 832 different calls generated automatically according to your options
*/
