/*
** charmstr@student.42.fr
*/

#include "../includes/printf_lover_test_func.h"
#include "../includes/ft_printf.h"
#include "../includes/printf_lover_test_func.h"
#include "../includes/ft_printf.h"
#include "../includes/printf_lover_test_func.h"
#include "../includes/ft_printf.h"
#include "../includes/printf_lover_test_func.h"
#include "../includes/ft_printf.h"
#include "../includes/printf_lover_test_func.h"
#include "../includes/ft_printf.h"
#include "../includes/printf_lover_test_func.h"
#include "../includes/ft_printf.h"
#include <stdio.h>
#include <assert.h>
#include "../includes/printf_lover_test_func.h"

int	test_func_u(unsigned int u)
{
setbuf(stdout, NULL);
assert(printf("-->|%-4.u|<--\n", u) == ft_printf("-->|%-4.u|<--\n", u));
assert(printf("-->|%-4.*u|<--\n", -4, u) == ft_printf("-->|%-4.*u|<--\n", -4, u));
assert(printf("-->|%-4.*u|<--\n", -3, u) == ft_printf("-->|%-4.*u|<--\n", -3, u));
assert(printf("-->|%-4.*u|<--\n", -2, u) == ft_printf("-->|%-4.*u|<--\n", -2, u));
assert(printf("-->|%-4.*u|<--\n", -1, u) == ft_printf("-->|%-4.*u|<--\n", -1, u));
assert(printf("-->|%-4.*u|<--\n", 0, u) == ft_printf("-->|%-4.*u|<--\n", 0, u));
assert(printf("-->|%-4.*u|<--\n", 1, u) == ft_printf("-->|%-4.*u|<--\n", 1, u));
assert(printf("-->|%-4.*u|<--\n", 2, u) == ft_printf("-->|%-4.*u|<--\n", 2, u));
assert(printf("-->|%-4.*u|<--\n", 3, u) == ft_printf("-->|%-4.*u|<--\n", 3, u));
assert(printf("-->|%-4.*u|<--\n", 4, u) == ft_printf("-->|%-4.*u|<--\n", 4, u));
assert(printf("-->|%-4.0u|<--\n", u) == ft_printf("-->|%-4.0u|<--\n", u));
assert(printf("-->|%-4.1u|<--\n", u) == ft_printf("-->|%-4.1u|<--\n", u));
assert(printf("-->|%-4.2u|<--\n", u) == ft_printf("-->|%-4.2u|<--\n", u));
assert(printf("-->|%-4.3u|<--\n", u) == ft_printf("-->|%-4.3u|<--\n", u));
assert(printf("-->|%-4.4u|<--\n", u) == ft_printf("-->|%-4.4u|<--\n", u));
assert(printf("-->|%-4u|<--\n", u) == ft_printf("-->|%-4u|<--\n", u));
assert(printf("-->|%-3.u|<--\n", u) == ft_printf("-->|%-3.u|<--\n", u));
assert(printf("-->|%-3.*u|<--\n", -4, u) == ft_printf("-->|%-3.*u|<--\n", -4, u));
assert(printf("-->|%-3.*u|<--\n", -3, u) == ft_printf("-->|%-3.*u|<--\n", -3, u));
assert(printf("-->|%-3.*u|<--\n", -2, u) == ft_printf("-->|%-3.*u|<--\n", -2, u));
assert(printf("-->|%-3.*u|<--\n", -1, u) == ft_printf("-->|%-3.*u|<--\n", -1, u));
assert(printf("-->|%-3.*u|<--\n", 0, u) == ft_printf("-->|%-3.*u|<--\n", 0, u));
assert(printf("-->|%-3.*u|<--\n", 1, u) == ft_printf("-->|%-3.*u|<--\n", 1, u));
assert(printf("-->|%-3.*u|<--\n", 2, u) == ft_printf("-->|%-3.*u|<--\n", 2, u));
assert(printf("-->|%-3.*u|<--\n", 3, u) == ft_printf("-->|%-3.*u|<--\n", 3, u));
assert(printf("-->|%-3.*u|<--\n", 4, u) == ft_printf("-->|%-3.*u|<--\n", 4, u));
assert(printf("-->|%-3.0u|<--\n", u) == ft_printf("-->|%-3.0u|<--\n", u));
assert(printf("-->|%-3.1u|<--\n", u) == ft_printf("-->|%-3.1u|<--\n", u));
assert(printf("-->|%-3.2u|<--\n", u) == ft_printf("-->|%-3.2u|<--\n", u));
assert(printf("-->|%-3.3u|<--\n", u) == ft_printf("-->|%-3.3u|<--\n", u));
assert(printf("-->|%-3.4u|<--\n", u) == ft_printf("-->|%-3.4u|<--\n", u));
assert(printf("-->|%-3u|<--\n", u) == ft_printf("-->|%-3u|<--\n", u));
assert(printf("-->|%-2.u|<--\n", u) == ft_printf("-->|%-2.u|<--\n", u));
assert(printf("-->|%-2.*u|<--\n", -4, u) == ft_printf("-->|%-2.*u|<--\n", -4, u));
assert(printf("-->|%-2.*u|<--\n", -3, u) == ft_printf("-->|%-2.*u|<--\n", -3, u));
assert(printf("-->|%-2.*u|<--\n", -2, u) == ft_printf("-->|%-2.*u|<--\n", -2, u));
assert(printf("-->|%-2.*u|<--\n", -1, u) == ft_printf("-->|%-2.*u|<--\n", -1, u));
assert(printf("-->|%-2.*u|<--\n", 0, u) == ft_printf("-->|%-2.*u|<--\n", 0, u));
assert(printf("-->|%-2.*u|<--\n", 1, u) == ft_printf("-->|%-2.*u|<--\n", 1, u));
assert(printf("-->|%-2.*u|<--\n", 2, u) == ft_printf("-->|%-2.*u|<--\n", 2, u));
assert(printf("-->|%-2.*u|<--\n", 3, u) == ft_printf("-->|%-2.*u|<--\n", 3, u));
assert(printf("-->|%-2.*u|<--\n", 4, u) == ft_printf("-->|%-2.*u|<--\n", 4, u));
assert(printf("-->|%-2.0u|<--\n", u) == ft_printf("-->|%-2.0u|<--\n", u));
assert(printf("-->|%-2.1u|<--\n", u) == ft_printf("-->|%-2.1u|<--\n", u));
assert(printf("-->|%-2.2u|<--\n", u) == ft_printf("-->|%-2.2u|<--\n", u));
assert(printf("-->|%-2.3u|<--\n", u) == ft_printf("-->|%-2.3u|<--\n", u));
assert(printf("-->|%-2.4u|<--\n", u) == ft_printf("-->|%-2.4u|<--\n", u));
assert(printf("-->|%-2u|<--\n", u) == ft_printf("-->|%-2u|<--\n", u));
assert(printf("-->|%-1.u|<--\n", u) == ft_printf("-->|%-1.u|<--\n", u));
assert(printf("-->|%-1.*u|<--\n", -4, u) == ft_printf("-->|%-1.*u|<--\n", -4, u));
assert(printf("-->|%-1.*u|<--\n", -3, u) == ft_printf("-->|%-1.*u|<--\n", -3, u));
assert(printf("-->|%-1.*u|<--\n", -2, u) == ft_printf("-->|%-1.*u|<--\n", -2, u));
assert(printf("-->|%-1.*u|<--\n", -1, u) == ft_printf("-->|%-1.*u|<--\n", -1, u));
assert(printf("-->|%-1.*u|<--\n", 0, u) == ft_printf("-->|%-1.*u|<--\n", 0, u));
assert(printf("-->|%-1.*u|<--\n", 1, u) == ft_printf("-->|%-1.*u|<--\n", 1, u));
assert(printf("-->|%-1.*u|<--\n", 2, u) == ft_printf("-->|%-1.*u|<--\n", 2, u));
assert(printf("-->|%-1.*u|<--\n", 3, u) == ft_printf("-->|%-1.*u|<--\n", 3, u));
assert(printf("-->|%-1.*u|<--\n", 4, u) == ft_printf("-->|%-1.*u|<--\n", 4, u));
assert(printf("-->|%-1.0u|<--\n", u) == ft_printf("-->|%-1.0u|<--\n", u));
assert(printf("-->|%-1.1u|<--\n", u) == ft_printf("-->|%-1.1u|<--\n", u));
assert(printf("-->|%-1.2u|<--\n", u) == ft_printf("-->|%-1.2u|<--\n", u));
assert(printf("-->|%-1.3u|<--\n", u) == ft_printf("-->|%-1.3u|<--\n", u));
assert(printf("-->|%-1.4u|<--\n", u) == ft_printf("-->|%-1.4u|<--\n", u));
assert(printf("-->|%-1u|<--\n", u) == ft_printf("-->|%-1u|<--\n", u));
assert(printf("-->|%.u|<--\n", u) == ft_printf("-->|%.u|<--\n", u));
assert(printf("-->|%.*u|<--\n", -4, u) == ft_printf("-->|%.*u|<--\n", -4, u));
assert(printf("-->|%.*u|<--\n", -3, u) == ft_printf("-->|%.*u|<--\n", -3, u));
assert(printf("-->|%.*u|<--\n", -2, u) == ft_printf("-->|%.*u|<--\n", -2, u));
assert(printf("-->|%.*u|<--\n", -1, u) == ft_printf("-->|%.*u|<--\n", -1, u));
assert(printf("-->|%.*u|<--\n", 0, u) == ft_printf("-->|%.*u|<--\n", 0, u));
assert(printf("-->|%.*u|<--\n", 1, u) == ft_printf("-->|%.*u|<--\n", 1, u));
assert(printf("-->|%.*u|<--\n", 2, u) == ft_printf("-->|%.*u|<--\n", 2, u));
assert(printf("-->|%.*u|<--\n", 3, u) == ft_printf("-->|%.*u|<--\n", 3, u));
assert(printf("-->|%.*u|<--\n", 4, u) == ft_printf("-->|%.*u|<--\n", 4, u));
assert(printf("-->|%.0u|<--\n", u) == ft_printf("-->|%.0u|<--\n", u));
assert(printf("-->|%.1u|<--\n", u) == ft_printf("-->|%.1u|<--\n", u));
assert(printf("-->|%.2u|<--\n", u) == ft_printf("-->|%.2u|<--\n", u));
assert(printf("-->|%.3u|<--\n", u) == ft_printf("-->|%.3u|<--\n", u));
assert(printf("-->|%.4u|<--\n", u) == ft_printf("-->|%.4u|<--\n", u));
assert(printf("-->|%u|<--\n", u) == ft_printf("-->|%u|<--\n", u));
assert(printf("-->|%*.u|<--\n", -4, u) == ft_printf("-->|%*.u|<--\n", -4, u));
assert(printf("-->|%*.u|<--\n", -3, u) == ft_printf("-->|%*.u|<--\n", -3, u));
assert(printf("-->|%*.u|<--\n", -2, u) == ft_printf("-->|%*.u|<--\n", -2, u));
assert(printf("-->|%*.u|<--\n", -1, u) == ft_printf("-->|%*.u|<--\n", -1, u));
assert(printf("-->|%*.u|<--\n", 0, u) == ft_printf("-->|%*.u|<--\n", 0, u));
assert(printf("-->|%*.u|<--\n", 1, u) == ft_printf("-->|%*.u|<--\n", 1, u));
assert(printf("-->|%*.u|<--\n", 2, u) == ft_printf("-->|%*.u|<--\n", 2, u));
assert(printf("-->|%*.u|<--\n", 3, u) == ft_printf("-->|%*.u|<--\n", 3, u));
assert(printf("-->|%*.u|<--\n", 4, u) == ft_printf("-->|%*.u|<--\n", 4, u));
assert(printf("-->|%*.*u|<--\n", -4, -4, u) == ft_printf("-->|%*.*u|<--\n", -4, -4, u));
assert(printf("-->|%*.*u|<--\n", -4, -3, u) == ft_printf("-->|%*.*u|<--\n", -4, -3, u));
assert(printf("-->|%*.*u|<--\n", -4, -2, u) == ft_printf("-->|%*.*u|<--\n", -4, -2, u));
assert(printf("-->|%*.*u|<--\n", -4, -1, u) == ft_printf("-->|%*.*u|<--\n", -4, -1, u));
assert(printf("-->|%*.*u|<--\n", -4, 0, u) == ft_printf("-->|%*.*u|<--\n", -4, 0, u));
assert(printf("-->|%*.*u|<--\n", -4, 1, u) == ft_printf("-->|%*.*u|<--\n", -4, 1, u));
assert(printf("-->|%*.*u|<--\n", -4, 2, u) == ft_printf("-->|%*.*u|<--\n", -4, 2, u));
assert(printf("-->|%*.*u|<--\n", -4, 3, u) == ft_printf("-->|%*.*u|<--\n", -4, 3, u));
assert(printf("-->|%*.*u|<--\n", -4, 4, u) == ft_printf("-->|%*.*u|<--\n", -4, 4, u));
assert(printf("-->|%*.*u|<--\n", -3, -4, u) == ft_printf("-->|%*.*u|<--\n", -3, -4, u));
assert(printf("-->|%*.*u|<--\n", -3, -3, u) == ft_printf("-->|%*.*u|<--\n", -3, -3, u));
assert(printf("-->|%*.*u|<--\n", -3, -2, u) == ft_printf("-->|%*.*u|<--\n", -3, -2, u));
assert(printf("-->|%*.*u|<--\n", -3, -1, u) == ft_printf("-->|%*.*u|<--\n", -3, -1, u));
assert(printf("-->|%*.*u|<--\n", -3, 0, u) == ft_printf("-->|%*.*u|<--\n", -3, 0, u));
assert(printf("-->|%*.*u|<--\n", -3, 1, u) == ft_printf("-->|%*.*u|<--\n", -3, 1, u));
assert(printf("-->|%*.*u|<--\n", -3, 2, u) == ft_printf("-->|%*.*u|<--\n", -3, 2, u));
assert(printf("-->|%*.*u|<--\n", -3, 3, u) == ft_printf("-->|%*.*u|<--\n", -3, 3, u));
assert(printf("-->|%*.*u|<--\n", -3, 4, u) == ft_printf("-->|%*.*u|<--\n", -3, 4, u));
assert(printf("-->|%*.*u|<--\n", -2, -4, u) == ft_printf("-->|%*.*u|<--\n", -2, -4, u));
assert(printf("-->|%*.*u|<--\n", -2, -3, u) == ft_printf("-->|%*.*u|<--\n", -2, -3, u));
assert(printf("-->|%*.*u|<--\n", -2, -2, u) == ft_printf("-->|%*.*u|<--\n", -2, -2, u));
assert(printf("-->|%*.*u|<--\n", -2, -1, u) == ft_printf("-->|%*.*u|<--\n", -2, -1, u));
assert(printf("-->|%*.*u|<--\n", -2, 0, u) == ft_printf("-->|%*.*u|<--\n", -2, 0, u));
assert(printf("-->|%*.*u|<--\n", -2, 1, u) == ft_printf("-->|%*.*u|<--\n", -2, 1, u));
assert(printf("-->|%*.*u|<--\n", -2, 2, u) == ft_printf("-->|%*.*u|<--\n", -2, 2, u));
assert(printf("-->|%*.*u|<--\n", -2, 3, u) == ft_printf("-->|%*.*u|<--\n", -2, 3, u));
assert(printf("-->|%*.*u|<--\n", -2, 4, u) == ft_printf("-->|%*.*u|<--\n", -2, 4, u));
assert(printf("-->|%*.*u|<--\n", -1, -4, u) == ft_printf("-->|%*.*u|<--\n", -1, -4, u));
assert(printf("-->|%*.*u|<--\n", -1, -3, u) == ft_printf("-->|%*.*u|<--\n", -1, -3, u));
assert(printf("-->|%*.*u|<--\n", -1, -2, u) == ft_printf("-->|%*.*u|<--\n", -1, -2, u));
assert(printf("-->|%*.*u|<--\n", -1, -1, u) == ft_printf("-->|%*.*u|<--\n", -1, -1, u));
assert(printf("-->|%*.*u|<--\n", -1, 0, u) == ft_printf("-->|%*.*u|<--\n", -1, 0, u));
assert(printf("-->|%*.*u|<--\n", -1, 1, u) == ft_printf("-->|%*.*u|<--\n", -1, 1, u));
assert(printf("-->|%*.*u|<--\n", -1, 2, u) == ft_printf("-->|%*.*u|<--\n", -1, 2, u));
assert(printf("-->|%*.*u|<--\n", -1, 3, u) == ft_printf("-->|%*.*u|<--\n", -1, 3, u));
assert(printf("-->|%*.*u|<--\n", -1, 4, u) == ft_printf("-->|%*.*u|<--\n", -1, 4, u));
assert(printf("-->|%*.*u|<--\n", 0, -4, u) == ft_printf("-->|%*.*u|<--\n", 0, -4, u));
assert(printf("-->|%*.*u|<--\n", 0, -3, u) == ft_printf("-->|%*.*u|<--\n", 0, -3, u));
assert(printf("-->|%*.*u|<--\n", 0, -2, u) == ft_printf("-->|%*.*u|<--\n", 0, -2, u));
assert(printf("-->|%*.*u|<--\n", 0, -1, u) == ft_printf("-->|%*.*u|<--\n", 0, -1, u));
assert(printf("-->|%*.*u|<--\n", 0, 0, u) == ft_printf("-->|%*.*u|<--\n", 0, 0, u));
assert(printf("-->|%*.*u|<--\n", 0, 1, u) == ft_printf("-->|%*.*u|<--\n", 0, 1, u));
assert(printf("-->|%*.*u|<--\n", 0, 2, u) == ft_printf("-->|%*.*u|<--\n", 0, 2, u));
assert(printf("-->|%*.*u|<--\n", 0, 3, u) == ft_printf("-->|%*.*u|<--\n", 0, 3, u));
assert(printf("-->|%*.*u|<--\n", 0, 4, u) == ft_printf("-->|%*.*u|<--\n", 0, 4, u));
assert(printf("-->|%*.*u|<--\n", 1, -4, u) == ft_printf("-->|%*.*u|<--\n", 1, -4, u));
assert(printf("-->|%*.*u|<--\n", 1, -3, u) == ft_printf("-->|%*.*u|<--\n", 1, -3, u));
assert(printf("-->|%*.*u|<--\n", 1, -2, u) == ft_printf("-->|%*.*u|<--\n", 1, -2, u));
assert(printf("-->|%*.*u|<--\n", 1, -1, u) == ft_printf("-->|%*.*u|<--\n", 1, -1, u));
assert(printf("-->|%*.*u|<--\n", 1, 0, u) == ft_printf("-->|%*.*u|<--\n", 1, 0, u));
assert(printf("-->|%*.*u|<--\n", 1, 1, u) == ft_printf("-->|%*.*u|<--\n", 1, 1, u));
assert(printf("-->|%*.*u|<--\n", 1, 2, u) == ft_printf("-->|%*.*u|<--\n", 1, 2, u));
assert(printf("-->|%*.*u|<--\n", 1, 3, u) == ft_printf("-->|%*.*u|<--\n", 1, 3, u));
assert(printf("-->|%*.*u|<--\n", 1, 4, u) == ft_printf("-->|%*.*u|<--\n", 1, 4, u));
assert(printf("-->|%*.*u|<--\n", 2, -4, u) == ft_printf("-->|%*.*u|<--\n", 2, -4, u));
assert(printf("-->|%*.*u|<--\n", 2, -3, u) == ft_printf("-->|%*.*u|<--\n", 2, -3, u));
assert(printf("-->|%*.*u|<--\n", 2, -2, u) == ft_printf("-->|%*.*u|<--\n", 2, -2, u));
assert(printf("-->|%*.*u|<--\n", 2, -1, u) == ft_printf("-->|%*.*u|<--\n", 2, -1, u));
assert(printf("-->|%*.*u|<--\n", 2, 0, u) == ft_printf("-->|%*.*u|<--\n", 2, 0, u));
assert(printf("-->|%*.*u|<--\n", 2, 1, u) == ft_printf("-->|%*.*u|<--\n", 2, 1, u));
assert(printf("-->|%*.*u|<--\n", 2, 2, u) == ft_printf("-->|%*.*u|<--\n", 2, 2, u));
assert(printf("-->|%*.*u|<--\n", 2, 3, u) == ft_printf("-->|%*.*u|<--\n", 2, 3, u));
assert(printf("-->|%*.*u|<--\n", 2, 4, u) == ft_printf("-->|%*.*u|<--\n", 2, 4, u));
assert(printf("-->|%*.*u|<--\n", 3, -4, u) == ft_printf("-->|%*.*u|<--\n", 3, -4, u));
assert(printf("-->|%*.*u|<--\n", 3, -3, u) == ft_printf("-->|%*.*u|<--\n", 3, -3, u));
assert(printf("-->|%*.*u|<--\n", 3, -2, u) == ft_printf("-->|%*.*u|<--\n", 3, -2, u));
assert(printf("-->|%*.*u|<--\n", 3, -1, u) == ft_printf("-->|%*.*u|<--\n", 3, -1, u));
assert(printf("-->|%*.*u|<--\n", 3, 0, u) == ft_printf("-->|%*.*u|<--\n", 3, 0, u));
assert(printf("-->|%*.*u|<--\n", 3, 1, u) == ft_printf("-->|%*.*u|<--\n", 3, 1, u));
assert(printf("-->|%*.*u|<--\n", 3, 2, u) == ft_printf("-->|%*.*u|<--\n", 3, 2, u));
assert(printf("-->|%*.*u|<--\n", 3, 3, u) == ft_printf("-->|%*.*u|<--\n", 3, 3, u));
assert(printf("-->|%*.*u|<--\n", 3, 4, u) == ft_printf("-->|%*.*u|<--\n", 3, 4, u));
assert(printf("-->|%*.*u|<--\n", 4, -4, u) == ft_printf("-->|%*.*u|<--\n", 4, -4, u));
assert(printf("-->|%*.*u|<--\n", 4, -3, u) == ft_printf("-->|%*.*u|<--\n", 4, -3, u));
assert(printf("-->|%*.*u|<--\n", 4, -2, u) == ft_printf("-->|%*.*u|<--\n", 4, -2, u));
assert(printf("-->|%*.*u|<--\n", 4, -1, u) == ft_printf("-->|%*.*u|<--\n", 4, -1, u));
assert(printf("-->|%*.*u|<--\n", 4, 0, u) == ft_printf("-->|%*.*u|<--\n", 4, 0, u));
assert(printf("-->|%*.*u|<--\n", 4, 1, u) == ft_printf("-->|%*.*u|<--\n", 4, 1, u));
assert(printf("-->|%*.*u|<--\n", 4, 2, u) == ft_printf("-->|%*.*u|<--\n", 4, 2, u));
assert(printf("-->|%*.*u|<--\n", 4, 3, u) == ft_printf("-->|%*.*u|<--\n", 4, 3, u));
assert(printf("-->|%*.*u|<--\n", 4, 4, u) == ft_printf("-->|%*.*u|<--\n", 4, 4, u));
assert(printf("-->|%*.0u|<--\n", -4, u) == ft_printf("-->|%*.0u|<--\n", -4, u));
assert(printf("-->|%*.0u|<--\n", -3, u) == ft_printf("-->|%*.0u|<--\n", -3, u));
assert(printf("-->|%*.0u|<--\n", -2, u) == ft_printf("-->|%*.0u|<--\n", -2, u));
assert(printf("-->|%*.0u|<--\n", -1, u) == ft_printf("-->|%*.0u|<--\n", -1, u));
assert(printf("-->|%*.0u|<--\n", 0, u) == ft_printf("-->|%*.0u|<--\n", 0, u));
assert(printf("-->|%*.0u|<--\n", 1, u) == ft_printf("-->|%*.0u|<--\n", 1, u));
assert(printf("-->|%*.0u|<--\n", 2, u) == ft_printf("-->|%*.0u|<--\n", 2, u));
assert(printf("-->|%*.0u|<--\n", 3, u) == ft_printf("-->|%*.0u|<--\n", 3, u));
assert(printf("-->|%*.0u|<--\n", 4, u) == ft_printf("-->|%*.0u|<--\n", 4, u));
assert(printf("-->|%*.1u|<--\n", -4, u) == ft_printf("-->|%*.1u|<--\n", -4, u));
assert(printf("-->|%*.1u|<--\n", -3, u) == ft_printf("-->|%*.1u|<--\n", -3, u));
assert(printf("-->|%*.1u|<--\n", -2, u) == ft_printf("-->|%*.1u|<--\n", -2, u));
assert(printf("-->|%*.1u|<--\n", -1, u) == ft_printf("-->|%*.1u|<--\n", -1, u));
assert(printf("-->|%*.1u|<--\n", 0, u) == ft_printf("-->|%*.1u|<--\n", 0, u));
assert(printf("-->|%*.1u|<--\n", 1, u) == ft_printf("-->|%*.1u|<--\n", 1, u));
assert(printf("-->|%*.1u|<--\n", 2, u) == ft_printf("-->|%*.1u|<--\n", 2, u));
assert(printf("-->|%*.1u|<--\n", 3, u) == ft_printf("-->|%*.1u|<--\n", 3, u));
assert(printf("-->|%*.1u|<--\n", 4, u) == ft_printf("-->|%*.1u|<--\n", 4, u));
assert(printf("-->|%*.2u|<--\n", -4, u) == ft_printf("-->|%*.2u|<--\n", -4, u));
assert(printf("-->|%*.2u|<--\n", -3, u) == ft_printf("-->|%*.2u|<--\n", -3, u));
assert(printf("-->|%*.2u|<--\n", -2, u) == ft_printf("-->|%*.2u|<--\n", -2, u));
assert(printf("-->|%*.2u|<--\n", -1, u) == ft_printf("-->|%*.2u|<--\n", -1, u));
assert(printf("-->|%*.2u|<--\n", 0, u) == ft_printf("-->|%*.2u|<--\n", 0, u));
assert(printf("-->|%*.2u|<--\n", 1, u) == ft_printf("-->|%*.2u|<--\n", 1, u));
assert(printf("-->|%*.2u|<--\n", 2, u) == ft_printf("-->|%*.2u|<--\n", 2, u));
assert(printf("-->|%*.2u|<--\n", 3, u) == ft_printf("-->|%*.2u|<--\n", 3, u));
assert(printf("-->|%*.2u|<--\n", 4, u) == ft_printf("-->|%*.2u|<--\n", 4, u));
assert(printf("-->|%*.3u|<--\n", -4, u) == ft_printf("-->|%*.3u|<--\n", -4, u));
assert(printf("-->|%*.3u|<--\n", -3, u) == ft_printf("-->|%*.3u|<--\n", -3, u));
assert(printf("-->|%*.3u|<--\n", -2, u) == ft_printf("-->|%*.3u|<--\n", -2, u));
assert(printf("-->|%*.3u|<--\n", -1, u) == ft_printf("-->|%*.3u|<--\n", -1, u));
assert(printf("-->|%*.3u|<--\n", 0, u) == ft_printf("-->|%*.3u|<--\n", 0, u));
assert(printf("-->|%*.3u|<--\n", 1, u) == ft_printf("-->|%*.3u|<--\n", 1, u));
assert(printf("-->|%*.3u|<--\n", 2, u) == ft_printf("-->|%*.3u|<--\n", 2, u));
assert(printf("-->|%*.3u|<--\n", 3, u) == ft_printf("-->|%*.3u|<--\n", 3, u));
assert(printf("-->|%*.3u|<--\n", 4, u) == ft_printf("-->|%*.3u|<--\n", 4, u));
assert(printf("-->|%*.4u|<--\n", -4, u) == ft_printf("-->|%*.4u|<--\n", -4, u));
assert(printf("-->|%*.4u|<--\n", -3, u) == ft_printf("-->|%*.4u|<--\n", -3, u));
assert(printf("-->|%*.4u|<--\n", -2, u) == ft_printf("-->|%*.4u|<--\n", -2, u));
assert(printf("-->|%*.4u|<--\n", -1, u) == ft_printf("-->|%*.4u|<--\n", -1, u));
assert(printf("-->|%*.4u|<--\n", 0, u) == ft_printf("-->|%*.4u|<--\n", 0, u));
assert(printf("-->|%*.4u|<--\n", 1, u) == ft_printf("-->|%*.4u|<--\n", 1, u));
assert(printf("-->|%*.4u|<--\n", 2, u) == ft_printf("-->|%*.4u|<--\n", 2, u));
assert(printf("-->|%*.4u|<--\n", 3, u) == ft_printf("-->|%*.4u|<--\n", 3, u));
assert(printf("-->|%*.4u|<--\n", 4, u) == ft_printf("-->|%*.4u|<--\n", 4, u));
assert(printf("-->|%*u|<--\n", -4, u) == ft_printf("-->|%*u|<--\n", -4, u));
assert(printf("-->|%*u|<--\n", -3, u) == ft_printf("-->|%*u|<--\n", -3, u));
assert(printf("-->|%*u|<--\n", -2, u) == ft_printf("-->|%*u|<--\n", -2, u));
assert(printf("-->|%*u|<--\n", -1, u) == ft_printf("-->|%*u|<--\n", -1, u));
assert(printf("-->|%*u|<--\n", 0, u) == ft_printf("-->|%*u|<--\n", 0, u));
assert(printf("-->|%*u|<--\n", 1, u) == ft_printf("-->|%*u|<--\n", 1, u));
assert(printf("-->|%*u|<--\n", 2, u) == ft_printf("-->|%*u|<--\n", 2, u));
assert(printf("-->|%*u|<--\n", 3, u) == ft_printf("-->|%*u|<--\n", 3, u));
assert(printf("-->|%*u|<--\n", 4, u) == ft_printf("-->|%*u|<--\n", 4, u));
assert(printf("-->|%0.u|<--\n", u) == ft_printf("-->|%0.u|<--\n", u));
assert(printf("-->|%0.*u|<--\n", -4, u) == ft_printf("-->|%0.*u|<--\n", -4, u));
assert(printf("-->|%0.*u|<--\n", -3, u) == ft_printf("-->|%0.*u|<--\n", -3, u));
assert(printf("-->|%0.*u|<--\n", -2, u) == ft_printf("-->|%0.*u|<--\n", -2, u));
assert(printf("-->|%0.*u|<--\n", -1, u) == ft_printf("-->|%0.*u|<--\n", -1, u));
assert(printf("-->|%0.*u|<--\n", 0, u) == ft_printf("-->|%0.*u|<--\n", 0, u));
assert(printf("-->|%0.*u|<--\n", 1, u) == ft_printf("-->|%0.*u|<--\n", 1, u));
assert(printf("-->|%0.*u|<--\n", 2, u) == ft_printf("-->|%0.*u|<--\n", 2, u));
assert(printf("-->|%0.*u|<--\n", 3, u) == ft_printf("-->|%0.*u|<--\n", 3, u));
assert(printf("-->|%0.*u|<--\n", 4, u) == ft_printf("-->|%0.*u|<--\n", 4, u));
assert(printf("-->|%0.0u|<--\n", u) == ft_printf("-->|%0.0u|<--\n", u));
assert(printf("-->|%0.1u|<--\n", u) == ft_printf("-->|%0.1u|<--\n", u));
assert(printf("-->|%0.2u|<--\n", u) == ft_printf("-->|%0.2u|<--\n", u));
assert(printf("-->|%0.3u|<--\n", u) == ft_printf("-->|%0.3u|<--\n", u));
assert(printf("-->|%0.4u|<--\n", u) == ft_printf("-->|%0.4u|<--\n", u));
assert(printf("-->|%0u|<--\n", u) == ft_printf("-->|%0u|<--\n", u));
assert(printf("-->|%1.u|<--\n", u) == ft_printf("-->|%1.u|<--\n", u));
assert(printf("-->|%1.*u|<--\n", -4, u) == ft_printf("-->|%1.*u|<--\n", -4, u));
assert(printf("-->|%1.*u|<--\n", -3, u) == ft_printf("-->|%1.*u|<--\n", -3, u));
assert(printf("-->|%1.*u|<--\n", -2, u) == ft_printf("-->|%1.*u|<--\n", -2, u));
assert(printf("-->|%1.*u|<--\n", -1, u) == ft_printf("-->|%1.*u|<--\n", -1, u));
assert(printf("-->|%1.*u|<--\n", 0, u) == ft_printf("-->|%1.*u|<--\n", 0, u));
assert(printf("-->|%1.*u|<--\n", 1, u) == ft_printf("-->|%1.*u|<--\n", 1, u));
assert(printf("-->|%1.*u|<--\n", 2, u) == ft_printf("-->|%1.*u|<--\n", 2, u));
assert(printf("-->|%1.*u|<--\n", 3, u) == ft_printf("-->|%1.*u|<--\n", 3, u));
assert(printf("-->|%1.*u|<--\n", 4, u) == ft_printf("-->|%1.*u|<--\n", 4, u));
assert(printf("-->|%1.0u|<--\n", u) == ft_printf("-->|%1.0u|<--\n", u));
assert(printf("-->|%1.1u|<--\n", u) == ft_printf("-->|%1.1u|<--\n", u));
assert(printf("-->|%1.2u|<--\n", u) == ft_printf("-->|%1.2u|<--\n", u));
assert(printf("-->|%1.3u|<--\n", u) == ft_printf("-->|%1.3u|<--\n", u));
assert(printf("-->|%1.4u|<--\n", u) == ft_printf("-->|%1.4u|<--\n", u));
assert(printf("-->|%1u|<--\n", u) == ft_printf("-->|%1u|<--\n", u));
assert(printf("-->|%2.u|<--\n", u) == ft_printf("-->|%2.u|<--\n", u));
assert(printf("-->|%2.*u|<--\n", -4, u) == ft_printf("-->|%2.*u|<--\n", -4, u));
assert(printf("-->|%2.*u|<--\n", -3, u) == ft_printf("-->|%2.*u|<--\n", -3, u));
assert(printf("-->|%2.*u|<--\n", -2, u) == ft_printf("-->|%2.*u|<--\n", -2, u));
assert(printf("-->|%2.*u|<--\n", -1, u) == ft_printf("-->|%2.*u|<--\n", -1, u));
assert(printf("-->|%2.*u|<--\n", 0, u) == ft_printf("-->|%2.*u|<--\n", 0, u));
assert(printf("-->|%2.*u|<--\n", 1, u) == ft_printf("-->|%2.*u|<--\n", 1, u));
assert(printf("-->|%2.*u|<--\n", 2, u) == ft_printf("-->|%2.*u|<--\n", 2, u));
assert(printf("-->|%2.*u|<--\n", 3, u) == ft_printf("-->|%2.*u|<--\n", 3, u));
assert(printf("-->|%2.*u|<--\n", 4, u) == ft_printf("-->|%2.*u|<--\n", 4, u));
assert(printf("-->|%2.0u|<--\n", u) == ft_printf("-->|%2.0u|<--\n", u));
assert(printf("-->|%2.1u|<--\n", u) == ft_printf("-->|%2.1u|<--\n", u));
assert(printf("-->|%2.2u|<--\n", u) == ft_printf("-->|%2.2u|<--\n", u));
assert(printf("-->|%2.3u|<--\n", u) == ft_printf("-->|%2.3u|<--\n", u));
assert(printf("-->|%2.4u|<--\n", u) == ft_printf("-->|%2.4u|<--\n", u));
assert(printf("-->|%2u|<--\n", u) == ft_printf("-->|%2u|<--\n", u));
assert(printf("-->|%3.u|<--\n", u) == ft_printf("-->|%3.u|<--\n", u));
assert(printf("-->|%3.*u|<--\n", -4, u) == ft_printf("-->|%3.*u|<--\n", -4, u));
assert(printf("-->|%3.*u|<--\n", -3, u) == ft_printf("-->|%3.*u|<--\n", -3, u));
assert(printf("-->|%3.*u|<--\n", -2, u) == ft_printf("-->|%3.*u|<--\n", -2, u));
assert(printf("-->|%3.*u|<--\n", -1, u) == ft_printf("-->|%3.*u|<--\n", -1, u));
assert(printf("-->|%3.*u|<--\n", 0, u) == ft_printf("-->|%3.*u|<--\n", 0, u));
assert(printf("-->|%3.*u|<--\n", 1, u) == ft_printf("-->|%3.*u|<--\n", 1, u));
assert(printf("-->|%3.*u|<--\n", 2, u) == ft_printf("-->|%3.*u|<--\n", 2, u));
assert(printf("-->|%3.*u|<--\n", 3, u) == ft_printf("-->|%3.*u|<--\n", 3, u));
assert(printf("-->|%3.*u|<--\n", 4, u) == ft_printf("-->|%3.*u|<--\n", 4, u));
assert(printf("-->|%3.0u|<--\n", u) == ft_printf("-->|%3.0u|<--\n", u));
assert(printf("-->|%3.1u|<--\n", u) == ft_printf("-->|%3.1u|<--\n", u));
assert(printf("-->|%3.2u|<--\n", u) == ft_printf("-->|%3.2u|<--\n", u));
assert(printf("-->|%3.3u|<--\n", u) == ft_printf("-->|%3.3u|<--\n", u));
assert(printf("-->|%3.4u|<--\n", u) == ft_printf("-->|%3.4u|<--\n", u));
assert(printf("-->|%3u|<--\n", u) == ft_printf("-->|%3u|<--\n", u));
assert(printf("-->|%4.u|<--\n", u) == ft_printf("-->|%4.u|<--\n", u));
assert(printf("-->|%4.*u|<--\n", -4, u) == ft_printf("-->|%4.*u|<--\n", -4, u));
assert(printf("-->|%4.*u|<--\n", -3, u) == ft_printf("-->|%4.*u|<--\n", -3, u));
assert(printf("-->|%4.*u|<--\n", -2, u) == ft_printf("-->|%4.*u|<--\n", -2, u));
assert(printf("-->|%4.*u|<--\n", -1, u) == ft_printf("-->|%4.*u|<--\n", -1, u));
assert(printf("-->|%4.*u|<--\n", 0, u) == ft_printf("-->|%4.*u|<--\n", 0, u));
assert(printf("-->|%4.*u|<--\n", 1, u) == ft_printf("-->|%4.*u|<--\n", 1, u));
assert(printf("-->|%4.*u|<--\n", 2, u) == ft_printf("-->|%4.*u|<--\n", 2, u));
assert(printf("-->|%4.*u|<--\n", 3, u) == ft_printf("-->|%4.*u|<--\n", 3, u));
assert(printf("-->|%4.*u|<--\n", 4, u) == ft_printf("-->|%4.*u|<--\n", 4, u));
assert(printf("-->|%4.0u|<--\n", u) == ft_printf("-->|%4.0u|<--\n", u));
assert(printf("-->|%4.1u|<--\n", u) == ft_printf("-->|%4.1u|<--\n", u));
assert(printf("-->|%4.2u|<--\n", u) == ft_printf("-->|%4.2u|<--\n", u));
assert(printf("-->|%4.3u|<--\n", u) == ft_printf("-->|%4.3u|<--\n", u));
assert(printf("-->|%4.4u|<--\n", u) == ft_printf("-->|%4.4u|<--\n", u));
assert(printf("-->|%4u|<--\n", u) == ft_printf("-->|%4u|<--\n", u));
assert(printf("-->|%0.u|<--\n", u) == ft_printf("-->|%0.u|<--\n", u));
assert(printf("-->|%0.*u|<--\n", -4, u) == ft_printf("-->|%0.*u|<--\n", -4, u));
assert(printf("-->|%0.*u|<--\n", -3, u) == ft_printf("-->|%0.*u|<--\n", -3, u));
assert(printf("-->|%0.*u|<--\n", -2, u) == ft_printf("-->|%0.*u|<--\n", -2, u));
assert(printf("-->|%0.*u|<--\n", -1, u) == ft_printf("-->|%0.*u|<--\n", -1, u));
assert(printf("-->|%0.*u|<--\n", 0, u) == ft_printf("-->|%0.*u|<--\n", 0, u));
assert(printf("-->|%0.*u|<--\n", 1, u) == ft_printf("-->|%0.*u|<--\n", 1, u));
assert(printf("-->|%0.*u|<--\n", 2, u) == ft_printf("-->|%0.*u|<--\n", 2, u));
assert(printf("-->|%0.*u|<--\n", 3, u) == ft_printf("-->|%0.*u|<--\n", 3, u));
assert(printf("-->|%0.*u|<--\n", 4, u) == ft_printf("-->|%0.*u|<--\n", 4, u));
assert(printf("-->|%0.0u|<--\n", u) == ft_printf("-->|%0.0u|<--\n", u));
assert(printf("-->|%0.1u|<--\n", u) == ft_printf("-->|%0.1u|<--\n", u));
assert(printf("-->|%0.2u|<--\n", u) == ft_printf("-->|%0.2u|<--\n", u));
assert(printf("-->|%0.3u|<--\n", u) == ft_printf("-->|%0.3u|<--\n", u));
assert(printf("-->|%0.4u|<--\n", u) == ft_printf("-->|%0.4u|<--\n", u));
assert(printf("-->|%0u|<--\n", u) == ft_printf("-->|%0u|<--\n", u));
assert(printf("-->|%0*.u|<--\n", -4, u) == ft_printf("-->|%0*.u|<--\n", -4, u));
assert(printf("-->|%0*.u|<--\n", -3, u) == ft_printf("-->|%0*.u|<--\n", -3, u));
assert(printf("-->|%0*.u|<--\n", -2, u) == ft_printf("-->|%0*.u|<--\n", -2, u));
assert(printf("-->|%0*.u|<--\n", -1, u) == ft_printf("-->|%0*.u|<--\n", -1, u));
assert(printf("-->|%0*.u|<--\n", 0, u) == ft_printf("-->|%0*.u|<--\n", 0, u));
assert(printf("-->|%0*.u|<--\n", 1, u) == ft_printf("-->|%0*.u|<--\n", 1, u));
assert(printf("-->|%0*.u|<--\n", 2, u) == ft_printf("-->|%0*.u|<--\n", 2, u));
assert(printf("-->|%0*.u|<--\n", 3, u) == ft_printf("-->|%0*.u|<--\n", 3, u));
assert(printf("-->|%0*.u|<--\n", 4, u) == ft_printf("-->|%0*.u|<--\n", 4, u));
assert(printf("-->|%0*.*u|<--\n", -4, -4, u) == ft_printf("-->|%0*.*u|<--\n", -4, -4, u));
assert(printf("-->|%0*.*u|<--\n", -4, -3, u) == ft_printf("-->|%0*.*u|<--\n", -4, -3, u));
assert(printf("-->|%0*.*u|<--\n", -4, -2, u) == ft_printf("-->|%0*.*u|<--\n", -4, -2, u));
assert(printf("-->|%0*.*u|<--\n", -4, -1, u) == ft_printf("-->|%0*.*u|<--\n", -4, -1, u));
assert(printf("-->|%0*.*u|<--\n", -4, 0, u) == ft_printf("-->|%0*.*u|<--\n", -4, 0, u));
assert(printf("-->|%0*.*u|<--\n", -4, 1, u) == ft_printf("-->|%0*.*u|<--\n", -4, 1, u));
assert(printf("-->|%0*.*u|<--\n", -4, 2, u) == ft_printf("-->|%0*.*u|<--\n", -4, 2, u));
assert(printf("-->|%0*.*u|<--\n", -4, 3, u) == ft_printf("-->|%0*.*u|<--\n", -4, 3, u));
assert(printf("-->|%0*.*u|<--\n", -4, 4, u) == ft_printf("-->|%0*.*u|<--\n", -4, 4, u));
assert(printf("-->|%0*.*u|<--\n", -3, -4, u) == ft_printf("-->|%0*.*u|<--\n", -3, -4, u));
assert(printf("-->|%0*.*u|<--\n", -3, -3, u) == ft_printf("-->|%0*.*u|<--\n", -3, -3, u));
assert(printf("-->|%0*.*u|<--\n", -3, -2, u) == ft_printf("-->|%0*.*u|<--\n", -3, -2, u));
assert(printf("-->|%0*.*u|<--\n", -3, -1, u) == ft_printf("-->|%0*.*u|<--\n", -3, -1, u));
assert(printf("-->|%0*.*u|<--\n", -3, 0, u) == ft_printf("-->|%0*.*u|<--\n", -3, 0, u));
assert(printf("-->|%0*.*u|<--\n", -3, 1, u) == ft_printf("-->|%0*.*u|<--\n", -3, 1, u));
assert(printf("-->|%0*.*u|<--\n", -3, 2, u) == ft_printf("-->|%0*.*u|<--\n", -3, 2, u));
assert(printf("-->|%0*.*u|<--\n", -3, 3, u) == ft_printf("-->|%0*.*u|<--\n", -3, 3, u));
assert(printf("-->|%0*.*u|<--\n", -3, 4, u) == ft_printf("-->|%0*.*u|<--\n", -3, 4, u));
assert(printf("-->|%0*.*u|<--\n", -2, -4, u) == ft_printf("-->|%0*.*u|<--\n", -2, -4, u));
assert(printf("-->|%0*.*u|<--\n", -2, -3, u) == ft_printf("-->|%0*.*u|<--\n", -2, -3, u));
assert(printf("-->|%0*.*u|<--\n", -2, -2, u) == ft_printf("-->|%0*.*u|<--\n", -2, -2, u));
assert(printf("-->|%0*.*u|<--\n", -2, -1, u) == ft_printf("-->|%0*.*u|<--\n", -2, -1, u));
assert(printf("-->|%0*.*u|<--\n", -2, 0, u) == ft_printf("-->|%0*.*u|<--\n", -2, 0, u));
assert(printf("-->|%0*.*u|<--\n", -2, 1, u) == ft_printf("-->|%0*.*u|<--\n", -2, 1, u));
assert(printf("-->|%0*.*u|<--\n", -2, 2, u) == ft_printf("-->|%0*.*u|<--\n", -2, 2, u));
assert(printf("-->|%0*.*u|<--\n", -2, 3, u) == ft_printf("-->|%0*.*u|<--\n", -2, 3, u));
assert(printf("-->|%0*.*u|<--\n", -2, 4, u) == ft_printf("-->|%0*.*u|<--\n", -2, 4, u));
assert(printf("-->|%0*.*u|<--\n", -1, -4, u) == ft_printf("-->|%0*.*u|<--\n", -1, -4, u));
assert(printf("-->|%0*.*u|<--\n", -1, -3, u) == ft_printf("-->|%0*.*u|<--\n", -1, -3, u));
assert(printf("-->|%0*.*u|<--\n", -1, -2, u) == ft_printf("-->|%0*.*u|<--\n", -1, -2, u));
assert(printf("-->|%0*.*u|<--\n", -1, -1, u) == ft_printf("-->|%0*.*u|<--\n", -1, -1, u));
assert(printf("-->|%0*.*u|<--\n", -1, 0, u) == ft_printf("-->|%0*.*u|<--\n", -1, 0, u));
assert(printf("-->|%0*.*u|<--\n", -1, 1, u) == ft_printf("-->|%0*.*u|<--\n", -1, 1, u));
assert(printf("-->|%0*.*u|<--\n", -1, 2, u) == ft_printf("-->|%0*.*u|<--\n", -1, 2, u));
assert(printf("-->|%0*.*u|<--\n", -1, 3, u) == ft_printf("-->|%0*.*u|<--\n", -1, 3, u));
assert(printf("-->|%0*.*u|<--\n", -1, 4, u) == ft_printf("-->|%0*.*u|<--\n", -1, 4, u));
assert(printf("-->|%0*.*u|<--\n", 0, -4, u) == ft_printf("-->|%0*.*u|<--\n", 0, -4, u));
assert(printf("-->|%0*.*u|<--\n", 0, -3, u) == ft_printf("-->|%0*.*u|<--\n", 0, -3, u));
assert(printf("-->|%0*.*u|<--\n", 0, -2, u) == ft_printf("-->|%0*.*u|<--\n", 0, -2, u));
assert(printf("-->|%0*.*u|<--\n", 0, -1, u) == ft_printf("-->|%0*.*u|<--\n", 0, -1, u));
assert(printf("-->|%0*.*u|<--\n", 0, 0, u) == ft_printf("-->|%0*.*u|<--\n", 0, 0, u));
assert(printf("-->|%0*.*u|<--\n", 0, 1, u) == ft_printf("-->|%0*.*u|<--\n", 0, 1, u));
assert(printf("-->|%0*.*u|<--\n", 0, 2, u) == ft_printf("-->|%0*.*u|<--\n", 0, 2, u));
assert(printf("-->|%0*.*u|<--\n", 0, 3, u) == ft_printf("-->|%0*.*u|<--\n", 0, 3, u));
assert(printf("-->|%0*.*u|<--\n", 0, 4, u) == ft_printf("-->|%0*.*u|<--\n", 0, 4, u));
assert(printf("-->|%0*.*u|<--\n", 1, -4, u) == ft_printf("-->|%0*.*u|<--\n", 1, -4, u));
assert(printf("-->|%0*.*u|<--\n", 1, -3, u) == ft_printf("-->|%0*.*u|<--\n", 1, -3, u));
assert(printf("-->|%0*.*u|<--\n", 1, -2, u) == ft_printf("-->|%0*.*u|<--\n", 1, -2, u));
assert(printf("-->|%0*.*u|<--\n", 1, -1, u) == ft_printf("-->|%0*.*u|<--\n", 1, -1, u));
assert(printf("-->|%0*.*u|<--\n", 1, 0, u) == ft_printf("-->|%0*.*u|<--\n", 1, 0, u));
assert(printf("-->|%0*.*u|<--\n", 1, 1, u) == ft_printf("-->|%0*.*u|<--\n", 1, 1, u));
assert(printf("-->|%0*.*u|<--\n", 1, 2, u) == ft_printf("-->|%0*.*u|<--\n", 1, 2, u));
assert(printf("-->|%0*.*u|<--\n", 1, 3, u) == ft_printf("-->|%0*.*u|<--\n", 1, 3, u));
assert(printf("-->|%0*.*u|<--\n", 1, 4, u) == ft_printf("-->|%0*.*u|<--\n", 1, 4, u));
assert(printf("-->|%0*.*u|<--\n", 2, -4, u) == ft_printf("-->|%0*.*u|<--\n", 2, -4, u));
assert(printf("-->|%0*.*u|<--\n", 2, -3, u) == ft_printf("-->|%0*.*u|<--\n", 2, -3, u));
assert(printf("-->|%0*.*u|<--\n", 2, -2, u) == ft_printf("-->|%0*.*u|<--\n", 2, -2, u));
assert(printf("-->|%0*.*u|<--\n", 2, -1, u) == ft_printf("-->|%0*.*u|<--\n", 2, -1, u));
assert(printf("-->|%0*.*u|<--\n", 2, 0, u) == ft_printf("-->|%0*.*u|<--\n", 2, 0, u));
assert(printf("-->|%0*.*u|<--\n", 2, 1, u) == ft_printf("-->|%0*.*u|<--\n", 2, 1, u));
assert(printf("-->|%0*.*u|<--\n", 2, 2, u) == ft_printf("-->|%0*.*u|<--\n", 2, 2, u));
assert(printf("-->|%0*.*u|<--\n", 2, 3, u) == ft_printf("-->|%0*.*u|<--\n", 2, 3, u));
assert(printf("-->|%0*.*u|<--\n", 2, 4, u) == ft_printf("-->|%0*.*u|<--\n", 2, 4, u));
assert(printf("-->|%0*.*u|<--\n", 3, -4, u) == ft_printf("-->|%0*.*u|<--\n", 3, -4, u));
assert(printf("-->|%0*.*u|<--\n", 3, -3, u) == ft_printf("-->|%0*.*u|<--\n", 3, -3, u));
assert(printf("-->|%0*.*u|<--\n", 3, -2, u) == ft_printf("-->|%0*.*u|<--\n", 3, -2, u));
assert(printf("-->|%0*.*u|<--\n", 3, -1, u) == ft_printf("-->|%0*.*u|<--\n", 3, -1, u));
assert(printf("-->|%0*.*u|<--\n", 3, 0, u) == ft_printf("-->|%0*.*u|<--\n", 3, 0, u));
assert(printf("-->|%0*.*u|<--\n", 3, 1, u) == ft_printf("-->|%0*.*u|<--\n", 3, 1, u));
assert(printf("-->|%0*.*u|<--\n", 3, 2, u) == ft_printf("-->|%0*.*u|<--\n", 3, 2, u));
assert(printf("-->|%0*.*u|<--\n", 3, 3, u) == ft_printf("-->|%0*.*u|<--\n", 3, 3, u));
assert(printf("-->|%0*.*u|<--\n", 3, 4, u) == ft_printf("-->|%0*.*u|<--\n", 3, 4, u));
assert(printf("-->|%0*.*u|<--\n", 4, -4, u) == ft_printf("-->|%0*.*u|<--\n", 4, -4, u));
assert(printf("-->|%0*.*u|<--\n", 4, -3, u) == ft_printf("-->|%0*.*u|<--\n", 4, -3, u));
assert(printf("-->|%0*.*u|<--\n", 4, -2, u) == ft_printf("-->|%0*.*u|<--\n", 4, -2, u));
assert(printf("-->|%0*.*u|<--\n", 4, -1, u) == ft_printf("-->|%0*.*u|<--\n", 4, -1, u));
assert(printf("-->|%0*.*u|<--\n", 4, 0, u) == ft_printf("-->|%0*.*u|<--\n", 4, 0, u));
assert(printf("-->|%0*.*u|<--\n", 4, 1, u) == ft_printf("-->|%0*.*u|<--\n", 4, 1, u));
assert(printf("-->|%0*.*u|<--\n", 4, 2, u) == ft_printf("-->|%0*.*u|<--\n", 4, 2, u));
assert(printf("-->|%0*.*u|<--\n", 4, 3, u) == ft_printf("-->|%0*.*u|<--\n", 4, 3, u));
assert(printf("-->|%0*.*u|<--\n", 4, 4, u) == ft_printf("-->|%0*.*u|<--\n", 4, 4, u));
assert(printf("-->|%0*.0u|<--\n", -4, u) == ft_printf("-->|%0*.0u|<--\n", -4, u));
assert(printf("-->|%0*.0u|<--\n", -3, u) == ft_printf("-->|%0*.0u|<--\n", -3, u));
assert(printf("-->|%0*.0u|<--\n", -2, u) == ft_printf("-->|%0*.0u|<--\n", -2, u));
assert(printf("-->|%0*.0u|<--\n", -1, u) == ft_printf("-->|%0*.0u|<--\n", -1, u));
assert(printf("-->|%0*.0u|<--\n", 0, u) == ft_printf("-->|%0*.0u|<--\n", 0, u));
assert(printf("-->|%0*.0u|<--\n", 1, u) == ft_printf("-->|%0*.0u|<--\n", 1, u));
assert(printf("-->|%0*.0u|<--\n", 2, u) == ft_printf("-->|%0*.0u|<--\n", 2, u));
assert(printf("-->|%0*.0u|<--\n", 3, u) == ft_printf("-->|%0*.0u|<--\n", 3, u));
assert(printf("-->|%0*.0u|<--\n", 4, u) == ft_printf("-->|%0*.0u|<--\n", 4, u));
assert(printf("-->|%0*.1u|<--\n", -4, u) == ft_printf("-->|%0*.1u|<--\n", -4, u));
assert(printf("-->|%0*.1u|<--\n", -3, u) == ft_printf("-->|%0*.1u|<--\n", -3, u));
assert(printf("-->|%0*.1u|<--\n", -2, u) == ft_printf("-->|%0*.1u|<--\n", -2, u));
assert(printf("-->|%0*.1u|<--\n", -1, u) == ft_printf("-->|%0*.1u|<--\n", -1, u));
assert(printf("-->|%0*.1u|<--\n", 0, u) == ft_printf("-->|%0*.1u|<--\n", 0, u));
assert(printf("-->|%0*.1u|<--\n", 1, u) == ft_printf("-->|%0*.1u|<--\n", 1, u));
assert(printf("-->|%0*.1u|<--\n", 2, u) == ft_printf("-->|%0*.1u|<--\n", 2, u));
assert(printf("-->|%0*.1u|<--\n", 3, u) == ft_printf("-->|%0*.1u|<--\n", 3, u));
assert(printf("-->|%0*.1u|<--\n", 4, u) == ft_printf("-->|%0*.1u|<--\n", 4, u));
assert(printf("-->|%0*.2u|<--\n", -4, u) == ft_printf("-->|%0*.2u|<--\n", -4, u));
assert(printf("-->|%0*.2u|<--\n", -3, u) == ft_printf("-->|%0*.2u|<--\n", -3, u));
assert(printf("-->|%0*.2u|<--\n", -2, u) == ft_printf("-->|%0*.2u|<--\n", -2, u));
assert(printf("-->|%0*.2u|<--\n", -1, u) == ft_printf("-->|%0*.2u|<--\n", -1, u));
assert(printf("-->|%0*.2u|<--\n", 0, u) == ft_printf("-->|%0*.2u|<--\n", 0, u));
assert(printf("-->|%0*.2u|<--\n", 1, u) == ft_printf("-->|%0*.2u|<--\n", 1, u));
assert(printf("-->|%0*.2u|<--\n", 2, u) == ft_printf("-->|%0*.2u|<--\n", 2, u));
assert(printf("-->|%0*.2u|<--\n", 3, u) == ft_printf("-->|%0*.2u|<--\n", 3, u));
assert(printf("-->|%0*.2u|<--\n", 4, u) == ft_printf("-->|%0*.2u|<--\n", 4, u));
assert(printf("-->|%0*.3u|<--\n", -4, u) == ft_printf("-->|%0*.3u|<--\n", -4, u));
assert(printf("-->|%0*.3u|<--\n", -3, u) == ft_printf("-->|%0*.3u|<--\n", -3, u));
assert(printf("-->|%0*.3u|<--\n", -2, u) == ft_printf("-->|%0*.3u|<--\n", -2, u));
assert(printf("-->|%0*.3u|<--\n", -1, u) == ft_printf("-->|%0*.3u|<--\n", -1, u));
assert(printf("-->|%0*.3u|<--\n", 0, u) == ft_printf("-->|%0*.3u|<--\n", 0, u));
assert(printf("-->|%0*.3u|<--\n", 1, u) == ft_printf("-->|%0*.3u|<--\n", 1, u));
assert(printf("-->|%0*.3u|<--\n", 2, u) == ft_printf("-->|%0*.3u|<--\n", 2, u));
assert(printf("-->|%0*.3u|<--\n", 3, u) == ft_printf("-->|%0*.3u|<--\n", 3, u));
assert(printf("-->|%0*.3u|<--\n", 4, u) == ft_printf("-->|%0*.3u|<--\n", 4, u));
assert(printf("-->|%0*.4u|<--\n", -4, u) == ft_printf("-->|%0*.4u|<--\n", -4, u));
assert(printf("-->|%0*.4u|<--\n", -3, u) == ft_printf("-->|%0*.4u|<--\n", -3, u));
assert(printf("-->|%0*.4u|<--\n", -2, u) == ft_printf("-->|%0*.4u|<--\n", -2, u));
assert(printf("-->|%0*.4u|<--\n", -1, u) == ft_printf("-->|%0*.4u|<--\n", -1, u));
assert(printf("-->|%0*.4u|<--\n", 0, u) == ft_printf("-->|%0*.4u|<--\n", 0, u));
assert(printf("-->|%0*.4u|<--\n", 1, u) == ft_printf("-->|%0*.4u|<--\n", 1, u));
assert(printf("-->|%0*.4u|<--\n", 2, u) == ft_printf("-->|%0*.4u|<--\n", 2, u));
assert(printf("-->|%0*.4u|<--\n", 3, u) == ft_printf("-->|%0*.4u|<--\n", 3, u));
assert(printf("-->|%0*.4u|<--\n", 4, u) == ft_printf("-->|%0*.4u|<--\n", 4, u));
assert(printf("-->|%0*u|<--\n", -4, u) == ft_printf("-->|%0*u|<--\n", -4, u));
assert(printf("-->|%0*u|<--\n", -3, u) == ft_printf("-->|%0*u|<--\n", -3, u));
assert(printf("-->|%0*u|<--\n", -2, u) == ft_printf("-->|%0*u|<--\n", -2, u));
assert(printf("-->|%0*u|<--\n", -1, u) == ft_printf("-->|%0*u|<--\n", -1, u));
assert(printf("-->|%0*u|<--\n", 0, u) == ft_printf("-->|%0*u|<--\n", 0, u));
assert(printf("-->|%0*u|<--\n", 1, u) == ft_printf("-->|%0*u|<--\n", 1, u));
assert(printf("-->|%0*u|<--\n", 2, u) == ft_printf("-->|%0*u|<--\n", 2, u));
assert(printf("-->|%0*u|<--\n", 3, u) == ft_printf("-->|%0*u|<--\n", 3, u));
assert(printf("-->|%0*u|<--\n", 4, u) == ft_printf("-->|%0*u|<--\n", 4, u));
assert(printf("-->|%00.u|<--\n", u) == ft_printf("-->|%00.u|<--\n", u));
assert(printf("-->|%00.*u|<--\n", -4, u) == ft_printf("-->|%00.*u|<--\n", -4, u));
assert(printf("-->|%00.*u|<--\n", -3, u) == ft_printf("-->|%00.*u|<--\n", -3, u));
assert(printf("-->|%00.*u|<--\n", -2, u) == ft_printf("-->|%00.*u|<--\n", -2, u));
assert(printf("-->|%00.*u|<--\n", -1, u) == ft_printf("-->|%00.*u|<--\n", -1, u));
assert(printf("-->|%00.*u|<--\n", 0, u) == ft_printf("-->|%00.*u|<--\n", 0, u));
assert(printf("-->|%00.*u|<--\n", 1, u) == ft_printf("-->|%00.*u|<--\n", 1, u));
assert(printf("-->|%00.*u|<--\n", 2, u) == ft_printf("-->|%00.*u|<--\n", 2, u));
assert(printf("-->|%00.*u|<--\n", 3, u) == ft_printf("-->|%00.*u|<--\n", 3, u));
assert(printf("-->|%00.*u|<--\n", 4, u) == ft_printf("-->|%00.*u|<--\n", 4, u));
assert(printf("-->|%00.0u|<--\n", u) == ft_printf("-->|%00.0u|<--\n", u));
assert(printf("-->|%00.1u|<--\n", u) == ft_printf("-->|%00.1u|<--\n", u));
assert(printf("-->|%00.2u|<--\n", u) == ft_printf("-->|%00.2u|<--\n", u));
assert(printf("-->|%00.3u|<--\n", u) == ft_printf("-->|%00.3u|<--\n", u));
assert(printf("-->|%00.4u|<--\n", u) == ft_printf("-->|%00.4u|<--\n", u));
assert(printf("-->|%00u|<--\n", u) == ft_printf("-->|%00u|<--\n", u));
assert(printf("-->|%01.u|<--\n", u) == ft_printf("-->|%01.u|<--\n", u));
assert(printf("-->|%01.*u|<--\n", -4, u) == ft_printf("-->|%01.*u|<--\n", -4, u));
assert(printf("-->|%01.*u|<--\n", -3, u) == ft_printf("-->|%01.*u|<--\n", -3, u));
assert(printf("-->|%01.*u|<--\n", -2, u) == ft_printf("-->|%01.*u|<--\n", -2, u));
assert(printf("-->|%01.*u|<--\n", -1, u) == ft_printf("-->|%01.*u|<--\n", -1, u));
assert(printf("-->|%01.*u|<--\n", 0, u) == ft_printf("-->|%01.*u|<--\n", 0, u));
assert(printf("-->|%01.*u|<--\n", 1, u) == ft_printf("-->|%01.*u|<--\n", 1, u));
assert(printf("-->|%01.*u|<--\n", 2, u) == ft_printf("-->|%01.*u|<--\n", 2, u));
assert(printf("-->|%01.*u|<--\n", 3, u) == ft_printf("-->|%01.*u|<--\n", 3, u));
assert(printf("-->|%01.*u|<--\n", 4, u) == ft_printf("-->|%01.*u|<--\n", 4, u));
assert(printf("-->|%01.0u|<--\n", u) == ft_printf("-->|%01.0u|<--\n", u));
assert(printf("-->|%01.1u|<--\n", u) == ft_printf("-->|%01.1u|<--\n", u));
assert(printf("-->|%01.2u|<--\n", u) == ft_printf("-->|%01.2u|<--\n", u));
assert(printf("-->|%01.3u|<--\n", u) == ft_printf("-->|%01.3u|<--\n", u));
assert(printf("-->|%01.4u|<--\n", u) == ft_printf("-->|%01.4u|<--\n", u));
assert(printf("-->|%01u|<--\n", u) == ft_printf("-->|%01u|<--\n", u));
assert(printf("-->|%02.u|<--\n", u) == ft_printf("-->|%02.u|<--\n", u));
assert(printf("-->|%02.*u|<--\n", -4, u) == ft_printf("-->|%02.*u|<--\n", -4, u));
assert(printf("-->|%02.*u|<--\n", -3, u) == ft_printf("-->|%02.*u|<--\n", -3, u));
assert(printf("-->|%02.*u|<--\n", -2, u) == ft_printf("-->|%02.*u|<--\n", -2, u));
assert(printf("-->|%02.*u|<--\n", -1, u) == ft_printf("-->|%02.*u|<--\n", -1, u));
assert(printf("-->|%02.*u|<--\n", 0, u) == ft_printf("-->|%02.*u|<--\n", 0, u));
assert(printf("-->|%02.*u|<--\n", 1, u) == ft_printf("-->|%02.*u|<--\n", 1, u));
assert(printf("-->|%02.*u|<--\n", 2, u) == ft_printf("-->|%02.*u|<--\n", 2, u));
assert(printf("-->|%02.*u|<--\n", 3, u) == ft_printf("-->|%02.*u|<--\n", 3, u));
assert(printf("-->|%02.*u|<--\n", 4, u) == ft_printf("-->|%02.*u|<--\n", 4, u));
assert(printf("-->|%02.0u|<--\n", u) == ft_printf("-->|%02.0u|<--\n", u));
assert(printf("-->|%02.1u|<--\n", u) == ft_printf("-->|%02.1u|<--\n", u));
assert(printf("-->|%02.2u|<--\n", u) == ft_printf("-->|%02.2u|<--\n", u));
assert(printf("-->|%02.3u|<--\n", u) == ft_printf("-->|%02.3u|<--\n", u));
assert(printf("-->|%02.4u|<--\n", u) == ft_printf("-->|%02.4u|<--\n", u));
assert(printf("-->|%02u|<--\n", u) == ft_printf("-->|%02u|<--\n", u));
assert(printf("-->|%03.u|<--\n", u) == ft_printf("-->|%03.u|<--\n", u));
assert(printf("-->|%03.*u|<--\n", -4, u) == ft_printf("-->|%03.*u|<--\n", -4, u));
assert(printf("-->|%03.*u|<--\n", -3, u) == ft_printf("-->|%03.*u|<--\n", -3, u));
assert(printf("-->|%03.*u|<--\n", -2, u) == ft_printf("-->|%03.*u|<--\n", -2, u));
assert(printf("-->|%03.*u|<--\n", -1, u) == ft_printf("-->|%03.*u|<--\n", -1, u));
assert(printf("-->|%03.*u|<--\n", 0, u) == ft_printf("-->|%03.*u|<--\n", 0, u));
assert(printf("-->|%03.*u|<--\n", 1, u) == ft_printf("-->|%03.*u|<--\n", 1, u));
assert(printf("-->|%03.*u|<--\n", 2, u) == ft_printf("-->|%03.*u|<--\n", 2, u));
assert(printf("-->|%03.*u|<--\n", 3, u) == ft_printf("-->|%03.*u|<--\n", 3, u));
assert(printf("-->|%03.*u|<--\n", 4, u) == ft_printf("-->|%03.*u|<--\n", 4, u));
assert(printf("-->|%03.0u|<--\n", u) == ft_printf("-->|%03.0u|<--\n", u));
assert(printf("-->|%03.1u|<--\n", u) == ft_printf("-->|%03.1u|<--\n", u));
assert(printf("-->|%03.2u|<--\n", u) == ft_printf("-->|%03.2u|<--\n", u));
assert(printf("-->|%03.3u|<--\n", u) == ft_printf("-->|%03.3u|<--\n", u));
assert(printf("-->|%03.4u|<--\n", u) == ft_printf("-->|%03.4u|<--\n", u));
assert(printf("-->|%03u|<--\n", u) == ft_printf("-->|%03u|<--\n", u));
assert(printf("-->|%04.u|<--\n", u) == ft_printf("-->|%04.u|<--\n", u));
assert(printf("-->|%04.*u|<--\n", -4, u) == ft_printf("-->|%04.*u|<--\n", -4, u));
assert(printf("-->|%04.*u|<--\n", -3, u) == ft_printf("-->|%04.*u|<--\n", -3, u));
assert(printf("-->|%04.*u|<--\n", -2, u) == ft_printf("-->|%04.*u|<--\n", -2, u));
assert(printf("-->|%04.*u|<--\n", -1, u) == ft_printf("-->|%04.*u|<--\n", -1, u));
assert(printf("-->|%04.*u|<--\n", 0, u) == ft_printf("-->|%04.*u|<--\n", 0, u));
assert(printf("-->|%04.*u|<--\n", 1, u) == ft_printf("-->|%04.*u|<--\n", 1, u));
assert(printf("-->|%04.*u|<--\n", 2, u) == ft_printf("-->|%04.*u|<--\n", 2, u));
assert(printf("-->|%04.*u|<--\n", 3, u) == ft_printf("-->|%04.*u|<--\n", 3, u));
assert(printf("-->|%04.*u|<--\n", 4, u) == ft_printf("-->|%04.*u|<--\n", 4, u));
assert(printf("-->|%04.0u|<--\n", u) == ft_printf("-->|%04.0u|<--\n", u));
assert(printf("-->|%04.1u|<--\n", u) == ft_printf("-->|%04.1u|<--\n", u));
assert(printf("-->|%04.2u|<--\n", u) == ft_printf("-->|%04.2u|<--\n", u));
assert(printf("-->|%04.3u|<--\n", u) == ft_printf("-->|%04.3u|<--\n", u));
assert(printf("-->|%04.4u|<--\n", u) == ft_printf("-->|%04.4u|<--\n", u));
assert(printf("-->|%04u|<--\n", u) == ft_printf("-->|%04u|<--\n", u));
assert(printf("-->|%--4.u|<--\n", u) == ft_printf("-->|%--4.u|<--\n", u));
assert(printf("-->|%--4.*u|<--\n", -4, u) == ft_printf("-->|%--4.*u|<--\n", -4, u));
assert(printf("-->|%--4.*u|<--\n", -3, u) == ft_printf("-->|%--4.*u|<--\n", -3, u));
assert(printf("-->|%--4.*u|<--\n", -2, u) == ft_printf("-->|%--4.*u|<--\n", -2, u));
assert(printf("-->|%--4.*u|<--\n", -1, u) == ft_printf("-->|%--4.*u|<--\n", -1, u));
assert(printf("-->|%--4.*u|<--\n", 0, u) == ft_printf("-->|%--4.*u|<--\n", 0, u));
assert(printf("-->|%--4.*u|<--\n", 1, u) == ft_printf("-->|%--4.*u|<--\n", 1, u));
assert(printf("-->|%--4.*u|<--\n", 2, u) == ft_printf("-->|%--4.*u|<--\n", 2, u));
assert(printf("-->|%--4.*u|<--\n", 3, u) == ft_printf("-->|%--4.*u|<--\n", 3, u));
assert(printf("-->|%--4.*u|<--\n", 4, u) == ft_printf("-->|%--4.*u|<--\n", 4, u));
assert(printf("-->|%--4.0u|<--\n", u) == ft_printf("-->|%--4.0u|<--\n", u));
assert(printf("-->|%--4.1u|<--\n", u) == ft_printf("-->|%--4.1u|<--\n", u));
assert(printf("-->|%--4.2u|<--\n", u) == ft_printf("-->|%--4.2u|<--\n", u));
assert(printf("-->|%--4.3u|<--\n", u) == ft_printf("-->|%--4.3u|<--\n", u));
assert(printf("-->|%--4.4u|<--\n", u) == ft_printf("-->|%--4.4u|<--\n", u));
assert(printf("-->|%--4u|<--\n", u) == ft_printf("-->|%--4u|<--\n", u));
assert(printf("-->|%--3.u|<--\n", u) == ft_printf("-->|%--3.u|<--\n", u));
assert(printf("-->|%--3.*u|<--\n", -4, u) == ft_printf("-->|%--3.*u|<--\n", -4, u));
assert(printf("-->|%--3.*u|<--\n", -3, u) == ft_printf("-->|%--3.*u|<--\n", -3, u));
assert(printf("-->|%--3.*u|<--\n", -2, u) == ft_printf("-->|%--3.*u|<--\n", -2, u));
assert(printf("-->|%--3.*u|<--\n", -1, u) == ft_printf("-->|%--3.*u|<--\n", -1, u));
assert(printf("-->|%--3.*u|<--\n", 0, u) == ft_printf("-->|%--3.*u|<--\n", 0, u));
assert(printf("-->|%--3.*u|<--\n", 1, u) == ft_printf("-->|%--3.*u|<--\n", 1, u));
assert(printf("-->|%--3.*u|<--\n", 2, u) == ft_printf("-->|%--3.*u|<--\n", 2, u));
assert(printf("-->|%--3.*u|<--\n", 3, u) == ft_printf("-->|%--3.*u|<--\n", 3, u));
assert(printf("-->|%--3.*u|<--\n", 4, u) == ft_printf("-->|%--3.*u|<--\n", 4, u));
assert(printf("-->|%--3.0u|<--\n", u) == ft_printf("-->|%--3.0u|<--\n", u));
assert(printf("-->|%--3.1u|<--\n", u) == ft_printf("-->|%--3.1u|<--\n", u));
assert(printf("-->|%--3.2u|<--\n", u) == ft_printf("-->|%--3.2u|<--\n", u));
assert(printf("-->|%--3.3u|<--\n", u) == ft_printf("-->|%--3.3u|<--\n", u));
assert(printf("-->|%--3.4u|<--\n", u) == ft_printf("-->|%--3.4u|<--\n", u));
assert(printf("-->|%--3u|<--\n", u) == ft_printf("-->|%--3u|<--\n", u));
assert(printf("-->|%--2.u|<--\n", u) == ft_printf("-->|%--2.u|<--\n", u));
assert(printf("-->|%--2.*u|<--\n", -4, u) == ft_printf("-->|%--2.*u|<--\n", -4, u));
assert(printf("-->|%--2.*u|<--\n", -3, u) == ft_printf("-->|%--2.*u|<--\n", -3, u));
assert(printf("-->|%--2.*u|<--\n", -2, u) == ft_printf("-->|%--2.*u|<--\n", -2, u));
assert(printf("-->|%--2.*u|<--\n", -1, u) == ft_printf("-->|%--2.*u|<--\n", -1, u));
assert(printf("-->|%--2.*u|<--\n", 0, u) == ft_printf("-->|%--2.*u|<--\n", 0, u));
assert(printf("-->|%--2.*u|<--\n", 1, u) == ft_printf("-->|%--2.*u|<--\n", 1, u));
assert(printf("-->|%--2.*u|<--\n", 2, u) == ft_printf("-->|%--2.*u|<--\n", 2, u));
assert(printf("-->|%--2.*u|<--\n", 3, u) == ft_printf("-->|%--2.*u|<--\n", 3, u));
assert(printf("-->|%--2.*u|<--\n", 4, u) == ft_printf("-->|%--2.*u|<--\n", 4, u));
assert(printf("-->|%--2.0u|<--\n", u) == ft_printf("-->|%--2.0u|<--\n", u));
assert(printf("-->|%--2.1u|<--\n", u) == ft_printf("-->|%--2.1u|<--\n", u));
assert(printf("-->|%--2.2u|<--\n", u) == ft_printf("-->|%--2.2u|<--\n", u));
assert(printf("-->|%--2.3u|<--\n", u) == ft_printf("-->|%--2.3u|<--\n", u));
assert(printf("-->|%--2.4u|<--\n", u) == ft_printf("-->|%--2.4u|<--\n", u));
assert(printf("-->|%--2u|<--\n", u) == ft_printf("-->|%--2u|<--\n", u));
assert(printf("-->|%--1.u|<--\n", u) == ft_printf("-->|%--1.u|<--\n", u));
assert(printf("-->|%--1.*u|<--\n", -4, u) == ft_printf("-->|%--1.*u|<--\n", -4, u));
assert(printf("-->|%--1.*u|<--\n", -3, u) == ft_printf("-->|%--1.*u|<--\n", -3, u));
assert(printf("-->|%--1.*u|<--\n", -2, u) == ft_printf("-->|%--1.*u|<--\n", -2, u));
assert(printf("-->|%--1.*u|<--\n", -1, u) == ft_printf("-->|%--1.*u|<--\n", -1, u));
assert(printf("-->|%--1.*u|<--\n", 0, u) == ft_printf("-->|%--1.*u|<--\n", 0, u));
assert(printf("-->|%--1.*u|<--\n", 1, u) == ft_printf("-->|%--1.*u|<--\n", 1, u));
assert(printf("-->|%--1.*u|<--\n", 2, u) == ft_printf("-->|%--1.*u|<--\n", 2, u));
assert(printf("-->|%--1.*u|<--\n", 3, u) == ft_printf("-->|%--1.*u|<--\n", 3, u));
assert(printf("-->|%--1.*u|<--\n", 4, u) == ft_printf("-->|%--1.*u|<--\n", 4, u));
assert(printf("-->|%--1.0u|<--\n", u) == ft_printf("-->|%--1.0u|<--\n", u));
assert(printf("-->|%--1.1u|<--\n", u) == ft_printf("-->|%--1.1u|<--\n", u));
assert(printf("-->|%--1.2u|<--\n", u) == ft_printf("-->|%--1.2u|<--\n", u));
assert(printf("-->|%--1.3u|<--\n", u) == ft_printf("-->|%--1.3u|<--\n", u));
assert(printf("-->|%--1.4u|<--\n", u) == ft_printf("-->|%--1.4u|<--\n", u));
assert(printf("-->|%--1u|<--\n", u) == ft_printf("-->|%--1u|<--\n", u));
assert(printf("-->|%-.u|<--\n", u) == ft_printf("-->|%-.u|<--\n", u));
assert(printf("-->|%-.*u|<--\n", -4, u) == ft_printf("-->|%-.*u|<--\n", -4, u));
assert(printf("-->|%-.*u|<--\n", -3, u) == ft_printf("-->|%-.*u|<--\n", -3, u));
assert(printf("-->|%-.*u|<--\n", -2, u) == ft_printf("-->|%-.*u|<--\n", -2, u));
assert(printf("-->|%-.*u|<--\n", -1, u) == ft_printf("-->|%-.*u|<--\n", -1, u));
assert(printf("-->|%-.*u|<--\n", 0, u) == ft_printf("-->|%-.*u|<--\n", 0, u));
assert(printf("-->|%-.*u|<--\n", 1, u) == ft_printf("-->|%-.*u|<--\n", 1, u));
assert(printf("-->|%-.*u|<--\n", 2, u) == ft_printf("-->|%-.*u|<--\n", 2, u));
assert(printf("-->|%-.*u|<--\n", 3, u) == ft_printf("-->|%-.*u|<--\n", 3, u));
assert(printf("-->|%-.*u|<--\n", 4, u) == ft_printf("-->|%-.*u|<--\n", 4, u));
assert(printf("-->|%-.0u|<--\n", u) == ft_printf("-->|%-.0u|<--\n", u));
assert(printf("-->|%-.1u|<--\n", u) == ft_printf("-->|%-.1u|<--\n", u));
assert(printf("-->|%-.2u|<--\n", u) == ft_printf("-->|%-.2u|<--\n", u));
assert(printf("-->|%-.3u|<--\n", u) == ft_printf("-->|%-.3u|<--\n", u));
assert(printf("-->|%-.4u|<--\n", u) == ft_printf("-->|%-.4u|<--\n", u));
assert(printf("-->|%-u|<--\n", u) == ft_printf("-->|%-u|<--\n", u));
assert(printf("-->|%-*.u|<--\n", -4, u) == ft_printf("-->|%-*.u|<--\n", -4, u));
assert(printf("-->|%-*.u|<--\n", -3, u) == ft_printf("-->|%-*.u|<--\n", -3, u));
assert(printf("-->|%-*.u|<--\n", -2, u) == ft_printf("-->|%-*.u|<--\n", -2, u));
assert(printf("-->|%-*.u|<--\n", -1, u) == ft_printf("-->|%-*.u|<--\n", -1, u));
assert(printf("-->|%-*.u|<--\n", 0, u) == ft_printf("-->|%-*.u|<--\n", 0, u));
assert(printf("-->|%-*.u|<--\n", 1, u) == ft_printf("-->|%-*.u|<--\n", 1, u));
assert(printf("-->|%-*.u|<--\n", 2, u) == ft_printf("-->|%-*.u|<--\n", 2, u));
assert(printf("-->|%-*.u|<--\n", 3, u) == ft_printf("-->|%-*.u|<--\n", 3, u));
assert(printf("-->|%-*.u|<--\n", 4, u) == ft_printf("-->|%-*.u|<--\n", 4, u));
assert(printf("-->|%-*.*u|<--\n", -4, -4, u) == ft_printf("-->|%-*.*u|<--\n", -4, -4, u));
assert(printf("-->|%-*.*u|<--\n", -4, -3, u) == ft_printf("-->|%-*.*u|<--\n", -4, -3, u));
assert(printf("-->|%-*.*u|<--\n", -4, -2, u) == ft_printf("-->|%-*.*u|<--\n", -4, -2, u));
assert(printf("-->|%-*.*u|<--\n", -4, -1, u) == ft_printf("-->|%-*.*u|<--\n", -4, -1, u));
assert(printf("-->|%-*.*u|<--\n", -4, 0, u) == ft_printf("-->|%-*.*u|<--\n", -4, 0, u));
assert(printf("-->|%-*.*u|<--\n", -4, 1, u) == ft_printf("-->|%-*.*u|<--\n", -4, 1, u));
assert(printf("-->|%-*.*u|<--\n", -4, 2, u) == ft_printf("-->|%-*.*u|<--\n", -4, 2, u));
assert(printf("-->|%-*.*u|<--\n", -4, 3, u) == ft_printf("-->|%-*.*u|<--\n", -4, 3, u));
assert(printf("-->|%-*.*u|<--\n", -4, 4, u) == ft_printf("-->|%-*.*u|<--\n", -4, 4, u));
assert(printf("-->|%-*.*u|<--\n", -3, -4, u) == ft_printf("-->|%-*.*u|<--\n", -3, -4, u));
assert(printf("-->|%-*.*u|<--\n", -3, -3, u) == ft_printf("-->|%-*.*u|<--\n", -3, -3, u));
assert(printf("-->|%-*.*u|<--\n", -3, -2, u) == ft_printf("-->|%-*.*u|<--\n", -3, -2, u));
assert(printf("-->|%-*.*u|<--\n", -3, -1, u) == ft_printf("-->|%-*.*u|<--\n", -3, -1, u));
assert(printf("-->|%-*.*u|<--\n", -3, 0, u) == ft_printf("-->|%-*.*u|<--\n", -3, 0, u));
assert(printf("-->|%-*.*u|<--\n", -3, 1, u) == ft_printf("-->|%-*.*u|<--\n", -3, 1, u));
assert(printf("-->|%-*.*u|<--\n", -3, 2, u) == ft_printf("-->|%-*.*u|<--\n", -3, 2, u));
assert(printf("-->|%-*.*u|<--\n", -3, 3, u) == ft_printf("-->|%-*.*u|<--\n", -3, 3, u));
assert(printf("-->|%-*.*u|<--\n", -3, 4, u) == ft_printf("-->|%-*.*u|<--\n", -3, 4, u));
assert(printf("-->|%-*.*u|<--\n", -2, -4, u) == ft_printf("-->|%-*.*u|<--\n", -2, -4, u));
assert(printf("-->|%-*.*u|<--\n", -2, -3, u) == ft_printf("-->|%-*.*u|<--\n", -2, -3, u));
assert(printf("-->|%-*.*u|<--\n", -2, -2, u) == ft_printf("-->|%-*.*u|<--\n", -2, -2, u));
assert(printf("-->|%-*.*u|<--\n", -2, -1, u) == ft_printf("-->|%-*.*u|<--\n", -2, -1, u));
assert(printf("-->|%-*.*u|<--\n", -2, 0, u) == ft_printf("-->|%-*.*u|<--\n", -2, 0, u));
assert(printf("-->|%-*.*u|<--\n", -2, 1, u) == ft_printf("-->|%-*.*u|<--\n", -2, 1, u));
assert(printf("-->|%-*.*u|<--\n", -2, 2, u) == ft_printf("-->|%-*.*u|<--\n", -2, 2, u));
assert(printf("-->|%-*.*u|<--\n", -2, 3, u) == ft_printf("-->|%-*.*u|<--\n", -2, 3, u));
assert(printf("-->|%-*.*u|<--\n", -2, 4, u) == ft_printf("-->|%-*.*u|<--\n", -2, 4, u));
assert(printf("-->|%-*.*u|<--\n", -1, -4, u) == ft_printf("-->|%-*.*u|<--\n", -1, -4, u));
assert(printf("-->|%-*.*u|<--\n", -1, -3, u) == ft_printf("-->|%-*.*u|<--\n", -1, -3, u));
assert(printf("-->|%-*.*u|<--\n", -1, -2, u) == ft_printf("-->|%-*.*u|<--\n", -1, -2, u));
assert(printf("-->|%-*.*u|<--\n", -1, -1, u) == ft_printf("-->|%-*.*u|<--\n", -1, -1, u));
assert(printf("-->|%-*.*u|<--\n", -1, 0, u) == ft_printf("-->|%-*.*u|<--\n", -1, 0, u));
assert(printf("-->|%-*.*u|<--\n", -1, 1, u) == ft_printf("-->|%-*.*u|<--\n", -1, 1, u));
assert(printf("-->|%-*.*u|<--\n", -1, 2, u) == ft_printf("-->|%-*.*u|<--\n", -1, 2, u));
assert(printf("-->|%-*.*u|<--\n", -1, 3, u) == ft_printf("-->|%-*.*u|<--\n", -1, 3, u));
assert(printf("-->|%-*.*u|<--\n", -1, 4, u) == ft_printf("-->|%-*.*u|<--\n", -1, 4, u));
assert(printf("-->|%-*.*u|<--\n", 0, -4, u) == ft_printf("-->|%-*.*u|<--\n", 0, -4, u));
assert(printf("-->|%-*.*u|<--\n", 0, -3, u) == ft_printf("-->|%-*.*u|<--\n", 0, -3, u));
assert(printf("-->|%-*.*u|<--\n", 0, -2, u) == ft_printf("-->|%-*.*u|<--\n", 0, -2, u));
assert(printf("-->|%-*.*u|<--\n", 0, -1, u) == ft_printf("-->|%-*.*u|<--\n", 0, -1, u));
assert(printf("-->|%-*.*u|<--\n", 0, 0, u) == ft_printf("-->|%-*.*u|<--\n", 0, 0, u));
assert(printf("-->|%-*.*u|<--\n", 0, 1, u) == ft_printf("-->|%-*.*u|<--\n", 0, 1, u));
assert(printf("-->|%-*.*u|<--\n", 0, 2, u) == ft_printf("-->|%-*.*u|<--\n", 0, 2, u));
assert(printf("-->|%-*.*u|<--\n", 0, 3, u) == ft_printf("-->|%-*.*u|<--\n", 0, 3, u));
assert(printf("-->|%-*.*u|<--\n", 0, 4, u) == ft_printf("-->|%-*.*u|<--\n", 0, 4, u));
assert(printf("-->|%-*.*u|<--\n", 1, -4, u) == ft_printf("-->|%-*.*u|<--\n", 1, -4, u));
assert(printf("-->|%-*.*u|<--\n", 1, -3, u) == ft_printf("-->|%-*.*u|<--\n", 1, -3, u));
assert(printf("-->|%-*.*u|<--\n", 1, -2, u) == ft_printf("-->|%-*.*u|<--\n", 1, -2, u));
assert(printf("-->|%-*.*u|<--\n", 1, -1, u) == ft_printf("-->|%-*.*u|<--\n", 1, -1, u));
assert(printf("-->|%-*.*u|<--\n", 1, 0, u) == ft_printf("-->|%-*.*u|<--\n", 1, 0, u));
assert(printf("-->|%-*.*u|<--\n", 1, 1, u) == ft_printf("-->|%-*.*u|<--\n", 1, 1, u));
assert(printf("-->|%-*.*u|<--\n", 1, 2, u) == ft_printf("-->|%-*.*u|<--\n", 1, 2, u));
assert(printf("-->|%-*.*u|<--\n", 1, 3, u) == ft_printf("-->|%-*.*u|<--\n", 1, 3, u));
assert(printf("-->|%-*.*u|<--\n", 1, 4, u) == ft_printf("-->|%-*.*u|<--\n", 1, 4, u));
assert(printf("-->|%-*.*u|<--\n", 2, -4, u) == ft_printf("-->|%-*.*u|<--\n", 2, -4, u));
assert(printf("-->|%-*.*u|<--\n", 2, -3, u) == ft_printf("-->|%-*.*u|<--\n", 2, -3, u));
assert(printf("-->|%-*.*u|<--\n", 2, -2, u) == ft_printf("-->|%-*.*u|<--\n", 2, -2, u));
assert(printf("-->|%-*.*u|<--\n", 2, -1, u) == ft_printf("-->|%-*.*u|<--\n", 2, -1, u));
assert(printf("-->|%-*.*u|<--\n", 2, 0, u) == ft_printf("-->|%-*.*u|<--\n", 2, 0, u));
assert(printf("-->|%-*.*u|<--\n", 2, 1, u) == ft_printf("-->|%-*.*u|<--\n", 2, 1, u));
assert(printf("-->|%-*.*u|<--\n", 2, 2, u) == ft_printf("-->|%-*.*u|<--\n", 2, 2, u));
assert(printf("-->|%-*.*u|<--\n", 2, 3, u) == ft_printf("-->|%-*.*u|<--\n", 2, 3, u));
assert(printf("-->|%-*.*u|<--\n", 2, 4, u) == ft_printf("-->|%-*.*u|<--\n", 2, 4, u));
assert(printf("-->|%-*.*u|<--\n", 3, -4, u) == ft_printf("-->|%-*.*u|<--\n", 3, -4, u));
assert(printf("-->|%-*.*u|<--\n", 3, -3, u) == ft_printf("-->|%-*.*u|<--\n", 3, -3, u));
assert(printf("-->|%-*.*u|<--\n", 3, -2, u) == ft_printf("-->|%-*.*u|<--\n", 3, -2, u));
assert(printf("-->|%-*.*u|<--\n", 3, -1, u) == ft_printf("-->|%-*.*u|<--\n", 3, -1, u));
assert(printf("-->|%-*.*u|<--\n", 3, 0, u) == ft_printf("-->|%-*.*u|<--\n", 3, 0, u));
assert(printf("-->|%-*.*u|<--\n", 3, 1, u) == ft_printf("-->|%-*.*u|<--\n", 3, 1, u));
assert(printf("-->|%-*.*u|<--\n", 3, 2, u) == ft_printf("-->|%-*.*u|<--\n", 3, 2, u));
assert(printf("-->|%-*.*u|<--\n", 3, 3, u) == ft_printf("-->|%-*.*u|<--\n", 3, 3, u));
assert(printf("-->|%-*.*u|<--\n", 3, 4, u) == ft_printf("-->|%-*.*u|<--\n", 3, 4, u));
assert(printf("-->|%-*.*u|<--\n", 4, -4, u) == ft_printf("-->|%-*.*u|<--\n", 4, -4, u));
assert(printf("-->|%-*.*u|<--\n", 4, -3, u) == ft_printf("-->|%-*.*u|<--\n", 4, -3, u));
assert(printf("-->|%-*.*u|<--\n", 4, -2, u) == ft_printf("-->|%-*.*u|<--\n", 4, -2, u));
assert(printf("-->|%-*.*u|<--\n", 4, -1, u) == ft_printf("-->|%-*.*u|<--\n", 4, -1, u));
assert(printf("-->|%-*.*u|<--\n", 4, 0, u) == ft_printf("-->|%-*.*u|<--\n", 4, 0, u));
assert(printf("-->|%-*.*u|<--\n", 4, 1, u) == ft_printf("-->|%-*.*u|<--\n", 4, 1, u));
assert(printf("-->|%-*.*u|<--\n", 4, 2, u) == ft_printf("-->|%-*.*u|<--\n", 4, 2, u));
assert(printf("-->|%-*.*u|<--\n", 4, 3, u) == ft_printf("-->|%-*.*u|<--\n", 4, 3, u));
assert(printf("-->|%-*.*u|<--\n", 4, 4, u) == ft_printf("-->|%-*.*u|<--\n", 4, 4, u));
assert(printf("-->|%-*.0u|<--\n", -4, u) == ft_printf("-->|%-*.0u|<--\n", -4, u));
assert(printf("-->|%-*.0u|<--\n", -3, u) == ft_printf("-->|%-*.0u|<--\n", -3, u));
assert(printf("-->|%-*.0u|<--\n", -2, u) == ft_printf("-->|%-*.0u|<--\n", -2, u));
assert(printf("-->|%-*.0u|<--\n", -1, u) == ft_printf("-->|%-*.0u|<--\n", -1, u));
assert(printf("-->|%-*.0u|<--\n", 0, u) == ft_printf("-->|%-*.0u|<--\n", 0, u));
assert(printf("-->|%-*.0u|<--\n", 1, u) == ft_printf("-->|%-*.0u|<--\n", 1, u));
assert(printf("-->|%-*.0u|<--\n", 2, u) == ft_printf("-->|%-*.0u|<--\n", 2, u));
assert(printf("-->|%-*.0u|<--\n", 3, u) == ft_printf("-->|%-*.0u|<--\n", 3, u));
assert(printf("-->|%-*.0u|<--\n", 4, u) == ft_printf("-->|%-*.0u|<--\n", 4, u));
assert(printf("-->|%-*.1u|<--\n", -4, u) == ft_printf("-->|%-*.1u|<--\n", -4, u));
assert(printf("-->|%-*.1u|<--\n", -3, u) == ft_printf("-->|%-*.1u|<--\n", -3, u));
assert(printf("-->|%-*.1u|<--\n", -2, u) == ft_printf("-->|%-*.1u|<--\n", -2, u));
assert(printf("-->|%-*.1u|<--\n", -1, u) == ft_printf("-->|%-*.1u|<--\n", -1, u));
assert(printf("-->|%-*.1u|<--\n", 0, u) == ft_printf("-->|%-*.1u|<--\n", 0, u));
assert(printf("-->|%-*.1u|<--\n", 1, u) == ft_printf("-->|%-*.1u|<--\n", 1, u));
assert(printf("-->|%-*.1u|<--\n", 2, u) == ft_printf("-->|%-*.1u|<--\n", 2, u));
assert(printf("-->|%-*.1u|<--\n", 3, u) == ft_printf("-->|%-*.1u|<--\n", 3, u));
assert(printf("-->|%-*.1u|<--\n", 4, u) == ft_printf("-->|%-*.1u|<--\n", 4, u));
assert(printf("-->|%-*.2u|<--\n", -4, u) == ft_printf("-->|%-*.2u|<--\n", -4, u));
assert(printf("-->|%-*.2u|<--\n", -3, u) == ft_printf("-->|%-*.2u|<--\n", -3, u));
assert(printf("-->|%-*.2u|<--\n", -2, u) == ft_printf("-->|%-*.2u|<--\n", -2, u));
assert(printf("-->|%-*.2u|<--\n", -1, u) == ft_printf("-->|%-*.2u|<--\n", -1, u));
assert(printf("-->|%-*.2u|<--\n", 0, u) == ft_printf("-->|%-*.2u|<--\n", 0, u));
assert(printf("-->|%-*.2u|<--\n", 1, u) == ft_printf("-->|%-*.2u|<--\n", 1, u));
assert(printf("-->|%-*.2u|<--\n", 2, u) == ft_printf("-->|%-*.2u|<--\n", 2, u));
assert(printf("-->|%-*.2u|<--\n", 3, u) == ft_printf("-->|%-*.2u|<--\n", 3, u));
assert(printf("-->|%-*.2u|<--\n", 4, u) == ft_printf("-->|%-*.2u|<--\n", 4, u));
assert(printf("-->|%-*.3u|<--\n", -4, u) == ft_printf("-->|%-*.3u|<--\n", -4, u));
assert(printf("-->|%-*.3u|<--\n", -3, u) == ft_printf("-->|%-*.3u|<--\n", -3, u));
assert(printf("-->|%-*.3u|<--\n", -2, u) == ft_printf("-->|%-*.3u|<--\n", -2, u));
assert(printf("-->|%-*.3u|<--\n", -1, u) == ft_printf("-->|%-*.3u|<--\n", -1, u));
assert(printf("-->|%-*.3u|<--\n", 0, u) == ft_printf("-->|%-*.3u|<--\n", 0, u));
assert(printf("-->|%-*.3u|<--\n", 1, u) == ft_printf("-->|%-*.3u|<--\n", 1, u));
assert(printf("-->|%-*.3u|<--\n", 2, u) == ft_printf("-->|%-*.3u|<--\n", 2, u));
assert(printf("-->|%-*.3u|<--\n", 3, u) == ft_printf("-->|%-*.3u|<--\n", 3, u));
assert(printf("-->|%-*.3u|<--\n", 4, u) == ft_printf("-->|%-*.3u|<--\n", 4, u));
assert(printf("-->|%-*.4u|<--\n", -4, u) == ft_printf("-->|%-*.4u|<--\n", -4, u));
assert(printf("-->|%-*.4u|<--\n", -3, u) == ft_printf("-->|%-*.4u|<--\n", -3, u));
assert(printf("-->|%-*.4u|<--\n", -2, u) == ft_printf("-->|%-*.4u|<--\n", -2, u));
assert(printf("-->|%-*.4u|<--\n", -1, u) == ft_printf("-->|%-*.4u|<--\n", -1, u));
assert(printf("-->|%-*.4u|<--\n", 0, u) == ft_printf("-->|%-*.4u|<--\n", 0, u));
assert(printf("-->|%-*.4u|<--\n", 1, u) == ft_printf("-->|%-*.4u|<--\n", 1, u));
assert(printf("-->|%-*.4u|<--\n", 2, u) == ft_printf("-->|%-*.4u|<--\n", 2, u));
assert(printf("-->|%-*.4u|<--\n", 3, u) == ft_printf("-->|%-*.4u|<--\n", 3, u));
assert(printf("-->|%-*.4u|<--\n", 4, u) == ft_printf("-->|%-*.4u|<--\n", 4, u));
assert(printf("-->|%-*u|<--\n", -4, u) == ft_printf("-->|%-*u|<--\n", -4, u));
assert(printf("-->|%-*u|<--\n", -3, u) == ft_printf("-->|%-*u|<--\n", -3, u));
assert(printf("-->|%-*u|<--\n", -2, u) == ft_printf("-->|%-*u|<--\n", -2, u));
assert(printf("-->|%-*u|<--\n", -1, u) == ft_printf("-->|%-*u|<--\n", -1, u));
assert(printf("-->|%-*u|<--\n", 0, u) == ft_printf("-->|%-*u|<--\n", 0, u));
assert(printf("-->|%-*u|<--\n", 1, u) == ft_printf("-->|%-*u|<--\n", 1, u));
assert(printf("-->|%-*u|<--\n", 2, u) == ft_printf("-->|%-*u|<--\n", 2, u));
assert(printf("-->|%-*u|<--\n", 3, u) == ft_printf("-->|%-*u|<--\n", 3, u));
assert(printf("-->|%-*u|<--\n", 4, u) == ft_printf("-->|%-*u|<--\n", 4, u));
assert(printf("-->|%-1.u|<--\n", u) == ft_printf("-->|%-1.u|<--\n", u));
assert(printf("-->|%-1.*u|<--\n", -4, u) == ft_printf("-->|%-1.*u|<--\n", -4, u));
assert(printf("-->|%-1.*u|<--\n", -3, u) == ft_printf("-->|%-1.*u|<--\n", -3, u));
assert(printf("-->|%-1.*u|<--\n", -2, u) == ft_printf("-->|%-1.*u|<--\n", -2, u));
assert(printf("-->|%-1.*u|<--\n", -1, u) == ft_printf("-->|%-1.*u|<--\n", -1, u));
assert(printf("-->|%-1.*u|<--\n", 0, u) == ft_printf("-->|%-1.*u|<--\n", 0, u));
assert(printf("-->|%-1.*u|<--\n", 1, u) == ft_printf("-->|%-1.*u|<--\n", 1, u));
assert(printf("-->|%-1.*u|<--\n", 2, u) == ft_printf("-->|%-1.*u|<--\n", 2, u));
assert(printf("-->|%-1.*u|<--\n", 3, u) == ft_printf("-->|%-1.*u|<--\n", 3, u));
assert(printf("-->|%-1.*u|<--\n", 4, u) == ft_printf("-->|%-1.*u|<--\n", 4, u));
assert(printf("-->|%-1.0u|<--\n", u) == ft_printf("-->|%-1.0u|<--\n", u));
assert(printf("-->|%-1.1u|<--\n", u) == ft_printf("-->|%-1.1u|<--\n", u));
assert(printf("-->|%-1.2u|<--\n", u) == ft_printf("-->|%-1.2u|<--\n", u));
assert(printf("-->|%-1.3u|<--\n", u) == ft_printf("-->|%-1.3u|<--\n", u));
assert(printf("-->|%-1.4u|<--\n", u) == ft_printf("-->|%-1.4u|<--\n", u));
assert(printf("-->|%-1u|<--\n", u) == ft_printf("-->|%-1u|<--\n", u));
assert(printf("-->|%-2.u|<--\n", u) == ft_printf("-->|%-2.u|<--\n", u));
assert(printf("-->|%-2.*u|<--\n", -4, u) == ft_printf("-->|%-2.*u|<--\n", -4, u));
assert(printf("-->|%-2.*u|<--\n", -3, u) == ft_printf("-->|%-2.*u|<--\n", -3, u));
assert(printf("-->|%-2.*u|<--\n", -2, u) == ft_printf("-->|%-2.*u|<--\n", -2, u));
assert(printf("-->|%-2.*u|<--\n", -1, u) == ft_printf("-->|%-2.*u|<--\n", -1, u));
assert(printf("-->|%-2.*u|<--\n", 0, u) == ft_printf("-->|%-2.*u|<--\n", 0, u));
assert(printf("-->|%-2.*u|<--\n", 1, u) == ft_printf("-->|%-2.*u|<--\n", 1, u));
assert(printf("-->|%-2.*u|<--\n", 2, u) == ft_printf("-->|%-2.*u|<--\n", 2, u));
assert(printf("-->|%-2.*u|<--\n", 3, u) == ft_printf("-->|%-2.*u|<--\n", 3, u));
assert(printf("-->|%-2.*u|<--\n", 4, u) == ft_printf("-->|%-2.*u|<--\n", 4, u));
assert(printf("-->|%-2.0u|<--\n", u) == ft_printf("-->|%-2.0u|<--\n", u));
assert(printf("-->|%-2.1u|<--\n", u) == ft_printf("-->|%-2.1u|<--\n", u));
assert(printf("-->|%-2.2u|<--\n", u) == ft_printf("-->|%-2.2u|<--\n", u));
assert(printf("-->|%-2.3u|<--\n", u) == ft_printf("-->|%-2.3u|<--\n", u));
assert(printf("-->|%-2.4u|<--\n", u) == ft_printf("-->|%-2.4u|<--\n", u));
assert(printf("-->|%-2u|<--\n", u) == ft_printf("-->|%-2u|<--\n", u));
assert(printf("-->|%-3.u|<--\n", u) == ft_printf("-->|%-3.u|<--\n", u));
assert(printf("-->|%-3.*u|<--\n", -4, u) == ft_printf("-->|%-3.*u|<--\n", -4, u));
assert(printf("-->|%-3.*u|<--\n", -3, u) == ft_printf("-->|%-3.*u|<--\n", -3, u));
assert(printf("-->|%-3.*u|<--\n", -2, u) == ft_printf("-->|%-3.*u|<--\n", -2, u));
assert(printf("-->|%-3.*u|<--\n", -1, u) == ft_printf("-->|%-3.*u|<--\n", -1, u));
assert(printf("-->|%-3.*u|<--\n", 0, u) == ft_printf("-->|%-3.*u|<--\n", 0, u));
assert(printf("-->|%-3.*u|<--\n", 1, u) == ft_printf("-->|%-3.*u|<--\n", 1, u));
assert(printf("-->|%-3.*u|<--\n", 2, u) == ft_printf("-->|%-3.*u|<--\n", 2, u));
assert(printf("-->|%-3.*u|<--\n", 3, u) == ft_printf("-->|%-3.*u|<--\n", 3, u));
assert(printf("-->|%-3.*u|<--\n", 4, u) == ft_printf("-->|%-3.*u|<--\n", 4, u));
assert(printf("-->|%-3.0u|<--\n", u) == ft_printf("-->|%-3.0u|<--\n", u));
assert(printf("-->|%-3.1u|<--\n", u) == ft_printf("-->|%-3.1u|<--\n", u));
assert(printf("-->|%-3.2u|<--\n", u) == ft_printf("-->|%-3.2u|<--\n", u));
assert(printf("-->|%-3.3u|<--\n", u) == ft_printf("-->|%-3.3u|<--\n", u));
assert(printf("-->|%-3.4u|<--\n", u) == ft_printf("-->|%-3.4u|<--\n", u));
assert(printf("-->|%-3u|<--\n", u) == ft_printf("-->|%-3u|<--\n", u));
assert(printf("-->|%-4.u|<--\n", u) == ft_printf("-->|%-4.u|<--\n", u));
assert(printf("-->|%-4.*u|<--\n", -4, u) == ft_printf("-->|%-4.*u|<--\n", -4, u));
assert(printf("-->|%-4.*u|<--\n", -3, u) == ft_printf("-->|%-4.*u|<--\n", -3, u));
assert(printf("-->|%-4.*u|<--\n", -2, u) == ft_printf("-->|%-4.*u|<--\n", -2, u));
assert(printf("-->|%-4.*u|<--\n", -1, u) == ft_printf("-->|%-4.*u|<--\n", -1, u));
assert(printf("-->|%-4.*u|<--\n", 0, u) == ft_printf("-->|%-4.*u|<--\n", 0, u));
assert(printf("-->|%-4.*u|<--\n", 1, u) == ft_printf("-->|%-4.*u|<--\n", 1, u));
assert(printf("-->|%-4.*u|<--\n", 2, u) == ft_printf("-->|%-4.*u|<--\n", 2, u));
assert(printf("-->|%-4.*u|<--\n", 3, u) == ft_printf("-->|%-4.*u|<--\n", 3, u));
assert(printf("-->|%-4.*u|<--\n", 4, u) == ft_printf("-->|%-4.*u|<--\n", 4, u));
assert(printf("-->|%-4.0u|<--\n", u) == ft_printf("-->|%-4.0u|<--\n", u));
assert(printf("-->|%-4.1u|<--\n", u) == ft_printf("-->|%-4.1u|<--\n", u));
assert(printf("-->|%-4.2u|<--\n", u) == ft_printf("-->|%-4.2u|<--\n", u));
assert(printf("-->|%-4.3u|<--\n", u) == ft_printf("-->|%-4.3u|<--\n", u));
assert(printf("-->|%-4.4u|<--\n", u) == ft_printf("-->|%-4.4u|<--\n", u));
assert(printf("-->|%-4u|<--\n", u) == ft_printf("-->|%-4u|<--\n", u));
	return(0);
}
/*
** charmstr@student.42.fr
**
** 1664 different calls generated automatically according to your options
*/
