/*
** charmstr@student.42.fr
*/

#include "../includes/printf_lover_test_func.h"
#include "../includes/ft_printf.h"
#include "../includes/printf_lover_test_func.h"
#include "../includes/ft_printf.h"
#include "../includes/printf_lover_test_func.h"
#include "../includes/ft_printf.h"
#include "../includes/printf_lover_test_func.h"
#include "../includes/ft_printf.h"
#include "../includes/printf_lover_test_func.h"
#include "../includes/ft_printf.h"
#include "../includes/printf_lover_test_func.h"
#include "../includes/ft_printf.h"
#include "../includes/printf_lover_test_func.h"
#include "../includes/ft_printf.h"
#include "../includes/printf_lover_test_func.h"
#include "../includes/ft_printf.h"
#include "../includes/printf_lover_test_func.h"
#include "../includes/ft_printf.h"
#include "../includes/printf_lover_test_func.h"
#include "../includes/ft_printf.h"
#include "../includes/printf_lover_test_func.h"
#include "../includes/ft_printf.h"
#include "../includes/printf_lover_test_func.h"
#include "../includes/ft_printf.h"
#include "../includes/printf_lover_test_func.h"
#include "../includes/ft_printf.h"
#include "../includes/printf_lover_test_func.h"
#include "../includes/ft_printf.h"
#include "../includes/printf_lover_test_func.h"
#include "../includes/ft_printf.h"
#include <stdio.h>
#include <assert.h>
#include "../includes/printf_lover_test_func.h"

int	test_func_i(int i)
{
setbuf(stdout, NULL);
assert(printf("-->|%-4.i|<--\n", i) == ft_printf("-->|%-4.i|<--\n", i));
assert(printf("-->|%-4.*i|<--\n", -4, i) == ft_printf("-->|%-4.*i|<--\n", -4, i));
assert(printf("-->|%-4.*i|<--\n", -3, i) == ft_printf("-->|%-4.*i|<--\n", -3, i));
assert(printf("-->|%-4.*i|<--\n", -2, i) == ft_printf("-->|%-4.*i|<--\n", -2, i));
assert(printf("-->|%-4.*i|<--\n", -1, i) == ft_printf("-->|%-4.*i|<--\n", -1, i));
assert(printf("-->|%-4.*i|<--\n", 0, i) == ft_printf("-->|%-4.*i|<--\n", 0, i));
assert(printf("-->|%-4.*i|<--\n", 1, i) == ft_printf("-->|%-4.*i|<--\n", 1, i));
assert(printf("-->|%-4.*i|<--\n", 2, i) == ft_printf("-->|%-4.*i|<--\n", 2, i));
assert(printf("-->|%-4.*i|<--\n", 3, i) == ft_printf("-->|%-4.*i|<--\n", 3, i));
assert(printf("-->|%-4.*i|<--\n", 4, i) == ft_printf("-->|%-4.*i|<--\n", 4, i));
assert(printf("-->|%-4.0i|<--\n", i) == ft_printf("-->|%-4.0i|<--\n", i));
assert(printf("-->|%-4.1i|<--\n", i) == ft_printf("-->|%-4.1i|<--\n", i));
assert(printf("-->|%-4.2i|<--\n", i) == ft_printf("-->|%-4.2i|<--\n", i));
assert(printf("-->|%-4.3i|<--\n", i) == ft_printf("-->|%-4.3i|<--\n", i));
assert(printf("-->|%-4.4i|<--\n", i) == ft_printf("-->|%-4.4i|<--\n", i));
assert(printf("-->|%-4i|<--\n", i) == ft_printf("-->|%-4i|<--\n", i));
assert(printf("-->|%-3.i|<--\n", i) == ft_printf("-->|%-3.i|<--\n", i));
assert(printf("-->|%-3.*i|<--\n", -4, i) == ft_printf("-->|%-3.*i|<--\n", -4, i));
assert(printf("-->|%-3.*i|<--\n", -3, i) == ft_printf("-->|%-3.*i|<--\n", -3, i));
assert(printf("-->|%-3.*i|<--\n", -2, i) == ft_printf("-->|%-3.*i|<--\n", -2, i));
assert(printf("-->|%-3.*i|<--\n", -1, i) == ft_printf("-->|%-3.*i|<--\n", -1, i));
assert(printf("-->|%-3.*i|<--\n", 0, i) == ft_printf("-->|%-3.*i|<--\n", 0, i));
assert(printf("-->|%-3.*i|<--\n", 1, i) == ft_printf("-->|%-3.*i|<--\n", 1, i));
assert(printf("-->|%-3.*i|<--\n", 2, i) == ft_printf("-->|%-3.*i|<--\n", 2, i));
assert(printf("-->|%-3.*i|<--\n", 3, i) == ft_printf("-->|%-3.*i|<--\n", 3, i));
assert(printf("-->|%-3.*i|<--\n", 4, i) == ft_printf("-->|%-3.*i|<--\n", 4, i));
assert(printf("-->|%-3.0i|<--\n", i) == ft_printf("-->|%-3.0i|<--\n", i));
assert(printf("-->|%-3.1i|<--\n", i) == ft_printf("-->|%-3.1i|<--\n", i));
assert(printf("-->|%-3.2i|<--\n", i) == ft_printf("-->|%-3.2i|<--\n", i));
assert(printf("-->|%-3.3i|<--\n", i) == ft_printf("-->|%-3.3i|<--\n", i));
assert(printf("-->|%-3.4i|<--\n", i) == ft_printf("-->|%-3.4i|<--\n", i));
assert(printf("-->|%-3i|<--\n", i) == ft_printf("-->|%-3i|<--\n", i));
assert(printf("-->|%-2.i|<--\n", i) == ft_printf("-->|%-2.i|<--\n", i));
assert(printf("-->|%-2.*i|<--\n", -4, i) == ft_printf("-->|%-2.*i|<--\n", -4, i));
assert(printf("-->|%-2.*i|<--\n", -3, i) == ft_printf("-->|%-2.*i|<--\n", -3, i));
assert(printf("-->|%-2.*i|<--\n", -2, i) == ft_printf("-->|%-2.*i|<--\n", -2, i));
assert(printf("-->|%-2.*i|<--\n", -1, i) == ft_printf("-->|%-2.*i|<--\n", -1, i));
assert(printf("-->|%-2.*i|<--\n", 0, i) == ft_printf("-->|%-2.*i|<--\n", 0, i));
assert(printf("-->|%-2.*i|<--\n", 1, i) == ft_printf("-->|%-2.*i|<--\n", 1, i));
assert(printf("-->|%-2.*i|<--\n", 2, i) == ft_printf("-->|%-2.*i|<--\n", 2, i));
assert(printf("-->|%-2.*i|<--\n", 3, i) == ft_printf("-->|%-2.*i|<--\n", 3, i));
assert(printf("-->|%-2.*i|<--\n", 4, i) == ft_printf("-->|%-2.*i|<--\n", 4, i));
assert(printf("-->|%-2.0i|<--\n", i) == ft_printf("-->|%-2.0i|<--\n", i));
assert(printf("-->|%-2.1i|<--\n", i) == ft_printf("-->|%-2.1i|<--\n", i));
assert(printf("-->|%-2.2i|<--\n", i) == ft_printf("-->|%-2.2i|<--\n", i));
assert(printf("-->|%-2.3i|<--\n", i) == ft_printf("-->|%-2.3i|<--\n", i));
assert(printf("-->|%-2.4i|<--\n", i) == ft_printf("-->|%-2.4i|<--\n", i));
assert(printf("-->|%-2i|<--\n", i) == ft_printf("-->|%-2i|<--\n", i));
assert(printf("-->|%-1.i|<--\n", i) == ft_printf("-->|%-1.i|<--\n", i));
assert(printf("-->|%-1.*i|<--\n", -4, i) == ft_printf("-->|%-1.*i|<--\n", -4, i));
assert(printf("-->|%-1.*i|<--\n", -3, i) == ft_printf("-->|%-1.*i|<--\n", -3, i));
assert(printf("-->|%-1.*i|<--\n", -2, i) == ft_printf("-->|%-1.*i|<--\n", -2, i));
assert(printf("-->|%-1.*i|<--\n", -1, i) == ft_printf("-->|%-1.*i|<--\n", -1, i));
assert(printf("-->|%-1.*i|<--\n", 0, i) == ft_printf("-->|%-1.*i|<--\n", 0, i));
assert(printf("-->|%-1.*i|<--\n", 1, i) == ft_printf("-->|%-1.*i|<--\n", 1, i));
assert(printf("-->|%-1.*i|<--\n", 2, i) == ft_printf("-->|%-1.*i|<--\n", 2, i));
assert(printf("-->|%-1.*i|<--\n", 3, i) == ft_printf("-->|%-1.*i|<--\n", 3, i));
assert(printf("-->|%-1.*i|<--\n", 4, i) == ft_printf("-->|%-1.*i|<--\n", 4, i));
assert(printf("-->|%-1.0i|<--\n", i) == ft_printf("-->|%-1.0i|<--\n", i));
assert(printf("-->|%-1.1i|<--\n", i) == ft_printf("-->|%-1.1i|<--\n", i));
assert(printf("-->|%-1.2i|<--\n", i) == ft_printf("-->|%-1.2i|<--\n", i));
assert(printf("-->|%-1.3i|<--\n", i) == ft_printf("-->|%-1.3i|<--\n", i));
assert(printf("-->|%-1.4i|<--\n", i) == ft_printf("-->|%-1.4i|<--\n", i));
assert(printf("-->|%-1i|<--\n", i) == ft_printf("-->|%-1i|<--\n", i));
assert(printf("-->|%.i|<--\n", i) == ft_printf("-->|%.i|<--\n", i));
assert(printf("-->|%.*i|<--\n", -4, i) == ft_printf("-->|%.*i|<--\n", -4, i));
assert(printf("-->|%.*i|<--\n", -3, i) == ft_printf("-->|%.*i|<--\n", -3, i));
assert(printf("-->|%.*i|<--\n", -2, i) == ft_printf("-->|%.*i|<--\n", -2, i));
assert(printf("-->|%.*i|<--\n", -1, i) == ft_printf("-->|%.*i|<--\n", -1, i));
assert(printf("-->|%.*i|<--\n", 0, i) == ft_printf("-->|%.*i|<--\n", 0, i));
assert(printf("-->|%.*i|<--\n", 1, i) == ft_printf("-->|%.*i|<--\n", 1, i));
assert(printf("-->|%.*i|<--\n", 2, i) == ft_printf("-->|%.*i|<--\n", 2, i));
assert(printf("-->|%.*i|<--\n", 3, i) == ft_printf("-->|%.*i|<--\n", 3, i));
assert(printf("-->|%.*i|<--\n", 4, i) == ft_printf("-->|%.*i|<--\n", 4, i));
assert(printf("-->|%.0i|<--\n", i) == ft_printf("-->|%.0i|<--\n", i));
assert(printf("-->|%.1i|<--\n", i) == ft_printf("-->|%.1i|<--\n", i));
assert(printf("-->|%.2i|<--\n", i) == ft_printf("-->|%.2i|<--\n", i));
assert(printf("-->|%.3i|<--\n", i) == ft_printf("-->|%.3i|<--\n", i));
assert(printf("-->|%.4i|<--\n", i) == ft_printf("-->|%.4i|<--\n", i));
assert(printf("-->|%i|<--\n", i) == ft_printf("-->|%i|<--\n", i));
assert(printf("-->|%*.i|<--\n", -4, i) == ft_printf("-->|%*.i|<--\n", -4, i));
assert(printf("-->|%*.i|<--\n", -3, i) == ft_printf("-->|%*.i|<--\n", -3, i));
assert(printf("-->|%*.i|<--\n", -2, i) == ft_printf("-->|%*.i|<--\n", -2, i));
assert(printf("-->|%*.i|<--\n", -1, i) == ft_printf("-->|%*.i|<--\n", -1, i));
assert(printf("-->|%*.i|<--\n", 0, i) == ft_printf("-->|%*.i|<--\n", 0, i));
assert(printf("-->|%*.i|<--\n", 1, i) == ft_printf("-->|%*.i|<--\n", 1, i));
assert(printf("-->|%*.i|<--\n", 2, i) == ft_printf("-->|%*.i|<--\n", 2, i));
assert(printf("-->|%*.i|<--\n", 3, i) == ft_printf("-->|%*.i|<--\n", 3, i));
assert(printf("-->|%*.i|<--\n", 4, i) == ft_printf("-->|%*.i|<--\n", 4, i));
assert(printf("-->|%*.*i|<--\n", -4, -4, i) == ft_printf("-->|%*.*i|<--\n", -4, -4, i));
assert(printf("-->|%*.*i|<--\n", -4, -3, i) == ft_printf("-->|%*.*i|<--\n", -4, -3, i));
assert(printf("-->|%*.*i|<--\n", -4, -2, i) == ft_printf("-->|%*.*i|<--\n", -4, -2, i));
assert(printf("-->|%*.*i|<--\n", -4, -1, i) == ft_printf("-->|%*.*i|<--\n", -4, -1, i));
assert(printf("-->|%*.*i|<--\n", -4, 0, i) == ft_printf("-->|%*.*i|<--\n", -4, 0, i));
assert(printf("-->|%*.*i|<--\n", -4, 1, i) == ft_printf("-->|%*.*i|<--\n", -4, 1, i));
assert(printf("-->|%*.*i|<--\n", -4, 2, i) == ft_printf("-->|%*.*i|<--\n", -4, 2, i));
assert(printf("-->|%*.*i|<--\n", -4, 3, i) == ft_printf("-->|%*.*i|<--\n", -4, 3, i));
assert(printf("-->|%*.*i|<--\n", -4, 4, i) == ft_printf("-->|%*.*i|<--\n", -4, 4, i));
assert(printf("-->|%*.*i|<--\n", -3, -4, i) == ft_printf("-->|%*.*i|<--\n", -3, -4, i));
assert(printf("-->|%*.*i|<--\n", -3, -3, i) == ft_printf("-->|%*.*i|<--\n", -3, -3, i));
assert(printf("-->|%*.*i|<--\n", -3, -2, i) == ft_printf("-->|%*.*i|<--\n", -3, -2, i));
assert(printf("-->|%*.*i|<--\n", -3, -1, i) == ft_printf("-->|%*.*i|<--\n", -3, -1, i));
assert(printf("-->|%*.*i|<--\n", -3, 0, i) == ft_printf("-->|%*.*i|<--\n", -3, 0, i));
assert(printf("-->|%*.*i|<--\n", -3, 1, i) == ft_printf("-->|%*.*i|<--\n", -3, 1, i));
assert(printf("-->|%*.*i|<--\n", -3, 2, i) == ft_printf("-->|%*.*i|<--\n", -3, 2, i));
assert(printf("-->|%*.*i|<--\n", -3, 3, i) == ft_printf("-->|%*.*i|<--\n", -3, 3, i));
assert(printf("-->|%*.*i|<--\n", -3, 4, i) == ft_printf("-->|%*.*i|<--\n", -3, 4, i));
assert(printf("-->|%*.*i|<--\n", -2, -4, i) == ft_printf("-->|%*.*i|<--\n", -2, -4, i));
assert(printf("-->|%*.*i|<--\n", -2, -3, i) == ft_printf("-->|%*.*i|<--\n", -2, -3, i));
assert(printf("-->|%*.*i|<--\n", -2, -2, i) == ft_printf("-->|%*.*i|<--\n", -2, -2, i));
assert(printf("-->|%*.*i|<--\n", -2, -1, i) == ft_printf("-->|%*.*i|<--\n", -2, -1, i));
assert(printf("-->|%*.*i|<--\n", -2, 0, i) == ft_printf("-->|%*.*i|<--\n", -2, 0, i));
assert(printf("-->|%*.*i|<--\n", -2, 1, i) == ft_printf("-->|%*.*i|<--\n", -2, 1, i));
assert(printf("-->|%*.*i|<--\n", -2, 2, i) == ft_printf("-->|%*.*i|<--\n", -2, 2, i));
assert(printf("-->|%*.*i|<--\n", -2, 3, i) == ft_printf("-->|%*.*i|<--\n", -2, 3, i));
assert(printf("-->|%*.*i|<--\n", -2, 4, i) == ft_printf("-->|%*.*i|<--\n", -2, 4, i));
assert(printf("-->|%*.*i|<--\n", -1, -4, i) == ft_printf("-->|%*.*i|<--\n", -1, -4, i));
assert(printf("-->|%*.*i|<--\n", -1, -3, i) == ft_printf("-->|%*.*i|<--\n", -1, -3, i));
assert(printf("-->|%*.*i|<--\n", -1, -2, i) == ft_printf("-->|%*.*i|<--\n", -1, -2, i));
assert(printf("-->|%*.*i|<--\n", -1, -1, i) == ft_printf("-->|%*.*i|<--\n", -1, -1, i));
assert(printf("-->|%*.*i|<--\n", -1, 0, i) == ft_printf("-->|%*.*i|<--\n", -1, 0, i));
assert(printf("-->|%*.*i|<--\n", -1, 1, i) == ft_printf("-->|%*.*i|<--\n", -1, 1, i));
assert(printf("-->|%*.*i|<--\n", -1, 2, i) == ft_printf("-->|%*.*i|<--\n", -1, 2, i));
assert(printf("-->|%*.*i|<--\n", -1, 3, i) == ft_printf("-->|%*.*i|<--\n", -1, 3, i));
assert(printf("-->|%*.*i|<--\n", -1, 4, i) == ft_printf("-->|%*.*i|<--\n", -1, 4, i));
assert(printf("-->|%*.*i|<--\n", 0, -4, i) == ft_printf("-->|%*.*i|<--\n", 0, -4, i));
assert(printf("-->|%*.*i|<--\n", 0, -3, i) == ft_printf("-->|%*.*i|<--\n", 0, -3, i));
assert(printf("-->|%*.*i|<--\n", 0, -2, i) == ft_printf("-->|%*.*i|<--\n", 0, -2, i));
assert(printf("-->|%*.*i|<--\n", 0, -1, i) == ft_printf("-->|%*.*i|<--\n", 0, -1, i));
assert(printf("-->|%*.*i|<--\n", 0, 0, i) == ft_printf("-->|%*.*i|<--\n", 0, 0, i));
assert(printf("-->|%*.*i|<--\n", 0, 1, i) == ft_printf("-->|%*.*i|<--\n", 0, 1, i));
assert(printf("-->|%*.*i|<--\n", 0, 2, i) == ft_printf("-->|%*.*i|<--\n", 0, 2, i));
assert(printf("-->|%*.*i|<--\n", 0, 3, i) == ft_printf("-->|%*.*i|<--\n", 0, 3, i));
assert(printf("-->|%*.*i|<--\n", 0, 4, i) == ft_printf("-->|%*.*i|<--\n", 0, 4, i));
assert(printf("-->|%*.*i|<--\n", 1, -4, i) == ft_printf("-->|%*.*i|<--\n", 1, -4, i));
assert(printf("-->|%*.*i|<--\n", 1, -3, i) == ft_printf("-->|%*.*i|<--\n", 1, -3, i));
assert(printf("-->|%*.*i|<--\n", 1, -2, i) == ft_printf("-->|%*.*i|<--\n", 1, -2, i));
assert(printf("-->|%*.*i|<--\n", 1, -1, i) == ft_printf("-->|%*.*i|<--\n", 1, -1, i));
assert(printf("-->|%*.*i|<--\n", 1, 0, i) == ft_printf("-->|%*.*i|<--\n", 1, 0, i));
assert(printf("-->|%*.*i|<--\n", 1, 1, i) == ft_printf("-->|%*.*i|<--\n", 1, 1, i));
assert(printf("-->|%*.*i|<--\n", 1, 2, i) == ft_printf("-->|%*.*i|<--\n", 1, 2, i));
assert(printf("-->|%*.*i|<--\n", 1, 3, i) == ft_printf("-->|%*.*i|<--\n", 1, 3, i));
assert(printf("-->|%*.*i|<--\n", 1, 4, i) == ft_printf("-->|%*.*i|<--\n", 1, 4, i));
assert(printf("-->|%*.*i|<--\n", 2, -4, i) == ft_printf("-->|%*.*i|<--\n", 2, -4, i));
assert(printf("-->|%*.*i|<--\n", 2, -3, i) == ft_printf("-->|%*.*i|<--\n", 2, -3, i));
assert(printf("-->|%*.*i|<--\n", 2, -2, i) == ft_printf("-->|%*.*i|<--\n", 2, -2, i));
assert(printf("-->|%*.*i|<--\n", 2, -1, i) == ft_printf("-->|%*.*i|<--\n", 2, -1, i));
assert(printf("-->|%*.*i|<--\n", 2, 0, i) == ft_printf("-->|%*.*i|<--\n", 2, 0, i));
assert(printf("-->|%*.*i|<--\n", 2, 1, i) == ft_printf("-->|%*.*i|<--\n", 2, 1, i));
assert(printf("-->|%*.*i|<--\n", 2, 2, i) == ft_printf("-->|%*.*i|<--\n", 2, 2, i));
assert(printf("-->|%*.*i|<--\n", 2, 3, i) == ft_printf("-->|%*.*i|<--\n", 2, 3, i));
assert(printf("-->|%*.*i|<--\n", 2, 4, i) == ft_printf("-->|%*.*i|<--\n", 2, 4, i));
assert(printf("-->|%*.*i|<--\n", 3, -4, i) == ft_printf("-->|%*.*i|<--\n", 3, -4, i));
assert(printf("-->|%*.*i|<--\n", 3, -3, i) == ft_printf("-->|%*.*i|<--\n", 3, -3, i));
assert(printf("-->|%*.*i|<--\n", 3, -2, i) == ft_printf("-->|%*.*i|<--\n", 3, -2, i));
assert(printf("-->|%*.*i|<--\n", 3, -1, i) == ft_printf("-->|%*.*i|<--\n", 3, -1, i));
assert(printf("-->|%*.*i|<--\n", 3, 0, i) == ft_printf("-->|%*.*i|<--\n", 3, 0, i));
assert(printf("-->|%*.*i|<--\n", 3, 1, i) == ft_printf("-->|%*.*i|<--\n", 3, 1, i));
assert(printf("-->|%*.*i|<--\n", 3, 2, i) == ft_printf("-->|%*.*i|<--\n", 3, 2, i));
assert(printf("-->|%*.*i|<--\n", 3, 3, i) == ft_printf("-->|%*.*i|<--\n", 3, 3, i));
assert(printf("-->|%*.*i|<--\n", 3, 4, i) == ft_printf("-->|%*.*i|<--\n", 3, 4, i));
assert(printf("-->|%*.*i|<--\n", 4, -4, i) == ft_printf("-->|%*.*i|<--\n", 4, -4, i));
assert(printf("-->|%*.*i|<--\n", 4, -3, i) == ft_printf("-->|%*.*i|<--\n", 4, -3, i));
assert(printf("-->|%*.*i|<--\n", 4, -2, i) == ft_printf("-->|%*.*i|<--\n", 4, -2, i));
assert(printf("-->|%*.*i|<--\n", 4, -1, i) == ft_printf("-->|%*.*i|<--\n", 4, -1, i));
assert(printf("-->|%*.*i|<--\n", 4, 0, i) == ft_printf("-->|%*.*i|<--\n", 4, 0, i));
assert(printf("-->|%*.*i|<--\n", 4, 1, i) == ft_printf("-->|%*.*i|<--\n", 4, 1, i));
assert(printf("-->|%*.*i|<--\n", 4, 2, i) == ft_printf("-->|%*.*i|<--\n", 4, 2, i));
assert(printf("-->|%*.*i|<--\n", 4, 3, i) == ft_printf("-->|%*.*i|<--\n", 4, 3, i));
assert(printf("-->|%*.*i|<--\n", 4, 4, i) == ft_printf("-->|%*.*i|<--\n", 4, 4, i));
assert(printf("-->|%*.0i|<--\n", -4, i) == ft_printf("-->|%*.0i|<--\n", -4, i));
assert(printf("-->|%*.0i|<--\n", -3, i) == ft_printf("-->|%*.0i|<--\n", -3, i));
assert(printf("-->|%*.0i|<--\n", -2, i) == ft_printf("-->|%*.0i|<--\n", -2, i));
assert(printf("-->|%*.0i|<--\n", -1, i) == ft_printf("-->|%*.0i|<--\n", -1, i));
assert(printf("-->|%*.0i|<--\n", 0, i) == ft_printf("-->|%*.0i|<--\n", 0, i));
assert(printf("-->|%*.0i|<--\n", 1, i) == ft_printf("-->|%*.0i|<--\n", 1, i));
assert(printf("-->|%*.0i|<--\n", 2, i) == ft_printf("-->|%*.0i|<--\n", 2, i));
assert(printf("-->|%*.0i|<--\n", 3, i) == ft_printf("-->|%*.0i|<--\n", 3, i));
assert(printf("-->|%*.0i|<--\n", 4, i) == ft_printf("-->|%*.0i|<--\n", 4, i));
assert(printf("-->|%*.1i|<--\n", -4, i) == ft_printf("-->|%*.1i|<--\n", -4, i));
assert(printf("-->|%*.1i|<--\n", -3, i) == ft_printf("-->|%*.1i|<--\n", -3, i));
assert(printf("-->|%*.1i|<--\n", -2, i) == ft_printf("-->|%*.1i|<--\n", -2, i));
assert(printf("-->|%*.1i|<--\n", -1, i) == ft_printf("-->|%*.1i|<--\n", -1, i));
assert(printf("-->|%*.1i|<--\n", 0, i) == ft_printf("-->|%*.1i|<--\n", 0, i));
assert(printf("-->|%*.1i|<--\n", 1, i) == ft_printf("-->|%*.1i|<--\n", 1, i));
assert(printf("-->|%*.1i|<--\n", 2, i) == ft_printf("-->|%*.1i|<--\n", 2, i));
assert(printf("-->|%*.1i|<--\n", 3, i) == ft_printf("-->|%*.1i|<--\n", 3, i));
assert(printf("-->|%*.1i|<--\n", 4, i) == ft_printf("-->|%*.1i|<--\n", 4, i));
assert(printf("-->|%*.2i|<--\n", -4, i) == ft_printf("-->|%*.2i|<--\n", -4, i));
assert(printf("-->|%*.2i|<--\n", -3, i) == ft_printf("-->|%*.2i|<--\n", -3, i));
assert(printf("-->|%*.2i|<--\n", -2, i) == ft_printf("-->|%*.2i|<--\n", -2, i));
assert(printf("-->|%*.2i|<--\n", -1, i) == ft_printf("-->|%*.2i|<--\n", -1, i));
assert(printf("-->|%*.2i|<--\n", 0, i) == ft_printf("-->|%*.2i|<--\n", 0, i));
assert(printf("-->|%*.2i|<--\n", 1, i) == ft_printf("-->|%*.2i|<--\n", 1, i));
assert(printf("-->|%*.2i|<--\n", 2, i) == ft_printf("-->|%*.2i|<--\n", 2, i));
assert(printf("-->|%*.2i|<--\n", 3, i) == ft_printf("-->|%*.2i|<--\n", 3, i));
assert(printf("-->|%*.2i|<--\n", 4, i) == ft_printf("-->|%*.2i|<--\n", 4, i));
assert(printf("-->|%*.3i|<--\n", -4, i) == ft_printf("-->|%*.3i|<--\n", -4, i));
assert(printf("-->|%*.3i|<--\n", -3, i) == ft_printf("-->|%*.3i|<--\n", -3, i));
assert(printf("-->|%*.3i|<--\n", -2, i) == ft_printf("-->|%*.3i|<--\n", -2, i));
assert(printf("-->|%*.3i|<--\n", -1, i) == ft_printf("-->|%*.3i|<--\n", -1, i));
assert(printf("-->|%*.3i|<--\n", 0, i) == ft_printf("-->|%*.3i|<--\n", 0, i));
assert(printf("-->|%*.3i|<--\n", 1, i) == ft_printf("-->|%*.3i|<--\n", 1, i));
assert(printf("-->|%*.3i|<--\n", 2, i) == ft_printf("-->|%*.3i|<--\n", 2, i));
assert(printf("-->|%*.3i|<--\n", 3, i) == ft_printf("-->|%*.3i|<--\n", 3, i));
assert(printf("-->|%*.3i|<--\n", 4, i) == ft_printf("-->|%*.3i|<--\n", 4, i));
assert(printf("-->|%*.4i|<--\n", -4, i) == ft_printf("-->|%*.4i|<--\n", -4, i));
assert(printf("-->|%*.4i|<--\n", -3, i) == ft_printf("-->|%*.4i|<--\n", -3, i));
assert(printf("-->|%*.4i|<--\n", -2, i) == ft_printf("-->|%*.4i|<--\n", -2, i));
assert(printf("-->|%*.4i|<--\n", -1, i) == ft_printf("-->|%*.4i|<--\n", -1, i));
assert(printf("-->|%*.4i|<--\n", 0, i) == ft_printf("-->|%*.4i|<--\n", 0, i));
assert(printf("-->|%*.4i|<--\n", 1, i) == ft_printf("-->|%*.4i|<--\n", 1, i));
assert(printf("-->|%*.4i|<--\n", 2, i) == ft_printf("-->|%*.4i|<--\n", 2, i));
assert(printf("-->|%*.4i|<--\n", 3, i) == ft_printf("-->|%*.4i|<--\n", 3, i));
assert(printf("-->|%*.4i|<--\n", 4, i) == ft_printf("-->|%*.4i|<--\n", 4, i));
assert(printf("-->|%*i|<--\n", -4, i) == ft_printf("-->|%*i|<--\n", -4, i));
assert(printf("-->|%*i|<--\n", -3, i) == ft_printf("-->|%*i|<--\n", -3, i));
assert(printf("-->|%*i|<--\n", -2, i) == ft_printf("-->|%*i|<--\n", -2, i));
assert(printf("-->|%*i|<--\n", -1, i) == ft_printf("-->|%*i|<--\n", -1, i));
assert(printf("-->|%*i|<--\n", 0, i) == ft_printf("-->|%*i|<--\n", 0, i));
assert(printf("-->|%*i|<--\n", 1, i) == ft_printf("-->|%*i|<--\n", 1, i));
assert(printf("-->|%*i|<--\n", 2, i) == ft_printf("-->|%*i|<--\n", 2, i));
assert(printf("-->|%*i|<--\n", 3, i) == ft_printf("-->|%*i|<--\n", 3, i));
assert(printf("-->|%*i|<--\n", 4, i) == ft_printf("-->|%*i|<--\n", 4, i));
assert(printf("-->|%0.i|<--\n", i) == ft_printf("-->|%0.i|<--\n", i));
assert(printf("-->|%0.*i|<--\n", -4, i) == ft_printf("-->|%0.*i|<--\n", -4, i));
assert(printf("-->|%0.*i|<--\n", -3, i) == ft_printf("-->|%0.*i|<--\n", -3, i));
assert(printf("-->|%0.*i|<--\n", -2, i) == ft_printf("-->|%0.*i|<--\n", -2, i));
assert(printf("-->|%0.*i|<--\n", -1, i) == ft_printf("-->|%0.*i|<--\n", -1, i));
assert(printf("-->|%0.*i|<--\n", 0, i) == ft_printf("-->|%0.*i|<--\n", 0, i));
assert(printf("-->|%0.*i|<--\n", 1, i) == ft_printf("-->|%0.*i|<--\n", 1, i));
assert(printf("-->|%0.*i|<--\n", 2, i) == ft_printf("-->|%0.*i|<--\n", 2, i));
assert(printf("-->|%0.*i|<--\n", 3, i) == ft_printf("-->|%0.*i|<--\n", 3, i));
assert(printf("-->|%0.*i|<--\n", 4, i) == ft_printf("-->|%0.*i|<--\n", 4, i));
assert(printf("-->|%0.0i|<--\n", i) == ft_printf("-->|%0.0i|<--\n", i));
assert(printf("-->|%0.1i|<--\n", i) == ft_printf("-->|%0.1i|<--\n", i));
assert(printf("-->|%0.2i|<--\n", i) == ft_printf("-->|%0.2i|<--\n", i));
assert(printf("-->|%0.3i|<--\n", i) == ft_printf("-->|%0.3i|<--\n", i));
assert(printf("-->|%0.4i|<--\n", i) == ft_printf("-->|%0.4i|<--\n", i));
assert(printf("-->|%0i|<--\n", i) == ft_printf("-->|%0i|<--\n", i));
assert(printf("-->|%1.i|<--\n", i) == ft_printf("-->|%1.i|<--\n", i));
assert(printf("-->|%1.*i|<--\n", -4, i) == ft_printf("-->|%1.*i|<--\n", -4, i));
assert(printf("-->|%1.*i|<--\n", -3, i) == ft_printf("-->|%1.*i|<--\n", -3, i));
assert(printf("-->|%1.*i|<--\n", -2, i) == ft_printf("-->|%1.*i|<--\n", -2, i));
assert(printf("-->|%1.*i|<--\n", -1, i) == ft_printf("-->|%1.*i|<--\n", -1, i));
assert(printf("-->|%1.*i|<--\n", 0, i) == ft_printf("-->|%1.*i|<--\n", 0, i));
assert(printf("-->|%1.*i|<--\n", 1, i) == ft_printf("-->|%1.*i|<--\n", 1, i));
assert(printf("-->|%1.*i|<--\n", 2, i) == ft_printf("-->|%1.*i|<--\n", 2, i));
assert(printf("-->|%1.*i|<--\n", 3, i) == ft_printf("-->|%1.*i|<--\n", 3, i));
assert(printf("-->|%1.*i|<--\n", 4, i) == ft_printf("-->|%1.*i|<--\n", 4, i));
assert(printf("-->|%1.0i|<--\n", i) == ft_printf("-->|%1.0i|<--\n", i));
assert(printf("-->|%1.1i|<--\n", i) == ft_printf("-->|%1.1i|<--\n", i));
assert(printf("-->|%1.2i|<--\n", i) == ft_printf("-->|%1.2i|<--\n", i));
assert(printf("-->|%1.3i|<--\n", i) == ft_printf("-->|%1.3i|<--\n", i));
assert(printf("-->|%1.4i|<--\n", i) == ft_printf("-->|%1.4i|<--\n", i));
assert(printf("-->|%1i|<--\n", i) == ft_printf("-->|%1i|<--\n", i));
assert(printf("-->|%2.i|<--\n", i) == ft_printf("-->|%2.i|<--\n", i));
assert(printf("-->|%2.*i|<--\n", -4, i) == ft_printf("-->|%2.*i|<--\n", -4, i));
assert(printf("-->|%2.*i|<--\n", -3, i) == ft_printf("-->|%2.*i|<--\n", -3, i));
assert(printf("-->|%2.*i|<--\n", -2, i) == ft_printf("-->|%2.*i|<--\n", -2, i));
assert(printf("-->|%2.*i|<--\n", -1, i) == ft_printf("-->|%2.*i|<--\n", -1, i));
assert(printf("-->|%2.*i|<--\n", 0, i) == ft_printf("-->|%2.*i|<--\n", 0, i));
assert(printf("-->|%2.*i|<--\n", 1, i) == ft_printf("-->|%2.*i|<--\n", 1, i));
assert(printf("-->|%2.*i|<--\n", 2, i) == ft_printf("-->|%2.*i|<--\n", 2, i));
assert(printf("-->|%2.*i|<--\n", 3, i) == ft_printf("-->|%2.*i|<--\n", 3, i));
assert(printf("-->|%2.*i|<--\n", 4, i) == ft_printf("-->|%2.*i|<--\n", 4, i));
assert(printf("-->|%2.0i|<--\n", i) == ft_printf("-->|%2.0i|<--\n", i));
assert(printf("-->|%2.1i|<--\n", i) == ft_printf("-->|%2.1i|<--\n", i));
assert(printf("-->|%2.2i|<--\n", i) == ft_printf("-->|%2.2i|<--\n", i));
assert(printf("-->|%2.3i|<--\n", i) == ft_printf("-->|%2.3i|<--\n", i));
assert(printf("-->|%2.4i|<--\n", i) == ft_printf("-->|%2.4i|<--\n", i));
assert(printf("-->|%2i|<--\n", i) == ft_printf("-->|%2i|<--\n", i));
assert(printf("-->|%3.i|<--\n", i) == ft_printf("-->|%3.i|<--\n", i));
assert(printf("-->|%3.*i|<--\n", -4, i) == ft_printf("-->|%3.*i|<--\n", -4, i));
assert(printf("-->|%3.*i|<--\n", -3, i) == ft_printf("-->|%3.*i|<--\n", -3, i));
assert(printf("-->|%3.*i|<--\n", -2, i) == ft_printf("-->|%3.*i|<--\n", -2, i));
assert(printf("-->|%3.*i|<--\n", -1, i) == ft_printf("-->|%3.*i|<--\n", -1, i));
assert(printf("-->|%3.*i|<--\n", 0, i) == ft_printf("-->|%3.*i|<--\n", 0, i));
assert(printf("-->|%3.*i|<--\n", 1, i) == ft_printf("-->|%3.*i|<--\n", 1, i));
assert(printf("-->|%3.*i|<--\n", 2, i) == ft_printf("-->|%3.*i|<--\n", 2, i));
assert(printf("-->|%3.*i|<--\n", 3, i) == ft_printf("-->|%3.*i|<--\n", 3, i));
assert(printf("-->|%3.*i|<--\n", 4, i) == ft_printf("-->|%3.*i|<--\n", 4, i));
assert(printf("-->|%3.0i|<--\n", i) == ft_printf("-->|%3.0i|<--\n", i));
assert(printf("-->|%3.1i|<--\n", i) == ft_printf("-->|%3.1i|<--\n", i));
assert(printf("-->|%3.2i|<--\n", i) == ft_printf("-->|%3.2i|<--\n", i));
assert(printf("-->|%3.3i|<--\n", i) == ft_printf("-->|%3.3i|<--\n", i));
assert(printf("-->|%3.4i|<--\n", i) == ft_printf("-->|%3.4i|<--\n", i));
assert(printf("-->|%3i|<--\n", i) == ft_printf("-->|%3i|<--\n", i));
assert(printf("-->|%4.i|<--\n", i) == ft_printf("-->|%4.i|<--\n", i));
assert(printf("-->|%4.*i|<--\n", -4, i) == ft_printf("-->|%4.*i|<--\n", -4, i));
assert(printf("-->|%4.*i|<--\n", -3, i) == ft_printf("-->|%4.*i|<--\n", -3, i));
assert(printf("-->|%4.*i|<--\n", -2, i) == ft_printf("-->|%4.*i|<--\n", -2, i));
assert(printf("-->|%4.*i|<--\n", -1, i) == ft_printf("-->|%4.*i|<--\n", -1, i));
assert(printf("-->|%4.*i|<--\n", 0, i) == ft_printf("-->|%4.*i|<--\n", 0, i));
assert(printf("-->|%4.*i|<--\n", 1, i) == ft_printf("-->|%4.*i|<--\n", 1, i));
assert(printf("-->|%4.*i|<--\n", 2, i) == ft_printf("-->|%4.*i|<--\n", 2, i));
assert(printf("-->|%4.*i|<--\n", 3, i) == ft_printf("-->|%4.*i|<--\n", 3, i));
assert(printf("-->|%4.*i|<--\n", 4, i) == ft_printf("-->|%4.*i|<--\n", 4, i));
assert(printf("-->|%4.0i|<--\n", i) == ft_printf("-->|%4.0i|<--\n", i));
assert(printf("-->|%4.1i|<--\n", i) == ft_printf("-->|%4.1i|<--\n", i));
assert(printf("-->|%4.2i|<--\n", i) == ft_printf("-->|%4.2i|<--\n", i));
assert(printf("-->|%4.3i|<--\n", i) == ft_printf("-->|%4.3i|<--\n", i));
assert(printf("-->|%4.4i|<--\n", i) == ft_printf("-->|%4.4i|<--\n", i));
assert(printf("-->|%4i|<--\n", i) == ft_printf("-->|%4i|<--\n", i));
assert(printf("-->|%0.i|<--\n", i) == ft_printf("-->|%0.i|<--\n", i));
assert(printf("-->|%0.*i|<--\n", -4, i) == ft_printf("-->|%0.*i|<--\n", -4, i));
assert(printf("-->|%0.*i|<--\n", -3, i) == ft_printf("-->|%0.*i|<--\n", -3, i));
assert(printf("-->|%0.*i|<--\n", -2, i) == ft_printf("-->|%0.*i|<--\n", -2, i));
assert(printf("-->|%0.*i|<--\n", -1, i) == ft_printf("-->|%0.*i|<--\n", -1, i));
assert(printf("-->|%0.*i|<--\n", 0, i) == ft_printf("-->|%0.*i|<--\n", 0, i));
assert(printf("-->|%0.*i|<--\n", 1, i) == ft_printf("-->|%0.*i|<--\n", 1, i));
assert(printf("-->|%0.*i|<--\n", 2, i) == ft_printf("-->|%0.*i|<--\n", 2, i));
assert(printf("-->|%0.*i|<--\n", 3, i) == ft_printf("-->|%0.*i|<--\n", 3, i));
assert(printf("-->|%0.*i|<--\n", 4, i) == ft_printf("-->|%0.*i|<--\n", 4, i));
assert(printf("-->|%0.0i|<--\n", i) == ft_printf("-->|%0.0i|<--\n", i));
assert(printf("-->|%0.1i|<--\n", i) == ft_printf("-->|%0.1i|<--\n", i));
assert(printf("-->|%0.2i|<--\n", i) == ft_printf("-->|%0.2i|<--\n", i));
assert(printf("-->|%0.3i|<--\n", i) == ft_printf("-->|%0.3i|<--\n", i));
assert(printf("-->|%0.4i|<--\n", i) == ft_printf("-->|%0.4i|<--\n", i));
assert(printf("-->|%0i|<--\n", i) == ft_printf("-->|%0i|<--\n", i));
assert(printf("-->|%0*.i|<--\n", -4, i) == ft_printf("-->|%0*.i|<--\n", -4, i));
assert(printf("-->|%0*.i|<--\n", -3, i) == ft_printf("-->|%0*.i|<--\n", -3, i));
assert(printf("-->|%0*.i|<--\n", -2, i) == ft_printf("-->|%0*.i|<--\n", -2, i));
assert(printf("-->|%0*.i|<--\n", -1, i) == ft_printf("-->|%0*.i|<--\n", -1, i));
assert(printf("-->|%0*.i|<--\n", 0, i) == ft_printf("-->|%0*.i|<--\n", 0, i));
assert(printf("-->|%0*.i|<--\n", 1, i) == ft_printf("-->|%0*.i|<--\n", 1, i));
assert(printf("-->|%0*.i|<--\n", 2, i) == ft_printf("-->|%0*.i|<--\n", 2, i));
assert(printf("-->|%0*.i|<--\n", 3, i) == ft_printf("-->|%0*.i|<--\n", 3, i));
assert(printf("-->|%0*.i|<--\n", 4, i) == ft_printf("-->|%0*.i|<--\n", 4, i));
assert(printf("-->|%0*.*i|<--\n", -4, -4, i) == ft_printf("-->|%0*.*i|<--\n", -4, -4, i));
assert(printf("-->|%0*.*i|<--\n", -4, -3, i) == ft_printf("-->|%0*.*i|<--\n", -4, -3, i));
assert(printf("-->|%0*.*i|<--\n", -4, -2, i) == ft_printf("-->|%0*.*i|<--\n", -4, -2, i));
assert(printf("-->|%0*.*i|<--\n", -4, -1, i) == ft_printf("-->|%0*.*i|<--\n", -4, -1, i));
assert(printf("-->|%0*.*i|<--\n", -4, 0, i) == ft_printf("-->|%0*.*i|<--\n", -4, 0, i));
assert(printf("-->|%0*.*i|<--\n", -4, 1, i) == ft_printf("-->|%0*.*i|<--\n", -4, 1, i));
assert(printf("-->|%0*.*i|<--\n", -4, 2, i) == ft_printf("-->|%0*.*i|<--\n", -4, 2, i));
assert(printf("-->|%0*.*i|<--\n", -4, 3, i) == ft_printf("-->|%0*.*i|<--\n", -4, 3, i));
assert(printf("-->|%0*.*i|<--\n", -4, 4, i) == ft_printf("-->|%0*.*i|<--\n", -4, 4, i));
assert(printf("-->|%0*.*i|<--\n", -3, -4, i) == ft_printf("-->|%0*.*i|<--\n", -3, -4, i));
assert(printf("-->|%0*.*i|<--\n", -3, -3, i) == ft_printf("-->|%0*.*i|<--\n", -3, -3, i));
assert(printf("-->|%0*.*i|<--\n", -3, -2, i) == ft_printf("-->|%0*.*i|<--\n", -3, -2, i));
assert(printf("-->|%0*.*i|<--\n", -3, -1, i) == ft_printf("-->|%0*.*i|<--\n", -3, -1, i));
assert(printf("-->|%0*.*i|<--\n", -3, 0, i) == ft_printf("-->|%0*.*i|<--\n", -3, 0, i));
assert(printf("-->|%0*.*i|<--\n", -3, 1, i) == ft_printf("-->|%0*.*i|<--\n", -3, 1, i));
assert(printf("-->|%0*.*i|<--\n", -3, 2, i) == ft_printf("-->|%0*.*i|<--\n", -3, 2, i));
assert(printf("-->|%0*.*i|<--\n", -3, 3, i) == ft_printf("-->|%0*.*i|<--\n", -3, 3, i));
assert(printf("-->|%0*.*i|<--\n", -3, 4, i) == ft_printf("-->|%0*.*i|<--\n", -3, 4, i));
assert(printf("-->|%0*.*i|<--\n", -2, -4, i) == ft_printf("-->|%0*.*i|<--\n", -2, -4, i));
assert(printf("-->|%0*.*i|<--\n", -2, -3, i) == ft_printf("-->|%0*.*i|<--\n", -2, -3, i));
assert(printf("-->|%0*.*i|<--\n", -2, -2, i) == ft_printf("-->|%0*.*i|<--\n", -2, -2, i));
assert(printf("-->|%0*.*i|<--\n", -2, -1, i) == ft_printf("-->|%0*.*i|<--\n", -2, -1, i));
assert(printf("-->|%0*.*i|<--\n", -2, 0, i) == ft_printf("-->|%0*.*i|<--\n", -2, 0, i));
assert(printf("-->|%0*.*i|<--\n", -2, 1, i) == ft_printf("-->|%0*.*i|<--\n", -2, 1, i));
assert(printf("-->|%0*.*i|<--\n", -2, 2, i) == ft_printf("-->|%0*.*i|<--\n", -2, 2, i));
assert(printf("-->|%0*.*i|<--\n", -2, 3, i) == ft_printf("-->|%0*.*i|<--\n", -2, 3, i));
assert(printf("-->|%0*.*i|<--\n", -2, 4, i) == ft_printf("-->|%0*.*i|<--\n", -2, 4, i));
assert(printf("-->|%0*.*i|<--\n", -1, -4, i) == ft_printf("-->|%0*.*i|<--\n", -1, -4, i));
assert(printf("-->|%0*.*i|<--\n", -1, -3, i) == ft_printf("-->|%0*.*i|<--\n", -1, -3, i));
assert(printf("-->|%0*.*i|<--\n", -1, -2, i) == ft_printf("-->|%0*.*i|<--\n", -1, -2, i));
assert(printf("-->|%0*.*i|<--\n", -1, -1, i) == ft_printf("-->|%0*.*i|<--\n", -1, -1, i));
assert(printf("-->|%0*.*i|<--\n", -1, 0, i) == ft_printf("-->|%0*.*i|<--\n", -1, 0, i));
assert(printf("-->|%0*.*i|<--\n", -1, 1, i) == ft_printf("-->|%0*.*i|<--\n", -1, 1, i));
assert(printf("-->|%0*.*i|<--\n", -1, 2, i) == ft_printf("-->|%0*.*i|<--\n", -1, 2, i));
assert(printf("-->|%0*.*i|<--\n", -1, 3, i) == ft_printf("-->|%0*.*i|<--\n", -1, 3, i));
assert(printf("-->|%0*.*i|<--\n", -1, 4, i) == ft_printf("-->|%0*.*i|<--\n", -1, 4, i));
assert(printf("-->|%0*.*i|<--\n", 0, -4, i) == ft_printf("-->|%0*.*i|<--\n", 0, -4, i));
assert(printf("-->|%0*.*i|<--\n", 0, -3, i) == ft_printf("-->|%0*.*i|<--\n", 0, -3, i));
assert(printf("-->|%0*.*i|<--\n", 0, -2, i) == ft_printf("-->|%0*.*i|<--\n", 0, -2, i));
assert(printf("-->|%0*.*i|<--\n", 0, -1, i) == ft_printf("-->|%0*.*i|<--\n", 0, -1, i));
assert(printf("-->|%0*.*i|<--\n", 0, 0, i) == ft_printf("-->|%0*.*i|<--\n", 0, 0, i));
assert(printf("-->|%0*.*i|<--\n", 0, 1, i) == ft_printf("-->|%0*.*i|<--\n", 0, 1, i));
assert(printf("-->|%0*.*i|<--\n", 0, 2, i) == ft_printf("-->|%0*.*i|<--\n", 0, 2, i));
assert(printf("-->|%0*.*i|<--\n", 0, 3, i) == ft_printf("-->|%0*.*i|<--\n", 0, 3, i));
assert(printf("-->|%0*.*i|<--\n", 0, 4, i) == ft_printf("-->|%0*.*i|<--\n", 0, 4, i));
assert(printf("-->|%0*.*i|<--\n", 1, -4, i) == ft_printf("-->|%0*.*i|<--\n", 1, -4, i));
assert(printf("-->|%0*.*i|<--\n", 1, -3, i) == ft_printf("-->|%0*.*i|<--\n", 1, -3, i));
assert(printf("-->|%0*.*i|<--\n", 1, -2, i) == ft_printf("-->|%0*.*i|<--\n", 1, -2, i));
assert(printf("-->|%0*.*i|<--\n", 1, -1, i) == ft_printf("-->|%0*.*i|<--\n", 1, -1, i));
assert(printf("-->|%0*.*i|<--\n", 1, 0, i) == ft_printf("-->|%0*.*i|<--\n", 1, 0, i));
assert(printf("-->|%0*.*i|<--\n", 1, 1, i) == ft_printf("-->|%0*.*i|<--\n", 1, 1, i));
assert(printf("-->|%0*.*i|<--\n", 1, 2, i) == ft_printf("-->|%0*.*i|<--\n", 1, 2, i));
assert(printf("-->|%0*.*i|<--\n", 1, 3, i) == ft_printf("-->|%0*.*i|<--\n", 1, 3, i));
assert(printf("-->|%0*.*i|<--\n", 1, 4, i) == ft_printf("-->|%0*.*i|<--\n", 1, 4, i));
assert(printf("-->|%0*.*i|<--\n", 2, -4, i) == ft_printf("-->|%0*.*i|<--\n", 2, -4, i));
assert(printf("-->|%0*.*i|<--\n", 2, -3, i) == ft_printf("-->|%0*.*i|<--\n", 2, -3, i));
assert(printf("-->|%0*.*i|<--\n", 2, -2, i) == ft_printf("-->|%0*.*i|<--\n", 2, -2, i));
assert(printf("-->|%0*.*i|<--\n", 2, -1, i) == ft_printf("-->|%0*.*i|<--\n", 2, -1, i));
assert(printf("-->|%0*.*i|<--\n", 2, 0, i) == ft_printf("-->|%0*.*i|<--\n", 2, 0, i));
assert(printf("-->|%0*.*i|<--\n", 2, 1, i) == ft_printf("-->|%0*.*i|<--\n", 2, 1, i));
assert(printf("-->|%0*.*i|<--\n", 2, 2, i) == ft_printf("-->|%0*.*i|<--\n", 2, 2, i));
assert(printf("-->|%0*.*i|<--\n", 2, 3, i) == ft_printf("-->|%0*.*i|<--\n", 2, 3, i));
assert(printf("-->|%0*.*i|<--\n", 2, 4, i) == ft_printf("-->|%0*.*i|<--\n", 2, 4, i));
assert(printf("-->|%0*.*i|<--\n", 3, -4, i) == ft_printf("-->|%0*.*i|<--\n", 3, -4, i));
assert(printf("-->|%0*.*i|<--\n", 3, -3, i) == ft_printf("-->|%0*.*i|<--\n", 3, -3, i));
assert(printf("-->|%0*.*i|<--\n", 3, -2, i) == ft_printf("-->|%0*.*i|<--\n", 3, -2, i));
assert(printf("-->|%0*.*i|<--\n", 3, -1, i) == ft_printf("-->|%0*.*i|<--\n", 3, -1, i));
assert(printf("-->|%0*.*i|<--\n", 3, 0, i) == ft_printf("-->|%0*.*i|<--\n", 3, 0, i));
assert(printf("-->|%0*.*i|<--\n", 3, 1, i) == ft_printf("-->|%0*.*i|<--\n", 3, 1, i));
assert(printf("-->|%0*.*i|<--\n", 3, 2, i) == ft_printf("-->|%0*.*i|<--\n", 3, 2, i));
assert(printf("-->|%0*.*i|<--\n", 3, 3, i) == ft_printf("-->|%0*.*i|<--\n", 3, 3, i));
assert(printf("-->|%0*.*i|<--\n", 3, 4, i) == ft_printf("-->|%0*.*i|<--\n", 3, 4, i));
assert(printf("-->|%0*.*i|<--\n", 4, -4, i) == ft_printf("-->|%0*.*i|<--\n", 4, -4, i));
assert(printf("-->|%0*.*i|<--\n", 4, -3, i) == ft_printf("-->|%0*.*i|<--\n", 4, -3, i));
assert(printf("-->|%0*.*i|<--\n", 4, -2, i) == ft_printf("-->|%0*.*i|<--\n", 4, -2, i));
assert(printf("-->|%0*.*i|<--\n", 4, -1, i) == ft_printf("-->|%0*.*i|<--\n", 4, -1, i));
assert(printf("-->|%0*.*i|<--\n", 4, 0, i) == ft_printf("-->|%0*.*i|<--\n", 4, 0, i));
assert(printf("-->|%0*.*i|<--\n", 4, 1, i) == ft_printf("-->|%0*.*i|<--\n", 4, 1, i));
assert(printf("-->|%0*.*i|<--\n", 4, 2, i) == ft_printf("-->|%0*.*i|<--\n", 4, 2, i));
assert(printf("-->|%0*.*i|<--\n", 4, 3, i) == ft_printf("-->|%0*.*i|<--\n", 4, 3, i));
assert(printf("-->|%0*.*i|<--\n", 4, 4, i) == ft_printf("-->|%0*.*i|<--\n", 4, 4, i));
assert(printf("-->|%0*.0i|<--\n", -4, i) == ft_printf("-->|%0*.0i|<--\n", -4, i));
assert(printf("-->|%0*.0i|<--\n", -3, i) == ft_printf("-->|%0*.0i|<--\n", -3, i));
assert(printf("-->|%0*.0i|<--\n", -2, i) == ft_printf("-->|%0*.0i|<--\n", -2, i));
assert(printf("-->|%0*.0i|<--\n", -1, i) == ft_printf("-->|%0*.0i|<--\n", -1, i));
assert(printf("-->|%0*.0i|<--\n", 0, i) == ft_printf("-->|%0*.0i|<--\n", 0, i));
assert(printf("-->|%0*.0i|<--\n", 1, i) == ft_printf("-->|%0*.0i|<--\n", 1, i));
assert(printf("-->|%0*.0i|<--\n", 2, i) == ft_printf("-->|%0*.0i|<--\n", 2, i));
assert(printf("-->|%0*.0i|<--\n", 3, i) == ft_printf("-->|%0*.0i|<--\n", 3, i));
assert(printf("-->|%0*.0i|<--\n", 4, i) == ft_printf("-->|%0*.0i|<--\n", 4, i));
assert(printf("-->|%0*.1i|<--\n", -4, i) == ft_printf("-->|%0*.1i|<--\n", -4, i));
assert(printf("-->|%0*.1i|<--\n", -3, i) == ft_printf("-->|%0*.1i|<--\n", -3, i));
assert(printf("-->|%0*.1i|<--\n", -2, i) == ft_printf("-->|%0*.1i|<--\n", -2, i));
assert(printf("-->|%0*.1i|<--\n", -1, i) == ft_printf("-->|%0*.1i|<--\n", -1, i));
assert(printf("-->|%0*.1i|<--\n", 0, i) == ft_printf("-->|%0*.1i|<--\n", 0, i));
assert(printf("-->|%0*.1i|<--\n", 1, i) == ft_printf("-->|%0*.1i|<--\n", 1, i));
assert(printf("-->|%0*.1i|<--\n", 2, i) == ft_printf("-->|%0*.1i|<--\n", 2, i));
assert(printf("-->|%0*.1i|<--\n", 3, i) == ft_printf("-->|%0*.1i|<--\n", 3, i));
assert(printf("-->|%0*.1i|<--\n", 4, i) == ft_printf("-->|%0*.1i|<--\n", 4, i));
assert(printf("-->|%0*.2i|<--\n", -4, i) == ft_printf("-->|%0*.2i|<--\n", -4, i));
assert(printf("-->|%0*.2i|<--\n", -3, i) == ft_printf("-->|%0*.2i|<--\n", -3, i));
assert(printf("-->|%0*.2i|<--\n", -2, i) == ft_printf("-->|%0*.2i|<--\n", -2, i));
assert(printf("-->|%0*.2i|<--\n", -1, i) == ft_printf("-->|%0*.2i|<--\n", -1, i));
assert(printf("-->|%0*.2i|<--\n", 0, i) == ft_printf("-->|%0*.2i|<--\n", 0, i));
assert(printf("-->|%0*.2i|<--\n", 1, i) == ft_printf("-->|%0*.2i|<--\n", 1, i));
assert(printf("-->|%0*.2i|<--\n", 2, i) == ft_printf("-->|%0*.2i|<--\n", 2, i));
assert(printf("-->|%0*.2i|<--\n", 3, i) == ft_printf("-->|%0*.2i|<--\n", 3, i));
assert(printf("-->|%0*.2i|<--\n", 4, i) == ft_printf("-->|%0*.2i|<--\n", 4, i));
assert(printf("-->|%0*.3i|<--\n", -4, i) == ft_printf("-->|%0*.3i|<--\n", -4, i));
assert(printf("-->|%0*.3i|<--\n", -3, i) == ft_printf("-->|%0*.3i|<--\n", -3, i));
assert(printf("-->|%0*.3i|<--\n", -2, i) == ft_printf("-->|%0*.3i|<--\n", -2, i));
assert(printf("-->|%0*.3i|<--\n", -1, i) == ft_printf("-->|%0*.3i|<--\n", -1, i));
assert(printf("-->|%0*.3i|<--\n", 0, i) == ft_printf("-->|%0*.3i|<--\n", 0, i));
assert(printf("-->|%0*.3i|<--\n", 1, i) == ft_printf("-->|%0*.3i|<--\n", 1, i));
assert(printf("-->|%0*.3i|<--\n", 2, i) == ft_printf("-->|%0*.3i|<--\n", 2, i));
assert(printf("-->|%0*.3i|<--\n", 3, i) == ft_printf("-->|%0*.3i|<--\n", 3, i));
assert(printf("-->|%0*.3i|<--\n", 4, i) == ft_printf("-->|%0*.3i|<--\n", 4, i));
assert(printf("-->|%0*.4i|<--\n", -4, i) == ft_printf("-->|%0*.4i|<--\n", -4, i));
assert(printf("-->|%0*.4i|<--\n", -3, i) == ft_printf("-->|%0*.4i|<--\n", -3, i));
assert(printf("-->|%0*.4i|<--\n", -2, i) == ft_printf("-->|%0*.4i|<--\n", -2, i));
assert(printf("-->|%0*.4i|<--\n", -1, i) == ft_printf("-->|%0*.4i|<--\n", -1, i));
assert(printf("-->|%0*.4i|<--\n", 0, i) == ft_printf("-->|%0*.4i|<--\n", 0, i));
assert(printf("-->|%0*.4i|<--\n", 1, i) == ft_printf("-->|%0*.4i|<--\n", 1, i));
assert(printf("-->|%0*.4i|<--\n", 2, i) == ft_printf("-->|%0*.4i|<--\n", 2, i));
assert(printf("-->|%0*.4i|<--\n", 3, i) == ft_printf("-->|%0*.4i|<--\n", 3, i));
assert(printf("-->|%0*.4i|<--\n", 4, i) == ft_printf("-->|%0*.4i|<--\n", 4, i));
assert(printf("-->|%0*i|<--\n", -4, i) == ft_printf("-->|%0*i|<--\n", -4, i));
assert(printf("-->|%0*i|<--\n", -3, i) == ft_printf("-->|%0*i|<--\n", -3, i));
assert(printf("-->|%0*i|<--\n", -2, i) == ft_printf("-->|%0*i|<--\n", -2, i));
assert(printf("-->|%0*i|<--\n", -1, i) == ft_printf("-->|%0*i|<--\n", -1, i));
assert(printf("-->|%0*i|<--\n", 0, i) == ft_printf("-->|%0*i|<--\n", 0, i));
assert(printf("-->|%0*i|<--\n", 1, i) == ft_printf("-->|%0*i|<--\n", 1, i));
assert(printf("-->|%0*i|<--\n", 2, i) == ft_printf("-->|%0*i|<--\n", 2, i));
assert(printf("-->|%0*i|<--\n", 3, i) == ft_printf("-->|%0*i|<--\n", 3, i));
assert(printf("-->|%0*i|<--\n", 4, i) == ft_printf("-->|%0*i|<--\n", 4, i));
assert(printf("-->|%00.i|<--\n", i) == ft_printf("-->|%00.i|<--\n", i));
assert(printf("-->|%00.*i|<--\n", -4, i) == ft_printf("-->|%00.*i|<--\n", -4, i));
assert(printf("-->|%00.*i|<--\n", -3, i) == ft_printf("-->|%00.*i|<--\n", -3, i));
assert(printf("-->|%00.*i|<--\n", -2, i) == ft_printf("-->|%00.*i|<--\n", -2, i));
assert(printf("-->|%00.*i|<--\n", -1, i) == ft_printf("-->|%00.*i|<--\n", -1, i));
assert(printf("-->|%00.*i|<--\n", 0, i) == ft_printf("-->|%00.*i|<--\n", 0, i));
assert(printf("-->|%00.*i|<--\n", 1, i) == ft_printf("-->|%00.*i|<--\n", 1, i));
assert(printf("-->|%00.*i|<--\n", 2, i) == ft_printf("-->|%00.*i|<--\n", 2, i));
assert(printf("-->|%00.*i|<--\n", 3, i) == ft_printf("-->|%00.*i|<--\n", 3, i));
assert(printf("-->|%00.*i|<--\n", 4, i) == ft_printf("-->|%00.*i|<--\n", 4, i));
assert(printf("-->|%00.0i|<--\n", i) == ft_printf("-->|%00.0i|<--\n", i));
assert(printf("-->|%00.1i|<--\n", i) == ft_printf("-->|%00.1i|<--\n", i));
assert(printf("-->|%00.2i|<--\n", i) == ft_printf("-->|%00.2i|<--\n", i));
assert(printf("-->|%00.3i|<--\n", i) == ft_printf("-->|%00.3i|<--\n", i));
assert(printf("-->|%00.4i|<--\n", i) == ft_printf("-->|%00.4i|<--\n", i));
assert(printf("-->|%00i|<--\n", i) == ft_printf("-->|%00i|<--\n", i));
assert(printf("-->|%01.i|<--\n", i) == ft_printf("-->|%01.i|<--\n", i));
assert(printf("-->|%01.*i|<--\n", -4, i) == ft_printf("-->|%01.*i|<--\n", -4, i));
assert(printf("-->|%01.*i|<--\n", -3, i) == ft_printf("-->|%01.*i|<--\n", -3, i));
assert(printf("-->|%01.*i|<--\n", -2, i) == ft_printf("-->|%01.*i|<--\n", -2, i));
assert(printf("-->|%01.*i|<--\n", -1, i) == ft_printf("-->|%01.*i|<--\n", -1, i));
assert(printf("-->|%01.*i|<--\n", 0, i) == ft_printf("-->|%01.*i|<--\n", 0, i));
assert(printf("-->|%01.*i|<--\n", 1, i) == ft_printf("-->|%01.*i|<--\n", 1, i));
assert(printf("-->|%01.*i|<--\n", 2, i) == ft_printf("-->|%01.*i|<--\n", 2, i));
assert(printf("-->|%01.*i|<--\n", 3, i) == ft_printf("-->|%01.*i|<--\n", 3, i));
assert(printf("-->|%01.*i|<--\n", 4, i) == ft_printf("-->|%01.*i|<--\n", 4, i));
assert(printf("-->|%01.0i|<--\n", i) == ft_printf("-->|%01.0i|<--\n", i));
assert(printf("-->|%01.1i|<--\n", i) == ft_printf("-->|%01.1i|<--\n", i));
assert(printf("-->|%01.2i|<--\n", i) == ft_printf("-->|%01.2i|<--\n", i));
assert(printf("-->|%01.3i|<--\n", i) == ft_printf("-->|%01.3i|<--\n", i));
assert(printf("-->|%01.4i|<--\n", i) == ft_printf("-->|%01.4i|<--\n", i));
assert(printf("-->|%01i|<--\n", i) == ft_printf("-->|%01i|<--\n", i));
assert(printf("-->|%02.i|<--\n", i) == ft_printf("-->|%02.i|<--\n", i));
assert(printf("-->|%02.*i|<--\n", -4, i) == ft_printf("-->|%02.*i|<--\n", -4, i));
assert(printf("-->|%02.*i|<--\n", -3, i) == ft_printf("-->|%02.*i|<--\n", -3, i));
assert(printf("-->|%02.*i|<--\n", -2, i) == ft_printf("-->|%02.*i|<--\n", -2, i));
assert(printf("-->|%02.*i|<--\n", -1, i) == ft_printf("-->|%02.*i|<--\n", -1, i));
assert(printf("-->|%02.*i|<--\n", 0, i) == ft_printf("-->|%02.*i|<--\n", 0, i));
assert(printf("-->|%02.*i|<--\n", 1, i) == ft_printf("-->|%02.*i|<--\n", 1, i));
assert(printf("-->|%02.*i|<--\n", 2, i) == ft_printf("-->|%02.*i|<--\n", 2, i));
assert(printf("-->|%02.*i|<--\n", 3, i) == ft_printf("-->|%02.*i|<--\n", 3, i));
assert(printf("-->|%02.*i|<--\n", 4, i) == ft_printf("-->|%02.*i|<--\n", 4, i));
assert(printf("-->|%02.0i|<--\n", i) == ft_printf("-->|%02.0i|<--\n", i));
assert(printf("-->|%02.1i|<--\n", i) == ft_printf("-->|%02.1i|<--\n", i));
assert(printf("-->|%02.2i|<--\n", i) == ft_printf("-->|%02.2i|<--\n", i));
assert(printf("-->|%02.3i|<--\n", i) == ft_printf("-->|%02.3i|<--\n", i));
assert(printf("-->|%02.4i|<--\n", i) == ft_printf("-->|%02.4i|<--\n", i));
assert(printf("-->|%02i|<--\n", i) == ft_printf("-->|%02i|<--\n", i));
assert(printf("-->|%03.i|<--\n", i) == ft_printf("-->|%03.i|<--\n", i));
assert(printf("-->|%03.*i|<--\n", -4, i) == ft_printf("-->|%03.*i|<--\n", -4, i));
assert(printf("-->|%03.*i|<--\n", -3, i) == ft_printf("-->|%03.*i|<--\n", -3, i));
assert(printf("-->|%03.*i|<--\n", -2, i) == ft_printf("-->|%03.*i|<--\n", -2, i));
assert(printf("-->|%03.*i|<--\n", -1, i) == ft_printf("-->|%03.*i|<--\n", -1, i));
assert(printf("-->|%03.*i|<--\n", 0, i) == ft_printf("-->|%03.*i|<--\n", 0, i));
assert(printf("-->|%03.*i|<--\n", 1, i) == ft_printf("-->|%03.*i|<--\n", 1, i));
assert(printf("-->|%03.*i|<--\n", 2, i) == ft_printf("-->|%03.*i|<--\n", 2, i));
assert(printf("-->|%03.*i|<--\n", 3, i) == ft_printf("-->|%03.*i|<--\n", 3, i));
assert(printf("-->|%03.*i|<--\n", 4, i) == ft_printf("-->|%03.*i|<--\n", 4, i));
assert(printf("-->|%03.0i|<--\n", i) == ft_printf("-->|%03.0i|<--\n", i));
assert(printf("-->|%03.1i|<--\n", i) == ft_printf("-->|%03.1i|<--\n", i));
assert(printf("-->|%03.2i|<--\n", i) == ft_printf("-->|%03.2i|<--\n", i));
assert(printf("-->|%03.3i|<--\n", i) == ft_printf("-->|%03.3i|<--\n", i));
assert(printf("-->|%03.4i|<--\n", i) == ft_printf("-->|%03.4i|<--\n", i));
assert(printf("-->|%03i|<--\n", i) == ft_printf("-->|%03i|<--\n", i));
assert(printf("-->|%04.i|<--\n", i) == ft_printf("-->|%04.i|<--\n", i));
assert(printf("-->|%04.*i|<--\n", -4, i) == ft_printf("-->|%04.*i|<--\n", -4, i));
assert(printf("-->|%04.*i|<--\n", -3, i) == ft_printf("-->|%04.*i|<--\n", -3, i));
assert(printf("-->|%04.*i|<--\n", -2, i) == ft_printf("-->|%04.*i|<--\n", -2, i));
assert(printf("-->|%04.*i|<--\n", -1, i) == ft_printf("-->|%04.*i|<--\n", -1, i));
assert(printf("-->|%04.*i|<--\n", 0, i) == ft_printf("-->|%04.*i|<--\n", 0, i));
assert(printf("-->|%04.*i|<--\n", 1, i) == ft_printf("-->|%04.*i|<--\n", 1, i));
assert(printf("-->|%04.*i|<--\n", 2, i) == ft_printf("-->|%04.*i|<--\n", 2, i));
assert(printf("-->|%04.*i|<--\n", 3, i) == ft_printf("-->|%04.*i|<--\n", 3, i));
assert(printf("-->|%04.*i|<--\n", 4, i) == ft_printf("-->|%04.*i|<--\n", 4, i));
assert(printf("-->|%04.0i|<--\n", i) == ft_printf("-->|%04.0i|<--\n", i));
assert(printf("-->|%04.1i|<--\n", i) == ft_printf("-->|%04.1i|<--\n", i));
assert(printf("-->|%04.2i|<--\n", i) == ft_printf("-->|%04.2i|<--\n", i));
assert(printf("-->|%04.3i|<--\n", i) == ft_printf("-->|%04.3i|<--\n", i));
assert(printf("-->|%04.4i|<--\n", i) == ft_printf("-->|%04.4i|<--\n", i));
assert(printf("-->|%04i|<--\n", i) == ft_printf("-->|%04i|<--\n", i));
assert(printf("-->|%--4.i|<--\n", i) == ft_printf("-->|%--4.i|<--\n", i));
assert(printf("-->|%--4.*i|<--\n", -4, i) == ft_printf("-->|%--4.*i|<--\n", -4, i));
assert(printf("-->|%--4.*i|<--\n", -3, i) == ft_printf("-->|%--4.*i|<--\n", -3, i));
assert(printf("-->|%--4.*i|<--\n", -2, i) == ft_printf("-->|%--4.*i|<--\n", -2, i));
assert(printf("-->|%--4.*i|<--\n", -1, i) == ft_printf("-->|%--4.*i|<--\n", -1, i));
assert(printf("-->|%--4.*i|<--\n", 0, i) == ft_printf("-->|%--4.*i|<--\n", 0, i));
assert(printf("-->|%--4.*i|<--\n", 1, i) == ft_printf("-->|%--4.*i|<--\n", 1, i));
assert(printf("-->|%--4.*i|<--\n", 2, i) == ft_printf("-->|%--4.*i|<--\n", 2, i));
assert(printf("-->|%--4.*i|<--\n", 3, i) == ft_printf("-->|%--4.*i|<--\n", 3, i));
assert(printf("-->|%--4.*i|<--\n", 4, i) == ft_printf("-->|%--4.*i|<--\n", 4, i));
assert(printf("-->|%--4.0i|<--\n", i) == ft_printf("-->|%--4.0i|<--\n", i));
assert(printf("-->|%--4.1i|<--\n", i) == ft_printf("-->|%--4.1i|<--\n", i));
assert(printf("-->|%--4.2i|<--\n", i) == ft_printf("-->|%--4.2i|<--\n", i));
assert(printf("-->|%--4.3i|<--\n", i) == ft_printf("-->|%--4.3i|<--\n", i));
assert(printf("-->|%--4.4i|<--\n", i) == ft_printf("-->|%--4.4i|<--\n", i));
assert(printf("-->|%--4i|<--\n", i) == ft_printf("-->|%--4i|<--\n", i));
assert(printf("-->|%--3.i|<--\n", i) == ft_printf("-->|%--3.i|<--\n", i));
assert(printf("-->|%--3.*i|<--\n", -4, i) == ft_printf("-->|%--3.*i|<--\n", -4, i));
assert(printf("-->|%--3.*i|<--\n", -3, i) == ft_printf("-->|%--3.*i|<--\n", -3, i));
assert(printf("-->|%--3.*i|<--\n", -2, i) == ft_printf("-->|%--3.*i|<--\n", -2, i));
assert(printf("-->|%--3.*i|<--\n", -1, i) == ft_printf("-->|%--3.*i|<--\n", -1, i));
assert(printf("-->|%--3.*i|<--\n", 0, i) == ft_printf("-->|%--3.*i|<--\n", 0, i));
assert(printf("-->|%--3.*i|<--\n", 1, i) == ft_printf("-->|%--3.*i|<--\n", 1, i));
assert(printf("-->|%--3.*i|<--\n", 2, i) == ft_printf("-->|%--3.*i|<--\n", 2, i));
assert(printf("-->|%--3.*i|<--\n", 3, i) == ft_printf("-->|%--3.*i|<--\n", 3, i));
assert(printf("-->|%--3.*i|<--\n", 4, i) == ft_printf("-->|%--3.*i|<--\n", 4, i));
assert(printf("-->|%--3.0i|<--\n", i) == ft_printf("-->|%--3.0i|<--\n", i));
assert(printf("-->|%--3.1i|<--\n", i) == ft_printf("-->|%--3.1i|<--\n", i));
assert(printf("-->|%--3.2i|<--\n", i) == ft_printf("-->|%--3.2i|<--\n", i));
assert(printf("-->|%--3.3i|<--\n", i) == ft_printf("-->|%--3.3i|<--\n", i));
assert(printf("-->|%--3.4i|<--\n", i) == ft_printf("-->|%--3.4i|<--\n", i));
assert(printf("-->|%--3i|<--\n", i) == ft_printf("-->|%--3i|<--\n", i));
assert(printf("-->|%--2.i|<--\n", i) == ft_printf("-->|%--2.i|<--\n", i));
assert(printf("-->|%--2.*i|<--\n", -4, i) == ft_printf("-->|%--2.*i|<--\n", -4, i));
assert(printf("-->|%--2.*i|<--\n", -3, i) == ft_printf("-->|%--2.*i|<--\n", -3, i));
assert(printf("-->|%--2.*i|<--\n", -2, i) == ft_printf("-->|%--2.*i|<--\n", -2, i));
assert(printf("-->|%--2.*i|<--\n", -1, i) == ft_printf("-->|%--2.*i|<--\n", -1, i));
assert(printf("-->|%--2.*i|<--\n", 0, i) == ft_printf("-->|%--2.*i|<--\n", 0, i));
assert(printf("-->|%--2.*i|<--\n", 1, i) == ft_printf("-->|%--2.*i|<--\n", 1, i));
assert(printf("-->|%--2.*i|<--\n", 2, i) == ft_printf("-->|%--2.*i|<--\n", 2, i));
assert(printf("-->|%--2.*i|<--\n", 3, i) == ft_printf("-->|%--2.*i|<--\n", 3, i));
assert(printf("-->|%--2.*i|<--\n", 4, i) == ft_printf("-->|%--2.*i|<--\n", 4, i));
assert(printf("-->|%--2.0i|<--\n", i) == ft_printf("-->|%--2.0i|<--\n", i));
assert(printf("-->|%--2.1i|<--\n", i) == ft_printf("-->|%--2.1i|<--\n", i));
assert(printf("-->|%--2.2i|<--\n", i) == ft_printf("-->|%--2.2i|<--\n", i));
assert(printf("-->|%--2.3i|<--\n", i) == ft_printf("-->|%--2.3i|<--\n", i));
assert(printf("-->|%--2.4i|<--\n", i) == ft_printf("-->|%--2.4i|<--\n", i));
assert(printf("-->|%--2i|<--\n", i) == ft_printf("-->|%--2i|<--\n", i));
assert(printf("-->|%--1.i|<--\n", i) == ft_printf("-->|%--1.i|<--\n", i));
assert(printf("-->|%--1.*i|<--\n", -4, i) == ft_printf("-->|%--1.*i|<--\n", -4, i));
assert(printf("-->|%--1.*i|<--\n", -3, i) == ft_printf("-->|%--1.*i|<--\n", -3, i));
assert(printf("-->|%--1.*i|<--\n", -2, i) == ft_printf("-->|%--1.*i|<--\n", -2, i));
assert(printf("-->|%--1.*i|<--\n", -1, i) == ft_printf("-->|%--1.*i|<--\n", -1, i));
assert(printf("-->|%--1.*i|<--\n", 0, i) == ft_printf("-->|%--1.*i|<--\n", 0, i));
assert(printf("-->|%--1.*i|<--\n", 1, i) == ft_printf("-->|%--1.*i|<--\n", 1, i));
assert(printf("-->|%--1.*i|<--\n", 2, i) == ft_printf("-->|%--1.*i|<--\n", 2, i));
assert(printf("-->|%--1.*i|<--\n", 3, i) == ft_printf("-->|%--1.*i|<--\n", 3, i));
assert(printf("-->|%--1.*i|<--\n", 4, i) == ft_printf("-->|%--1.*i|<--\n", 4, i));
assert(printf("-->|%--1.0i|<--\n", i) == ft_printf("-->|%--1.0i|<--\n", i));
assert(printf("-->|%--1.1i|<--\n", i) == ft_printf("-->|%--1.1i|<--\n", i));
assert(printf("-->|%--1.2i|<--\n", i) == ft_printf("-->|%--1.2i|<--\n", i));
assert(printf("-->|%--1.3i|<--\n", i) == ft_printf("-->|%--1.3i|<--\n", i));
assert(printf("-->|%--1.4i|<--\n", i) == ft_printf("-->|%--1.4i|<--\n", i));
assert(printf("-->|%--1i|<--\n", i) == ft_printf("-->|%--1i|<--\n", i));
assert(printf("-->|%-.i|<--\n", i) == ft_printf("-->|%-.i|<--\n", i));
assert(printf("-->|%-.*i|<--\n", -4, i) == ft_printf("-->|%-.*i|<--\n", -4, i));
assert(printf("-->|%-.*i|<--\n", -3, i) == ft_printf("-->|%-.*i|<--\n", -3, i));
assert(printf("-->|%-.*i|<--\n", -2, i) == ft_printf("-->|%-.*i|<--\n", -2, i));
assert(printf("-->|%-.*i|<--\n", -1, i) == ft_printf("-->|%-.*i|<--\n", -1, i));
assert(printf("-->|%-.*i|<--\n", 0, i) == ft_printf("-->|%-.*i|<--\n", 0, i));
assert(printf("-->|%-.*i|<--\n", 1, i) == ft_printf("-->|%-.*i|<--\n", 1, i));
assert(printf("-->|%-.*i|<--\n", 2, i) == ft_printf("-->|%-.*i|<--\n", 2, i));
assert(printf("-->|%-.*i|<--\n", 3, i) == ft_printf("-->|%-.*i|<--\n", 3, i));
assert(printf("-->|%-.*i|<--\n", 4, i) == ft_printf("-->|%-.*i|<--\n", 4, i));
assert(printf("-->|%-.0i|<--\n", i) == ft_printf("-->|%-.0i|<--\n", i));
assert(printf("-->|%-.1i|<--\n", i) == ft_printf("-->|%-.1i|<--\n", i));
assert(printf("-->|%-.2i|<--\n", i) == ft_printf("-->|%-.2i|<--\n", i));
assert(printf("-->|%-.3i|<--\n", i) == ft_printf("-->|%-.3i|<--\n", i));
assert(printf("-->|%-.4i|<--\n", i) == ft_printf("-->|%-.4i|<--\n", i));
assert(printf("-->|%-i|<--\n", i) == ft_printf("-->|%-i|<--\n", i));
assert(printf("-->|%-*.i|<--\n", -4, i) == ft_printf("-->|%-*.i|<--\n", -4, i));
assert(printf("-->|%-*.i|<--\n", -3, i) == ft_printf("-->|%-*.i|<--\n", -3, i));
assert(printf("-->|%-*.i|<--\n", -2, i) == ft_printf("-->|%-*.i|<--\n", -2, i));
assert(printf("-->|%-*.i|<--\n", -1, i) == ft_printf("-->|%-*.i|<--\n", -1, i));
assert(printf("-->|%-*.i|<--\n", 0, i) == ft_printf("-->|%-*.i|<--\n", 0, i));
assert(printf("-->|%-*.i|<--\n", 1, i) == ft_printf("-->|%-*.i|<--\n", 1, i));
assert(printf("-->|%-*.i|<--\n", 2, i) == ft_printf("-->|%-*.i|<--\n", 2, i));
assert(printf("-->|%-*.i|<--\n", 3, i) == ft_printf("-->|%-*.i|<--\n", 3, i));
assert(printf("-->|%-*.i|<--\n", 4, i) == ft_printf("-->|%-*.i|<--\n", 4, i));
assert(printf("-->|%-*.*i|<--\n", -4, -4, i) == ft_printf("-->|%-*.*i|<--\n", -4, -4, i));
assert(printf("-->|%-*.*i|<--\n", -4, -3, i) == ft_printf("-->|%-*.*i|<--\n", -4, -3, i));
assert(printf("-->|%-*.*i|<--\n", -4, -2, i) == ft_printf("-->|%-*.*i|<--\n", -4, -2, i));
assert(printf("-->|%-*.*i|<--\n", -4, -1, i) == ft_printf("-->|%-*.*i|<--\n", -4, -1, i));
assert(printf("-->|%-*.*i|<--\n", -4, 0, i) == ft_printf("-->|%-*.*i|<--\n", -4, 0, i));
assert(printf("-->|%-*.*i|<--\n", -4, 1, i) == ft_printf("-->|%-*.*i|<--\n", -4, 1, i));
assert(printf("-->|%-*.*i|<--\n", -4, 2, i) == ft_printf("-->|%-*.*i|<--\n", -4, 2, i));
assert(printf("-->|%-*.*i|<--\n", -4, 3, i) == ft_printf("-->|%-*.*i|<--\n", -4, 3, i));
assert(printf("-->|%-*.*i|<--\n", -4, 4, i) == ft_printf("-->|%-*.*i|<--\n", -4, 4, i));
assert(printf("-->|%-*.*i|<--\n", -3, -4, i) == ft_printf("-->|%-*.*i|<--\n", -3, -4, i));
assert(printf("-->|%-*.*i|<--\n", -3, -3, i) == ft_printf("-->|%-*.*i|<--\n", -3, -3, i));
assert(printf("-->|%-*.*i|<--\n", -3, -2, i) == ft_printf("-->|%-*.*i|<--\n", -3, -2, i));
assert(printf("-->|%-*.*i|<--\n", -3, -1, i) == ft_printf("-->|%-*.*i|<--\n", -3, -1, i));
assert(printf("-->|%-*.*i|<--\n", -3, 0, i) == ft_printf("-->|%-*.*i|<--\n", -3, 0, i));
assert(printf("-->|%-*.*i|<--\n", -3, 1, i) == ft_printf("-->|%-*.*i|<--\n", -3, 1, i));
assert(printf("-->|%-*.*i|<--\n", -3, 2, i) == ft_printf("-->|%-*.*i|<--\n", -3, 2, i));
assert(printf("-->|%-*.*i|<--\n", -3, 3, i) == ft_printf("-->|%-*.*i|<--\n", -3, 3, i));
assert(printf("-->|%-*.*i|<--\n", -3, 4, i) == ft_printf("-->|%-*.*i|<--\n", -3, 4, i));
assert(printf("-->|%-*.*i|<--\n", -2, -4, i) == ft_printf("-->|%-*.*i|<--\n", -2, -4, i));
assert(printf("-->|%-*.*i|<--\n", -2, -3, i) == ft_printf("-->|%-*.*i|<--\n", -2, -3, i));
assert(printf("-->|%-*.*i|<--\n", -2, -2, i) == ft_printf("-->|%-*.*i|<--\n", -2, -2, i));
assert(printf("-->|%-*.*i|<--\n", -2, -1, i) == ft_printf("-->|%-*.*i|<--\n", -2, -1, i));
assert(printf("-->|%-*.*i|<--\n", -2, 0, i) == ft_printf("-->|%-*.*i|<--\n", -2, 0, i));
assert(printf("-->|%-*.*i|<--\n", -2, 1, i) == ft_printf("-->|%-*.*i|<--\n", -2, 1, i));
assert(printf("-->|%-*.*i|<--\n", -2, 2, i) == ft_printf("-->|%-*.*i|<--\n", -2, 2, i));
assert(printf("-->|%-*.*i|<--\n", -2, 3, i) == ft_printf("-->|%-*.*i|<--\n", -2, 3, i));
assert(printf("-->|%-*.*i|<--\n", -2, 4, i) == ft_printf("-->|%-*.*i|<--\n", -2, 4, i));
assert(printf("-->|%-*.*i|<--\n", -1, -4, i) == ft_printf("-->|%-*.*i|<--\n", -1, -4, i));
assert(printf("-->|%-*.*i|<--\n", -1, -3, i) == ft_printf("-->|%-*.*i|<--\n", -1, -3, i));
assert(printf("-->|%-*.*i|<--\n", -1, -2, i) == ft_printf("-->|%-*.*i|<--\n", -1, -2, i));
assert(printf("-->|%-*.*i|<--\n", -1, -1, i) == ft_printf("-->|%-*.*i|<--\n", -1, -1, i));
assert(printf("-->|%-*.*i|<--\n", -1, 0, i) == ft_printf("-->|%-*.*i|<--\n", -1, 0, i));
assert(printf("-->|%-*.*i|<--\n", -1, 1, i) == ft_printf("-->|%-*.*i|<--\n", -1, 1, i));
assert(printf("-->|%-*.*i|<--\n", -1, 2, i) == ft_printf("-->|%-*.*i|<--\n", -1, 2, i));
assert(printf("-->|%-*.*i|<--\n", -1, 3, i) == ft_printf("-->|%-*.*i|<--\n", -1, 3, i));
assert(printf("-->|%-*.*i|<--\n", -1, 4, i) == ft_printf("-->|%-*.*i|<--\n", -1, 4, i));
assert(printf("-->|%-*.*i|<--\n", 0, -4, i) == ft_printf("-->|%-*.*i|<--\n", 0, -4, i));
assert(printf("-->|%-*.*i|<--\n", 0, -3, i) == ft_printf("-->|%-*.*i|<--\n", 0, -3, i));
assert(printf("-->|%-*.*i|<--\n", 0, -2, i) == ft_printf("-->|%-*.*i|<--\n", 0, -2, i));
assert(printf("-->|%-*.*i|<--\n", 0, -1, i) == ft_printf("-->|%-*.*i|<--\n", 0, -1, i));
assert(printf("-->|%-*.*i|<--\n", 0, 0, i) == ft_printf("-->|%-*.*i|<--\n", 0, 0, i));
assert(printf("-->|%-*.*i|<--\n", 0, 1, i) == ft_printf("-->|%-*.*i|<--\n", 0, 1, i));
assert(printf("-->|%-*.*i|<--\n", 0, 2, i) == ft_printf("-->|%-*.*i|<--\n", 0, 2, i));
assert(printf("-->|%-*.*i|<--\n", 0, 3, i) == ft_printf("-->|%-*.*i|<--\n", 0, 3, i));
assert(printf("-->|%-*.*i|<--\n", 0, 4, i) == ft_printf("-->|%-*.*i|<--\n", 0, 4, i));
assert(printf("-->|%-*.*i|<--\n", 1, -4, i) == ft_printf("-->|%-*.*i|<--\n", 1, -4, i));
assert(printf("-->|%-*.*i|<--\n", 1, -3, i) == ft_printf("-->|%-*.*i|<--\n", 1, -3, i));
assert(printf("-->|%-*.*i|<--\n", 1, -2, i) == ft_printf("-->|%-*.*i|<--\n", 1, -2, i));
assert(printf("-->|%-*.*i|<--\n", 1, -1, i) == ft_printf("-->|%-*.*i|<--\n", 1, -1, i));
assert(printf("-->|%-*.*i|<--\n", 1, 0, i) == ft_printf("-->|%-*.*i|<--\n", 1, 0, i));
assert(printf("-->|%-*.*i|<--\n", 1, 1, i) == ft_printf("-->|%-*.*i|<--\n", 1, 1, i));
assert(printf("-->|%-*.*i|<--\n", 1, 2, i) == ft_printf("-->|%-*.*i|<--\n", 1, 2, i));
assert(printf("-->|%-*.*i|<--\n", 1, 3, i) == ft_printf("-->|%-*.*i|<--\n", 1, 3, i));
assert(printf("-->|%-*.*i|<--\n", 1, 4, i) == ft_printf("-->|%-*.*i|<--\n", 1, 4, i));
assert(printf("-->|%-*.*i|<--\n", 2, -4, i) == ft_printf("-->|%-*.*i|<--\n", 2, -4, i));
assert(printf("-->|%-*.*i|<--\n", 2, -3, i) == ft_printf("-->|%-*.*i|<--\n", 2, -3, i));
assert(printf("-->|%-*.*i|<--\n", 2, -2, i) == ft_printf("-->|%-*.*i|<--\n", 2, -2, i));
assert(printf("-->|%-*.*i|<--\n", 2, -1, i) == ft_printf("-->|%-*.*i|<--\n", 2, -1, i));
assert(printf("-->|%-*.*i|<--\n", 2, 0, i) == ft_printf("-->|%-*.*i|<--\n", 2, 0, i));
assert(printf("-->|%-*.*i|<--\n", 2, 1, i) == ft_printf("-->|%-*.*i|<--\n", 2, 1, i));
assert(printf("-->|%-*.*i|<--\n", 2, 2, i) == ft_printf("-->|%-*.*i|<--\n", 2, 2, i));
assert(printf("-->|%-*.*i|<--\n", 2, 3, i) == ft_printf("-->|%-*.*i|<--\n", 2, 3, i));
assert(printf("-->|%-*.*i|<--\n", 2, 4, i) == ft_printf("-->|%-*.*i|<--\n", 2, 4, i));
assert(printf("-->|%-*.*i|<--\n", 3, -4, i) == ft_printf("-->|%-*.*i|<--\n", 3, -4, i));
assert(printf("-->|%-*.*i|<--\n", 3, -3, i) == ft_printf("-->|%-*.*i|<--\n", 3, -3, i));
assert(printf("-->|%-*.*i|<--\n", 3, -2, i) == ft_printf("-->|%-*.*i|<--\n", 3, -2, i));
assert(printf("-->|%-*.*i|<--\n", 3, -1, i) == ft_printf("-->|%-*.*i|<--\n", 3, -1, i));
assert(printf("-->|%-*.*i|<--\n", 3, 0, i) == ft_printf("-->|%-*.*i|<--\n", 3, 0, i));
assert(printf("-->|%-*.*i|<--\n", 3, 1, i) == ft_printf("-->|%-*.*i|<--\n", 3, 1, i));
assert(printf("-->|%-*.*i|<--\n", 3, 2, i) == ft_printf("-->|%-*.*i|<--\n", 3, 2, i));
assert(printf("-->|%-*.*i|<--\n", 3, 3, i) == ft_printf("-->|%-*.*i|<--\n", 3, 3, i));
assert(printf("-->|%-*.*i|<--\n", 3, 4, i) == ft_printf("-->|%-*.*i|<--\n", 3, 4, i));
assert(printf("-->|%-*.*i|<--\n", 4, -4, i) == ft_printf("-->|%-*.*i|<--\n", 4, -4, i));
assert(printf("-->|%-*.*i|<--\n", 4, -3, i) == ft_printf("-->|%-*.*i|<--\n", 4, -3, i));
assert(printf("-->|%-*.*i|<--\n", 4, -2, i) == ft_printf("-->|%-*.*i|<--\n", 4, -2, i));
assert(printf("-->|%-*.*i|<--\n", 4, -1, i) == ft_printf("-->|%-*.*i|<--\n", 4, -1, i));
assert(printf("-->|%-*.*i|<--\n", 4, 0, i) == ft_printf("-->|%-*.*i|<--\n", 4, 0, i));
assert(printf("-->|%-*.*i|<--\n", 4, 1, i) == ft_printf("-->|%-*.*i|<--\n", 4, 1, i));
assert(printf("-->|%-*.*i|<--\n", 4, 2, i) == ft_printf("-->|%-*.*i|<--\n", 4, 2, i));
assert(printf("-->|%-*.*i|<--\n", 4, 3, i) == ft_printf("-->|%-*.*i|<--\n", 4, 3, i));
assert(printf("-->|%-*.*i|<--\n", 4, 4, i) == ft_printf("-->|%-*.*i|<--\n", 4, 4, i));
assert(printf("-->|%-*.0i|<--\n", -4, i) == ft_printf("-->|%-*.0i|<--\n", -4, i));
assert(printf("-->|%-*.0i|<--\n", -3, i) == ft_printf("-->|%-*.0i|<--\n", -3, i));
assert(printf("-->|%-*.0i|<--\n", -2, i) == ft_printf("-->|%-*.0i|<--\n", -2, i));
assert(printf("-->|%-*.0i|<--\n", -1, i) == ft_printf("-->|%-*.0i|<--\n", -1, i));
assert(printf("-->|%-*.0i|<--\n", 0, i) == ft_printf("-->|%-*.0i|<--\n", 0, i));
assert(printf("-->|%-*.0i|<--\n", 1, i) == ft_printf("-->|%-*.0i|<--\n", 1, i));
assert(printf("-->|%-*.0i|<--\n", 2, i) == ft_printf("-->|%-*.0i|<--\n", 2, i));
assert(printf("-->|%-*.0i|<--\n", 3, i) == ft_printf("-->|%-*.0i|<--\n", 3, i));
assert(printf("-->|%-*.0i|<--\n", 4, i) == ft_printf("-->|%-*.0i|<--\n", 4, i));
assert(printf("-->|%-*.1i|<--\n", -4, i) == ft_printf("-->|%-*.1i|<--\n", -4, i));
assert(printf("-->|%-*.1i|<--\n", -3, i) == ft_printf("-->|%-*.1i|<--\n", -3, i));
assert(printf("-->|%-*.1i|<--\n", -2, i) == ft_printf("-->|%-*.1i|<--\n", -2, i));
assert(printf("-->|%-*.1i|<--\n", -1, i) == ft_printf("-->|%-*.1i|<--\n", -1, i));
assert(printf("-->|%-*.1i|<--\n", 0, i) == ft_printf("-->|%-*.1i|<--\n", 0, i));
assert(printf("-->|%-*.1i|<--\n", 1, i) == ft_printf("-->|%-*.1i|<--\n", 1, i));
assert(printf("-->|%-*.1i|<--\n", 2, i) == ft_printf("-->|%-*.1i|<--\n", 2, i));
assert(printf("-->|%-*.1i|<--\n", 3, i) == ft_printf("-->|%-*.1i|<--\n", 3, i));
assert(printf("-->|%-*.1i|<--\n", 4, i) == ft_printf("-->|%-*.1i|<--\n", 4, i));
assert(printf("-->|%-*.2i|<--\n", -4, i) == ft_printf("-->|%-*.2i|<--\n", -4, i));
assert(printf("-->|%-*.2i|<--\n", -3, i) == ft_printf("-->|%-*.2i|<--\n", -3, i));
assert(printf("-->|%-*.2i|<--\n", -2, i) == ft_printf("-->|%-*.2i|<--\n", -2, i));
assert(printf("-->|%-*.2i|<--\n", -1, i) == ft_printf("-->|%-*.2i|<--\n", -1, i));
assert(printf("-->|%-*.2i|<--\n", 0, i) == ft_printf("-->|%-*.2i|<--\n", 0, i));
assert(printf("-->|%-*.2i|<--\n", 1, i) == ft_printf("-->|%-*.2i|<--\n", 1, i));
assert(printf("-->|%-*.2i|<--\n", 2, i) == ft_printf("-->|%-*.2i|<--\n", 2, i));
assert(printf("-->|%-*.2i|<--\n", 3, i) == ft_printf("-->|%-*.2i|<--\n", 3, i));
assert(printf("-->|%-*.2i|<--\n", 4, i) == ft_printf("-->|%-*.2i|<--\n", 4, i));
assert(printf("-->|%-*.3i|<--\n", -4, i) == ft_printf("-->|%-*.3i|<--\n", -4, i));
assert(printf("-->|%-*.3i|<--\n", -3, i) == ft_printf("-->|%-*.3i|<--\n", -3, i));
assert(printf("-->|%-*.3i|<--\n", -2, i) == ft_printf("-->|%-*.3i|<--\n", -2, i));
assert(printf("-->|%-*.3i|<--\n", -1, i) == ft_printf("-->|%-*.3i|<--\n", -1, i));
assert(printf("-->|%-*.3i|<--\n", 0, i) == ft_printf("-->|%-*.3i|<--\n", 0, i));
assert(printf("-->|%-*.3i|<--\n", 1, i) == ft_printf("-->|%-*.3i|<--\n", 1, i));
assert(printf("-->|%-*.3i|<--\n", 2, i) == ft_printf("-->|%-*.3i|<--\n", 2, i));
assert(printf("-->|%-*.3i|<--\n", 3, i) == ft_printf("-->|%-*.3i|<--\n", 3, i));
assert(printf("-->|%-*.3i|<--\n", 4, i) == ft_printf("-->|%-*.3i|<--\n", 4, i));
assert(printf("-->|%-*.4i|<--\n", -4, i) == ft_printf("-->|%-*.4i|<--\n", -4, i));
assert(printf("-->|%-*.4i|<--\n", -3, i) == ft_printf("-->|%-*.4i|<--\n", -3, i));
assert(printf("-->|%-*.4i|<--\n", -2, i) == ft_printf("-->|%-*.4i|<--\n", -2, i));
assert(printf("-->|%-*.4i|<--\n", -1, i) == ft_printf("-->|%-*.4i|<--\n", -1, i));
assert(printf("-->|%-*.4i|<--\n", 0, i) == ft_printf("-->|%-*.4i|<--\n", 0, i));
assert(printf("-->|%-*.4i|<--\n", 1, i) == ft_printf("-->|%-*.4i|<--\n", 1, i));
assert(printf("-->|%-*.4i|<--\n", 2, i) == ft_printf("-->|%-*.4i|<--\n", 2, i));
assert(printf("-->|%-*.4i|<--\n", 3, i) == ft_printf("-->|%-*.4i|<--\n", 3, i));
assert(printf("-->|%-*.4i|<--\n", 4, i) == ft_printf("-->|%-*.4i|<--\n", 4, i));
assert(printf("-->|%-*i|<--\n", -4, i) == ft_printf("-->|%-*i|<--\n", -4, i));
assert(printf("-->|%-*i|<--\n", -3, i) == ft_printf("-->|%-*i|<--\n", -3, i));
assert(printf("-->|%-*i|<--\n", -2, i) == ft_printf("-->|%-*i|<--\n", -2, i));
assert(printf("-->|%-*i|<--\n", -1, i) == ft_printf("-->|%-*i|<--\n", -1, i));
assert(printf("-->|%-*i|<--\n", 0, i) == ft_printf("-->|%-*i|<--\n", 0, i));
assert(printf("-->|%-*i|<--\n", 1, i) == ft_printf("-->|%-*i|<--\n", 1, i));
assert(printf("-->|%-*i|<--\n", 2, i) == ft_printf("-->|%-*i|<--\n", 2, i));
assert(printf("-->|%-*i|<--\n", 3, i) == ft_printf("-->|%-*i|<--\n", 3, i));
assert(printf("-->|%-*i|<--\n", 4, i) == ft_printf("-->|%-*i|<--\n", 4, i));
assert(printf("-->|%-1.i|<--\n", i) == ft_printf("-->|%-1.i|<--\n", i));
assert(printf("-->|%-1.*i|<--\n", -4, i) == ft_printf("-->|%-1.*i|<--\n", -4, i));
assert(printf("-->|%-1.*i|<--\n", -3, i) == ft_printf("-->|%-1.*i|<--\n", -3, i));
assert(printf("-->|%-1.*i|<--\n", -2, i) == ft_printf("-->|%-1.*i|<--\n", -2, i));
assert(printf("-->|%-1.*i|<--\n", -1, i) == ft_printf("-->|%-1.*i|<--\n", -1, i));
assert(printf("-->|%-1.*i|<--\n", 0, i) == ft_printf("-->|%-1.*i|<--\n", 0, i));
assert(printf("-->|%-1.*i|<--\n", 1, i) == ft_printf("-->|%-1.*i|<--\n", 1, i));
assert(printf("-->|%-1.*i|<--\n", 2, i) == ft_printf("-->|%-1.*i|<--\n", 2, i));
assert(printf("-->|%-1.*i|<--\n", 3, i) == ft_printf("-->|%-1.*i|<--\n", 3, i));
assert(printf("-->|%-1.*i|<--\n", 4, i) == ft_printf("-->|%-1.*i|<--\n", 4, i));
assert(printf("-->|%-1.0i|<--\n", i) == ft_printf("-->|%-1.0i|<--\n", i));
assert(printf("-->|%-1.1i|<--\n", i) == ft_printf("-->|%-1.1i|<--\n", i));
assert(printf("-->|%-1.2i|<--\n", i) == ft_printf("-->|%-1.2i|<--\n", i));
assert(printf("-->|%-1.3i|<--\n", i) == ft_printf("-->|%-1.3i|<--\n", i));
assert(printf("-->|%-1.4i|<--\n", i) == ft_printf("-->|%-1.4i|<--\n", i));
assert(printf("-->|%-1i|<--\n", i) == ft_printf("-->|%-1i|<--\n", i));
assert(printf("-->|%-2.i|<--\n", i) == ft_printf("-->|%-2.i|<--\n", i));
assert(printf("-->|%-2.*i|<--\n", -4, i) == ft_printf("-->|%-2.*i|<--\n", -4, i));
assert(printf("-->|%-2.*i|<--\n", -3, i) == ft_printf("-->|%-2.*i|<--\n", -3, i));
assert(printf("-->|%-2.*i|<--\n", -2, i) == ft_printf("-->|%-2.*i|<--\n", -2, i));
assert(printf("-->|%-2.*i|<--\n", -1, i) == ft_printf("-->|%-2.*i|<--\n", -1, i));
assert(printf("-->|%-2.*i|<--\n", 0, i) == ft_printf("-->|%-2.*i|<--\n", 0, i));
assert(printf("-->|%-2.*i|<--\n", 1, i) == ft_printf("-->|%-2.*i|<--\n", 1, i));
assert(printf("-->|%-2.*i|<--\n", 2, i) == ft_printf("-->|%-2.*i|<--\n", 2, i));
assert(printf("-->|%-2.*i|<--\n", 3, i) == ft_printf("-->|%-2.*i|<--\n", 3, i));
assert(printf("-->|%-2.*i|<--\n", 4, i) == ft_printf("-->|%-2.*i|<--\n", 4, i));
assert(printf("-->|%-2.0i|<--\n", i) == ft_printf("-->|%-2.0i|<--\n", i));
assert(printf("-->|%-2.1i|<--\n", i) == ft_printf("-->|%-2.1i|<--\n", i));
assert(printf("-->|%-2.2i|<--\n", i) == ft_printf("-->|%-2.2i|<--\n", i));
assert(printf("-->|%-2.3i|<--\n", i) == ft_printf("-->|%-2.3i|<--\n", i));
assert(printf("-->|%-2.4i|<--\n", i) == ft_printf("-->|%-2.4i|<--\n", i));
assert(printf("-->|%-2i|<--\n", i) == ft_printf("-->|%-2i|<--\n", i));
assert(printf("-->|%-3.i|<--\n", i) == ft_printf("-->|%-3.i|<--\n", i));
assert(printf("-->|%-3.*i|<--\n", -4, i) == ft_printf("-->|%-3.*i|<--\n", -4, i));
assert(printf("-->|%-3.*i|<--\n", -3, i) == ft_printf("-->|%-3.*i|<--\n", -3, i));
assert(printf("-->|%-3.*i|<--\n", -2, i) == ft_printf("-->|%-3.*i|<--\n", -2, i));
assert(printf("-->|%-3.*i|<--\n", -1, i) == ft_printf("-->|%-3.*i|<--\n", -1, i));
assert(printf("-->|%-3.*i|<--\n", 0, i) == ft_printf("-->|%-3.*i|<--\n", 0, i));
assert(printf("-->|%-3.*i|<--\n", 1, i) == ft_printf("-->|%-3.*i|<--\n", 1, i));
assert(printf("-->|%-3.*i|<--\n", 2, i) == ft_printf("-->|%-3.*i|<--\n", 2, i));
assert(printf("-->|%-3.*i|<--\n", 3, i) == ft_printf("-->|%-3.*i|<--\n", 3, i));
assert(printf("-->|%-3.*i|<--\n", 4, i) == ft_printf("-->|%-3.*i|<--\n", 4, i));
assert(printf("-->|%-3.0i|<--\n", i) == ft_printf("-->|%-3.0i|<--\n", i));
assert(printf("-->|%-3.1i|<--\n", i) == ft_printf("-->|%-3.1i|<--\n", i));
assert(printf("-->|%-3.2i|<--\n", i) == ft_printf("-->|%-3.2i|<--\n", i));
assert(printf("-->|%-3.3i|<--\n", i) == ft_printf("-->|%-3.3i|<--\n", i));
assert(printf("-->|%-3.4i|<--\n", i) == ft_printf("-->|%-3.4i|<--\n", i));
assert(printf("-->|%-3i|<--\n", i) == ft_printf("-->|%-3i|<--\n", i));
assert(printf("-->|%-4.i|<--\n", i) == ft_printf("-->|%-4.i|<--\n", i));
assert(printf("-->|%-4.*i|<--\n", -4, i) == ft_printf("-->|%-4.*i|<--\n", -4, i));
assert(printf("-->|%-4.*i|<--\n", -3, i) == ft_printf("-->|%-4.*i|<--\n", -3, i));
assert(printf("-->|%-4.*i|<--\n", -2, i) == ft_printf("-->|%-4.*i|<--\n", -2, i));
assert(printf("-->|%-4.*i|<--\n", -1, i) == ft_printf("-->|%-4.*i|<--\n", -1, i));
assert(printf("-->|%-4.*i|<--\n", 0, i) == ft_printf("-->|%-4.*i|<--\n", 0, i));
assert(printf("-->|%-4.*i|<--\n", 1, i) == ft_printf("-->|%-4.*i|<--\n", 1, i));
assert(printf("-->|%-4.*i|<--\n", 2, i) == ft_printf("-->|%-4.*i|<--\n", 2, i));
assert(printf("-->|%-4.*i|<--\n", 3, i) == ft_printf("-->|%-4.*i|<--\n", 3, i));
assert(printf("-->|%-4.*i|<--\n", 4, i) == ft_printf("-->|%-4.*i|<--\n", 4, i));
assert(printf("-->|%-4.0i|<--\n", i) == ft_printf("-->|%-4.0i|<--\n", i));
assert(printf("-->|%-4.1i|<--\n", i) == ft_printf("-->|%-4.1i|<--\n", i));
assert(printf("-->|%-4.2i|<--\n", i) == ft_printf("-->|%-4.2i|<--\n", i));
assert(printf("-->|%-4.3i|<--\n", i) == ft_printf("-->|%-4.3i|<--\n", i));
assert(printf("-->|%-4.4i|<--\n", i) == ft_printf("-->|%-4.4i|<--\n", i));
assert(printf("-->|%-4i|<--\n", i) == ft_printf("-->|%-4i|<--\n", i));
	return(0);
}
/*
** charmstr@student.42.fr
**
** 1664 different calls generated automatically according to your options
*/
